/* GENERATED by tools/service-discovery/build-data.mjs from
   docs/research/dosje-scheme-master-2026-09.json — do not edit here. */

export interface SdPersona { id: string; label: string; short: string; sub: string }
export interface SdOffering { id: string; label: string; short: string; sub: string }
export interface SdScheme {
  id: string; name: string; umbrella: string | null; type: string;
  who: string[]; offers: string[]; provides: string; named: string; apply: string[];
  offersFor?: Record<string, string[]>;
  /** The scheme's page on the Department's legacy site, where one was cited. */
  page?: string;
}

export const SD_PERSONAS: SdPersona[] = [
  {
    "id": "sc",
    "label": "Scheduled Castes",
    "short": "Scheduled Castes",
    "sub": "As notified under Article 341 of the Constitution"
  },
  {
    "id": "obc",
    "label": "Other Backward Classes",
    "short": "Other Backward Classes",
    "sub": "Including Economically Backward Classes"
  },
  {
    "id": "senior",
    "label": "Senior Citizens",
    "short": "Senior Citizens",
    "sub": "Aged 60 years or above"
  },
  {
    "id": "drug",
    "label": "Persons Affected by Substance Use",
    "short": "Affected by Substance Use",
    "sub": "The person, and their family"
  },
  {
    "id": "tg",
    "label": "Transgender Persons",
    "short": "Transgender Persons",
    "sub": "As defined in the Transgender Persons (Protection of Rights) Act, 2019"
  },
  {
    "id": "begging",
    "label": "Persons Engaged in Begging",
    "short": "Engaged in Begging",
    "sub": "Rescue, shelter and rehabilitation"
  },
  {
    "id": "dnt",
    "label": "De-notified, Nomadic and Semi-Nomadic Tribes",
    "short": "DNT, Nomadic and Semi-Nomadic Tribes",
    "sub": "Communities listed as DNT, NT or SNT"
  },
  {
    "id": "safai",
    "label": "Safai Karamcharis",
    "short": "Safai Karamcharis",
    "sub": "Manual scavengers, sewer and septic tank workers, waste pickers, and their dependants"
  },
  {
    "id": "student",
    "label": "Students",
    "short": "Students",
    "sub": "From Class I to Ph.D. and study abroad, from the groups the Department serves"
  },
  {
    "id": "atrocity",
    "label": "Victims of Atrocities",
    "short": "Victims of Atrocities",
    "sub": "Under the PCR Act, 1955 and the SC/ST (PoA) Act, 1989"
  },
  {
    "id": "ngo",
    "label": "Voluntary Organisations",
    "short": "Voluntary Organisations",
    "sub": "NGOs, CBOs and institutions applying for grant-in-aid"
  }
];
export const SD_OFFERINGS: SdOffering[] = [
  {
    "id": "scholarship",
    "label": "Scholarships and Fellowships",
    "short": "Scholarships and Fellowships",
    "sub": "Pre-matric to Ph.D., and study abroad"
  },
  {
    "id": "schooling",
    "label": "Residential Schools, Hostels and Coaching",
    "short": "Schools, Hostels and Coaching",
    "sub": "Top-class schools, hostels and free coaching for competitive examinations"
  },
  {
    "id": "loan",
    "label": "Loans and Credit",
    "short": "Loans and Credit",
    "sub": "Concessional loans, interest subvention and venture capital through the Department's corporations"
  },
  {
    "id": "skill",
    "label": "Skill Training and Livelihood",
    "short": "Skill Training and Livelihood",
    "sub": "Free training with stipend, self-employment support, village development"
  },
  {
    "id": "care",
    "label": "Care, Shelter and Health",
    "short": "Care, Shelter and Health",
    "sub": "Old-age homes, shelter homes, assistive devices and health cover"
  },
  {
    "id": "deaddiction",
    "label": "De-addiction and Counselling",
    "short": "De-addiction and Counselling",
    "sub": "Treatment centres, the 14446 helpline and Nasha Mukt Bharat Abhiyaan"
  },
  {
    "id": "protection",
    "label": "Protection, Relief and Grievance",
    "short": "Protection, Relief and Grievance",
    "sub": "Relief to atrocity victims, the 14566 helpline, and the Commissions' grievance portals"
  },
  {
    "id": "grant",
    "label": "Grants to Voluntary Organisations",
    "short": "Grants to Voluntary Organisations",
    "sub": "Grant-in-aid through the e-Anudaan portal"
  }
];
export const SD_ROUTES: Record<string, { label: string; href: string | null }> = {
  "nsp": {
    "label": "National Scholarship Portal",
    "href": "https://scholarships.gov.in"
  },
  "state": {
    "label": "the State's scholarship portal",
    "href": null
  },
  "nos": {
    "label": "the NOS portal",
    "href": "https://nosmsje.gov.in"
  },
  "ugc": {
    "label": "the UGC",
    "href": "https://www.ugc.gov.in"
  },
  "nbcfdc": {
    "label": "NBCFDC",
    "href": "https://nbcfdc.gov.in"
  },
  "nsfdc": {
    "label": "NSFDC",
    "href": "https://nsfdc.nic.in"
  },
  "nskfdc": {
    "label": "NSKFDC",
    "href": "https://nskfdc.nic.in"
  },
  "canara": {
    "label": "Canara Bank",
    "href": null
  },
  "shreshta": {
    "label": "the SHRESHTA entrance test (NTA)",
    "href": null
  },
  "pmajay": {
    "label": "the PM-AJAY portal",
    "href": "https://pmajay.dosje.gov.in"
  },
  "district": {
    "label": "the District administration",
    "href": null
  },
  "nhaa": {
    "label": "Helpline 14566",
    "href": "tel:14566"
  },
  "ncsc": {
    "label": "the NCSC grievance portal",
    "href": "https://ncsc.nic.in"
  },
  "ncsk": {
    "label": "the NCSK",
    "href": null
  },
  "namaste": {
    "label": "the urban local body (NAMASTE)",
    "href": null
  },
  "bank": {
    "label": "the lending bank",
    "href": null
  },
  "ifci": {
    "label": "IFCI Venture",
    "href": null
  },
  "pmdaksh": {
    "label": "the PM-DAKSH portal",
    "href": null
  },
  "alimco": {
    "label": "an ALIMCO camp",
    "href": null
  },
  "elderline": {
    "label": "Elderline 14567",
    "href": "tel:14567"
  },
  "eanudaan": {
    "label": "the e-Anudaan portal",
    "href": "https://grants-msje.gov.in"
  },
  "nmba": {
    "label": "Helpline 14446, or the nearest centre",
    "href": "tel:14446"
  },
  "smile": {
    "label": "the shelter home (urban local body)",
    "href": null
  },
  "tgportal": {
    "label": "the National Portal for Transgender Persons",
    "href": null
  },
  "seed": {
    "label": "the SEED portal",
    "href": "https://seed.dosje.gov.in"
  },
  "institution": {
    "label": "the school or college",
    "href": null
  },
  "wcd": {
    "label": "the District Magistrate (WCD)",
    "href": null
  },
  "daf": {
    "label": "Dr. Ambedkar Foundation",
    "href": null
  },
  "nisd": {
    "label": "a NISD-affiliated institute",
    "href": null
  }
};
export const SD_SCHEMES: SdScheme[] = [
  {
    "id": "pms-sc",
    "name": "Post Matric Scholarship for Scheduled Castes",
    "umbrella": "Umbrella Scheme for Development of Scheduled Castes",
    "type": "Centrally Sponsored",
    "who": [
      "sc",
      "student"
    ],
    "offers": [
      "scholarship"
    ],
    "provides": "Compulsory non-refundable fees, including tuition, and an academic allowance for the whole course after Class X.",
    "named": "SC students studying at the post-matric stage; parent or guardian income up to ₹2.5 lakh a year.",
    "apply": [
      "state",
      "nsp"
    ],
    "page": "https://socialjustice.gov.in/schemes/25"
  },
  {
    "id": "pre-matric-sc",
    "name": "Pre-Matric Scholarship for Scheduled Castes and Others",
    "umbrella": "Umbrella Scheme for Development of Scheduled Castes",
    "type": "Centrally Sponsored",
    "who": [
      "sc",
      "safai",
      "student"
    ],
    "offers": [
      "scholarship"
    ],
    "provides": "An academic allowance of ₹3,500 a year for day scholars and ₹7,000 or ₹8,000 for hostellers.",
    "named": "SC students in Class IX and X with family income up to ₹2.5 lakh; and children in Class I to X of manual scavengers, tanners and flayers, waste pickers and hazardous-cleaning workers, with no income limit.",
    "apply": [
      "state",
      "nsp"
    ]
  },
  {
    "id": "nfsc",
    "name": "National Fellowship for Scheduled Caste Students",
    "umbrella": "SHREYAS for SCs",
    "type": "Central Sector",
    "who": [
      "sc",
      "student"
    ],
    "offers": [
      "scholarship"
    ],
    "provides": "A Ph.D. fellowship with contingency and house rent allowance; 2,000 new fellowships a year.",
    "named": "SC students who have qualified UGC NET-JRF or UGC-CSIR NET-JRF, for Ph.D. at a UGC-recognised institution.",
    "apply": [
      "ugc"
    ]
  },
  {
    "id": "nos",
    "name": "National Overseas Scholarship for SCs and Others",
    "umbrella": "SHREYAS for SCs",
    "type": "Central Sector",
    "who": [
      "sc",
      "dnt",
      "student"
    ],
    "offers": [
      "scholarship"
    ],
    "provides": "Tuition, maintenance and contingency allowances, visa, insurance and air passage for a Master's or Ph.D. abroad; 125 slots a year, 30% for women.",
    "named": "Students from Scheduled Castes, DNT, NT and SNT communities, landless agricultural labourers and traditional artisans; family income up to ₹8 lakh; age up to 35; admission to a top-500 QS-ranked university.",
    "apply": [
      "nos"
    ],
    "page": "https://socialjustice.gov.in/schemes/28"
  },
  {
    "id": "top-class-sc",
    "name": "Top Class Education for Scheduled Caste Students",
    "umbrella": "SHREYAS for SCs",
    "type": "Central Sector",
    "who": [
      "sc",
      "student"
    ],
    "offers": [
      "scholarship"
    ],
    "provides": "Full tuition and non-refundable charges, plus an academic allowance of ₹86,000 in the first year and ₹41,000 in each later year, at 274 notified institutions.",
    "named": "SC students with family income up to ₹8 lakh admitted to a notified institution; 30% of slots for SC girl students.",
    "apply": [
      "nsp"
    ]
  },
  {
    "id": "free-coaching",
    "name": "Free Coaching for SCs, OBCs and PM CARES Children",
    "umbrella": "SHREYAS for SCs",
    "type": "Central Sector",
    "who": [
      "sc",
      "obc",
      "student"
    ],
    "offers": [
      "schooling"
    ],
    "provides": "Course fee up to ₹75,000 and a stipend of ₹4,000 a month for up to 12 months of coaching for competitive and entrance examinations.",
    "named": "SC and OBC students with family income up to ₹8 lakh, and beneficiaries of the PM CARES for Children scheme with no income or caste condition.",
    "apply": [
      "nsp"
    ]
  },
  {
    "id": "shreshta",
    "name": "SHRESHTA — Residential Education for Students in High Schools in Targeted Areas",
    "umbrella": null,
    "type": "Central Sector",
    "who": [
      "sc",
      "student",
      "ngo"
    ],
    "offers": [
      "schooling",
      "grant"
    ],
    "provides": "Mode I: full tuition and hostel fees at a top private residential school from Class 9 or 11 to Class 12. Mode II: grant-in-aid to NGO-run residential schools and hostels for SC students.",
    "named": "Meritorious SC students selected through the National Entrance Test for SHRESHTA; and voluntary organisations running schools and hostels for SC students.",
    "apply": [
      "shreshta",
      "eanudaan"
    ],
    "offersFor": {
      "grant": [
        "ngo"
      ],
      "schooling": [
        "sc",
        "student"
      ]
    }
  },
  {
    "id": "pm-ajay",
    "name": "Pradhan Mantri Anusuchit Jaati Abhyuday Yojana (PM-AJAY)",
    "umbrella": "Umbrella Scheme for Development of Scheduled Castes",
    "type": "Centrally Sponsored",
    "who": [
      "sc"
    ],
    "offers": [
      "skill"
    ],
    "provides": "Development of SC-dominated villages as Adarsh Gram; grants-in-aid for district and State livelihood and infrastructure projects; hostels in higher-education institutions.",
    "named": "Scheduled Caste communities, through the State Government and District administration; 100% centrally funded.",
    "apply": [
      "pmajay"
    ],
    "page": "https://socialjustice.gov.in/schemes/104"
  },
  {
    "id": "pcr-poa",
    "name": "Implementation of the PCR Act, 1955 and the SC/ST (PoA) Act, 1989",
    "umbrella": "Umbrella Scheme for Development of Scheduled Castes",
    "type": "Centrally Sponsored",
    "who": [
      "atrocity",
      "sc"
    ],
    "offers": [
      "protection"
    ],
    "provides": "Relief and rehabilitation of atrocity victims and their dependants; an incentive for inter-caste marriages where one spouse is a Scheduled Caste; SC/ST Protection Cells, special police stations and exclusive special courts.",
    "named": "Victims of atrocities under the two Acts, and their dependants, through the State Government.",
    "apply": [
      "nhaa",
      "district"
    ]
  },
  {
    "id": "nhaa",
    "name": "National Helpline Against Atrocities — 14566",
    "umbrella": null,
    "type": "Helpline",
    "who": [
      "atrocity",
      "sc"
    ],
    "offers": [
      "protection"
    ],
    "provides": "A toll-free, round-the-clock helpline in Hindi, English and regional languages that registers complaints under the PoA Act and follows them to an FIR.",
    "named": "Anyone reporting an atrocity against a member of a Scheduled Caste or Scheduled Tribe.",
    "apply": [
      "nhaa"
    ]
  },
  {
    "id": "ncsc-egmp",
    "name": "NCSC e-Grievance Management Portal",
    "umbrella": null,
    "type": "Grievance",
    "who": [
      "sc"
    ],
    "offers": [
      "protection"
    ],
    "provides": "Lodging and tracking of a complaint about deprivation of the rights and safeguards of Scheduled Castes, with SMS and e-mail updates at each stage.",
    "named": "Any member of a Scheduled Caste with a grievance about a safeguard.",
    "apply": [
      "ncsc"
    ]
  },
  {
    "id": "namaste",
    "name": "National Action for Mechanised Sanitation Ecosystem (NAMASTE)",
    "umbrella": null,
    "type": "Central Sector",
    "who": [
      "safai"
    ],
    "offers": [
      "care",
      "skill",
      "loan"
    ],
    "provides": "Profiling and a NAMASTE card; PPE kits and safety training; health cover under Ayushman Bharat PM-JAY; capital subsidy for sanitation vehicles and equipment under Swachhta Udyami Yojana; skill training with stipend for manual scavengers and dependants.",
    "named": "Sewer and septic tank workers, waste pickers, and manual scavengers and their dependants.",
    "apply": [
      "namaste",
      "nskfdc"
    ],
    "page": "https://socialjustice.gov.in/schemes/37"
  },
  {
    "id": "nskfdc-loans",
    "name": "NSKFDC Concessional Loans",
    "umbrella": null,
    "type": "Corporation",
    "who": [
      "safai"
    ],
    "offers": [
      "loan"
    ],
    "provides": "Concessional loans for income-generating activities and education, with priority to women through Mahila Samridhi Yojana and Mahila Adhikarita Yojana.",
    "named": "Safai Karamcharis including waste pickers, manual scavengers, and their dependants.",
    "apply": [
      "nskfdc"
    ]
  },
  {
    "id": "ncsk",
    "name": "National Commission for Safai Karamcharis",
    "umbrella": null,
    "type": "Grievance",
    "who": [
      "safai"
    ],
    "offers": [
      "protection"
    ],
    "provides": "Investigation of grievances of Safai Karamcharis, and pursuit of compensation in sewer and septic tank death and disability cases.",
    "named": "Safai Karamcharis and the families of sewer and septic tank workers.",
    "apply": [
      "ncsk"
    ]
  },
  {
    "id": "nsfdc-loans",
    "name": "NSFDC Concessional Loans",
    "umbrella": null,
    "type": "Corporation",
    "who": [
      "sc"
    ],
    "offers": [
      "loan"
    ],
    "provides": "Micro finance up to ₹1.40 lakh, term loans up to ₹50 lakh and education loans up to ₹40 lakh at concessional interest, through State Channelising Agencies and banks.",
    "named": "Scheduled Caste families within the Corporation's income ceiling.",
    "apply": [
      "nsfdc"
    ],
    "page": "https://socialjustice.gov.in/schemes/34"
  },
  {
    "id": "nbcfdc-loans",
    "name": "NBCFDC Concessional Loans",
    "umbrella": null,
    "type": "Corporation",
    "who": [
      "obc"
    ],
    "offers": [
      "loan"
    ],
    "provides": "Individual loans up to ₹25 lakh, group loans up to ₹25 lakh per self-help group, and education loans up to ₹25 lakh at concessional interest.",
    "named": "Members of Backward Classes with annual family income up to ₹3 lakh.",
    "apply": [
      "nbcfdc"
    ]
  },
  {
    "id": "visvas",
    "name": "VISVAS Yojana — Interest Subvention",
    "umbrella": null,
    "type": "Central Sector",
    "who": [
      "sc",
      "obc",
      "safai"
    ],
    "offers": [
      "loan"
    ],
    "provides": "A 5% interest subvention, paid by direct benefit transfer, on income-generating loans up to ₹5 lakh for individuals and ₹10 lakh for self-help groups.",
    "named": "SC and OBC borrowers with family income up to ₹3 lakh, and Safai Karamcharis with no income limit, holding standard loan accounts.",
    "apply": [
      "bank"
    ]
  },
  {
    "id": "vcf",
    "name": "Venture Capital Fund for SCs and for Backward Classes, with ASIIM",
    "umbrella": null,
    "type": "Central Sector",
    "who": [
      "sc",
      "obc"
    ],
    "offers": [
      "loan"
    ],
    "provides": "Concessional finance from ₹10 lakh to ₹15 crore for SC enterprises and ₹20 lakh to ₹15 crore for Backward Class enterprises; equity up to ₹30 lakh for SC youth start-ups under ASIIM.",
    "named": "SC and Backward Class entrepreneurs and start-ups.",
    "apply": [
      "ifci"
    ]
  },
  {
    "id": "pm-daksh",
    "name": "PM-DAKSH — Skill Training",
    "umbrella": null,
    "type": "Central Sector",
    "who": [
      "sc",
      "obc",
      "dnt",
      "safai"
    ],
    "offers": [
      "skill"
    ],
    "provides": "Free skill training, from up-skilling to long-term courses, with a stipend or boarding and lodging, and placement support.",
    "named": "Persons aged 18 to 45 from Scheduled Castes, DNTs and sanitation work with no income limit; OBCs with family income up to ₹3 lakh; EBCs up to ₹1 lakh.",
    "apply": [
      "pmdaksh"
    ]
  },
  {
    "id": "avyay-ipsrc",
    "name": "Integrated Programme for Senior Citizens",
    "umbrella": "Atal Vayo Abhyuday Yojana",
    "type": "Centrally Sponsored",
    "who": [
      "senior",
      "ngo"
    ],
    "offers": [
      "care",
      "grant"
    ],
    "provides": "Grant-in-aid to organisations running senior citizen homes, continuous care homes and day-care centres that give free shelter, food, medical care and recreation.",
    "named": "Indigent senior citizens; and organisations working in old-age care for at least two years.",
    "apply": [
      "eanudaan"
    ],
    "offersFor": {
      "grant": [
        "ngo"
      ],
      "care": [
        "senior"
      ]
    }
  },
  {
    "id": "avyay-rvy",
    "name": "Rashtriya Vayoshri Yojana",
    "umbrella": "Atal Vayo Abhyuday Yojana",
    "type": "Central Sector",
    "who": [
      "senior"
    ],
    "offers": [
      "care"
    ],
    "provides": "Free physical aids and assistive devices for age-related disability or infirmity, distributed through ALIMCO camps.",
    "named": "Senior citizens aged 60 or above, holding Aadhaar, who are BPL or have a monthly income of not more than ₹15,000.",
    "apply": [
      "alimco"
    ]
  },
  {
    "id": "avyay-elderline",
    "name": "Elderline — National Helpline for Senior Citizens, 14567",
    "umbrella": "Atal Vayo Abhyuday Yojana",
    "type": "Helpline",
    "who": [
      "senior"
    ],
    "offers": [
      "care",
      "protection"
    ],
    "provides": "Free information, guidance, emotional support and field intervention in cases of abuse and rescue, in every State and UT.",
    "named": "All senior citizens.",
    "apply": [
      "elderline"
    ]
  },
  {
    "id": "avyay-caregivers",
    "name": "Training of Geriatric Caregivers",
    "umbrella": "Atal Vayo Abhyuday Yojana",
    "type": "Central Sector",
    "who": [
      "senior"
    ],
    "offers": [
      "skill"
    ],
    "provides": "Certified training in geriatric care at medical and nursing colleges and NISD-affiliated institutes, to create a pool of professional caregivers.",
    "named": "Persons aged 18 or above with the qualification the job role requires.",
    "apply": [
      "nisd"
    ]
  },
  {
    "id": "napddr",
    "name": "National Action Plan for Drug Demand Reduction and Nasha Mukt Bharat Abhiyaan",
    "umbrella": "Umbrella Programme for Development of Other Vulnerable Groups",
    "type": "Centrally Sponsored",
    "who": [
      "drug",
      "ngo"
    ],
    "offers": [
      "deaddiction",
      "grant"
    ],
    "provides": "Integrated Rehabilitation Centres for Addicts, Outreach and Drop-In Centres, District De-Addiction Centres and Addiction Treatment Facilities in government hospitals; the toll-free de-addiction helpline 14446; grant-in-aid to the voluntary organisations that run the centres.",
    "named": "Persons dependent on alcohol or drugs and their families; and NGOs running de-addiction and outreach centres.",
    "apply": [
      "nmba",
      "eanudaan"
    ],
    "offersFor": {
      "grant": [
        "ngo"
      ],
      "deaddiction": [
        "drug"
      ]
    }
  },
  {
    "id": "smile-begging",
    "name": "SMILE — Comprehensive Rehabilitation of Persons Engaged in Begging",
    "umbrella": "SMILE",
    "type": "Central Sector",
    "who": [
      "begging"
    ],
    "offers": [
      "care",
      "skill"
    ],
    "provides": "Survey and identification, outreach and rescue, shelter homes with food, clothing, counselling and medical aid, and rehabilitation through education, skilling and self-employment; in 181 cities.",
    "named": "Persons engaged in begging, and their children.",
    "apply": [
      "smile"
    ],
    "page": "https://socialjustice.gov.in/schemes/99"
  },
  {
    "id": "smile-tg",
    "name": "SMILE — Comprehensive Rehabilitation for Welfare of Transgender Persons",
    "umbrella": "SMILE",
    "type": "Central Sector",
    "who": [
      "tg",
      "ngo"
    ],
    "offers": [
      "care",
      "skill",
      "protection",
      "grant"
    ],
    "provides": "A certificate of identity through the National Portal for Transgender Persons; Garima Greh shelter homes; health cover under Ayushman Bharat PM-JAY; skill development and entrepreneurship training; Transgender Protection Cells in the States.",
    "named": "Transgender persons holding a certificate of identity issued through the National Portal; and CBOs and NGOs able to run a shelter home.",
    "apply": [
      "tgportal",
      "eanudaan"
    ],
    "offersFor": {
      "grant": [
        "ngo"
      ],
      "care": [
        "tg"
      ],
      "skill": [
        "tg"
      ],
      "protection": [
        "tg"
      ]
    },
    "page": "https://socialjustice.gov.in/schemes/99"
  },
  {
    "id": "yasasvi-pre",
    "name": "PM-YASASVI Pre-Matric Scholarship for OBC, EBC and DNT Students",
    "umbrella": "PM-YASASVI",
    "type": "Centrally Sponsored",
    "who": [
      "obc",
      "dnt",
      "student"
    ],
    "offers": [
      "scholarship"
    ],
    "provides": "A consolidated academic allowance of ₹4,000 a year, paid by direct benefit transfer.",
    "named": "OBC, EBC and DNT students in Class IX and X in Government schools, with family income up to ₹2.5 lakh.",
    "apply": [
      "state",
      "nsp"
    ],
    "page": "https://socialjustice.gov.in/schemes/101"
  },
  {
    "id": "yasasvi-post",
    "name": "PM-YASASVI Post-Matric Scholarship for OBC, EBC and DNT Students",
    "umbrella": "PM-YASASVI",
    "type": "Centrally Sponsored",
    "who": [
      "obc",
      "dnt",
      "student"
    ],
    "offers": [
      "scholarship"
    ],
    "provides": "An academic allowance of ₹5,000 to ₹20,000 a year by category of course, for study after Class X.",
    "named": "OBC, EBC and DNT students at the post-matric stage, with family income up to ₹2.5 lakh.",
    "apply": [
      "state",
      "nsp"
    ],
    "page": "https://socialjustice.gov.in/schemes/101"
  },
  {
    "id": "yasasvi-school",
    "name": "PM-YASASVI Top Class School Education for OBC, EBC and DNT Students",
    "umbrella": "PM-YASASVI",
    "type": "Centrally Sponsored",
    "who": [
      "obc",
      "dnt",
      "student"
    ],
    "offers": [
      "scholarship",
      "schooling"
    ],
    "provides": "Tuition, hostel and other school charges up to ₹75,000 a year in Class 9 and 10 and ₹1,25,000 a year in Class 11 and 12, at shortlisted top schools; 30% of scholarships for girls.",
    "named": "OBC, EBC and DNT students admitted to a shortlisted school, with household income under ₹2.5 lakh; selected on the National Scholarship Portal merit list.",
    "apply": [
      "nsp"
    ]
  },
  {
    "id": "yasasvi-college",
    "name": "PM-YASASVI Top Class College Education for OBC, EBC and DNT Students",
    "umbrella": "PM-YASASVI",
    "type": "Centrally Sponsored",
    "who": [
      "obc",
      "dnt",
      "student"
    ],
    "offers": [
      "scholarship"
    ],
    "provides": "Full tuition and non-refundable charges, living expenses of ₹3,000 a month, ₹5,000 a year for books, and a one-time laptop allowance of ₹45,000, at IIMs, IITs, AIIMS, NITs, NLUs and other notified institutions.",
    "named": "OBC, EBC and DNT students with family income up to ₹2.5 lakh admitted to a notified institution; 30% of slots for girl students.",
    "apply": [
      "nsp"
    ]
  },
  {
    "id": "yasasvi-hostel",
    "name": "Construction of Hostels for OBC Boys and Girls",
    "umbrella": "PM-YASASVI",
    "type": "Centrally Sponsored",
    "who": [
      "obc",
      "student"
    ],
    "offers": [
      "schooling"
    ],
    "provides": "Central assistance to States, UTs and NIRF-ranked institutions to build hostels for OBC students near Government schools, colleges and universities.",
    "named": "OBC students from rural areas, through the institution or State that builds the hostel.",
    "apply": [
      "institution"
    ]
  },
  {
    "id": "nfobc",
    "name": "National Fellowship for OBC Students",
    "umbrella": "SHREYAS for OBCs and EBCs",
    "type": "Central Sector",
    "who": [
      "obc",
      "student"
    ],
    "offers": [
      "scholarship"
    ],
    "provides": "A Junior and Senior Research Fellowship at UGC rates for M.Phil. and Ph.D.; 1,000 fellowships a year, 750 in humanities and social sciences and 250 in science.",
    "named": "OBC students who have qualified UGC NET-JRF or UGC-CSIR NET-JRF.",
    "apply": [
      "nbcfdc"
    ]
  },
  {
    "id": "interest-subsidy-overseas",
    "name": "Dr. Ambedkar Interest Subsidy on Education Loans for Overseas Studies for OBCs and EBCs",
    "umbrella": "SHREYAS for OBCs and EBCs",
    "type": "Central Sector",
    "who": [
      "obc",
      "student"
    ],
    "offers": [
      "scholarship",
      "loan"
    ],
    "provides": "The full interest for the moratorium period on an education loan of up to ₹20 lakh for a Master's, M.Phil. or Ph.D. abroad; half of the assistance reserved for women.",
    "named": "OBC candidates within the creamy-layer limit and EBC candidates with family income up to ₹5 lakh, admitted to an approved course abroad.",
    "apply": [
      "canara"
    ]
  },
  {
    "id": "seed",
    "name": "Scheme for Economic Empowerment of DNTs (SEED)",
    "umbrella": null,
    "type": "Central Sector",
    "who": [
      "dnt",
      "student"
    ],
    "offers": [
      "schooling",
      "care",
      "skill"
    ],
    "provides": "Free coaching for competitive examinations; health insurance through Ayushman Bharat; livelihood support through self-help groups; and financial assistance for housing through PM Awas Yojana.",
    "named": "Members of De-notified, Nomadic and Semi-Nomadic communities holding a DNT certificate.",
    "apply": [
      "seed"
    ],
    "page": "https://socialjustice.gov.in/schemes/109"
  },
  {
    "id": "pm-cares-scholarship",
    "name": "Special Scholarship under PM CARES for Children",
    "umbrella": null,
    "type": "Central Sector",
    "who": [
      "student"
    ],
    "offers": [
      "scholarship"
    ],
    "provides": "₹20,000 a year for a child in Class 1 to 12: a monthly allowance of ₹1,000 and an academic allowance of ₹8,000 for fees, books, uniform and equipment.",
    "named": "Children who lost both parents, or their legal guardian or surviving parent, to COVID-19, identified by the District Magistrate under the PM CARES for Children scheme.",
    "apply": [
      "wcd"
    ]
  },
  {
    "id": "daf-medical-aid",
    "name": "Dr. Ambedkar Medical Aid Scheme",
    "umbrella": "Dr. Ambedkar Foundation",
    "type": "Foundation",
    "who": [
      "sc"
    ],
    "offers": [
      "care"
    ],
    "provides": "Medical treatment for serious ailments requiring surgery of the kidney, heart, liver, brain, cancer or other life-threatening disease.",
    "named": "SC and ST patients with annual family income under ₹3 lakh.",
    "apply": [
      "daf"
    ]
  },
  {
    "id": "daf-merit-award",
    "name": "Dr. Ambedkar National Merit Awards for Class 10 and Class 12",
    "umbrella": "Dr. Ambedkar Foundation",
    "type": "Foundation",
    "who": [
      "sc",
      "student"
    ],
    "offers": [
      "scholarship"
    ],
    "provides": "Cash awards of ₹40,000 to ₹60,000 for the top three SC and ST students of each recognised Board in Class 10, with a separate award for the highest-scoring girl; awards for SC students in Class 12 in four streams.",
    "named": "SC and ST students who scored at least 50% in a recognised Board's secondary examination; SC students in the senior secondary examination.",
    "apply": [
      "daf"
    ]
  },
  {
    "id": "eanudaan",
    "name": "e-Anudaan — Grant-in-Aid to Voluntary Organisations",
    "umbrella": null,
    "type": "Portal",
    "who": [
      "ngo"
    ],
    "offers": [
      "grant"
    ],
    "provides": "Online application, processing and sanction of grant-in-aid for five Department schemes, with NGO Darpan verification and PFMS payment.",
    "named": "Voluntary organisations registered on NGO Darpan applying under AVYAY, NAPDDR, SHRESHTA Mode II, SMILE and the Department's other grant schemes.",
    "apply": [
      "eanudaan"
    ]
  }
];

/** Does this record provide `offer` to `who`? Same rule as the prototypes' data.js. */
export function sdPairOk(s: SdScheme, who?: string, offer?: string): boolean {
  if (who && !s.who.includes(who)) return false;
  if (offer && !s.offers.includes(offer)) return false;
  if (who && offer && s.offersFor?.[offer] && !s.offersFor[offer].includes(who)) return false;
  if (who && !offer && s.offersFor) return s.offers.some((o) => !s.offersFor?.[o] || s.offersFor[o].includes(who));
  return true;
}
export function sdMatch(who?: string, offer?: string): SdScheme[] {
  return SD_SCHEMES.filter((s) => sdPairOk(s, who, offer));
}
export function sdOffersFor(who: string): SdOffering[] {
  return SD_OFFERINGS.filter((o) => SD_SCHEMES.some((s) => sdPairOk(s, who, o.id)));
}
/** "Apply on" a portal, "Call" a helpline, "Apply through" an office or agency. */
export function sdApplyLabel(routeId: string | undefined): string {
  const r = routeId ? SD_ROUTES[routeId] : undefined;
  if (!r) return "Apply";
  if (r.href?.startsWith("tel:")) return `Call ${r.label}`;
  return (/portal/i.test(r.label) ? "Apply on " : "Apply through ") + r.label;
}
