/* GENERATED by @mosje/tokens (build/generate-typography-docs-data.mjs) — do not edit.

   Every NUMBER here is read from packages/tokens/src/primitive.json, so this page cannot state
   a size, line height, tracking or paragraph spacing the token source does not declare. It
   replaced 168 hand-typed values which were correct at the time and had no way of staying that
   way — the same shape of table that left the colour page printing 14 dead colours.

   The bilingual specimens, tier blurbs and surface notes are WRITING, not derived values, so
   they stay hand-authored in typography-content.json. Edit them there.

   Regenerate: npm run build -w @mosje/tokens */

export type Surface = "website" | "portal";
export type Tier = "display" | "headline" | "title" | "body" | "label";

export interface RoleSpec {
  role: string;
  tier: Tier;
  weight: string;
  weightVal: number;
  size: Record<Surface, [number, number]>;
  lh: Record<Surface, [number, number]>;
  tracking: Record<Surface, [number, number]>;
  para: [number, number];
  en: string;
  hi: string;
}

export const ROLES: RoleSpec[] = [
  {
    "role": "display-1",
    "tier": "display",
    "weight": "Medium",
    "weightVal": 500,
    "size": {
      "website": [
        40,
        80
      ],
      "portal": [
        40,
        56
      ]
    },
    "lh": {
      "website": [
        44,
        88
      ],
      "portal": [
        48,
        64
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        -0.8,
        -1.12
      ]
    },
    "para": [
      24,
      32
    ],
    "en": "Digital India, Inclusive India",
    "hi": "डिजिटल भारत, समावेशी भारत"
  },
  {
    "role": "display-2",
    "tier": "display",
    "weight": "Medium",
    "weightVal": 500,
    "size": {
      "website": [
        36,
        72
      ],
      "portal": [
        32,
        48
      ]
    },
    "lh": {
      "website": [
        40,
        80
      ],
      "portal": [
        40,
        56
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        -0.64,
        -0.96
      ]
    },
    "para": [
      20,
      32
    ],
    "en": "Justice for every citizen",
    "hi": "हर नागरिक के लिए न्याय"
  },
  {
    "role": "display-3",
    "tier": "display",
    "weight": "Medium",
    "weightVal": 500,
    "size": {
      "website": [
        32,
        64
      ],
      "portal": [
        28,
        40
      ]
    },
    "lh": {
      "website": [
        36,
        72
      ],
      "portal": [
        36,
        48
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        -0.42,
        -0.6
      ]
    },
    "para": [
      16,
      24
    ],
    "en": "Empowerment through schemes",
    "hi": "योजनाओं से सशक्तिकरण"
  },
  {
    "role": "display-4",
    "tier": "display",
    "weight": "Medium",
    "weightVal": 500,
    "size": {
      "website": [
        28,
        56
      ],
      "portal": [
        24,
        32
      ]
    },
    "lh": {
      "website": [
        32,
        64
      ],
      "portal": [
        32,
        40
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        -0.24,
        -0.32
      ]
    },
    "para": [
      16,
      24
    ],
    "en": "Dignity, access, opportunity",
    "hi": "गरिमा, पहुँच, अवसर"
  },
  {
    "role": "display-5",
    "tier": "display",
    "weight": "Medium",
    "weightVal": 500,
    "size": {
      "website": [
        26,
        48
      ],
      "portal": [
        22,
        28
      ]
    },
    "lh": {
      "website": [
        28,
        56
      ],
      "portal": [
        28,
        36
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        -0.22,
        -0.28
      ]
    },
    "para": [
      16,
      20
    ],
    "en": "Serving the last mile",
    "hi": "अंतिम छोर तक सेवा"
  },
  {
    "role": "display-6",
    "tier": "display",
    "weight": "Medium",
    "weightVal": 500,
    "size": {
      "website": [
        24,
        40
      ],
      "portal": [
        20,
        24
      ]
    },
    "lh": {
      "website": [
        28,
        48
      ],
      "portal": [
        28,
        32
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      16,
      20
    ],
    "en": "A portal for every scheme",
    "hi": "हर योजना का पोर्टल"
  },
  {
    "role": "headline-1",
    "tier": "headline",
    "weight": "SemiBold",
    "weightVal": 600,
    "size": {
      "website": [
        28,
        40
      ],
      "portal": [
        24,
        32
      ]
    },
    "lh": {
      "website": [
        32,
        48
      ],
      "portal": [
        32,
        40
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      20,
      24
    ],
    "en": "Ministry of Social Justice & Empowerment",
    "hi": "सामाजिक न्याय और अधिकारिता मंत्रालय"
  },
  {
    "role": "headline-2",
    "tier": "headline",
    "weight": "SemiBold",
    "weightVal": 600,
    "size": {
      "website": [
        24,
        32
      ],
      "portal": [
        20,
        28
      ]
    },
    "lh": {
      "website": [
        28,
        40
      ],
      "portal": [
        28,
        36
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      16,
      24
    ],
    "en": "PM-AJAY Scheme Dashboard",
    "hi": "पीएम-अजय योजना डैशबोर्ड"
  },
  {
    "role": "headline-3",
    "tier": "headline",
    "weight": "SemiBold",
    "weightVal": 600,
    "size": {
      "website": [
        22,
        28
      ],
      "portal": [
        18,
        24
      ]
    },
    "lh": {
      "website": [
        28,
        32
      ],
      "portal": [
        24,
        32
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      16,
      20
    ],
    "en": "Scholarship applications this quarter",
    "hi": "इस तिमाही की छात्रवृत्ति आवेदन"
  },
  {
    "role": "headline-4",
    "tier": "headline",
    "weight": "SemiBold",
    "weightVal": 600,
    "size": {
      "website": [
        20,
        24
      ],
      "portal": [
        16,
        20
      ]
    },
    "lh": {
      "website": [
        24,
        28
      ],
      "portal": [
        24,
        28
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      16,
      20
    ],
    "en": "Beneficiary verification status",
    "hi": "लाभार्थी सत्यापन स्थिति"
  },
  {
    "role": "headline-5",
    "tier": "headline",
    "weight": "SemiBold",
    "weightVal": 600,
    "size": {
      "website": [
        18,
        20
      ],
      "portal": [
        15,
        18
      ]
    },
    "lh": {
      "website": [
        24,
        24
      ],
      "portal": [
        20,
        24
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      12,
      16
    ],
    "en": "Recent grievances",
    "hi": "हाल की शिकायतें"
  },
  {
    "role": "headline-6",
    "tier": "headline",
    "weight": "SemiBold",
    "weightVal": 600,
    "size": {
      "website": [
        16,
        16
      ],
      "portal": [
        14,
        16
      ]
    },
    "lh": {
      "website": [
        20,
        20
      ],
      "portal": [
        20,
        24
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      12,
      16
    ],
    "en": "Documents required",
    "hi": "आवश्यक दस्तावेज़"
  },
  {
    "role": "title-1",
    "tier": "title",
    "weight": "Medium",
    "weightVal": 500,
    "size": {
      "website": [
        18,
        22
      ],
      "portal": [
        16,
        20
      ]
    },
    "lh": {
      "website": [
        24,
        28
      ],
      "portal": [
        24,
        28
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      16,
      20
    ],
    "en": "Section heading and panel title",
    "hi": "अनुभाग शीर्षक और पैनल शीर्षक"
  },
  {
    "role": "title-2",
    "tier": "title",
    "weight": "Medium",
    "weightVal": 500,
    "size": {
      "website": [
        16,
        16
      ],
      "portal": [
        15,
        18
      ]
    },
    "lh": {
      "website": [
        24,
        24
      ],
      "portal": [
        20,
        24
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      12,
      16
    ],
    "en": "List headers and compact titles",
    "hi": "सूची शीर्षक और संक्षिप्त शीर्षक"
  },
  {
    "role": "title-3",
    "tier": "title",
    "weight": "Medium",
    "weightVal": 500,
    "size": {
      "website": [
        14,
        14
      ],
      "portal": [
        14,
        16
      ]
    },
    "lh": {
      "website": [
        20,
        20
      ],
      "portal": [
        20,
        24
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      12,
      16
    ],
    "en": "Sidebar and tertiary labels",
    "hi": "साइडबार और तृतीयक लेबल"
  },
  {
    "role": "body-1",
    "tier": "body",
    "weight": "Regular",
    "weightVal": 400,
    "size": {
      "website": [
        16,
        16
      ],
      "portal": [
        14,
        16
      ]
    },
    "lh": {
      "website": [
        24,
        24
      ],
      "portal": [
        20,
        24
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      12,
      16
    ],
    "en": "Submit your application along with all required documents.",
    "hi": "सभी आवश्यक दस्तावेज़ों के साथ अपना आवेदन जमा करें।"
  },
  {
    "role": "body-2",
    "tier": "body",
    "weight": "Regular",
    "weightVal": 400,
    "size": {
      "website": [
        14,
        14
      ],
      "portal": [
        13,
        14
      ]
    },
    "lh": {
      "website": [
        20,
        20
      ],
      "portal": [
        20,
        20
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      12,
      12
    ],
    "en": "Secondary information, helper text, and table cell content.",
    "hi": "द्वितीयक जानकारी, सहायक पाठ और तालिका सामग्री।"
  },
  {
    "role": "body-3",
    "tier": "body",
    "weight": "Regular",
    "weightVal": 400,
    "size": {
      "website": [
        12,
        12
      ],
      "portal": [
        12,
        13
      ]
    },
    "lh": {
      "website": [
        16,
        16
      ],
      "portal": [
        20,
        20
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      12,
      12
    ],
    "en": "Captions, timestamps, and fine print.",
    "hi": "कैप्शन, समय-चिह्न और बारीक अक्षर।"
  },
  {
    "role": "label-1",
    "tier": "label",
    "weight": "Medium",
    "weightVal": 500,
    "size": {
      "website": [
        14,
        14
      ],
      "portal": [
        14,
        14
      ]
    },
    "lh": {
      "website": [
        20,
        20
      ],
      "portal": [
        20,
        20
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      12,
      12
    ],
    "en": "Form label · Applicant name",
    "hi": "फ़ॉर्म लेबल · आवेदक का नाम"
  },
  {
    "role": "label-2",
    "tier": "label",
    "weight": "Medium",
    "weightVal": 500,
    "size": {
      "website": [
        12,
        12
      ],
      "portal": [
        12,
        12
      ]
    },
    "lh": {
      "website": [
        16,
        16
      ],
      "portal": [
        16,
        16
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      8,
      8
    ],
    "en": "Badge · Verified",
    "hi": "बैज · सत्यापित"
  },
  {
    "role": "label-3",
    "tier": "label",
    "weight": "Medium",
    "weightVal": 500,
    "size": {
      "website": [
        11,
        11
      ],
      "portal": [
        11,
        11
      ]
    },
    "lh": {
      "website": [
        16,
        16
      ],
      "portal": [
        16,
        16
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      8,
      8
    ],
    "en": "STATUS · UPLOADED",
    "hi": "स्थिति · अपलोड"
  }
];

export const TIERS: { key: Tier; label: string; blurb: string }[] = [
  {
    "key": "display",
    "label": "Display",
    "blurb": "Hero and marketing headings"
  },
  {
    "key": "headline",
    "label": "Headline",
    "blurb": "Page and section headings (h1–h3)"
  },
  {
    "key": "title",
    "label": "Title",
    "blurb": "Panel, list and card titles"
  },
  {
    "key": "body",
    "label": "Body",
    "blurb": "Running text and paragraphs"
  },
  {
    "key": "label",
    "label": "Label",
    "blurb": "UI controls, badges, captions"
  }
];

export const SURFACES: { key: Surface; label: string; note: string; sample: string }[] = [
  {
    "key": "website",
    "label": "Website",
    "note": "dosje.gov.in · expressive, editorial",
    "sample": "display-1 = 80px"
  },
  {
    "key": "portal",
    "label": "Portal",
    "note": "20+ workflow portals · dense, functional",
    "sample": "display-1 = 56px"
  }
];

export interface StandardsRule { rule: string; src: string }
export interface StandardsGroup { title: string; rules: StandardsRule[] }

/**
 * The typography rules, grouped as UX4G groups them, each tagged to the standard it comes from
 * so a reviewer can audit rather than trust. Editorial — authored in typography-content.json.
 *
 * This export was LOST when the generator first replaced this file: the generated version
 * compiled fine on its own and only failed once it met the page that imports it. Regenerating a
 * file means owning every export it had, not just the ones you came for.
 */
export const STANDARDS: StandardsGroup[] = [
  {
    "title": "Consistency",
    "rules": [
      {
        "rule": "Noto Sans is the typeface for every MoSJE property. No second family is introduced for display or accent.",
        "src": "DBIM 4.1"
      },
      {
        "rule": "Body text is left-aligned. Never justified, never centred for running paragraphs.",
        "src": "DBIM 4.1.1"
      },
      {
        "rule": "In tables: text left, numbers right, column headers centred.",
        "src": "DBIM 4.1.1"
      },
      {
        "rule": "No Hinglish. Write English or हिन्दी, each in its own script, each marked with lang.",
        "src": "DBIM 4.1.1"
      }
    ]
  },
  {
    "title": "Hierarchy",
    "rules": [
      {
        "rule": "One h1 per page, and heading order never skips a level.",
        "src": "GIGW · WCAG 1.3.1"
      },
      {
        "rule": "Pick a role by the job it does, not by the size it happens to be — the tiers overlap.",
        "src": "SAMAVESH"
      },
      {
        "rule": "Display carries presence; Headline carries document structure. Do not substitute one for the other.",
        "src": "SAMAVESH"
      },
      {
        "rule": "The 21-role scale is the DBIM type scale as implemented — no ad-hoc sizes outside it.",
        "src": "DBIM 4.3.1"
      }
    ]
  },
  {
    "title": "Spacing",
    "rules": [
      {
        "rule": "Latin body sits at 1.5–1.7 line height; Devanagari body targets ~1.7 at the same point size.",
        "src": "SAMAVESH · DBIM 4.3.1"
      },
      {
        "rule": "ALL-CAPS is never used for a sentence or paragraph — only 1–3 word labels, always with added tracking.",
        "src": "DBIM 4.1.1"
      },
      {
        "rule": "Measure stays between 45 and 75 characters; body copy is capped rather than run full width.",
        "src": "SAMAVESH"
      },
      {
        "rule": "Text spacing must survive user overrides of line height, word and letter spacing without clipping.",
        "src": "GIGW · WCAG 1.4.12"
      }
    ]
  },
  {
    "title": "Colour & contrast",
    "rules": [
      {
        "rule": "Body text ≥ 4.5:1 against its background; large text ≥ 3:1.",
        "src": "DBIM 4.4 · WCAG 1.4.3"
      },
      {
        "rule": "At 11px (label-3) treat 4.5:1 as a floor rather than a target, and avoid tinted fills behind it.",
        "src": "SAMAVESH"
      },
      {
        "rule": "In dbim brand mode, text uses shade 1 or 2 of the key colour group.",
        "src": "DBIM 4.4"
      }
    ]
  },
  {
    "title": "Responsiveness",
    "rules": [
      {
        "rule": "Text resizes to 200% with no loss of content or function.",
        "src": "GIGW · WCAG 1.4.4"
      },
      {
        "rule": "Content reflows at a 320px equivalent without two-dimensional scrolling.",
        "src": "GIGW · WCAG 1.4.10"
      },
      {
        "rule": "Sizes are fluid between 360px and 1280px — no type breakpoints, and no role grows as the viewport shrinks.",
        "src": "SAMAVESH"
      },
      {
        "rule": "Text-entry controls hold a hard 16px floor below 768px so iOS Safari does not trap the user zoomed in.",
        "src": "SAMAVESH · GIGW"
      }
    ]
  }
];

/** Round to 3dp for display, drop trailing zeros. */
export const px = (n: number): string => `${Math.round(n * 1000) / 1000}px`;
