/* GENERATED by @mosje/tokens (build/generate-typography-docs-data.mjs) — do not edit.

   Every NUMBER here is read from packages/tokens/src/primitive.json, so this page cannot state
   a size, line height, tracking or paragraph spacing the token source does not declare. It
   replaced 168 hand-typed values which were correct at the time and had no way of staying that
   way — the same shape of table that left the colour page printing 14 dead colours.

   The bilingual specimens, tier blurbs and surface notes are WRITING, not derived values, so
   they stay hand-authored in typography-content.json. Edit them there.

   Regenerate: npm run build -w @mosje/tokens */

export type Surface = "website" | "portal";
export type Tier = "display" | "headline" | "title" | "body" | "label";

export interface RoleSpec {
  role: string;
  tier: Tier;
  weight: string;
  weightVal: number;
  size: Record<Surface, [number, number]>;
  lh: Record<Surface, [number, number]>;
  tracking: Record<Surface, [number, number]>;
  para: [number, number];
  en: string;
  hi: string;
  /** Why the value is what it is — from the token source, mirrored in the Figma variable description. */
  why: string;
}

export const ROLES: RoleSpec[] = [
  {
    "role": "display-1",
    "tier": "display",
    "weight": "Medium",
    "weightVal": 500,
    "size": {
      "website": [
        40,
        80
      ],
      "portal": [
        40,
        56
      ]
    },
    "lh": {
      "website": [
        48,
        88
      ],
      "portal": [
        48,
        64
      ]
    },
    "tracking": {
      "website": [
        -0.6,
        -1.2
      ],
      "portal": [
        -0.6,
        -0.84
      ]
    },
    "para": [
      24,
      32
    ],
    "en": "Digital India, Inclusive India",
    "hi": "डिजिटल भारत, समावेशी भारत",
    "why": "The largest thing on the estate — one per hero, never for document structure. Website 40 → 80 / 48 → 88 (1.10 desktop, 1.20 phone); Portal 40 → 56 / 48 → 64. Tracking −0.015em."
  },
  {
    "role": "display-2",
    "tier": "display",
    "weight": "Medium",
    "weightVal": 500,
    "size": {
      "website": [
        36,
        72
      ],
      "portal": [
        32,
        48
      ]
    },
    "lh": {
      "website": [
        44,
        80
      ],
      "portal": [
        40,
        56
      ]
    },
    "tracking": {
      "website": [
        -0.54,
        -1.08
      ],
      "portal": [
        -0.48,
        -0.72
      ]
    },
    "para": [
      20,
      32
    ],
    "en": "Justice for every citizen",
    "hi": "हर नागरिक के लिए न्याय",
    "why": "Campaign hero. Website 36 → 72 / 44 → 80; Portal 32 → 48 / 40 → 56. 36 is DBIM §4's desktop H1 and the reason the ramp carries it. Tracking −0.015em."
  },
  {
    "role": "display-3",
    "tier": "display",
    "weight": "Medium",
    "weightVal": 500,
    "size": {
      "website": [
        32,
        64
      ],
      "portal": [
        28,
        40
      ]
    },
    "lh": {
      "website": [
        40,
        72
      ],
      "portal": [
        36,
        48
      ]
    },
    "tracking": {
      "website": [
        -0.32,
        -0.64
      ],
      "portal": [
        -0.28,
        -0.4
      ]
    },
    "para": [
      16,
      24
    ],
    "en": "Empowerment through schemes",
    "hi": "योजनाओं से सशक्तिकरण",
    "why": "The website home page's own hero size. Website 32 → 64 / 40 → 72; Portal 28 → 40 / 36 → 48. Tracking −0.01em."
  },
  {
    "role": "display-4",
    "tier": "display",
    "weight": "Medium",
    "weightVal": 500,
    "size": {
      "website": [
        28,
        56
      ],
      "portal": [
        24,
        32
      ]
    },
    "lh": {
      "website": [
        36,
        64
      ],
      "portal": [
        32,
        40
      ]
    },
    "tracking": {
      "website": [
        -0.28,
        -0.56
      ],
      "portal": [
        -0.24,
        -0.32
      ]
    },
    "para": [
      16,
      24
    ],
    "en": "Dignity, access, opportunity",
    "hi": "गरिमा, पहुँच, अवसर",
    "why": "Section hero, banner headline. Website 28 → 56 / 36 → 64; Portal 24 → 32 / 32 → 40. Tracking −0.01em."
  },
  {
    "role": "display-5",
    "tier": "display",
    "weight": "Medium",
    "weightVal": 500,
    "size": {
      "website": [
        24,
        48
      ],
      "portal": [
        24,
        28
      ]
    },
    "lh": {
      "website": [
        32,
        56
      ],
      "portal": [
        32,
        36
      ]
    },
    "tracking": {
      "website": [
        -0.12,
        -0.24
      ],
      "portal": [
        -0.12,
        -0.14
      ]
    },
    "para": [
      16,
      20
    ],
    "en": "Serving the last mile",
    "hi": "अंतिम छोर तक सेवा",
    "why": "Small hero — a login panel wordmark, a campaign strip. Website 24 → 48 / 32 → 56; Portal 24 → 28 / 32 → 36. Tracking −0.005em."
  },
  {
    "role": "display-6",
    "tier": "display",
    "weight": "Medium",
    "weightVal": 500,
    "size": {
      "website": [
        22,
        40
      ],
      "portal": [
        20,
        24
      ]
    },
    "lh": {
      "website": [
        28,
        48
      ],
      "portal": [
        28,
        32
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      16,
      20
    ],
    "en": "A portal for every scheme",
    "hi": "हर योजना का पोर्टल",
    "why": "The smallest display size, one step above headline-1 so a hero and a page title never share a size. Website 22 → 40 / 28 → 48 (1.20, on DBIM's floor); Portal 20 → 24 / 28 → 32. Tracking 0."
  },
  {
    "role": "headline-1",
    "tier": "headline",
    "weight": "SemiBold",
    "weightVal": 600,
    "size": {
      "website": [
        28,
        40
      ],
      "portal": [
        24,
        32
      ]
    },
    "lh": {
      "website": [
        36,
        48
      ],
      "portal": [
        32,
        40
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      20,
      24
    ],
    "en": "Ministry of Social Justice & Empowerment",
    "hi": "सामाजिक न्याय और अधिकारिता मंत्रालय",
    "why": "The page h1, one per page. Website 28 → 40 / 36 → 48; Portal 24 → 32 / 32 → 40. Leading 1.20 at desktop: the tightest a structural heading is allowed."
  },
  {
    "role": "headline-2",
    "tier": "headline",
    "weight": "SemiBold",
    "weightVal": 600,
    "size": {
      "website": [
        24,
        32
      ],
      "portal": [
        20,
        28
      ]
    },
    "lh": {
      "website": [
        32,
        40
      ],
      "portal": [
        28,
        36
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      16,
      24
    ],
    "en": "PM-AJAY Scheme Dashboard",
    "hi": "पीएम-अजय योजना डैशबोर्ड",
    "why": "Section h2. Website 24 → 32 / 32 → 40; Portal 20 → 28 / 28 → 36. Leading 1.25."
  },
  {
    "role": "headline-3",
    "tier": "headline",
    "weight": "SemiBold",
    "weightVal": 600,
    "size": {
      "website": [
        22,
        28
      ],
      "portal": [
        18,
        24
      ]
    },
    "lh": {
      "website": [
        28,
        36
      ],
      "portal": [
        24,
        32
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      16,
      20
    ],
    "en": "Scholarship applications this quarter",
    "hi": "इस तिमाही की छात्रवृत्ति आवेदन",
    "why": "Sub-section h3. Website 22 → 28 / 28 → 36; Portal 18 → 24 / 24 → 32. Was 28/32 (1.14) — tighter than the h2 above it — until the 2026-09-04 re-cut; now 1.29."
  },
  {
    "role": "headline-4",
    "tier": "headline",
    "weight": "SemiBold",
    "weightVal": 600,
    "size": {
      "website": [
        20,
        24
      ],
      "portal": [
        16,
        20
      ]
    },
    "lh": {
      "website": [
        28,
        32
      ],
      "portal": [
        24,
        28
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      16,
      20
    ],
    "en": "Beneficiary verification status",
    "hi": "लाभार्थी सत्यापन स्थिति",
    "why": "h4, and the SectionTitle component. Website 20 → 24 / 28 → 32; Portal 16 → 20 / 24 → 28. Leading 1.33."
  },
  {
    "role": "headline-5",
    "tier": "headline",
    "weight": "SemiBold",
    "weightVal": 600,
    "size": {
      "website": [
        18,
        20
      ],
      "portal": [
        16,
        18
      ]
    },
    "lh": {
      "website": [
        24,
        28
      ],
      "portal": [
        24,
        24
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      12,
      16
    ],
    "en": "Recent grievances",
    "hi": "हाल की शिकायतें",
    "why": "h5, minor heading. Website 18 → 20 / 24 → 28; Portal 16 → 18 / 24. Leading 1.40. 18 rather than DBIM's 16 so an h5 does not share the body size."
  },
  {
    "role": "headline-6",
    "tier": "headline",
    "weight": "SemiBold",
    "weightVal": 600,
    "size": {
      "website": [
        16,
        16
      ],
      "portal": [
        16,
        16
      ]
    },
    "lh": {
      "website": [
        24,
        24
      ],
      "portal": [
        24,
        24
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      12,
      16
    ],
    "en": "Documents required",
    "hi": "आवश्यक दस्तावेज़",
    "why": "h6, the smallest heading: body size, semibold, body leading. 16 / 24 on both surfaces (1.50). Distinguished from body-1 by weight (600 vs 400) and from title-2 by its element."
  },
  {
    "role": "title-1",
    "tier": "title",
    "weight": "SemiBold",
    "weightVal": 600,
    "size": {
      "website": [
        18,
        22
      ],
      "portal": [
        18,
        22
      ]
    },
    "lh": {
      "website": [
        24,
        28
      ],
      "portal": [
        24,
        28
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      16,
      20
    ],
    "en": "Section heading and panel title",
    "hi": "अनुभाग शीर्षक और पैनल शीर्षक",
    "why": "Card, panel and dialog title. 18 → 22 / 24 → 28 on both surfaces (1.27). 22 sits between headline-4 (24) and headline-5 (20) on purpose: a title is not a heading level."
  },
  {
    "role": "title-2",
    "tier": "title",
    "weight": "SemiBold",
    "weightVal": 600,
    "size": {
      "website": [
        16,
        16
      ],
      "portal": [
        16,
        16
      ]
    },
    "lh": {
      "website": [
        24,
        24
      ],
      "portal": [
        24,
        24
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      12,
      16
    ],
    "en": "List headers and compact titles",
    "hi": "सूची शीर्षक और संक्षिप्त शीर्षक",
    "why": "List-item title, small card title, table caption. 16 / 24 (1.50) — body-1's metrics at 600, so a title and its body align line for line."
  },
  {
    "role": "title-3",
    "tier": "title",
    "weight": "SemiBold",
    "weightVal": 600,
    "size": {
      "website": [
        14,
        14
      ],
      "portal": [
        14,
        14
      ]
    },
    "lh": {
      "website": [
        20,
        20
      ],
      "portal": [
        20,
        20
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      12,
      16
    ],
    "en": "Sidebar and tertiary labels",
    "hi": "साइडबार और तृतीयक लेबल",
    "why": "Dense table header, compact list title. 14 / 20 (1.43) — body-2's metrics at 600."
  },
  {
    "role": "body-1",
    "tier": "body",
    "weight": "Regular",
    "weightVal": 400,
    "size": {
      "website": [
        16,
        16
      ],
      "portal": [
        16,
        16
      ]
    },
    "lh": {
      "website": [
        24,
        24
      ],
      "portal": [
        24,
        24
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      12,
      16
    ],
    "en": "Submit your application along with all required documents.",
    "hi": "सभी आवश्यक दस्तावेज़ों के साथ अपना आवेदन जमा करें।",
    "why": "The reading size. 16 / 24 (1.50) everywhere, including phones: a citizen's paragraph is never smaller than the form field it explains."
  },
  {
    "role": "body-2",
    "tier": "body",
    "weight": "Regular",
    "weightVal": 400,
    "size": {
      "website": [
        14,
        14
      ],
      "portal": [
        14,
        14
      ]
    },
    "lh": {
      "website": [
        20,
        20
      ],
      "portal": [
        20,
        20
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      12,
      12
    ],
    "en": "Secondary information, helper text, and table cell content.",
    "hi": "द्वितीयक जानकारी, सहायक पाठ और तालिका सामग्री।",
    "why": "Secondary text, help text, table cells. 14 / 20 (1.43)."
  },
  {
    "role": "body-3",
    "tier": "body",
    "weight": "Regular",
    "weightVal": 400,
    "size": {
      "website": [
        12,
        12
      ],
      "portal": [
        12,
        12
      ]
    },
    "lh": {
      "website": [
        16,
        16
      ],
      "portal": [
        16,
        16
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      12,
      12
    ],
    "en": "Captions, timestamps, and fine print.",
    "hi": "कैप्शन, समय-चिह्न और बारीक अक्षर।",
    "why": "Captions, timestamps, legal, footnotes. 12 / 16 (1.33). The floor: UX4G 3.0 §2 calls 12px the minimum usable size and nothing in SAMAVESH renders below it."
  },
  {
    "role": "label-1",
    "tier": "label",
    "weight": "Medium",
    "weightVal": 500,
    "size": {
      "website": [
        14,
        14
      ],
      "portal": [
        14,
        14
      ]
    },
    "lh": {
      "website": [
        20,
        20
      ],
      "portal": [
        20,
        20
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      12,
      12
    ],
    "en": "Form label · Applicant name",
    "hi": "फ़ॉर्म लेबल · आवेदक का नाम",
    "why": "Form labels, button text, tabs, navigation items. 14 / 20 (1.43) — the UX4G Label/L size, one step below body-1 so a label sits under the value it names."
  },
  {
    "role": "label-2",
    "tier": "label",
    "weight": "Medium",
    "weightVal": 500,
    "size": {
      "website": [
        12,
        12
      ],
      "portal": [
        12,
        12
      ]
    },
    "lh": {
      "website": [
        16,
        16
      ],
      "portal": [
        16,
        16
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      8,
      8
    ],
    "en": "Badge · Verified",
    "hi": "बैज · सत्यापित",
    "why": "Badges, chips, small controls. 12 / 16 (1.33). The floor size at Medium."
  },
  {
    "role": "label-3",
    "tier": "label",
    "weight": "Medium",
    "weightVal": 500,
    "size": {
      "website": [
        12,
        12
      ],
      "portal": [
        12,
        12
      ]
    },
    "lh": {
      "website": [
        16,
        16
      ],
      "portal": [
        16,
        16
      ]
    },
    "tracking": {
      "website": [
        0,
        0
      ],
      "portal": [
        0,
        0
      ]
    },
    "para": [
      8,
      8
    ],
    "en": "STATUS · UPLOADED",
    "hi": "स्थिति · अपलोड",
    "why": "The CAPS role — overlines and eyebrows of 1–3 words, always uppercase, always with type/caps/tracking (+0.06em). 12 / 16, Medium. Moved from 11px on 2026-09-04: the estate renders nothing below 12. Uppercase anywhere else is a defect the type gate reports."
  }
];

/* ds-exempt-end */
export const TIERS: { key: Tier; label: string; blurb: string }[] = [
  {
    "key": "display",
    "label": "Display",
    "blurb": "Hero and campaign headings, on the optical Display cut"
  },
  {
    "key": "headline",
    "label": "Headline",
    "blurb": "Document structure — the page h1 and its sections"
  },
  {
    "key": "title",
    "label": "Title",
    "blurb": "The name of a thing: a card, a panel, a dialog, a table"
  },
  {
    "key": "body",
    "label": "Body",
    "blurb": "Running text and paragraphs, 1.5 leading on both surfaces"
  },
  {
    "key": "label",
    "label": "Label",
    "blurb": "Controls, badges and captions; label-3 is the uppercase overline"
  }
];

/** Per-tier reasoning, from font.role.<tier>.$description in primitive.json. */
export const TIER_WHY: Record<Tier, string> = {
  "display": "Display — hero and campaign headings, on the optical Display cut (Noto Sans Display, drawn for 40–80px so its spacing does not read loose at that size). Medium 500: a display heading carries presence by size, not weight. Website is expressive (80 → 40), Portal is restrained (56 → 24). Leading tightens as size grows, 1.20 at display-6 to 1.10 at display-1 — DBIM §4's 1.2 floor is departed from here on record (deviation register T3), because 1.2 at 80px opens a two-line hero into separate lines. Tracking is negative from one em rule per rung so the two surfaces track alike per pixel of type.",
  "headline": "Headline — document structure, h1 to h6. SemiBold 600, never 700: bold at these sizes on Noto Sans closes the counters and 700 is reserved for inline emphasis and KPI numerals. Leading rises as size falls — 1.20 at headline-1 to 1.50 at headline-6 — so every headline sits inside DBIM §4's 1.2–1.5 band and a smaller heading is never set tighter than the larger one above it. The website ramp is one step above DBIM's 36/24/20 (deviation register T1) because a six-level outline needs the intermediate steps; the portal ramp is one step above DBIM's mobile ladder.",
  "title": "Title — the name of a thing: a card, a panel, a dialog, a table, a list item. SemiBold 600 since 2026-09-04 (was Medium): a title and the paragraph under it are now two weight steps apart, not one, so hierarchy does not rest on a single step. Identical on both surfaces — a card reads the same wherever it sits (the productive core is shared, as Carbon's productive type set is).",
  "body": "Body — running text. Regular 400, leading 1.5 at the reading size on both surfaces (WCAG 1.4.8 and DBIM §4 iii). Identical on the website and in portals since 2026-09-04: the old Portal ramp dropped paragraphs to 14px on phones while the inputs beside them held 16px, and carried a 13px stop the contract bans. Tracking 0: Noto Sans is drawn with the spacing body text needs. Each size has a SemiBold companion text style for emphasis — never Bold.",
  "label": "Label — controls, badges and captions that are scanned, not read. Medium 500: one step above body so a label reads as a label beside a value without shouting. Identical on both surfaces."
};

export const SURFACES: { key: Surface; label: string; note: string; sample: string }[] = [
  {
    "key": "website",
    "label": "Website",
    "note": "dosje.gov.in · expressive, editorial",
    "sample": "display-1 = 80px"
  },
  {
    "key": "portal",
    "label": "Portal",
    "note": "20+ workflow portals · dense, functional — only Display and Headline differ from the website",
    "sample": "display-1 = 56px"
  }
];

export interface StandardsRule { rule: string; src: string }
export interface StandardsGroup { title: string; rules: StandardsRule[] }

/**
 * The typography rules, grouped as UX4G groups them, each tagged to the standard it comes from
 * so a reviewer can audit rather than trust. Editorial — authored in typography-content.json.
 *
 * This export was LOST when the generator first replaced this file: the generated version
 * compiled fine on its own and only failed once it met the page that imports it. Regenerating a
 * file means owning every export it had, not just the ones you came for.
 */
export const STANDARDS: StandardsGroup[] = [
  {
    "title": "Consistency",
    "rules": [
      {
        "rule": "Noto Sans is the typeface for every MoSJE property. No second family is introduced for display or accent.",
        "src": "DBIM 4.1"
      },
      {
        "rule": "Body text is left-aligned. Never justified, never centred for running paragraphs.",
        "src": "DBIM 4.1.1"
      },
      {
        "rule": "In tables: text left, numbers right, column headers centred.",
        "src": "DBIM 4.1.1"
      },
      {
        "rule": "No Hinglish. Write English or हिन्दी, each in its own script, each marked with lang.",
        "src": "DBIM 4.1.1"
      }
    ]
  },
  {
    "title": "Hierarchy",
    "rules": [
      {
        "rule": "One h1 per page, and heading order never skips a level.",
        "src": "GIGW · WCAG 1.3.1"
      },
      {
        "rule": "Pick a role by the job it does, not by the size it happens to be — the tiers overlap.",
        "src": "SAMAVESH"
      },
      {
        "rule": "Display carries presence; Headline carries document structure. Do not substitute one for the other.",
        "src": "SAMAVESH"
      },
      {
        "rule": "The 21-role scale is the estate's implementation of DBIM §4's hierarchy — with three recorded deviations: headline sizes (40/32/28 against DBIM's 36/24/20), display leading below 1.2, and no size below 12px. See the deviation register.",
        "src": "DBIM 4.3 · docs/audit/typography-deviation-register.md"
      }
    ]
  },
  {
    "title": "Spacing",
    "rules": [
      {
        "rule": "Latin body sits at 1.5–1.7 line height; Devanagari body targets ~1.7 at the same point size.",
        "src": "SAMAVESH · DBIM 4.3.1"
      },
      {
        "rule": "ALL-CAPS is never used for a sentence or paragraph — only 1–3 word overlines, and only in the label-3 role, which carries the +0.06em caps tracking.",
        "src": "DBIM 4.1.1"
      },
      {
        "rule": "Measure stays between 45 and 75 characters; body copy is capped rather than run full width.",
        "src": "SAMAVESH"
      },
      {
        "rule": "Text spacing must survive user overrides of line height, word and letter spacing without clipping.",
        "src": "GIGW · WCAG 1.4.12"
      }
    ]
  },
  {
    "title": "Colour & contrast",
    "rules": [
      {
        "rule": "Body text ≥ 4.5:1 against its background; large text ≥ 3:1.",
        "src": "DBIM 4.4 · WCAG 1.4.3"
      },
      {
        "rule": "At 11px (label-3) treat 4.5:1 as a floor rather than a target, and avoid tinted fills behind it.",
        "src": "SAMAVESH"
      },
      {
        "rule": "In dbim brand mode, text uses shade 1 or 2 of the key colour group.",
        "src": "DBIM 4.4"
      }
    ]
  },
  {
    "title": "Responsiveness",
    "rules": [
      {
        "rule": "Text resizes to 200% with no loss of content or function.",
        "src": "GIGW · WCAG 1.4.4"
      },
      {
        "rule": "Content reflows at a 320px equivalent without two-dimensional scrolling.",
        "src": "GIGW · WCAG 1.4.10"
      },
      {
        "rule": "Sizes are fluid between 360px and 1280px — no type breakpoints, and no role grows as the viewport shrinks.",
        "src": "SAMAVESH"
      },
      {
        "rule": "Text-entry controls hold a hard 16px floor below 768px so iOS Safari does not trap the user zoomed in.",
        "src": "SAMAVESH · GIGW"
      }
    ]
  },
  {
    "title": "Floor and rhythm",
    "rules": [
      {
        "rule": "Nothing renders below 12px. label-3 is 12px; there is no 11px, 10px or 9px anywhere.",
        "src": "UX4G 3.0 §2 · SAMAVESH"
      },
      {
        "rule": "Every size is on the 16-step ramp and every line height on the 4px grid; leading rises as size falls, from 1.10 at display-1 to 1.5 at body.",
        "src": "SAMAVESH"
      },
      {
        "rule": "Title, Body and Label are identical on both surfaces. Only Display and Headline are cut differently for the website and the portals.",
        "src": "SAMAVESH"
      },
      {
        "rule": "Headings and titles are semibold (600); display is medium (500) on the Display cut; body is regular; labels are medium. 700 is inline emphasis and KPI numerals only; 800 and 900 do not exist.",
        "src": "SAMAVESH"
      },
      {
        "rule": "Type is written through Heading and Text (or the text-<role> utilities). A raw size, leading, tracking or a stock Tailwind size utility fails the type gate.",
        "src": "SAMAVESH · check:type-linkage"
      }
    ]
  }
];

/** Round to 3dp for display, drop trailing zeros. */
export const px = (n: number): string => `${Math.round(n * 1000) / 1000}px`;
