/**
 * The offline fallback — chrome strings in Hindi, bundled.
 *
 * ── WHY THIS EXISTS ───────────────────────────────────────────────────────────
 * Bhashini needs credentials, and credentials need a registered organisation. A
 * prototype that shows nothing until someone has been through that process is a
 * prototype nobody can evaluate. So the language switch works out of the box for
 * Hindi from this table, and every other language — and every string not listed
 * here — waits for the API.
 *
 * ── WHY IT IS DELIBERATELY SMALL ──────────────────────────────────────────────
 * This is NOT a translation layer to grow. It covers the masthead and the words
 * around it: the identity lines, the navigation, the search field, the account
 * actions. Page content is Bhashini's job. If you find yourself adding a
 * paragraph here, the answer is credentials, not a bigger dictionary — a
 * hand-maintained second copy of the site's prose is exactly the drift the
 * `data/website` layer was built to end.
 *
 * ── THE IDENTITY LINES ARE NOT TRANSLATIONS ───────────────────────────────────
 * "सामाजिक न्याय और अधिकारिता मंत्रालय" is the Ministry's OWN Hindi name, not a
 * rendering of the English one. Same for the Department. These are the forms
 * that appear on the Ministry's own mastheads and publications, and they must
 * never be regenerated by a machine — a translated department name on a
 * government header is a factual error, not a stylistic one. Bhashini is
 * deliberately never asked for these two strings; see PROTECTED below.
 */

/** en → hi, for the chrome only. */
export const FALLBACK_HI: Readonly<Record<string, string>> = {
  // Identity — official names, not translations.
  "Government of India": "भारत सरकार",
  "Ministry of Social Justice & Empowerment": "सामाजिक न्याय और अधिकारिता मंत्रालय",
  "Department of Social Justice & Empowerment": "सामाजिक न्याय और अधिकारिता विभाग",

  // Accessibility bar
  "Skip to Main Content": "मुख्य सामग्री पर जाएँ",
  "Select language": "भाषा चुनें",
  "Accessibility options": "सुगम्यता विकल्प",

  // Primary navigation
  Home: "मुख्य पृष्ठ",
  Department: "विभाग",
  "Associated Organisations": "संबद्ध संगठन",
  Offerings: "सेवाएँ एवं योजनाएँ",
  Documents: "दस्तावेज़",
  "Events & Gallery": "कार्यक्रम एवं गैलरी",
  Connect: "संपर्क",

  // Search
  Search: "खोजें",
  "Search schemes and services": "योजनाएँ और सेवाएँ खोजें",
  "Clear search": "खोज साफ़ करें",

  // Account and actions
  "Admin Login": "प्रशासक लॉगिन",
  Login: "लॉगिन",
  Profile: "प्रोफ़ाइल",
  Settings: "सेटिंग्स",
  "Sign out": "साइन आउट",
  "Open navigation menu": "नेविगेशन मेनू खोलें",
  "Close navigation menu": "नेविगेशन मेनू बंद करें",
};

/**
 * Strings a machine must never be asked to translate.
 *
 * The Ministry and Department names have official Hindi forms and no official
 * form in most other languages; a neural model asked for "Department of Social
 * Justice & Empowerment" in Tamil will invent a plausible one, and a government
 * masthead is the last place an invented name belongs. These pass through
 * untranslated unless the table above has an authoritative entry.
 */
export const PROTECTED: ReadonlySet<string> = new Set([
  "Ministry of Social Justice & Empowerment",
  "Department of Social Justice & Empowerment",
  "SAMAVESH",
  "Digital India",
  "BETA",
]);

/** Look up a bundled translation, or `undefined` when there isn't one. */
export function fallbackFor(source: string, target: string): string | undefined {
  if (target === "hi") return FALLBACK_HI[source];
  return undefined;
}
