import { test } from "node:test";
import assert from "node:assert/strict";

import {
  digitsOnly,
  formatAadhaar,
  formatPan,
  isValidAadhaar,
  isValidPan,
  isValidVerhoeff,
  maskAadhaar,
  maskPan,
  panHolderType,
} from "./india-id.ts";

// Verhoeff-valid 12-digit numbers, first digit 2–9. Generated by appending the correct
// check digit to a base — these are structurally valid but issued to nobody.
const VALID_AADHAAR = ["234123412346", "999999999999", "499118665246"];

test("accepts structurally valid Aadhaar numbers", () => {
  for (const n of VALID_AADHAAR) {
    assert.ok(isValidAadhaar(n), `${n} should validate`);
  }
});

test("rejects Aadhaar numbers starting 0 or 1 — UIDAI never issues them", () => {
  // Take a valid number and force the leading digit low; the point is that the leading-digit
  // rule rejects it regardless of what the checksum says.
  assert.equal(isValidAadhaar("034123412346"), false);
  assert.equal(isValidAadhaar("134123412346"), false);
});

test("rejects wrong length and non-digits", () => {
  assert.equal(isValidAadhaar("23412341234"), false); // 11
  assert.equal(isValidAadhaar("2341234123467"), false); // 13
  assert.equal(isValidAadhaar(""), false);
  assert.equal(isValidAadhaar("2341-2341-234A"), false);
});

test("Verhoeff catches single-digit typos and adjacent transpositions", () => {
  // This is the entire reason for doing the checksum client-side rather than just a length
  // check: the two commonest ways a person mistypes a long number both get caught.
  const good = "234123412346";

  let singleDigitCaught = 0;
  for (let i = 0; i < good.length; i++) {
    for (let d = 0; d <= 9; d++) {
      if (String(d) === good[i]) continue;
      const typo = good.slice(0, i) + d + good.slice(i + 1);
      if (!isValidVerhoeff(typo)) singleDigitCaught++;
    }
  }
  assert.equal(singleDigitCaught, good.length * 9, "every single-digit error must be caught");

  let transpositionsTested = 0;
  for (let i = 0; i < good.length - 1; i++) {
    if (good[i] === good[i + 1]) continue;
    const swapped = good.slice(0, i) + good[i + 1] + good[i] + good.slice(i + 2);
    transpositionsTested++;
    assert.equal(isValidVerhoeff(swapped), false, `transposition at ${i} slipped through`);
  }
  assert.ok(transpositionsTested > 0);
});

test("formats Aadhaar in groups of four while typing", () => {
  assert.equal(formatAadhaar("2341"), "2341");
  assert.equal(formatAadhaar("23412"), "2341 2");
  assert.equal(formatAadhaar("234123412346"), "2341 2341 2346");
  assert.equal(formatAadhaar("2341 2341 2346"), "2341 2341 2346"); // idempotent
  assert.equal(formatAadhaar("234123412346999"), "2341 2341 2346"); // truncates at 12
});

test("masks Aadhaar to the last four digits", () => {
  // DPDP Act 2023 / UIDAI: never display a full Aadhaar back to the user.
  assert.equal(maskAadhaar("234123412346"), "XXXX XXXX 2346");
  assert.doesNotMatch(maskAadhaar("234123412346"), /2341 2341/);
});

test("digitsOnly strips separators", () => {
  assert.equal(digitsOnly("2341 2341-2346"), "234123412346");
});

// ── PAN ───────────────────────────────────────────────────────────────────────

test("accepts a well-formed PAN and normalises case", () => {
  assert.ok(isValidPan("ABCPE1234F"));
  assert.ok(isValidPan("abcpe1234f"));
  assert.equal(formatPan("abcpe-1234 f"), "ABCPE1234F");
});

test("rejects PANs with a bad shape or an unknown holder-type character", () => {
  assert.equal(isValidPan("ABCDE1234"), false); // too short
  assert.equal(isValidPan("ABCD01234F"), false); // digit in the letter block
  assert.equal(isValidPan("ABCPE12345"), false); // last char must be a letter
  // 4th char 'X' is not a holder type — shape alone would have passed this.
  assert.equal(isValidPan("ABCXE1234F"), false);
});

test("reports the holder type encoded in the 4th character", () => {
  assert.equal(panHolderType("ABCPE1234F"), "Individual");
  assert.equal(panHolderType("ABCCE1234F"), "Company");
  assert.equal(panHolderType("ABC"), null, "not determinable before the 4th character");
});

test("masks PAN for display", () => {
  assert.equal(maskPan("ABCPE1234F"), "ABCPE****F");
});
