"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import * as React from "react";
import {
  Alert,
  Badge,
  Breadcrumb,
  Button,
  Card,
  CardBody,
  DescriptionList,
  Icon,
  ListGroup,
  ListRow,
  PageHeader,
  SectionTitle,
  SideSheet,
  buttonClasses,
  useToast,
} from "@mosje/design-system";
import { useEAnudaan } from "@/lib/e-anudaan/store/store";
import { formatDate, formatGrant, schemeLabel, statusTone } from "@/lib/e-anudaan/selectors";
import { statusLabel } from "@/lib/e-anudaan/workflow";
import { ROLES, reviewKeyOf } from "@/lib/e-anudaan/roles";
import { RESTARTABLE, STAGE_INFO, returnedBy, stageOf } from "@/lib/e-anudaan/pfms/stages";
import type { PaymentCase } from "@/lib/e-anudaan/pfms/selectors";
import type { RoleId } from "@/lib/e-anudaan/types";
import { projectTitleFor } from "@/lib/e-anudaan/applicant";
import { RefText } from "@/components/e-anudaan/worklist-table";
import { instalmentSchedule, releasePatternFact } from "@/lib/e-anudaan/funding";
import { ServiceErrorNotice, useFailureOnLoad } from "@/components/e-anudaan/service-error";
import { usePfms } from "@/lib/e-anudaan/pfms/store";
import { paymentCase, BLOCKER_TEXT } from "@/lib/e-anudaan/pfms/selectors";
import { latestRequest } from "@/lib/e-anudaan/pfms/stages";
import { pfmsError } from "@/lib/e-anudaan/pfms/errors";
import { formatDateTime } from "@/lib/e-anudaan/format";
import { PaymentStages, StageBadge, exact, prepareHref, authoriseHref } from "@/components/e-anudaan/pfms/payment-ui";

/**
 * A stand-in for the return memo PFMS hosts. The BRD asks for PFMS's own document "via the configured
 * link" (FR-STS-005); NeGD has not supplied that link, so the prototype opens a marked sample until it
 * does (plan §4, question 15). Generated by tools/e-anudaan-samples/return-memo.mjs.
 */
const RETURN_MEMO_SAMPLE = "/e-anudaan/pfms/return-memo--sample.pdf";

/**
 * Payment status for a sanctioned application — the live bundle's /finance/payment-status/:id.
 *
 * Maintainer note: not linked from any captured nav, so the layout is inferred. Fund release is
 * mocked — this prototype moves no money and calls no PFMS. The page used to say so in a banner;
 * that is a note for the build team, not for a Finance officer (screen QA, 13 Sep 2026).
 *
 * Design-director audit O-12 (16 Sep 2026): the header showed only "LGCY/76001" — no NGO, project
 * or scheme, so the officer could not confirm they were on the right file — `₹29.00 L` sat beside
 * `₹48,00,000` on one page, and there was no way back. The header now follows the review screen
 * (NGO · project · scheme · FY · both references) under a breadcrumb.
 *
 * Money: every amount is in the SUMMARY form (glossary §2), the sanction figures and the instalment
 * rows alike. This page answers "where has the money reached?" — a status read, not the place a
 * figure is entered, confirmed or legally stated. The exact rupees are stated on the sanction order
 * and the review screen's Sanction Order panel, one press away through View Application; restating
 * them here in a second form is what put two shapes of one figure on the page.
 *
 * Width: fluid like every portal surface (X-07), the two short cards side by side from xl.
 *
 * PFMS payment leg, 29 Sep 2026 (docs/plans/2026-09-29-e-anudaan-pfms.md): the four fixed steps —
 * Sanctioned, Bill Raised, Released to PFMS, Credited to NGO — said "Bill Raised: Done" on every
 * sanctioned file, because nothing recorded a bill. They are replaced by the payment's real stage,
 * read from `paymentCase()` (the one expression the queues, the review screen and the NGO also
 * read), with what PFMS returned at each step: the bill and token, the voucher, each beneficiary's
 * UTR, the requests sent, and — when PFMS returns a bill — the reason (FR-STS-001 to 006).
 *
 * DS Audit: Breadcrumb ✅ · PageHeader ✅ · Card ✅ · SectionTitle ✅ · DescriptionList ✅ · ListGroup ✅ ·
 * Badge ✅ · Alert ✅ · SideSheet ✅ · VerticalTimeline ✅ · Stepper (via PaymentStages) ✅ — composed.
 */
export default function PaymentStatusPage() {
  const params = useParams<{ appId: string }>();
  const { state, findApp } = useEAnudaan();
  const { pfms } = usePfms();
  const [showReturn, setShowReturn] = React.useState(false);
  const app = findApp(decodeURIComponent(params.appId));
  const role = state.session ? ROLES[state.session] : null;
  // The status is read from PFMS when the page opens; that read can fail (error-catalogue.ts).
  // Keyed by the application: moving from one payment status to another does not remount the page.
  const [failure, clearFailure] = useFailureOnLoad("payment", params.appId);

  if (failure?.target === "page") {
    return <ServiceErrorNotice failure={failure} homeHref={role?.home} onRetry={clearFailure} onDismiss={clearFailure} />;
  }

  if (!app) {
    return <Alert status="warning" title="Application Not Found">This application is not in the register.</Alert>;
  }

  const ngo = state.ngos.find((n) => n.id === app.ngoId);
  const key = role ? reviewKeyOf(role) : null;
  // Payment Status is opened from Sanctioned Applications; an officer without that register goes back home.
  const register = role?.nav.find((n) => n.href.endsWith("/sanctioned"));

  const schedule = instalmentSchedule(state, app);
  const pc = app.sanction ? paymentCase(state, pfms, app) : null;
  const advice = pc?.advice;
  const req = advice ? latestRequest(advice) : undefined;
  const me = state.session;

  return (
    <div className="space-y-5">
      <Breadcrumb
        linkAs={Link}
        items={[
          register ? { label: register.label, href: register.href } : { label: "Dashboard", href: role?.home },
          { label: "Payment Status" },
        ]}
      />
      <PageHeader
        title={ngo?.name ?? app.ngoId}
        meta={
          <span className="block space-y-1">
            <span className="block text-body-2 text-ink">
              {projectTitleFor(state, app)} · {schemeLabel(app.schemeCode)} · FY {app.financialYear}
            </span>
            <span className="block text-body-3 text-ink-muted">
              Application No. <RefText value={app.id} className="text-ink" /> · Project ID {app.institutionId}
            </span>
          </span>
        }
        actions={
          <div className="flex min-w-0 max-w-full flex-wrap items-center gap-3">
            {pc && !pc.paidBeforeIntegration ? (
              <StageBadge stage={pc.stage} />
            ) : (
              <Badge status={statusTone(app.status)} className="h-auto max-w-full whitespace-normal">
                {statusLabel(app)}
              </Badge>
            )}
            {key && (
              <Link
                href={`/portals/e-anudaan/dashboard/sm2/${key}/review/${encodeURIComponent(app.id)}`}
                className={buttonClasses("primary", "outlined", "sm", "whitespace-nowrap")}
              >
                <Icon name="description" size={16} aria-hidden /> View Application
              </Link>
            )}
          </div>
        }
      />

      <ServiceErrorNotice failure={failure} homeHref={role?.home} onRetry={clearFailure} onDismiss={clearFailure} />

      {pc && <PaymentProgress pc={pc} me={me} onShowReturn={() => setShowReturn(true)} />}

      <div className="grid gap-5 xl:grid-cols-2 xl:items-start">
        <Card variant="outlined">
          <CardBody className="space-y-4">
            <SectionTitle title="Sanction" />
            {app.sanction ? (
              <DescriptionList
                columns={2}
                divided
                items={[
                  { term: "Order No.", value: app.sanction.orderNo },
                  { term: "Sanction Date", value: formatDate(app.sanction.sanctionedAt) },
                  { term: "Recurring", value: formatGrant(app.sanction.recurring) },
                  { term: "Non-Recurring", value: formatGrant(app.sanction.nonRecurring) },
                  { term: "Total Sanctioned", value: formatGrant(app.sanction.total) },
                  { term: "Credited", value: app.release ? `${formatGrant(app.release.amount)} · ${formatDate(app.release.releasedAt)}` : formatGrant(0) },
                ]}
              />
            ) : (
              <p className="text-body-2 text-ink-muted">This application has not been sanctioned yet.</p>
            )}
          </CardBody>
        </Card>

        {req && (req.bill || req.voucher) && (
          <Card variant="outlined">
            <CardBody className="space-y-4">
              <SectionTitle title="Bill and Voucher" description="As PFMS reports them." />
              <DescriptionList
                columns={2}
                divided
                items={[
                  { term: "Bill Number", value: req.bill?.billNumber ?? "" },
                  { term: "Bill Date", value: req.bill ? formatDate(req.bill.billDate) : "" },
                  { term: "Token Number", value: req.bill?.tokenNumber ?? "" },
                  { term: "Token Date", value: req.bill ? formatDate(req.bill.tokenDate) : "" },
                  { term: "Voucher Number", value: req.voucher?.number ?? "Not yet generated" },
                  { term: "Voucher Date", value: req.voucher ? formatDate(req.voucher.date) : "" },
                ]}
              />
            </CardBody>
          </Card>
        )}

        {req && req.payments.length > 0 && (
          <Card variant="outlined">
            <CardBody className="space-y-4">
              <SectionTitle title="Payment to the NGO" description="The bank's confirmation of each credit. The NGO is told only once a UTR is recorded." />
              <ListGroup aria-label="Payments to beneficiaries">
                {req.payments.map((p) => (
                  <ListRow
                    key={p.beneficiaryId}
                    title={<span className="tabular-nums">{exact(p.amount)}</span>}
                    description={
                      <span className="block">
                        Payee code <span className="font-mono">{p.payeeCode}</span>
                        {p.utr ? (
                          <>
                            {" "}· UTR <span className="font-mono">{p.utr}</span> · {p.scrollDate ? formatDate(p.scrollDate) : ""}
                          </>
                        ) : null}
                      </span>
                    }
                    trailing={<Badge status={p.scrollStatus === "Success" ? "success" : p.scrollStatus === "Failed" ? "danger" : "info"}>{p.scrollStatus === "Success" ? "Credited" : p.scrollStatus === "Failed" ? "Failed at Bank" : "With the Bank"}</Badge>}
                  />
                ))}
              </ListGroup>
            </CardBody>
          </Card>
        )}
      </div>

      {advice && (
        <div className="grid gap-5 xl:grid-cols-2 xl:items-start">
          <Card variant="outlined">
            <CardBody className="space-y-4">
              <SectionTitle title="Requests Sent to PFMS" description="Each transmission has its own identifier; a resend points back to the one before it." count={advice.requests.length} />
              {advice.requests.length === 0 ? (
                <p className="text-body-2 text-ink-muted">Nothing has been sent to PFMS yet.</p>
              ) : (
                <ListGroup aria-label="Requests sent to PFMS">
                  {[...advice.requests].reverse().map((r) => (
                    <ListRow
                      key={r.uniqueIdentifier}
                      title={<span className="font-mono text-body-2">{r.uniqueIdentifier}</span>}
                      description={
                        <span className="block">
                          Sent {formatDateTime(r.sentAt)}
                          {r.previousUniqueIdentifier ? <> · replaces <span className="font-mono">{r.previousUniqueIdentifier}</span></> : null}
                          {r.retries > 0 ? ` · resent automatically ${r.retries} time${r.retries === 1 ? "" : "s"}` : ""}
                        </span>
                      }
                      trailing={<Badge status={r.outcome === "accepted" ? "success" : r.outcome === "queued" ? "warning" : "danger"}>{r.outcome === "accepted" ? "Received" : r.outcome === "queued" ? "Waiting to Resend" : "Not Accepted"}</Badge>}
                    />
                  ))}
                </ListGroup>
              )}
            </CardBody>
          </Card>
          <Card variant="outlined">
            <CardBody className="space-y-4">
              <SectionTitle title="Payment History" description="Newest first." count={advice.history.length} />
              {/* A list, not VerticalTimeline: that component is a website history band, and in half a
                  1440 column its titles wrapped to headline size and its dates ran out of the card. */}
              <ListGroup aria-label="Payment history">
                {[...advice.history].reverse().map((e, i) => (
                  <ListRow key={`${e.at}-${i}`} title={<span className="font-normal">{e.text}</span>} description={formatDateTime(e.at)} />
                ))}
              </ListGroup>
            </CardBody>
          </Card>
        </div>
      )}

      {advice?.earlier && advice.earlier.length > 0 && (
        <Card variant="outlined">
          <CardBody className="space-y-4">
            <SectionTitle title="Earlier Payment Advices" description="Advices for this sanction that ended without a credit. They are kept as they were." count={advice.earlier.length} />
            <ListGroup aria-label="Earlier payment advices">
              {[...advice.earlier].reverse().map((e) => {
                const last = e.requests[e.requests.length - 1];
                return (
                  <ListRow
                    key={e.id}
                    title={e.id}
                    description={
                      <span className="block">
                        {last ? (
                          <>
                            Last sent {formatDateTime(last.sentAt)} as <span className="font-mono">{last.uniqueIdentifier}</span>
                            {last.returnReason ? ` · ${last.returnReason}` : ""}
                          </>
                        ) : (
                          "Never sent to PFMS."
                        )}
                      </span>
                    }
                    trailing={<StageBadge stage={stageOf(e)} size="sm" />}
                  />
                );
              })}
            </ListGroup>
          </CardBody>
        </Card>
      )}

      {req?.returnReason && (
        <SideSheet open={showReturn} onClose={() => setShowReturn(false)} title="Return Order" size="md">
          <DescriptionList
            columns={1}
            items={[
              { term: "Returned By", value: returnedBy(req) },
              { term: "Returned On", value: req.statusAt ? formatDate(req.statusAt) : "" },
              { term: "Reason", value: req.returnReason },
              { term: "Request", value: <span className="font-mono">{req.uniqueIdentifier}</span> },
              {
                term: "Return Memo (PFMS)",
                value: (
                  <span className="inline-flex flex-wrap items-center gap-2">
                    <a href={RETURN_MEMO_SAMPLE} target="_blank" rel="noopener noreferrer" className="font-semibold text-[var(--sa-text-link-brand-default)] underline underline-offset-2">
                      Open the Return Memo
                    </a>
                    <Badge status="neutral" size="sm">Sample</Badge>
                  </span>
                ),
              },
            ]}
          />
        </SideSheet>
      )}

      {schedule && (
        <Card variant="outlined">
          <CardBody className="space-y-4">
            <SectionTitle title="Instalments" description={`FY ${schedule.financialYear}. ${releasePatternFact(schedule.pattern)}`} />
            <ListGroup aria-label="Instalments">
              {schedule.rows.map((r) => (
                <ListRow
                  key={r.key}
                  title={`${r.label}${r.share != null ? ` · ${r.share}%` : ""}`}
                  description={`Planned ${formatGrant(r.planned)}${r.claim?.sanction ? ` · sanctioned ${formatGrant(r.claim.sanction.total)}` : ""} · released ${formatGrant(r.released)}`}
                  trailing={
                    <Badge status={r.state === "released" ? "success" : r.state === "to-release" ? "warning" : "neutral"}>
                      {r.state === "released" ? "Released" : r.state === "to-release" ? "In Payment" : r.state === "claimed" ? "Under Examination" : r.state === "open" ? "Open for Claim" : "Not Opened"}
                    </Badge>
                  }
                />
              ))}
            </ListGroup>
          </CardBody>
        </Card>
      )}
    </div>
  );
}

/**
 * Where the payment has reached, who holds it, and — for the officer whose turn it is — the way in.
 * Every sentence is chosen from the stage, so the page never says two things about one payment.
 */
function PaymentProgress({ pc, me, onShowReturn }: { pc: PaymentCase; me: RoleId | null; onShowReturn: () => void }) {
  const { pfms, startFresh } = usePfms();
  const router = useRouter();
  const { toast } = useToast();
  const caps = me ? ROLES[me].caps : [];
  const advice = pc.advice;
  const req = advice ? latestRequest(advice) : undefined;
  const info = STAGE_INFO[pc.stage];
  const credited = req?.payments.find((p) => p.utr);
  const restart =
    RESTARTABLE.includes(pc.stage) && caps.includes("prepareAdvice") ? (
      <Button
        size="sm"
        onClick={() => {
          const res = startFresh(pc.app.id);
          if (!res.ok) toast(res.error, "error");
          else router.push(prepareHref(pc.app.id));
        }}
      >
        Start a Fresh Payment Advice
      </Button>
    ) : undefined;
  const returnOrder = req?.returnReason ? (
    <Button size="sm" appearance="outlined" onClick={onShowReturn}>
      View Return Order
    </Button>
  ) : undefined;
  const actions = (...xs: React.ReactNode[]) => {
    const shown = xs.filter(Boolean);
    return shown.length ? (
      <span className="inline-flex flex-wrap gap-2">
        {shown.map((x, i) => (
          <React.Fragment key={i}>{x}</React.Fragment>
        ))}
      </span>
    ) : undefined;
  };

  let notice: React.ReactNode = null;
  if (pc.paidBeforeIntegration) {
    notice = (
      <Alert status="info" title="Paid Before the PFMS Integration">
        This grant was released on {pc.app.release ? formatDate(pc.app.release.releasedAt) : ""}, before payments were sent to PFMS from e-Anudaan. There is no payment advice for it.
      </Alert>
    );
  } else if (pc.blocker) {
    notice = (
      <Alert status="warning" title={BLOCKER_TEXT[pc.blocker].label}>
        {BLOCKER_TEXT[pc.blocker].body}
      </Alert>
    );
  } else {
    switch (pc.stage) {
      case "awaiting-advice":
      case "in-preparation":
      case "returned-by-checker":
        notice = (
          <Alert
            status={pc.stage === "returned-by-checker" ? "warning" : "info"}
            title={pc.stage === "returned-by-checker" ? "Returned to the Maker" : "With the Maker"}
            action={caps.includes("prepareAdvice") ? <Link href={prepareHref(pc.app.id)} className={buttonClasses("primary", "outlined", "sm", "whitespace-nowrap")}>{pc.advice ? "Open the Advice" : "Prepare Advice"}</Link> : undefined}
          >
            {pc.stage === "returned-by-checker" ? `The Checker returned the advice: ${advice?.checkerRemark ?? ""}` : "The Maker prepares the payment advice against this sanction."}
          </Alert>
        );
        break;
      case "awaiting-authorisation":
        notice = (
          <Alert status="info" title="With the Checker" action={caps.includes("authoriseAdvice") ? <Link href={authoriseHref(pc.app.id)} className={buttonClasses("primary", "outlined", "sm", "whitespace-nowrap")}>Review and Sign</Link> : undefined}>
            The payment advice is waiting for the Checker&apos;s review and digital signature.
          </Alert>
        );
        break;
      case "not-accepted":
        notice = (
          <Alert status="error" title="Not Accepted by PFMS" action={caps.includes("prepareAdvice") ? <Link href={prepareHref(pc.app.id)} className={buttonClasses("primary", "outlined", "sm", "whitespace-nowrap")}>Correct the Advice</Link> : undefined}>
            <span className="block">Nothing was created at PFMS. The advice is back with the Maker.</span>
            {advice?.issues.map((i) => (
              <span key={i.pfmsCode ?? i.field} className="block">
                {pfmsError(i.pfmsCode ?? "", pfms.errorOverrides).message}
              </span>
            ))}
          </Alert>
        );
        break;
      case "waiting-to-resend":
        notice = (
          <Alert status="warning" title="Waiting to Resend">
            PFMS could not be reached when the signed advice was sent{req ? ` on ${formatDateTime(req.sentAt)}` : ""}. It is sent again automatically; nobody needs to sign it again.
          </Alert>
        );
        break;
      case "returned-by-pfms":
        notice = (
          <Alert
            status="warning"
            title="Returned by PFMS"
            action={actions(caps.includes("prepareAdvice") ? <Link href={prepareHref(pc.app.id)} className={buttonClasses("primary", "outlined", "sm", "whitespace-nowrap")}>Correct the Advice</Link> : null, returnOrder)}
          >
            <span className="block">
              The {returnedBy(req)} returned the bill: {req?.returnReason}
            </span>
            <span className="block">The Maker corrects the advice; once the Checker signs it again, it is resubmitted to PFMS as a returned bill.</span>
          </Alert>
        );
        break;
      case "cancelled":
        notice = (
          <Alert status="error" title="Returned and Cancelled at PFMS" action={actions(restart, returnOrder)}>
            <span className="block">{req?.returnReason}</span>
            <span className="block">A cancelled payment advice cannot be revived. The Maker starts a fresh payment advice against the same sanction.</span>
          </Alert>
        );
        break;
      case "fy-expired":
        notice = (
          <Alert status="error" title="Financial Year Expired" action={actions(restart)}>
            The financial year closed before PFMS paid this bill{req?.statusAt ? ` (${formatDate(req.statusAt)})` : ""}. The Maker starts a fresh payment advice against the same sanction.
          </Alert>
        );
        break;
      case "credit-failed":
        notice = (
          <Alert status="error" title="Credit Failed at Bank" action={actions(restart)}>
            <span className="block">The bank could not credit the NGO&apos;s account. The NGO has been asked to check its bank details on Project Bank Accounts.</span>
            <span className="block">Once the account is correct, the Maker starts a fresh payment advice. It is paid to the account then on record.</span>
          </Alert>
        );
        break;
      case "paid":
      case "closed":
        notice = credited ? (
          <Alert status="success" title="Credited to the NGO">
            {exact(req!.payments.reduce((s, p) => s + p.amount, 0))} credited on {credited.scrollDate ? formatDate(credited.scrollDate) : ""}. UTR <span className="font-mono">{credited.utr}</span>. The NGO has been notified.
          </Alert>
        ) : null;
        break;
      default:
        notice = (
          <Alert status="info" title={info.label}>
            With the {info.holder} at PFMS{req?.statusAt ? ` since ${formatDate(req.statusAt)}` : ""}. The NGO is told only once the bank confirms the credit.
          </Alert>
        );
    }
  }

  return (
    <Card variant="outlined">
      <CardBody className="space-y-4">
        <SectionTitle title="Payment" description={advice ? `Payment advice ${advice.id}` : undefined} />
        {!pc.paidBeforeIntegration && <PaymentStages stage={pc.stage} />}
        {notice}
      </CardBody>
    </Card>
  );
}
