"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import * as React from "react";
import {
  Alert,
  Badge,
  Button,
  Card,
  CardBody,
  DescriptionList,
  Icon,
  ListGroup,
  ListRow,
  PageHeader,
  SectionTitle,
  SideSheet,
  buttonClasses,
  useToast,
} from "@mosje/design-system";
import { useEAnudaan } from "@/lib/e-anudaan/store/store";
import { formatDate, schemeLabel, statusTone } from "@/lib/e-anudaan/selectors";
import { statusLabel } from "@/lib/e-anudaan/workflow";
import { ROLES, reviewKeyOf } from "@/lib/e-anudaan/roles";
import { RESTARTABLE, STAGE_INFO, returnedBy, stageOf } from "@/lib/e-anudaan/pfms/stages";
import type { PaymentCase } from "@/lib/e-anudaan/pfms/selectors";
import { projectTitleFor } from "@/lib/e-anudaan/applicant";
import { RefText } from "@/components/e-anudaan/worklist-table";
import { ServiceErrorNotice, useFailureOnLoad } from "@/components/e-anudaan/service-error";
import { usePfms } from "@/lib/e-anudaan/pfms/store";
import { paymentCase, BLOCKER_TEXT } from "@/lib/e-anudaan/pfms/selectors";
import { latestRequest } from "@/lib/e-anudaan/pfms/stages";
import { pfmsError } from "@/lib/e-anudaan/pfms/errors";
import { formatDateTime } from "@/lib/e-anudaan/format";
import { PlainPaymentStages, StageBadge, exact, prepareHref } from "@/components/e-anudaan/pfms/payment-ui";
import { RECON_LABEL, reconcile } from "@/lib/e-anudaan/pfms/reports";

/**
 * A stand-in for the return memo PFMS hosts. The BRD asks for PFMS's own document "via the configured
 * link" (FR-STS-005); NeGD has not supplied that link, so the prototype opens a marked sample until it
 * does (plan §4, question 15). Generated by tools/e-anudaan-samples/return-memo.mjs.
 */
const RETURN_MEMO_SAMPLE = "/e-anudaan/pfms/return-memo--sample.pdf";

/**
 * Payment status for a sanctioned application — the live bundle's /finance/payment-status/:id.
 *
 * Maintainer note: not linked from any captured nav, so the layout is inferred. Fund release is
 * mocked — this prototype moves no money and calls no PFMS. The page used to say so in a banner;
 * that is a note for the build team, not for a Finance officer (screen QA, 13 Sep 2026).
 *
 * Design-director audit O-12 (16 Sep 2026): the header showed only "LGCY/76001" — no NGO, project
 * or scheme, so the officer could not confirm they were on the right file — `₹29.00 L` sat beside
 * `₹48,00,000` on one page, and there was no way back. The header now follows the review screen
 * (NGO · project · scheme · FY · both references) under a breadcrumb.
 *
 * Money: every amount is in the SUMMARY form (glossary §2), the sanction figures and the instalment
 * rows alike. This page answers "where has the money reached?" — a status read, not the place a
 * figure is entered, confirmed or legally stated. The exact rupees are stated on the sanction order
 * and the review screen's Sanction Order panel, one press away through View Application; restating
 * them here in a second form is what put two shapes of one figure on the page.
 *
 * Width: fluid like every portal surface (X-07), the two short cards side by side from xl.
 *
 * PFMS payment leg, 29 Sep 2026 (docs/plans/2026-09-29-e-anudaan-pfms.md): the four fixed steps —
 * Sanctioned, Bill Raised, Released to PFMS, Credited to NGO — said "Bill Raised: Done" on every
 * sanctioned file, because nothing recorded a bill. They are replaced by the payment's real stage,
 * read from `paymentCase()` (the one expression the queues, the review screen and the NGO also
 * read), with what PFMS returned at each step: the bill and token, the voucher, each beneficiary's
 * UTR, the requests sent, and — when PFMS returns a bill — the reason (FR-STS-001 to 006).
 *
 * DS Audit: Breadcrumb ✅ · PageHeader ✅ · Card ✅ · SectionTitle ✅ · DescriptionList ✅ · ListGroup ✅ ·
 * Badge ✅ · Alert ✅ · SideSheet ✅ · VerticalTimeline ✅ · Stepper (via PlainPaymentStages) ✅ — composed.
 */
export default function PaymentStatusPage() {
  const params = useParams<{ appId: string }>();
  const { state, findApp } = useEAnudaan();
  const { pfms } = usePfms();
  const [showReturn, setShowReturn] = React.useState(false);
  const app = findApp(decodeURIComponent(params.appId));
  const role = state.session ? ROLES[state.session] : null;
  // The status is read from PFMS when the page opens; that read can fail (error-catalogue.ts).
  // Keyed by the application: moving from one payment status to another does not remount the page.
  const [failure, clearFailure] = useFailureOnLoad("payment", params.appId);

  if (failure?.target === "page") {
    return <ServiceErrorNotice failure={failure} homeHref={role?.home} onRetry={clearFailure} onDismiss={clearFailure} />;
  }

  if (!app) {
    return <Alert status="warning" title="Application Not Found">This application is not in the register.</Alert>;
  }

  const ngo = state.ngos.find((n) => n.id === app.ngoId);
  const key = role ? reviewKeyOf(role) : null;

  const pc = app.sanction ? paymentCase(state, pfms, app) : null;
  const advice = pc?.advice;
  const req = advice ? latestRequest(advice) : undefined;
  const me = state.session;

  const caps = me ? ROLES[me].caps : [];
  const stopped = pc ? (["returned-by-pfms", "not-accepted", "cancelled", "fy-expired", "credit-failed"] as const).includes(pc.stage as never) : false;
  const recon = advice && req ? reconcile([advice], pfms.feed)[0] : undefined;
  const feedEntry = req ? pfms.feed.find((f) => f.uniqueIdentifier === req.uniqueIdentifier) : undefined;

  return (
    <div className="space-y-6">
      <PageHeader
        title={ngo?.name ?? app.ngoId}
        status={
          pc && !pc.paidBeforeIntegration ? (
            <StageBadge stage={pc.stage} />
          ) : (
            <Badge status={statusTone(app.status)} className="h-auto max-w-full whitespace-normal">
              {statusLabel(app)}
            </Badge>
          )
        }
        meta={
          <span className="block space-y-1">
            <span className="block text-body-2 text-ink">
              {projectTitleFor(state, app)} · {schemeLabel(app.schemeCode)} · FY {app.financialYear}
            </span>
            <span className="block text-body-3 text-ink-muted">
              Application No. <RefText value={app.id} className="text-ink" /> · Project ID {app.institutionId}
            </span>
          </span>
        }
        actions={
          <div className="flex min-w-0 max-w-full flex-wrap items-center gap-3">
            {key && (
              <Link
                href={`/portals/e-anudaan/dashboard/sm2/${key}/review/${encodeURIComponent(app.id)}`}
                className={buttonClasses("primary", "outlined", "sm", "whitespace-nowrap")}
              >
                <Icon name="description" size={16} aria-hidden /> View Application
              </Link>
            )}
            {pc && stopped && caps.includes("prepareAdvice") && <MakerNextStep pc={pc} />}
          </div>
        }
      />

      <ServiceErrorNotice failure={failure} homeHref={role?.home} onRetry={clearFailure} onDismiss={clearFailure} />

      {pc && <PaymentProgress pc={pc} onShowReturn={() => setShowReturn(true)} />}

      {advice && (
        <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_25rem]">
          <div className="space-y-6">
            <Card variant="outlined">
              <CardBody className="space-y-4">
                <SectionTitle title="Release Reconciliation" />
                <DescriptionList
                  columns={2}
                  items={[
                    { term: "Sanctioned", value: exact(advice.sanctionAmount) },
                    { term: "Released by the Ministry", value: feedEntry ? exact(feedEntry.amount) : "Not yet" },
                    { term: "Credited to the NGO", value: exact(req?.payments.filter((p) => p.utr).reduce((sum, p) => sum + p.amount, 0) ?? 0) },
                    { term: "Matches the Release Feed", value: recon ? RECON_LABEL[recon.state] : "Not yet checked" },
                  ]}
                />
              </CardBody>
            </Card>
            <Card variant="outlined">
              <CardBody className="space-y-4">
                <SectionTitle title="Bill and Voucher" />
                <DescriptionList
                  columns={2}
                  items={[
                    { term: "Bill Number", value: req?.bill?.billNumber ?? "Not yet generated" },
                    { term: "Bill Date", value: req?.bill ? formatDate(req.bill.billDate) : "—" },
                    { term: "Token Number", value: req?.bill?.tokenNumber ?? "Not yet generated" },
                    { term: "Token Date", value: req?.bill ? formatDate(req.bill.tokenDate) : "—" },
                    { term: "Voucher Number", value: req?.voucher?.number ?? "Not yet generated" },
                    { term: "Voucher Date", value: req?.voucher ? formatDate(req.voucher.date) : "—" },
                  ]}
                />
              </CardBody>
            </Card>
            <Card variant="outlined">
              <CardBody className="space-y-4">
                <SectionTitle title="Payment to the NGO" />
                {(req?.payments.length ? req.payments : [undefined]).map((p, i) => (
                  <DescriptionList
                    key={p?.beneficiaryId ?? i}
                    columns={2}
                    items={[
                      { term: "UTR (Bank Transaction ID)", value: p?.utr ? <span className="font-mono">{p.utr}</span> : "Awaiting" },
                      { term: "Scroll Status", value: p?.scrollStatus === "Success" ? "Credited" : p?.scrollStatus === "Failed" ? "Failed at Bank" : "Pending" },
                      { term: "Scroll Date", value: p?.scrollDate ? formatDate(p.scrollDate) : "—" },
                      { term: "Credited On", value: p?.utr && p.scrollDate ? formatDate(p.scrollDate) : "—" },
                    ]}
                  />
                ))}
              </CardBody>
            </Card>
          </div>
          <Card variant="outlined">
            <CardBody className="space-y-4">
              <SectionTitle title="Payment History" />
              {/* A list, not VerticalTimeline: that component is a website history band, and in a
                  narrow column its titles wrapped to headline size and its dates ran out of the card. */}
              <ListGroup aria-label="Payment history">
                {[...advice.history].reverse().map((e, i) => (
                  <ListRow key={`${e.at}-${i}`} className="px-0" title={<span className="font-semibold">{e.text}</span>} description={formatDateTime(e.at)} />
                ))}
              </ListGroup>
            </CardBody>
          </Card>
        </div>
      )}

      {advice?.earlier && advice.earlier.length > 0 && (
        <Card variant="outlined">
          <CardBody className="space-y-4">
            <SectionTitle title="Earlier Payment Advices" count={advice.earlier.length} />
            <ListGroup aria-label="Earlier payment advices">
              {[...advice.earlier].reverse().map((e) => {
                const last = e.requests[e.requests.length - 1];
                return (
                  <ListRow
                    key={e.id}
                    title={e.id}
                    description={
                      <span className="block">
                        {last ? (
                          <>
                            Last sent {formatDateTime(last.sentAt)} as <span className="font-mono">{last.uniqueIdentifier}</span>
                            {last.returnReason ? ` · ${last.returnReason}` : ""}
                          </>
                        ) : (
                          "Never sent to PFMS."
                        )}
                      </span>
                    }
                    trailing={<StageBadge stage={stageOf(e)} size="sm" />}
                  />
                );
              })}
            </ListGroup>
          </CardBody>
        </Card>
      )}

      {req?.returnReason && (
        <SideSheet open={showReturn} onClose={() => setShowReturn(false)} title="Return Order" size="md">
          <DescriptionList
            columns={1}
            items={[
              { term: "Returned By", value: returnedBy(req) },
              { term: "Returned On", value: req.statusAt ? formatDate(req.statusAt) : "" },
              { term: "Reason", value: req.returnReason },
              { term: "Request", value: <span className="font-mono">{req.uniqueIdentifier}</span> },
              {
                term: "Return Memo (PFMS)",
                value: (
                  <span className="inline-flex flex-wrap items-center gap-2">
                    <a href={RETURN_MEMO_SAMPLE} target="_blank" rel="noopener noreferrer" className="font-semibold text-[var(--sa-text-link-brand-default)] underline underline-offset-2">
                      Open the Return Memo
                    </a>
                    <Badge status="neutral" size="sm">Sample</Badge>
                  </span>
                ),
              },
            ]}
          />
        </SideSheet>
      )}
    </div>
  );
}

/** The Maker's way out of a stopped payment: correct it, or — where PFMS ended it — start afresh. */
function MakerNextStep({ pc }: { pc: PaymentCase }) {
  const { startFresh } = usePfms();
  const router = useRouter();
  const { toast } = useToast();
  if (RESTARTABLE.includes(pc.stage)) {
    return (
      <Button
        size="sm"
        onClick={() => {
          const res = startFresh(pc.app.id);
          if (!res.ok) toast(res.error, "error");
          else router.push(prepareHref(pc.app.id));
        }}
      >
        Start a Fresh Payment Advice
      </Button>
    );
  }
  return (
    <Link href={prepareHref(pc.app.id)} className={buttonClasses("primary", "filled", "sm", "whitespace-nowrap")}>
      Correct and Resubmit
    </Link>
  );
}

/**
 * Where the payment has reached, as six plain stages — and, only when it has stopped, why. A payment
 * moving normally needs no sentence: the stepper and the badge say it (handoff audit, 3 Oct 2026).
 */
function PaymentProgress({ pc, onShowReturn }: { pc: PaymentCase; onShowReturn: () => void }) {
  const { pfms } = usePfms();
  const advice = pc.advice;
  const req = advice ? latestRequest(advice) : undefined;
  const returnOrder = req?.returnReason ? (
    <Button size="sm" appearance="outlined" onClick={onShowReturn}>
      View Return Order
    </Button>
  ) : undefined;

  let notice: React.ReactNode = null;
  if (pc.paidBeforeIntegration) {
    notice = (
      <Alert status="info" title="Paid Before the PFMS Integration">
        Released on {pc.app.release ? formatDate(pc.app.release.releasedAt) : ""}, before payments were sent to PFMS from e-Anudaan.
      </Alert>
    );
  } else if (pc.blocker) {
    notice = (
      <Alert status="warning" title={BLOCKER_TEXT[pc.blocker].label}>
        {BLOCKER_TEXT[pc.blocker].body}
      </Alert>
    );
  } else {
    switch (pc.stage) {
      case "returned-by-pfms":
      case "cancelled":
        notice = (
          <Alert status={pc.stage === "cancelled" ? "error" : "warning"} title={`${STAGE_INFO[pc.stage].label} on ${req?.statusAt ? formatDate(req.statusAt) : ""}`} action={returnOrder}>
            Reason given by PFMS: {req?.returnReason}
          </Alert>
        );
        break;
      case "not-accepted":
        notice = (
          <Alert status="error" title="Not Accepted by PFMS">
            {advice?.issues.map((i) => (
              <span key={i.pfmsCode ?? i.field} className="block">
                {pfmsError(i.pfmsCode ?? "", pfms.errorOverrides).message}
              </span>
            ))}
          </Alert>
        );
        break;
      case "fy-expired":
        notice = (
          <Alert status="error" title="Financial Year Expired">
            The financial year closed before PFMS paid this bill{req?.statusAt ? ` (${formatDate(req.statusAt)})` : ""}.
          </Alert>
        );
        break;
      case "credit-failed":
        notice = (
          <Alert status="error" title="Credit Failed at Bank">
            The bank could not credit the NGO&apos;s account. The NGO has been asked to check its bank details.
          </Alert>
        );
        break;
      case "waiting-to-resend":
        notice = (
          <Alert status="warning" title="Waiting to Resend">
            PFMS could not be reached{req ? ` on ${formatDateTime(req.sentAt)}` : ""}. It is sent again automatically.
          </Alert>
        );
        break;
      default:
        notice = null;
    }
  }

  return (
    <Card variant="outlined">
      <CardBody className="space-y-4">
        <SectionTitle
          title="Payment"
          description={advice ? `Payment advice ${advice.id}${req ? ` · Unique Identifier ${req.uniqueIdentifier}` : ""}` : undefined}
        />
        {!pc.paidBeforeIntegration && <PlainPaymentStages stage={pc.stage} advice={advice} />}
        {notice}
      </CardBody>
    </Card>
  );
}
