/* GENERATED by @mosje/tokens (build/generate-ts-mirror.mjs) — do not edit.
   The typed named-export mirror of the token contract, for consumers that want values in TS
   rather than CSS custom properties. Values are READ FROM dist/tokens.css, so this file
   cannot disagree with what actually renders.

   It was hand-maintained until 2026-08-11, at which point 12 of its 22 colours had drifted —
   `warning` was gov-yellow, `info` was the primary blue, `danger` pointed at the wrong
   rung — along with radius.pill, every shadow, and a typography block still written in fixed
   px for a scale that is fluid. Regenerate with: npm run build -w @mosje/tokens

   PREFER THE CSS CUSTOM PROPERTIES. These literals are resolved at BUILD time, so they are
   frozen to the default brand and cannot follow `data-brand` — `var(--sa-color-action-primary-default)` repaints
   when the brand switches and `colors.primary` does not. */
export const colors = {
  primary: "#0373df",
  primaryTonal: "#c0dbff",
  primaryDark: "#004b96",
  primaryRing: "rgba(3, 115, 223, 0.48)",
  success: "#046a38",
  successTonal: "#bde3c7",
  danger: "#aa2d30",
  warning: "#8b5e00",
  info: "#006d85",
  ink: "#1e2124",
  inkStrong: "#0e1114",
  inkMuted: "#3a3d41",
  onPrimary: "#ffffff",
  surface: "#ffffff",
  surfaceAlt: "#eef0f3",
  surfaceMuted: "#eef0f3",
  border: "#dcdee1",
  borderStrong: "#c6c9cd",
  saffron: "#ff671f",
  saffronLight: "#fff2ed",
  saffronDark: "#a43a00",
  navy: "#003366",
  yellow: "#ffd323",
} as const;

export const radius = {
  xxs: "2px",
  xs: "4px",
  sm: "6px",
  md: "8px",
  pill: "999px",
} as const;

export const fontFamily = {
  sans: "\"Noto Sans\", ui-sans-serif, system-ui, sans-serif",
} as const;

/** Named type styles. Fluid: `size`/`leading` are clamp() or rem strings, not px numbers. */
export const typography = {
  display: { size: "clamp(2.5rem, calc(1.5217rem + 4.348vw), 5rem)", leading: "clamp(2.75rem, calc(1.6739rem + 4.783vw), 5.5rem)" },
  title1: { size: "clamp(1.5rem, calc(1.3043rem + 0.87vw), 2rem)", leading: "clamp(1.75rem, calc(1.4565rem + 1.304vw), 2.5rem)" },
  headline: { size: "clamp(1.75rem, calc(1.4565rem + 1.304vw), 2.5rem)", leading: "clamp(2rem, calc(1.6087rem + 1.739vw), 3rem)" },
  title2: { size: "clamp(1.125rem, calc(1.0272rem + 0.435vw), 1.375rem)", leading: "clamp(1.5rem, calc(1.4022rem + 0.435vw), 1.75rem)" },
  body1: { size: "1rem", leading: "1.5rem" },
  body2: { size: "0.875rem", leading: "1.25rem" },
  body3: { size: "0.75rem", leading: "1rem" },
  label1: { size: "0.875rem", leading: "1.25rem" },
  label3: { size: "0.6875rem", leading: "1rem" },
} as const;

export const shadow = {
  xs: "0 2px 3px 1px rgba(30, 33, 36, 0.12)",
  lg: "0 12px 16px -4px rgba(30, 33, 36, 0.08), 0 4px 6px -2px rgba(30, 33, 36, 0.03)",
  xl: "0 24px 48px -12px rgba(30, 33, 36, 0.18)",
} as const;

/** Icon sizes in px, read from the stylesheet so this list cannot fall behind the scale.
    DBIM 3.0 section 3.4 publishes 24, 32, 48 and 64; the smaller steps are ours and are kept
    deliberately (.claude/rules/standards-precedence.md). */
export const iconSize = {
  px16: 16,
  px20: 20,
  px24: 24,
  px32: 32,
  px40: 40,
  px48: 48,
  px64: 64,
} as const;

export const tokens = { colors, radius, fontFamily, typography, shadow, iconSize } as const;
export default tokens;
