/* GENERATED by @mosje/tokens (build/generate-color-docs-data.mjs) — do not edit.

   Every value here is READ FROM dist/tokens.css, so this page cannot state a colour or a
   contrast ratio the build does not produce. It replaced 88 hand-copied hex literals, 14 of
   which had stopped matching any token in the system.

   Its counterpart in Figma is variable-BOUND for the same reason. Both surfaces are pinned to
   one source; what they cannot pin is STRUCTURE, so SECTIONS below is gated by
   scripts/check-color-docs.mjs against the Figma frame's section list.

   Regenerate: npm run build -w @mosje/tokens */

export type RampStep = { step: number; token: string; blue: string; navy: string; onWhite: number | null; anchor: string | null };
export type Ramp = { name: string; steps: RampStep[]; brandVaries: boolean };
export type InkPair = { rung: string; bgToken: string; onToken: string; fill: string; ink: string; ratio: number | null };
export type PairFamily = { family: string; label: string; rungs: InkPair[] };
export type LedgerEntry = { token: string; measured?: number; implied?: number; rung?: string };
export type Section = { id: string; title: string };

export const META = {
  "ramps": 8,
  "brands": 2,
  "rungs": 6,
  "inkPairs": 46,
  "worstInkPair": 4.97,
  "belowAA": 0,
  "rungCaveats": 16,
  "brandVaryingRamps": [
    "primaryScale",
    "neutralScale"
  ],
  "worstChartSeries": 3.52,
  "generatedFrom": "packages/tokens/dist/tokens.css"
} as const;

export const SECTIONS: readonly Section[] = [
  {
    "id": "hero",
    "title": "At a glance"
  },
  {
    "id": "anatomy",
    "title": "How to read a colour token"
  },
  {
    "id": "tiers",
    "title": "Three tiers, and the one you are allowed to type"
  },
  {
    "id": "ramps",
    "title": "The ramps"
  },
  {
    "id": "prominence",
    "title": "Six rungs, from quiet to loud"
  },
  {
    "id": "ink-pairings",
    "title": "Never choose an ink — the system already measured one"
  },
  {
    "id": "slots",
    "title": "Seven slots, and a slot means one thing only"
  },
  {
    "id": "status",
    "title": "Four meanings, and never colour alone"
  },
  {
    "id": "states",
    "title": "Interaction states, and the ring that must always be visible"
  },
  {
    "id": "layers",
    "title": "Depth without guessing a grey"
  },
  {
    "id": "neutrals-alpha",
    "title": "A grey that belongs to the brand, and six levels of translucency"
  },
  {
    "id": "brands",
    "title": "Two brands, and exactly what a swap changes"
  },
  {
    "id": "conformance",
    "title": "What this palette owes to DBIM and UX4G"
  },
  {
    "id": "charts",
    "title": "Twelve series, and the rules that keep a chart readable"
  },
  {
    "id": "do-and-dont",
    "title": "Nine mistakes this estate has actually made"
  },
  {
    "id": "accessibility",
    "title": "The floors, and how they are held"
  },
  {
    "id": "handoff",
    "title": "From this variable to that line of code"
  },
  {
    "id": "retired",
    "title": "What was retired, and what replaced it"
  },
  {
    "id": "provenance",
    "title": "Where these numbers come from"
  }
];

export const RAMPS: readonly Ramp[] = [
  {
    "name": "primaryScale",
    "steps": [
      {
        "step": 50,
        "token": "--sa-color-primaryScale-50",
        "blue": "#ecf4ff",
        "navy": "#f8fafd",
        "onWhite": 1.11,
        "anchor": null
      },
      {
        "step": 100,
        "token": "--sa-color-primaryScale-100",
        "blue": "#c0dbff",
        "navy": "#c9d6e5",
        "onWhite": 1.42,
        "anchor": null
      },
      {
        "step": 200,
        "token": "--sa-color-primaryScale-200",
        "blue": "#95c2fb",
        "navy": "#9cb0ca",
        "onWhite": 1.84,
        "anchor": null
      },
      {
        "step": 300,
        "token": "--sa-color-primaryScale-300",
        "blue": "#6ca8f3",
        "navy": "#708caf",
        "onWhite": 2.46,
        "anchor": null
      },
      {
        "step": 400,
        "token": "--sa-color-primaryScale-400",
        "blue": "#428dea",
        "navy": "#486a94",
        "onWhite": 3.37,
        "anchor": null
      },
      {
        "step": 500,
        "token": "--sa-color-primaryScale-500",
        "blue": "#0373df",
        "navy": "#244c7b",
        "onWhite": 4.64,
        "anchor": "anchor · blue"
      },
      {
        "step": 600,
        "token": "--sa-color-primaryScale-600",
        "blue": "#005eb9",
        "navy": "#003366",
        "onWhite": 6.36,
        "anchor": "anchor · navy"
      },
      {
        "step": 700,
        "token": "--sa-color-primaryScale-700",
        "blue": "#004b96",
        "navy": "#002249",
        "onWhite": 8.58,
        "anchor": null
      },
      {
        "step": 800,
        "token": "--sa-color-primaryScale-800",
        "blue": "#003975",
        "navy": "#001734",
        "onWhite": 11.4,
        "anchor": null
      },
      {
        "step": 900,
        "token": "--sa-color-primaryScale-900",
        "blue": "#002855",
        "navy": "#000e24",
        "onWhite": 14.64,
        "anchor": null
      },
      {
        "step": 950,
        "token": "--sa-color-primaryScale-950",
        "blue": "#001737",
        "navy": "#000614",
        "onWhite": 17.83,
        "anchor": null
      }
    ],
    "brandVaries": true
  },
  {
    "name": "secondaryScale",
    "steps": [
      {
        "step": 50,
        "token": "--sa-color-secondaryScale-50",
        "blue": "#fff2ed",
        "navy": "#fff2ed",
        "onWhite": 1.1,
        "anchor": null
      },
      {
        "step": 100,
        "token": "--sa-color-secondaryScale-100",
        "blue": "#ffd4c4",
        "navy": "#ffd4c4",
        "onWhite": 1.36,
        "anchor": null
      },
      {
        "step": 200,
        "token": "--sa-color-secondaryScale-200",
        "blue": "#ffb498",
        "navy": "#ffb498",
        "onWhite": 1.72,
        "anchor": null
      },
      {
        "step": 300,
        "token": "--sa-color-secondaryScale-300",
        "blue": "#ff9167",
        "navy": "#ff9167",
        "onWhite": 2.21,
        "anchor": null
      },
      {
        "step": 400,
        "token": "--sa-color-secondaryScale-400",
        "blue": "#ff671f",
        "navy": "#ff671f",
        "onWhite": 2.91,
        "anchor": "anchor"
      },
      {
        "step": 500,
        "token": "--sa-color-secondaryScale-500",
        "blue": "#e1560f",
        "navy": "#e1560f",
        "onWhite": 3.79,
        "anchor": null
      },
      {
        "step": 600,
        "token": "--sa-color-secondaryScale-600",
        "blue": "#c34700",
        "navy": "#c34700",
        "onWhite": 4.97,
        "anchor": null
      },
      {
        "step": 700,
        "token": "--sa-color-secondaryScale-700",
        "blue": "#a43a00",
        "navy": "#a43a00",
        "onWhite": 6.6,
        "anchor": null
      },
      {
        "step": 800,
        "token": "--sa-color-secondaryScale-800",
        "blue": "#862e00",
        "navy": "#862e00",
        "onWhite": 8.73,
        "anchor": null
      },
      {
        "step": 900,
        "token": "--sa-color-secondaryScale-900",
        "blue": "#692200",
        "navy": "#692200",
        "onWhite": 11.48,
        "anchor": null
      },
      {
        "step": 950,
        "token": "--sa-color-secondaryScale-950",
        "blue": "#4d1700",
        "navy": "#4d1700",
        "onWhite": 14.6,
        "anchor": null
      }
    ],
    "brandVaries": false
  },
  {
    "name": "accentScale",
    "steps": [
      {
        "step": 50,
        "token": "--sa-color-accentScale-50",
        "blue": "#ecf4ee",
        "navy": "#ecf4ee",
        "onWhite": 1.12,
        "anchor": null
      },
      {
        "step": 100,
        "token": "--sa-color-accentScale-100",
        "blue": "#bed8c5",
        "navy": "#bed8c5",
        "onWhite": 1.52,
        "anchor": null
      },
      {
        "step": 200,
        "token": "--sa-color-accentScale-200",
        "blue": "#91b99c",
        "navy": "#91b99c",
        "onWhite": 2.18,
        "anchor": null
      },
      {
        "step": 300,
        "token": "--sa-color-accentScale-300",
        "blue": "#659c77",
        "navy": "#659c77",
        "onWhite": 3.19,
        "anchor": null
      },
      {
        "step": 400,
        "token": "--sa-color-accentScale-400",
        "blue": "#3b8155",
        "navy": "#3b8155",
        "onWhite": 4.71,
        "anchor": null
      },
      {
        "step": 500,
        "token": "--sa-color-accentScale-500",
        "blue": "#046a38",
        "navy": "#046a38",
        "onWhite": 6.72,
        "anchor": "anchor"
      },
      {
        "step": 600,
        "token": "--sa-color-accentScale-600",
        "blue": "#00542b",
        "navy": "#00542b",
        "onWhite": 9.12,
        "anchor": null
      },
      {
        "step": 700,
        "token": "--sa-color-accentScale-700",
        "blue": "#004220",
        "navy": "#004220",
        "onWhite": 11.67,
        "anchor": null
      },
      {
        "step": 800,
        "token": "--sa-color-accentScale-800",
        "blue": "#003318",
        "navy": "#003318",
        "onWhite": 14.13,
        "anchor": null
      },
      {
        "step": 900,
        "token": "--sa-color-accentScale-900",
        "blue": "#002510",
        "navy": "#002510",
        "onWhite": 16.51,
        "anchor": null
      },
      {
        "step": 950,
        "token": "--sa-color-accentScale-950",
        "blue": "#001708",
        "navy": "#001708",
        "onWhite": 18.65,
        "anchor": null
      }
    ],
    "brandVaries": false
  },
  {
    "name": "neutralScale",
    "steps": [
      {
        "step": 0,
        "token": "--sa-color-neutralScale-0",
        "blue": "#ffffff",
        "navy": "#ffffff",
        "onWhite": 1,
        "anchor": null
      },
      {
        "step": 50,
        "token": "--sa-color-neutralScale-50",
        "blue": "#eef0f3",
        "navy": "#eff0f2",
        "onWhite": 1.14,
        "anchor": null
      },
      {
        "step": 100,
        "token": "--sa-color-neutralScale-100",
        "blue": "#dcdee1",
        "navy": "#dcdee2",
        "onWhite": 1.35,
        "anchor": null
      },
      {
        "step": 200,
        "token": "--sa-color-neutralScale-200",
        "blue": "#c6c9cd",
        "navy": "#c6c9ce",
        "onWhite": 1.66,
        "anchor": null
      },
      {
        "step": 300,
        "token": "--sa-color-neutralScale-300",
        "blue": "#adb1b7",
        "navy": "#aeb1b7",
        "onWhite": 2.15,
        "anchor": null
      },
      {
        "step": 400,
        "token": "--sa-color-neutralScale-400",
        "blue": "#8e949c",
        "navy": "#8f949d",
        "onWhite": 3.06,
        "anchor": null
      },
      {
        "step": 500,
        "token": "--sa-color-neutralScale-500",
        "blue": "#6f757d",
        "navy": "#70757d",
        "onWhite": 4.65,
        "anchor": null
      },
      {
        "step": 600,
        "token": "--sa-color-neutralScale-600",
        "blue": "#54585e",
        "navy": "#55585e",
        "onWhite": 7.16,
        "anchor": null
      },
      {
        "step": 700,
        "token": "--sa-color-neutralScale-700",
        "blue": "#3a3d41",
        "navy": "#3b3d41",
        "onWhite": 10.92,
        "anchor": null
      },
      {
        "step": 800,
        "token": "--sa-color-neutralScale-800",
        "blue": "#1e2124",
        "navy": "#1e2024",
        "onWhite": 16.18,
        "anchor": null
      },
      {
        "step": 900,
        "token": "--sa-color-neutralScale-900",
        "blue": "#0e1114",
        "navy": "#0f1012",
        "onWhite": 18.94,
        "anchor": null
      },
      {
        "step": 950,
        "token": "--sa-color-neutralScale-950",
        "blue": "#030406",
        "navy": "#030406",
        "onWhite": 20.51,
        "anchor": null
      },
      {
        "step": 1000,
        "token": "--sa-color-neutralScale-1000",
        "blue": "#000000",
        "navy": "#000000",
        "onWhite": 21,
        "anchor": null
      }
    ],
    "brandVaries": true
  },
  {
    "name": "successScale",
    "steps": [
      {
        "step": 50,
        "token": "--sa-color-successScale-50",
        "blue": "#ecf4ee",
        "navy": "#ecf4ee",
        "onWhite": 1.12,
        "anchor": null
      },
      {
        "step": 100,
        "token": "--sa-color-successScale-100",
        "blue": "#bed8c5",
        "navy": "#bed8c5",
        "onWhite": 1.52,
        "anchor": null
      },
      {
        "step": 200,
        "token": "--sa-color-successScale-200",
        "blue": "#91b99c",
        "navy": "#91b99c",
        "onWhite": 2.18,
        "anchor": null
      },
      {
        "step": 300,
        "token": "--sa-color-successScale-300",
        "blue": "#659c77",
        "navy": "#659c77",
        "onWhite": 3.19,
        "anchor": null
      },
      {
        "step": 400,
        "token": "--sa-color-successScale-400",
        "blue": "#3b8155",
        "navy": "#3b8155",
        "onWhite": 4.71,
        "anchor": null
      },
      {
        "step": 500,
        "token": "--sa-color-successScale-500",
        "blue": "#046a38",
        "navy": "#046a38",
        "onWhite": 6.72,
        "anchor": "anchor"
      },
      {
        "step": 600,
        "token": "--sa-color-successScale-600",
        "blue": "#00542b",
        "navy": "#00542b",
        "onWhite": 9.12,
        "anchor": null
      },
      {
        "step": 700,
        "token": "--sa-color-successScale-700",
        "blue": "#004220",
        "navy": "#004220",
        "onWhite": 11.67,
        "anchor": null
      },
      {
        "step": 800,
        "token": "--sa-color-successScale-800",
        "blue": "#003318",
        "navy": "#003318",
        "onWhite": 14.13,
        "anchor": null
      },
      {
        "step": 900,
        "token": "--sa-color-successScale-900",
        "blue": "#002510",
        "navy": "#002510",
        "onWhite": 16.51,
        "anchor": null
      },
      {
        "step": 950,
        "token": "--sa-color-successScale-950",
        "blue": "#001708",
        "navy": "#001708",
        "onWhite": 18.65,
        "anchor": null
      }
    ],
    "brandVaries": false
  },
  {
    "name": "dangerScale",
    "steps": [
      {
        "step": 50,
        "token": "--sa-color-dangerScale-50",
        "blue": "#ffe4e0",
        "navy": "#ffe4e0",
        "onWhite": 1.21,
        "anchor": null
      },
      {
        "step": 100,
        "token": "--sa-color-dangerScale-100",
        "blue": "#ffc2b8",
        "navy": "#ffc2b8",
        "onWhite": 1.54,
        "anchor": null
      },
      {
        "step": 200,
        "token": "--sa-color-dangerScale-200",
        "blue": "#ff9d8f",
        "navy": "#ff9d8f",
        "onWhite": 2.01,
        "anchor": null
      },
      {
        "step": 300,
        "token": "--sa-color-dangerScale-300",
        "blue": "#f87868",
        "navy": "#f87868",
        "onWhite": 2.67,
        "anchor": null
      },
      {
        "step": 400,
        "token": "--sa-color-dangerScale-400",
        "blue": "#ec5042",
        "navy": "#ec5042",
        "onWhite": 3.63,
        "anchor": "anchor"
      },
      {
        "step": 500,
        "token": "--sa-color-dangerScale-500",
        "blue": "#cb3f33",
        "navy": "#cb3f33",
        "onWhite": 4.89,
        "anchor": null
      },
      {
        "step": 600,
        "token": "--sa-color-dangerScale-600",
        "blue": "#aa2f25",
        "navy": "#aa2f25",
        "onWhite": 6.68,
        "anchor": null
      },
      {
        "step": 700,
        "token": "--sa-color-dangerScale-700",
        "blue": "#8b1f18",
        "navy": "#8b1f18",
        "onWhite": 9.1,
        "anchor": null
      },
      {
        "step": 800,
        "token": "--sa-color-dangerScale-800",
        "blue": "#6c100c",
        "navy": "#6c100c",
        "onWhite": 12.23,
        "anchor": null
      },
      {
        "step": 900,
        "token": "--sa-color-dangerScale-900",
        "blue": "#4e0303",
        "navy": "#4e0303",
        "onWhite": 15.69,
        "anchor": null
      },
      {
        "step": 950,
        "token": "--sa-color-dangerScale-950",
        "blue": "#300000",
        "navy": "#300000",
        "onWhite": 18.66,
        "anchor": null
      }
    ],
    "brandVaries": false
  },
  {
    "name": "warningScale",
    "steps": [
      {
        "step": 50,
        "token": "--sa-color-warningScale-50",
        "blue": "#fef1e0",
        "navy": "#fef1e0",
        "onWhite": 1.11,
        "anchor": null
      },
      {
        "step": 100,
        "token": "--sa-color-warningScale-100",
        "blue": "#f7d5a6",
        "navy": "#f7d5a6",
        "onWhite": 1.4,
        "anchor": null
      },
      {
        "step": 200,
        "token": "--sa-color-warningScale-200",
        "blue": "#ecb96c",
        "navy": "#ecb96c",
        "onWhite": 1.79,
        "anchor": null
      },
      {
        "step": 300,
        "token": "--sa-color-warningScale-300",
        "blue": "#e09c1d",
        "navy": "#e09c1d",
        "onWhite": 2.35,
        "anchor": "anchor"
      },
      {
        "step": 400,
        "token": "--sa-color-warningScale-400",
        "blue": "#c48608",
        "navy": "#c48608",
        "onWhite": 3.11,
        "anchor": null
      },
      {
        "step": 500,
        "token": "--sa-color-warningScale-500",
        "blue": "#a77200",
        "navy": "#a77200",
        "onWhite": 4.16,
        "anchor": null
      },
      {
        "step": 600,
        "token": "--sa-color-warningScale-600",
        "blue": "#8b5e00",
        "navy": "#8b5e00",
        "onWhite": 5.68,
        "anchor": null
      },
      {
        "step": 700,
        "token": "--sa-color-warningScale-700",
        "blue": "#704b00",
        "navy": "#704b00",
        "onWhite": 7.79,
        "anchor": null
      },
      {
        "step": 800,
        "token": "--sa-color-warningScale-800",
        "blue": "#563900",
        "navy": "#563900",
        "onWhite": 10.6,
        "anchor": null
      },
      {
        "step": 900,
        "token": "--sa-color-warningScale-900",
        "blue": "#3e2700",
        "navy": "#3e2700",
        "onWhite": 14.05,
        "anchor": null
      },
      {
        "step": 950,
        "token": "--sa-color-warningScale-950",
        "blue": "#271700",
        "navy": "#271700",
        "onWhite": 17.37,
        "anchor": null
      }
    ],
    "brandVaries": false
  },
  {
    "name": "infoScale",
    "steps": [
      {
        "step": 50,
        "token": "--sa-color-infoScale-50",
        "blue": "#edf4ff",
        "navy": "#edf4ff",
        "onWhite": 1.11,
        "anchor": null
      },
      {
        "step": 100,
        "token": "--sa-color-infoScale-100",
        "blue": "#c3dcff",
        "navy": "#c3dcff",
        "onWhite": 1.4,
        "anchor": null
      },
      {
        "step": 200,
        "token": "--sa-color-infoScale-200",
        "blue": "#99c3ff",
        "navy": "#99c3ff",
        "onWhite": 1.81,
        "anchor": null
      },
      {
        "step": 300,
        "token": "--sa-color-infoScale-300",
        "blue": "#72a9fa",
        "navy": "#72a9fa",
        "onWhite": 2.39,
        "anchor": null
      },
      {
        "step": 400,
        "token": "--sa-color-infoScale-400",
        "blue": "#4a8ff2",
        "navy": "#4a8ff2",
        "onWhite": 3.23,
        "anchor": null
      },
      {
        "step": 500,
        "token": "--sa-color-infoScale-500",
        "blue": "#1a73e8",
        "navy": "#1a73e8",
        "onWhite": 4.51,
        "anchor": "anchor"
      },
      {
        "step": 600,
        "token": "--sa-color-infoScale-600",
        "blue": "#0a5cc3",
        "navy": "#0a5cc3",
        "onWhite": 6.3,
        "anchor": null
      },
      {
        "step": 700,
        "token": "--sa-color-infoScale-700",
        "blue": "#00479d",
        "navy": "#00479d",
        "onWhite": 8.79,
        "anchor": null
      },
      {
        "step": 800,
        "token": "--sa-color-infoScale-800",
        "blue": "#003376",
        "navy": "#003376",
        "onWhite": 12.1,
        "anchor": null
      },
      {
        "step": 900,
        "token": "--sa-color-infoScale-900",
        "blue": "#002150",
        "navy": "#002150",
        "onWhite": 15.75,
        "anchor": null
      },
      {
        "step": 950,
        "token": "--sa-color-infoScale-950",
        "blue": "#00102e",
        "navy": "#00102e",
        "onWhite": 18.86,
        "anchor": null
      }
    ],
    "brandVaries": false
  }
];

export const INK_PAIRS: readonly PairFamily[] = [
  {
    "family": "neutral",
    "label": "neutral",
    "rungs": [
      {
        "rung": "subtler",
        "bgToken": "bg/neutral/subtler",
        "onToken": "on/bg/neutral/subtler",
        "fill": "#eef0f3",
        "ink": "#1e2124",
        "ratio": 14.17
      },
      {
        "rung": "subtle",
        "bgToken": "bg/neutral/subtle",
        "onToken": "on/bg/neutral/subtle",
        "fill": "#dcdee1",
        "ink": "#1e2124",
        "ratio": 12
      },
      {
        "rung": "base",
        "bgToken": "bg/neutral/base",
        "onToken": "on/bg/neutral/base",
        "fill": "#ffffff",
        "ink": "#1e2124",
        "ratio": 16.18
      },
      {
        "rung": "bold",
        "bgToken": "bg/neutral/bold",
        "onToken": "on/bg/neutral/bold",
        "fill": "#c6c9cd",
        "ink": "#1e2124",
        "ratio": 9.73
      }
    ]
  },
  {
    "family": "brand-primary",
    "label": "brand / primary",
    "rungs": [
      {
        "rung": "subtler",
        "bgToken": "bg/brand/primary/subtler",
        "onToken": "on/bg/brand/primary/subtler",
        "fill": "#c0dbff",
        "ink": "#1e2124",
        "ratio": 11.41
      },
      {
        "rung": "subtle",
        "bgToken": "bg/brand/primary/subtle",
        "onToken": "on/bg/brand/primary/subtle",
        "fill": "#95c2fb",
        "ink": "#1e2124",
        "ratio": 8.77
      },
      {
        "rung": "base",
        "bgToken": "bg/brand/primary/base",
        "onToken": "on/bg/brand/primary/base",
        "fill": "#ecf4ff",
        "ink": "#1e2124",
        "ratio": 14.6
      },
      {
        "rung": "bold",
        "bgToken": "bg/brand/primary/bold",
        "onToken": "on/bg/brand/primary/bold",
        "fill": "#6ca8f3",
        "ink": "#1e2124",
        "ratio": 6.57
      },
      {
        "rung": "bolder",
        "bgToken": "bg/brand/primary/bolder",
        "onToken": "on/bg/brand/primary/bolder",
        "fill": "#005eb9",
        "ink": "#ffffff",
        "ratio": 6.36
      },
      {
        "rung": "boldest",
        "bgToken": "bg/brand/primary/boldest",
        "onToken": "on/bg/brand/primary/boldest",
        "fill": "#003975",
        "ink": "#ffffff",
        "ratio": 11.4
      }
    ]
  },
  {
    "family": "brand-secondary",
    "label": "brand / secondary",
    "rungs": [
      {
        "rung": "subtler",
        "bgToken": "bg/brand/secondary/subtler",
        "onToken": "on/bg/brand/secondary/subtler",
        "fill": "#ffd4c4",
        "ink": "#1e2124",
        "ratio": 11.91
      },
      {
        "rung": "subtle",
        "bgToken": "bg/brand/secondary/subtle",
        "onToken": "on/bg/brand/secondary/subtle",
        "fill": "#ffb498",
        "ink": "#1e2124",
        "ratio": 9.42
      },
      {
        "rung": "base",
        "bgToken": "bg/brand/secondary/base",
        "onToken": "on/bg/brand/secondary/base",
        "fill": "#fff2ed",
        "ink": "#1e2124",
        "ratio": 14.77
      },
      {
        "rung": "bold",
        "bgToken": "bg/brand/secondary/bold",
        "onToken": "on/bg/brand/secondary/bold",
        "fill": "#ff9167",
        "ink": "#1e2124",
        "ratio": 7.32
      },
      {
        "rung": "bolder",
        "bgToken": "bg/brand/secondary/bolder",
        "onToken": "on/bg/brand/secondary/bolder",
        "fill": "#c34700",
        "ink": "#ffffff",
        "ratio": 4.97
      },
      {
        "rung": "boldest",
        "bgToken": "bg/brand/secondary/boldest",
        "onToken": "on/bg/brand/secondary/boldest",
        "fill": "#862e00",
        "ink": "#ffffff",
        "ratio": 8.73
      }
    ]
  },
  {
    "family": "brand-accent",
    "label": "brand / accent",
    "rungs": [
      {
        "rung": "subtler",
        "bgToken": "bg/brand/accent/subtler",
        "onToken": "on/bg/brand/accent/subtler",
        "fill": "#bed8c5",
        "ink": "#1e2124",
        "ratio": 10.64
      },
      {
        "rung": "subtle",
        "bgToken": "bg/brand/accent/subtle",
        "onToken": "on/bg/brand/accent/subtle",
        "fill": "#91b99c",
        "ink": "#1e2124",
        "ratio": 7.41
      },
      {
        "rung": "base",
        "bgToken": "bg/brand/accent/base",
        "onToken": "on/bg/brand/accent/base",
        "fill": "#ecf4ee",
        "ink": "#1e2124",
        "ratio": 14.44
      },
      {
        "rung": "bold",
        "bgToken": "bg/brand/accent/bold",
        "onToken": "on/bg/brand/accent/bold",
        "fill": "#659c77",
        "ink": "#1e2124",
        "ratio": 5.06
      },
      {
        "rung": "bolder",
        "bgToken": "bg/brand/accent/bolder",
        "onToken": "on/bg/brand/accent/bolder",
        "fill": "#00542b",
        "ink": "#ffffff",
        "ratio": 9.12
      },
      {
        "rung": "boldest",
        "bgToken": "bg/brand/accent/boldest",
        "onToken": "on/bg/brand/accent/boldest",
        "fill": "#003318",
        "ink": "#ffffff",
        "ratio": 14.13
      }
    ]
  },
  {
    "family": "status-success",
    "label": "status / success",
    "rungs": [
      {
        "rung": "subtler",
        "bgToken": "bg/status/success/subtler",
        "onToken": "on/bg/status/success/subtler",
        "fill": "#bed8c5",
        "ink": "#1e2124",
        "ratio": 10.64
      },
      {
        "rung": "subtle",
        "bgToken": "bg/status/success/subtle",
        "onToken": "on/bg/status/success/subtle",
        "fill": "#91b99c",
        "ink": "#1e2124",
        "ratio": 7.41
      },
      {
        "rung": "base",
        "bgToken": "bg/status/success/base",
        "onToken": "on/bg/status/success/base",
        "fill": "#ecf4ee",
        "ink": "#1e2124",
        "ratio": 14.44
      },
      {
        "rung": "bold",
        "bgToken": "bg/status/success/bold",
        "onToken": "on/bg/status/success/bold",
        "fill": "#659c77",
        "ink": "#1e2124",
        "ratio": 5.06
      },
      {
        "rung": "bolder",
        "bgToken": "bg/status/success/bolder",
        "onToken": "on/bg/status/success/bolder",
        "fill": "#00542b",
        "ink": "#ffffff",
        "ratio": 9.12
      },
      {
        "rung": "boldest",
        "bgToken": "bg/status/success/boldest",
        "onToken": "on/bg/status/success/boldest",
        "fill": "#003318",
        "ink": "#ffffff",
        "ratio": 14.13
      }
    ]
  },
  {
    "family": "status-error",
    "label": "status / error",
    "rungs": [
      {
        "rung": "subtler",
        "bgToken": "bg/status/error/subtler",
        "onToken": "on/bg/status/error/subtler",
        "fill": "#ffc2b8",
        "ink": "#1e2124",
        "ratio": 10.52
      },
      {
        "rung": "subtle",
        "bgToken": "bg/status/error/subtle",
        "onToken": "on/bg/status/error/subtle",
        "fill": "#ff9d8f",
        "ink": "#1e2124",
        "ratio": 8.07
      },
      {
        "rung": "base",
        "bgToken": "bg/status/error/base",
        "onToken": "on/bg/status/error/base",
        "fill": "#ffe4e0",
        "ink": "#1e2124",
        "ratio": 13.42
      },
      {
        "rung": "bold",
        "bgToken": "bg/status/error/bold",
        "onToken": "on/bg/status/error/bold",
        "fill": "#f87868",
        "ink": "#1e2124",
        "ratio": 6.07
      },
      {
        "rung": "bolder",
        "bgToken": "bg/status/error/bolder",
        "onToken": "on/bg/status/error/bolder",
        "fill": "#aa2f25",
        "ink": "#ffffff",
        "ratio": 6.68
      },
      {
        "rung": "boldest",
        "bgToken": "bg/status/error/boldest",
        "onToken": "on/bg/status/error/boldest",
        "fill": "#6c100c",
        "ink": "#ffffff",
        "ratio": 12.23
      }
    ]
  },
  {
    "family": "status-warning",
    "label": "status / warning",
    "rungs": [
      {
        "rung": "subtler",
        "bgToken": "bg/status/warning/subtler",
        "onToken": "on/bg/status/warning/subtler",
        "fill": "#f7d5a6",
        "ink": "#1e2124",
        "ratio": 11.57
      },
      {
        "rung": "subtle",
        "bgToken": "bg/status/warning/subtle",
        "onToken": "on/bg/status/warning/subtle",
        "fill": "#ecb96c",
        "ink": "#1e2124",
        "ratio": 9.03
      },
      {
        "rung": "base",
        "bgToken": "bg/status/warning/base",
        "onToken": "on/bg/status/warning/base",
        "fill": "#fef1e0",
        "ink": "#1e2124",
        "ratio": 14.54
      },
      {
        "rung": "bold",
        "bgToken": "bg/status/warning/bold",
        "onToken": "on/bg/status/warning/bold",
        "fill": "#e09c1d",
        "ink": "#1e2124",
        "ratio": 6.89
      },
      {
        "rung": "bolder",
        "bgToken": "bg/status/warning/bolder",
        "onToken": "on/bg/status/warning/bolder",
        "fill": "#8b5e00",
        "ink": "#ffffff",
        "ratio": 5.68
      },
      {
        "rung": "boldest",
        "bgToken": "bg/status/warning/boldest",
        "onToken": "on/bg/status/warning/boldest",
        "fill": "#563900",
        "ink": "#ffffff",
        "ratio": 10.6
      }
    ]
  },
  {
    "family": "status-info",
    "label": "status / info",
    "rungs": [
      {
        "rung": "subtler",
        "bgToken": "bg/status/info/subtler",
        "onToken": "on/bg/status/info/subtler",
        "fill": "#c3dcff",
        "ink": "#1e2124",
        "ratio": 11.56
      },
      {
        "rung": "subtle",
        "bgToken": "bg/status/info/subtle",
        "onToken": "on/bg/status/info/subtle",
        "fill": "#99c3ff",
        "ink": "#1e2124",
        "ratio": 8.94
      },
      {
        "rung": "base",
        "bgToken": "bg/status/info/base",
        "onToken": "on/bg/status/info/base",
        "fill": "#edf4ff",
        "ink": "#1e2124",
        "ratio": 14.62
      },
      {
        "rung": "bold",
        "bgToken": "bg/status/info/bold",
        "onToken": "on/bg/status/info/bold",
        "fill": "#72a9fa",
        "ink": "#1e2124",
        "ratio": 6.76
      },
      {
        "rung": "bolder",
        "bgToken": "bg/status/info/bolder",
        "onToken": "on/bg/status/info/bolder",
        "fill": "#0a5cc3",
        "ink": "#ffffff",
        "ratio": 6.3
      },
      {
        "rung": "boldest",
        "bgToken": "bg/status/info/boldest",
        "onToken": "on/bg/status/info/boldest",
        "fill": "#003376",
        "ink": "#ffffff",
        "ratio": 12.1
      }
    ]
  }
];

export const RUNG_LEDGER: readonly LedgerEntry[] = [
  {
    "token": "bg/brand/accent/subtle",
    "measured": 2.18,
    "implied": 3,
    "rung": "subtle"
  },
  {
    "token": "bg/brand/primary/bold",
    "measured": 2.46,
    "implied": 3,
    "rung": "bold"
  },
  {
    "token": "bg/brand/primary/subtle",
    "measured": 1.84,
    "implied": 3,
    "rung": "subtle"
  },
  {
    "token": "bg/brand/secondary/bold",
    "measured": 2.21,
    "implied": 3,
    "rung": "bold"
  },
  {
    "token": "bg/brand/secondary/subtle",
    "measured": 1.72,
    "implied": 3,
    "rung": "subtle"
  },
  {
    "token": "bg/neutral/bold",
    "measured": 1.66,
    "implied": 3,
    "rung": "bold"
  },
  {
    "token": "bg/neutral/subtle",
    "measured": 1.35,
    "implied": 3,
    "rung": "subtle"
  },
  {
    "token": "bg/status/error/bold",
    "measured": 2.67,
    "implied": 3,
    "rung": "bold"
  },
  {
    "token": "bg/status/error/subtle",
    "measured": 2.01,
    "implied": 3,
    "rung": "subtle"
  },
  {
    "token": "bg/status/info/bold",
    "measured": 2.39,
    "implied": 3,
    "rung": "bold"
  },
  {
    "token": "bg/status/info/subtle",
    "measured": 1.81,
    "implied": 3,
    "rung": "subtle"
  },
  {
    "token": "bg/status/success/subtle",
    "measured": 2.18,
    "implied": 3,
    "rung": "subtle"
  },
  {
    "token": "bg/status/warning/bold",
    "measured": 2.35,
    "implied": 3,
    "rung": "bold"
  },
  {
    "token": "bg/status/warning/subtle",
    "measured": 1.79,
    "implied": 3,
    "rung": "subtle"
  },
  {
    "token": "border/neutral/bolder/default",
    "measured": 3.06,
    "implied": 4.5,
    "rung": "bolder"
  },
  {
    "token": "border/neutral/subtle",
    "measured": 1.35,
    "implied": 3,
    "rung": "subtle"
  }
];

export const CHART = {
  "categorical": [
    {
      "n": 1,
      "token": "chart/cat/1",
      "value": "#0373df",
      "onPage": 4.64
    },
    {
      "n": 2,
      "token": "chart/cat/2",
      "value": "#a25a00",
      "onPage": 5.25
    },
    {
      "n": 3,
      "token": "chart/cat/3",
      "value": "#007668",
      "onPage": 5.54
    },
    {
      "n": 4,
      "token": "chart/cat/4",
      "value": "#930121",
      "onPage": 9.26
    },
    {
      "n": 5,
      "token": "chart/cat/5",
      "value": "#b671a6",
      "onPage": 3.56
    },
    {
      "n": 6,
      "token": "chart/cat/6",
      "value": "#323ca8",
      "onPage": 8.95
    },
    {
      "n": 7,
      "token": "chart/cat/7",
      "value": "#719348",
      "onPage": 3.52
    },
    {
      "n": 8,
      "token": "chart/cat/8",
      "value": "#7261a8",
      "onPage": 5.26
    },
    {
      "n": 9,
      "token": "chart/cat/9",
      "value": "#5a406e",
      "onPage": 8.77
    },
    {
      "n": 10,
      "token": "chart/cat/10",
      "value": "#594d00",
      "onPage": 8.45
    },
    {
      "n": 11,
      "token": "chart/cat/11",
      "value": "#c02865",
      "onPage": 5.63
    },
    {
      "n": 12,
      "token": "chart/cat/12",
      "value": "#4c90ac",
      "onPage": 3.56
    }
  ],
  "sequential": [
    {
      "step": 50,
      "token": "chart/seq/50",
      "value": "#e8f2fd"
    },
    {
      "step": 100,
      "token": "chart/seq/100",
      "value": "#c6dcf9"
    },
    {
      "step": 200,
      "token": "chart/seq/200",
      "value": "#94bff5"
    },
    {
      "step": 300,
      "token": "chart/seq/300",
      "value": "#5fa0ef"
    },
    {
      "step": 400,
      "token": "chart/seq/400",
      "value": "#2d84e8"
    },
    {
      "step": 500,
      "token": "chart/seq/500",
      "value": "#0373df"
    },
    {
      "step": 600,
      "token": "chart/seq/600",
      "value": "#025fb8"
    },
    {
      "step": 700,
      "token": "chart/seq/700",
      "value": "#014b92"
    },
    {
      "step": 800,
      "token": "chart/seq/800",
      "value": "#01376b"
    },
    {
      "step": 900,
      "token": "chart/seq/900",
      "value": "#002448"
    }
  ],
  "diverging": [
    {
      "key": "negStrong",
      "token": "chart/div/negStrong",
      "value": "#6c100c"
    },
    {
      "key": "neg",
      "token": "chart/div/neg",
      "value": "#ec5042"
    },
    {
      "key": "negSoft",
      "token": "chart/div/negSoft",
      "value": "#ffc2b8"
    },
    {
      "key": "mid",
      "token": "chart/div/mid",
      "value": "#dcdee1"
    },
    {
      "key": "posSoft",
      "token": "chart/div/posSoft",
      "value": "#bed8c5"
    },
    {
      "key": "pos",
      "token": "chart/div/pos",
      "value": "#659c77"
    },
    {
      "key": "posStrong",
      "token": "chart/div/posStrong",
      "value": "#004220"
    }
  ],
  "trend": [
    {
      "key": "up",
      "token": "chart/trend/up",
      "value": "#046a38"
    },
    {
      "key": "down",
      "token": "chart/trend/down",
      "value": "#cb3f33"
    },
    {
      "key": "flat",
      "token": "chart/trend/flat",
      "value": "#6f757d"
    }
  ],
  "structural": [
    {
      "key": "grid",
      "token": "chart/grid",
      "value": "#dcdee1"
    },
    {
      "key": "axis",
      "token": "chart/axis",
      "value": "#6f757d"
    },
    {
      "key": "tooltipBg",
      "token": "chart/tooltipBg",
      "value": "#1e2124"
    },
    {
      "key": "tooltipInk",
      "token": "chart/tooltipInk",
      "value": "#ffffff"
    },
    {
      "key": "regionEmpty",
      "token": "chart/regionEmpty",
      "value": "#dcdee1"
    },
    {
      "key": "regionStroke",
      "token": "chart/regionStroke",
      "value": "#ffffff"
    }
  ]
} as const;

export const ALPHA = [
  {
    "family": "neutral",
    "steps": [
      {
        "step": 8,
        "token": "color/transparent/neutral/8",
        "value": "rgba(30, 33, 36, 0.08)"
      },
      {
        "step": 16,
        "token": "color/transparent/neutral/16",
        "value": "rgba(30, 33, 36, 0.16)"
      },
      {
        "step": 24,
        "token": "color/transparent/neutral/24",
        "value": "rgba(30, 33, 36, 0.24)"
      },
      {
        "step": 32,
        "token": "color/transparent/neutral/32",
        "value": "rgba(30, 33, 36, 0.32)"
      },
      {
        "step": 40,
        "token": "color/transparent/neutral/40",
        "value": "rgba(30, 33, 36, 0.4)"
      },
      {
        "step": 48,
        "token": "color/transparent/neutral/48",
        "value": "rgba(30, 33, 36, 0.48)"
      }
    ]
  },
  {
    "family": "primary",
    "steps": [
      {
        "step": 8,
        "token": "color/transparent/primary/8",
        "value": "rgba(3, 115, 223, 0.08)"
      },
      {
        "step": 16,
        "token": "color/transparent/primary/16",
        "value": "rgba(3, 115, 223, 0.16)"
      },
      {
        "step": 24,
        "token": "color/transparent/primary/24",
        "value": "rgba(3, 115, 223, 0.24)"
      },
      {
        "step": 32,
        "token": "color/transparent/primary/32",
        "value": "rgba(3, 115, 223, 0.32)"
      },
      {
        "step": 40,
        "token": "color/transparent/primary/40",
        "value": "rgba(3, 115, 223, 0.4)"
      },
      {
        "step": 48,
        "token": "color/transparent/primary/48",
        "value": "rgba(3, 115, 223, 0.48)"
      }
    ]
  },
  {
    "family": "secondary",
    "steps": [
      {
        "step": 8,
        "token": "color/transparent/secondary/8",
        "value": "rgba(255, 103, 31, 0.08)"
      },
      {
        "step": 16,
        "token": "color/transparent/secondary/16",
        "value": "rgba(255, 103, 31, 0.16)"
      },
      {
        "step": 24,
        "token": "color/transparent/secondary/24",
        "value": "rgba(255, 103, 31, 0.24)"
      },
      {
        "step": 32,
        "token": "color/transparent/secondary/32",
        "value": "rgba(255, 103, 31, 0.32)"
      },
      {
        "step": 40,
        "token": "color/transparent/secondary/40",
        "value": "rgba(255, 103, 31, 0.4)"
      },
      {
        "step": 48,
        "token": "color/transparent/secondary/48",
        "value": "rgba(255, 103, 31, 0.48)"
      }
    ]
  },
  {
    "family": "accent",
    "steps": [
      {
        "step": 8,
        "token": "color/transparent/accent/8",
        "value": "rgba(4, 106, 56, 0.08)"
      },
      {
        "step": 16,
        "token": "color/transparent/accent/16",
        "value": "rgba(4, 106, 56, 0.16)"
      },
      {
        "step": 24,
        "token": "color/transparent/accent/24",
        "value": "rgba(4, 106, 56, 0.24)"
      },
      {
        "step": 32,
        "token": "color/transparent/accent/32",
        "value": "rgba(4, 106, 56, 0.32)"
      },
      {
        "step": 40,
        "token": "color/transparent/accent/40",
        "value": "rgba(4, 106, 56, 0.4)"
      },
      {
        "step": 48,
        "token": "color/transparent/accent/48",
        "value": "rgba(4, 106, 56, 0.48)"
      }
    ]
  },
  {
    "family": "success",
    "steps": [
      {
        "step": 8,
        "token": "color/transparent/success/8",
        "value": "rgba(4, 106, 56, 0.08)"
      },
      {
        "step": 16,
        "token": "color/transparent/success/16",
        "value": "rgba(4, 106, 56, 0.16)"
      },
      {
        "step": 24,
        "token": "color/transparent/success/24",
        "value": "rgba(4, 106, 56, 0.24)"
      },
      {
        "step": 32,
        "token": "color/transparent/success/32",
        "value": "rgba(4, 106, 56, 0.32)"
      },
      {
        "step": 40,
        "token": "color/transparent/success/40",
        "value": "rgba(4, 106, 56, 0.4)"
      },
      {
        "step": 48,
        "token": "color/transparent/success/48",
        "value": "rgba(4, 106, 56, 0.48)"
      }
    ]
  },
  {
    "family": "danger",
    "steps": [
      {
        "step": 8,
        "token": "color/transparent/danger/8",
        "value": "rgba(203, 63, 51, 0.08)"
      },
      {
        "step": 16,
        "token": "color/transparent/danger/16",
        "value": "rgba(203, 63, 51, 0.16)"
      },
      {
        "step": 24,
        "token": "color/transparent/danger/24",
        "value": "rgba(203, 63, 51, 0.24)"
      },
      {
        "step": 32,
        "token": "color/transparent/danger/32",
        "value": "rgba(203, 63, 51, 0.32)"
      },
      {
        "step": 40,
        "token": "color/transparent/danger/40",
        "value": "rgba(203, 63, 51, 0.4)"
      },
      {
        "step": 48,
        "token": "color/transparent/danger/48",
        "value": "rgba(203, 63, 51, 0.48)"
      }
    ]
  },
  {
    "family": "warning",
    "steps": [
      {
        "step": 8,
        "token": "color/transparent/warning/8",
        "value": "rgba(167, 114, 0, 0.08)"
      },
      {
        "step": 16,
        "token": "color/transparent/warning/16",
        "value": "rgba(167, 114, 0, 0.16)"
      },
      {
        "step": 24,
        "token": "color/transparent/warning/24",
        "value": "rgba(167, 114, 0, 0.24)"
      },
      {
        "step": 32,
        "token": "color/transparent/warning/32",
        "value": "rgba(167, 114, 0, 0.32)"
      },
      {
        "step": 40,
        "token": "color/transparent/warning/40",
        "value": "rgba(167, 114, 0, 0.4)"
      },
      {
        "step": 48,
        "token": "color/transparent/warning/48",
        "value": "rgba(167, 114, 0, 0.48)"
      }
    ]
  },
  {
    "family": "white",
    "steps": [
      {
        "step": 8,
        "token": "color/transparent/white/8",
        "value": "rgba(255, 255, 255, 0.08)"
      },
      {
        "step": 16,
        "token": "color/transparent/white/16",
        "value": "rgba(255, 255, 255, 0.16)"
      },
      {
        "step": 24,
        "token": "color/transparent/white/24",
        "value": "rgba(255, 255, 255, 0.24)"
      },
      {
        "step": 32,
        "token": "color/transparent/white/32",
        "value": "rgba(255, 255, 255, 0.32)"
      },
      {
        "step": 40,
        "token": "color/transparent/white/40",
        "value": "rgba(255, 255, 255, 0.4)"
      },
      {
        "step": 48,
        "token": "color/transparent/white/48",
        "value": "rgba(255, 255, 255, 0.48)"
      }
    ]
  }
] as const;

export const LAYERS = [
  {
    "depth": 0,
    "surface": "#ffffff",
    "border": "#dcdee1"
  },
  {
    "depth": 1,
    "surface": "#eef0f3",
    "border": "#dcdee1"
  },
  {
    "depth": 2,
    "surface": "#dcdee1",
    "border": "#c6c9cd"
  },
  {
    "depth": 3,
    "surface": "#c6c9cd",
    "border": "#c6c9cd"
  }
] as const;

export const SLOT_COUNTS = {
  "border": 16,
  "bg": 48,
  "text": 22,
  "icon": 15,
  "cmp": 298,
  "focus": 1,
  "overlay": 3,
  "chart": 38,
  "layer": 8,
  "on": 46
} as const;

export const RETIRED = [
  {
    "from": "--ds-yellow",
    "to": "--sa-color-brand-yellow",
    "value": "#ffd323",
    "onWhite": 1.44,
    "note": "Retired 2026-08-12. Measured 1.44:1 — never text at any size. For yellow emphasis use bg/status/warning/subtler behind dark ink."
  },
  {
    "from": "--ds-saffron",
    "to": "--sa-color-brand-saffron",
    "value": "#ff671f",
    "onWhite": 2.91,
    "note": "Retired. 2.91:1 — below even the 3:1 that WCAG 1.4.11 asks of non-text. Decorative fills only."
  },
  {
    "from": "--ds-neutral-1000",
    "to": "--sa-color-neutralScale-950",
    "value": "#030406",
    "onWhite": 20.51,
    "note": "Retired, and it was off by one rung: it held neutralScale/950 while --ds-neutral-1100 held the real 1000."
  },
  {
    "from": "--ds-danger",
    "to": "--sa-color-status-danger",
    "value": "#8b1f18",
    "onWhite": 9.1,
    "note": "Retired. It was dangerScale/700, not the 500 its bare name suggested."
  },
  {
    "from": "--ds-border",
    "to": "--sa-border-neutral-subtle",
    "value": "#dcdee1",
    "onWhite": 1.35,
    "note": "Retired. A hairline divider at 1.35:1, not a control boundary."
  },
  {
    "from": "--ds-text-title-1",
    "to": "--sa-type-headline-2-size",
    "value": "clamp(1.5rem, calc(1.3043rem + 0.87vw), 2rem)",
    "onWhite": null,
    "note": "Retired. It resolved to the HEADLINE-2 role, not Title 1 — the alias trap behind four production bugs."
  }
] as const;
