/**
 * GENERATED by tools/e-anudaan-samples/generate.mjs — do not edit. 145 files, 850 KB.
 *
 * Every sample document in /e-anudaan/sample-documents/: the document type it is (`stem`, read by
 * `topicsOfFile`), and the check it is built to trip (`check`, read by `checkIdOfFile`).
 */

export interface SampleFile {
  file: string;
  stem: string;
  title: string;
  check: string;
  kb: number;
}

export const SAMPLE_FILES: readonly SampleFile[] = [
  {
    "file": "agreement-bond--blank-template.pdf",
    "stem": "agreement-bond",
    "title": "Agreement Bond (on Non-Judicial Stamp Paper of ₹100)",
    "check": "blank-template",
    "kb": 3
  },
  {
    "file": "agreement-bond--illegible.pdf",
    "stem": "agreement-bond",
    "title": "Agreement Bond (on Non-Judicial Stamp Paper of ₹100)",
    "check": "illegible",
    "kb": 17
  },
  {
    "file": "agreement-bond--not-notarised.pdf",
    "stem": "agreement-bond",
    "title": "Agreement Bond (on Non-Judicial Stamp Paper of ₹100)",
    "check": "not-notarised",
    "kb": 3
  },
  {
    "file": "agreement-bond--other-organisation.pdf",
    "stem": "agreement-bond",
    "title": "Agreement Bond (on Non-Judicial Stamp Paper of ₹100)",
    "check": "other-organisation",
    "kb": 3
  },
  {
    "file": "agreement-bond--unsigned.pdf",
    "stem": "agreement-bond",
    "title": "Agreement Bond (on Non-Judicial Stamp Paper of ₹100)",
    "check": "unsigned",
    "kb": 3
  },
  {
    "file": "agreement-bond--valid.pdf",
    "stem": "agreement-bond",
    "title": "Agreement Bond (on Non-Judicial Stamp Paper of ₹100)",
    "check": "valid",
    "kb": 3
  },
  {
    "file": "annual-report--illegible.pdf",
    "stem": "annual-report",
    "title": "Annual Report 2025-26",
    "check": "illegible",
    "kb": 17
  },
  {
    "file": "annual-report--missing-particulars.pdf",
    "stem": "annual-report",
    "title": "Annual Report 2025-26",
    "check": "missing-particulars",
    "kb": 3
  },
  {
    "file": "annual-report--missing-parts.pdf",
    "stem": "annual-report",
    "title": "Annual Report 2025-26",
    "check": "missing-parts",
    "kb": 3
  },
  {
    "file": "annual-report--other-organisation.pdf",
    "stem": "annual-report",
    "title": "Annual Report 2025-26",
    "check": "other-organisation",
    "kb": 3
  },
  {
    "file": "annual-report--unsigned.pdf",
    "stem": "annual-report",
    "title": "Annual Report 2025-26",
    "check": "unsigned",
    "kb": 3
  },
  {
    "file": "annual-report--valid.pdf",
    "stem": "annual-report",
    "title": "Annual Report 2025-26",
    "check": "valid",
    "kb": 3
  },
  {
    "file": "annual-report--wrong-year.pdf",
    "stem": "annual-report",
    "title": "Annual Report 2025-26",
    "check": "wrong-year",
    "kb": 3
  },
  {
    "file": "audited-accounts--illegible.pdf",
    "stem": "audited-accounts",
    "title": "Audited Accounts for the year ended 31 March 2026",
    "check": "illegible",
    "kb": 20
  },
  {
    "file": "audited-accounts--missing-particulars.pdf",
    "stem": "audited-accounts",
    "title": "Audited Accounts for the year ended 31 March 2026",
    "check": "missing-particulars",
    "kb": 4
  },
  {
    "file": "audited-accounts--missing-parts.pdf",
    "stem": "audited-accounts",
    "title": "Audited Accounts for the year ended 31 March 2026",
    "check": "missing-parts",
    "kb": 4
  },
  {
    "file": "audited-accounts--other-organisation.pdf",
    "stem": "audited-accounts",
    "title": "Audited Accounts for the year ended 31 March 2026",
    "check": "other-organisation",
    "kb": 4
  },
  {
    "file": "audited-accounts--unsigned.pdf",
    "stem": "audited-accounts",
    "title": "Audited Accounts for the year ended 31 March 2026",
    "check": "unsigned",
    "kb": 3
  },
  {
    "file": "audited-accounts--valid.pdf",
    "stem": "audited-accounts",
    "title": "Audited Accounts for the year ended 31 March 2026",
    "check": "valid",
    "kb": 4
  },
  {
    "file": "audited-accounts--wrong-variant.pdf",
    "stem": "audited-accounts",
    "title": "Audited Accounts for the year ended 31 March 2026",
    "check": "wrong-variant",
    "kb": 4
  },
  {
    "file": "audited-accounts--wrong-year.pdf",
    "stem": "audited-accounts",
    "title": "Audited Accounts for the year ended 31 March 2026",
    "check": "wrong-year",
    "kb": 4
  },
  {
    "file": "bank-authorisation-letter--account-name.pdf",
    "stem": "bank-authorisation-letter",
    "title": "Bank Authorisation Letter",
    "check": "account-name",
    "kb": 3
  },
  {
    "file": "bank-authorisation-letter--bank-mismatch.pdf",
    "stem": "bank-authorisation-letter",
    "title": "Bank Authorisation Letter",
    "check": "bank-mismatch",
    "kb": 3
  },
  {
    "file": "bank-authorisation-letter--illegible.pdf",
    "stem": "bank-authorisation-letter",
    "title": "Bank Authorisation Letter",
    "check": "illegible",
    "kb": 15
  },
  {
    "file": "bank-authorisation-letter--missing-particulars.pdf",
    "stem": "bank-authorisation-letter",
    "title": "Bank Authorisation Letter",
    "check": "missing-particulars",
    "kb": 3
  },
  {
    "file": "bank-authorisation-letter--other-organisation.pdf",
    "stem": "bank-authorisation-letter",
    "title": "Bank Authorisation Letter",
    "check": "other-organisation",
    "kb": 3
  },
  {
    "file": "bank-authorisation-letter--unsigned.pdf",
    "stem": "bank-authorisation-letter",
    "title": "Bank Authorisation Letter",
    "check": "unsigned",
    "kb": 3
  },
  {
    "file": "bank-authorisation-letter--valid.pdf",
    "stem": "bank-authorisation-letter",
    "title": "Bank Authorisation Letter",
    "check": "valid",
    "kb": 3
  },
  {
    "file": "beneficiary-list--blank-template.pdf",
    "stem": "beneficiary-list",
    "title": "List of Beneficiaries 2025-26",
    "check": "blank-template",
    "kb": 3
  },
  {
    "file": "beneficiary-list--illegible.pdf",
    "stem": "beneficiary-list",
    "title": "List of Beneficiaries 2025-26",
    "check": "illegible",
    "kb": 16
  },
  {
    "file": "beneficiary-list--incomplete-table.pdf",
    "stem": "beneficiary-list",
    "title": "List of Beneficiaries 2025-26",
    "check": "incomplete-table",
    "kb": 3
  },
  {
    "file": "beneficiary-list--other-organisation.pdf",
    "stem": "beneficiary-list",
    "title": "List of Beneficiaries 2025-26",
    "check": "other-organisation",
    "kb": 4
  },
  {
    "file": "beneficiary-list--unsigned.pdf",
    "stem": "beneficiary-list",
    "title": "List of Beneficiaries 2025-26",
    "check": "unsigned",
    "kb": 3
  },
  {
    "file": "beneficiary-list--valid.pdf",
    "stem": "beneficiary-list",
    "title": "List of Beneficiaries 2025-26",
    "check": "valid",
    "kb": 4
  },
  {
    "file": "beneficiary-list--wrong-year.pdf",
    "stem": "beneficiary-list",
    "title": "List of Beneficiaries 2025-26",
    "check": "wrong-year",
    "kb": 4
  },
  {
    "file": "budget-estimate--blank-template.pdf",
    "stem": "budget-estimate",
    "title": "Budget Estimate 2026-27",
    "check": "blank-template",
    "kb": 3
  },
  {
    "file": "budget-estimate--illegible.pdf",
    "stem": "budget-estimate",
    "title": "Budget Estimate 2026-27",
    "check": "illegible",
    "kb": 17
  },
  {
    "file": "budget-estimate--missing-particulars.pdf",
    "stem": "budget-estimate",
    "title": "Budget Estimate 2026-27",
    "check": "missing-particulars",
    "kb": 4
  },
  {
    "file": "budget-estimate--other-organisation.pdf",
    "stem": "budget-estimate",
    "title": "Budget Estimate 2026-27",
    "check": "other-organisation",
    "kb": 4
  },
  {
    "file": "budget-estimate--unsigned.pdf",
    "stem": "budget-estimate",
    "title": "Budget Estimate 2026-27",
    "check": "unsigned",
    "kb": 3
  },
  {
    "file": "budget-estimate--valid.pdf",
    "stem": "budget-estimate",
    "title": "Budget Estimate 2026-27",
    "check": "valid",
    "kb": 4
  },
  {
    "file": "budget-estimate--wrong-year.pdf",
    "stem": "budget-estimate",
    "title": "Budget Estimate 2026-27",
    "check": "wrong-year",
    "kb": 4
  },
  {
    "file": "committee-members--blank-template.pdf",
    "stem": "committee-members",
    "title": "List of Managing Committee Members",
    "check": "blank-template",
    "kb": 3
  },
  {
    "file": "committee-members--illegible.pdf",
    "stem": "committee-members",
    "title": "List of Managing Committee Members",
    "check": "illegible",
    "kb": 17
  },
  {
    "file": "committee-members--incomplete-table.pdf",
    "stem": "committee-members",
    "title": "List of Managing Committee Members",
    "check": "incomplete-table",
    "kb": 4
  },
  {
    "file": "committee-members--other-organisation.pdf",
    "stem": "committee-members",
    "title": "List of Managing Committee Members",
    "check": "other-organisation",
    "kb": 4
  },
  {
    "file": "committee-members--unsigned.pdf",
    "stem": "committee-members",
    "title": "List of Managing Committee Members",
    "check": "unsigned",
    "kb": 3
  },
  {
    "file": "committee-members--valid.pdf",
    "stem": "committee-members",
    "title": "List of Managing Committee Members",
    "check": "valid",
    "kb": 4
  },
  {
    "file": "compliance-status--illegible.pdf",
    "stem": "compliance-status",
    "title": "Compliance Status — Proactive Disclosures and CCTV Installation",
    "check": "illegible",
    "kb": 16
  },
  {
    "file": "compliance-status--other-organisation.pdf",
    "stem": "compliance-status",
    "title": "Compliance Status — Proactive Disclosures and CCTV Installation",
    "check": "other-organisation",
    "kb": 3
  },
  {
    "file": "compliance-status--unsigned.pdf",
    "stem": "compliance-status",
    "title": "Compliance Status — Proactive Disclosures and CCTV Installation",
    "check": "unsigned",
    "kb": 3
  },
  {
    "file": "compliance-status--valid.pdf",
    "stem": "compliance-status",
    "title": "Compliance Status — Proactive Disclosures and CCTV Installation",
    "check": "valid",
    "kb": 3
  },
  {
    "file": "eat-module-status--illegible.pdf",
    "stem": "eat-module-status",
    "title": "Expenditure, Advance and Transfer (EAT) Module — Implementation Status",
    "check": "illegible",
    "kb": 16
  },
  {
    "file": "eat-module-status--missing-particulars.pdf",
    "stem": "eat-module-status",
    "title": "Expenditure, Advance and Transfer (EAT) Module — Implementation Status",
    "check": "missing-particulars",
    "kb": 3
  },
  {
    "file": "eat-module-status--other-organisation.pdf",
    "stem": "eat-module-status",
    "title": "Expenditure, Advance and Transfer (EAT) Module — Implementation Status",
    "check": "other-organisation",
    "kb": 3
  },
  {
    "file": "eat-module-status--unsigned.pdf",
    "stem": "eat-module-status",
    "title": "Expenditure, Advance and Transfer (EAT) Module — Implementation Status",
    "check": "unsigned",
    "kb": 3
  },
  {
    "file": "eat-module-status--valid.pdf",
    "stem": "eat-module-status",
    "title": "Expenditure, Advance and Transfer (EAT) Module — Implementation Status",
    "check": "valid",
    "kb": 3
  },
  {
    "file": "eat-module-status--wrong-year.pdf",
    "stem": "eat-module-status",
    "title": "Expenditure, Advance and Transfer (EAT) Module — Implementation Status",
    "check": "wrong-year",
    "kb": 3
  },
  {
    "file": "fire-safety-report--address-mismatch.pdf",
    "stem": "fire-safety-report",
    "title": "Fire Safety Audit Report",
    "check": "address-mismatch",
    "kb": 3
  },
  {
    "file": "fire-safety-report--illegible.pdf",
    "stem": "fire-safety-report",
    "title": "Fire Safety Audit Report",
    "check": "illegible",
    "kb": 15
  },
  {
    "file": "fire-safety-report--other-organisation.pdf",
    "stem": "fire-safety-report",
    "title": "Fire Safety Audit Report",
    "check": "other-organisation",
    "kb": 3
  },
  {
    "file": "fire-safety-report--unsigned.pdf",
    "stem": "fire-safety-report",
    "title": "Fire Safety Audit Report",
    "check": "unsigned",
    "kb": 3
  },
  {
    "file": "fire-safety-report--valid.pdf",
    "stem": "fire-safety-report",
    "title": "Fire Safety Audit Report",
    "check": "valid",
    "kb": 3
  },
  {
    "file": "fire-safety-report--validity-lapsed.pdf",
    "stem": "fire-safety-report",
    "title": "Fire Safety Audit Report",
    "check": "validity-lapsed",
    "kb": 3
  },
  {
    "file": "income-expenditure--illegible.pdf",
    "stem": "income-expenditure",
    "title": "Details of Income and Expenditure 2025-26",
    "check": "illegible",
    "kb": 19
  },
  {
    "file": "income-expenditure--missing-parts.pdf",
    "stem": "income-expenditure",
    "title": "Details of Income and Expenditure 2025-26",
    "check": "missing-parts",
    "kb": 4
  },
  {
    "file": "income-expenditure--other-organisation.pdf",
    "stem": "income-expenditure",
    "title": "Details of Income and Expenditure 2025-26",
    "check": "other-organisation",
    "kb": 4
  },
  {
    "file": "income-expenditure--unsigned.pdf",
    "stem": "income-expenditure",
    "title": "Details of Income and Expenditure 2025-26",
    "check": "unsigned",
    "kb": 3
  },
  {
    "file": "income-expenditure--valid.pdf",
    "stem": "income-expenditure",
    "title": "Details of Income and Expenditure 2025-26",
    "check": "valid",
    "kb": 4
  },
  {
    "file": "income-expenditure--wrong-year.pdf",
    "stem": "income-expenditure",
    "title": "Details of Income and Expenditure 2025-26",
    "check": "wrong-year",
    "kb": 4
  },
  {
    "file": "infrastructure-details--address-mismatch.pdf",
    "stem": "infrastructure-details",
    "title": "Infrastructure Details",
    "check": "address-mismatch",
    "kb": 3
  },
  {
    "file": "infrastructure-details--illegible.pdf",
    "stem": "infrastructure-details",
    "title": "Infrastructure Details",
    "check": "illegible",
    "kb": 16
  },
  {
    "file": "infrastructure-details--other-organisation.pdf",
    "stem": "infrastructure-details",
    "title": "Infrastructure Details",
    "check": "other-organisation",
    "kb": 3
  },
  {
    "file": "infrastructure-details--unsigned.pdf",
    "stem": "infrastructure-details",
    "title": "Infrastructure Details",
    "check": "unsigned",
    "kb": 3
  },
  {
    "file": "infrastructure-details--valid.pdf",
    "stem": "infrastructure-details",
    "title": "Infrastructure Details",
    "check": "valid",
    "kb": 3
  },
  {
    "file": "justification-note--illegible.pdf",
    "stem": "justification-note",
    "title": "Justification for Continuation of Ongoing Institution",
    "check": "illegible",
    "kb": 15
  },
  {
    "file": "justification-note--missing-parts.pdf",
    "stem": "justification-note",
    "title": "Justification for Continuation of Ongoing Institution",
    "check": "missing-parts",
    "kb": 3
  },
  {
    "file": "justification-note--other-organisation.pdf",
    "stem": "justification-note",
    "title": "Justification for Continuation of Ongoing Institution",
    "check": "other-organisation",
    "kb": 3
  },
  {
    "file": "justification-note--unsigned.pdf",
    "stem": "justification-note",
    "title": "Justification for Continuation of Ongoing Institution",
    "check": "unsigned",
    "kb": 3
  },
  {
    "file": "justification-note--valid.pdf",
    "stem": "justification-note",
    "title": "Justification for Continuation of Ongoing Institution",
    "check": "valid",
    "kb": 3
  },
  {
    "file": "memorandum-of-association--illegible.pdf",
    "stem": "memorandum-of-association",
    "title": "Memorandum of Association and Rules",
    "check": "illegible",
    "kb": 17
  },
  {
    "file": "memorandum-of-association--missing-parts.pdf",
    "stem": "memorandum-of-association",
    "title": "Memorandum of Association and Rules",
    "check": "missing-parts",
    "kb": 3
  },
  {
    "file": "memorandum-of-association--other-organisation.pdf",
    "stem": "memorandum-of-association",
    "title": "Memorandum of Association and Rules",
    "check": "other-organisation",
    "kb": 3
  },
  {
    "file": "memorandum-of-association--unsigned.pdf",
    "stem": "memorandum-of-association",
    "title": "Memorandum of Association and Rules",
    "check": "unsigned",
    "kb": 3
  },
  {
    "file": "memorandum-of-association--valid.pdf",
    "stem": "memorandum-of-association",
    "title": "Memorandum of Association and Rules",
    "check": "valid",
    "kb": 3
  },
  {
    "file": "pan-card--illegible.pdf",
    "stem": "pan-card",
    "title": "Permanent Account Number Card",
    "check": "illegible",
    "kb": 13
  },
  {
    "file": "pan-card--missing-particulars.pdf",
    "stem": "pan-card",
    "title": "Permanent Account Number Card",
    "check": "missing-particulars",
    "kb": 3
  },
  {
    "file": "pan-card--other-organisation.pdf",
    "stem": "pan-card",
    "title": "Permanent Account Number Card",
    "check": "other-organisation",
    "kb": 3
  },
  {
    "file": "pan-card--valid.jpg",
    "stem": "pan-card",
    "title": "Permanent Account Number Card",
    "check": "valid",
    "kb": 38
  },
  {
    "file": "pan-card--valid.pdf",
    "stem": "pan-card",
    "title": "Permanent Account Number Card",
    "check": "valid",
    "kb": 3
  },
  {
    "file": "progress-report--illegible.pdf",
    "stem": "progress-report",
    "title": "Half-Yearly Progress Report (April–September 2026)",
    "check": "illegible",
    "kb": 16
  },
  {
    "file": "progress-report--missing-parts.pdf",
    "stem": "progress-report",
    "title": "Half-Yearly Progress Report (April–September 2026)",
    "check": "missing-parts",
    "kb": 3
  },
  {
    "file": "progress-report--other-organisation.pdf",
    "stem": "progress-report",
    "title": "Half-Yearly Progress Report (April–September 2026)",
    "check": "other-organisation",
    "kb": 3
  },
  {
    "file": "progress-report--unsigned.pdf",
    "stem": "progress-report",
    "title": "Half-Yearly Progress Report (April–September 2026)",
    "check": "unsigned",
    "kb": 3
  },
  {
    "file": "progress-report--valid.pdf",
    "stem": "progress-report",
    "title": "Half-Yearly Progress Report (April–September 2026)",
    "check": "valid",
    "kb": 3
  },
  {
    "file": "progress-report--wrong-year.pdf",
    "stem": "progress-report",
    "title": "Half-Yearly Progress Report (April–September 2026)",
    "check": "wrong-year",
    "kb": 3
  },
  {
    "file": "provisional-utilisation-certificate--illegible.pdf",
    "stem": "provisional-utilisation-certificate",
    "title": "Provisional Utilisation Certificate (GFR 12-A) 2026-27",
    "check": "illegible",
    "kb": 16
  },
  {
    "file": "provisional-utilisation-certificate--missing-particulars.pdf",
    "stem": "provisional-utilisation-certificate",
    "title": "Provisional Utilisation Certificate (GFR 12-A) 2026-27",
    "check": "missing-particulars",
    "kb": 3
  },
  {
    "file": "provisional-utilisation-certificate--other-organisation.pdf",
    "stem": "provisional-utilisation-certificate",
    "title": "Provisional Utilisation Certificate (GFR 12-A) 2026-27",
    "check": "other-organisation",
    "kb": 3
  },
  {
    "file": "provisional-utilisation-certificate--unsigned.pdf",
    "stem": "provisional-utilisation-certificate",
    "title": "Provisional Utilisation Certificate (GFR 12-A) 2026-27",
    "check": "unsigned",
    "kb": 3
  },
  {
    "file": "provisional-utilisation-certificate--valid.pdf",
    "stem": "provisional-utilisation-certificate",
    "title": "Provisional Utilisation Certificate (GFR 12-A) 2026-27",
    "check": "valid",
    "kb": 3
  },
  {
    "file": "provisional-utilisation-certificate--wrong-variant.pdf",
    "stem": "provisional-utilisation-certificate",
    "title": "Provisional Utilisation Certificate (GFR 12-A) 2026-27",
    "check": "wrong-variant",
    "kb": 3
  },
  {
    "file": "provisional-utilisation-certificate--wrong-year.pdf",
    "stem": "provisional-utilisation-certificate",
    "title": "Provisional Utilisation Certificate (GFR 12-A) 2026-27",
    "check": "wrong-year",
    "kb": 3
  },
  {
    "file": "registration-certificate--illegible.pdf",
    "stem": "registration-certificate",
    "title": "Certificate of Registration",
    "check": "illegible",
    "kb": 16
  },
  {
    "file": "registration-certificate--missing-particulars.pdf",
    "stem": "registration-certificate",
    "title": "Certificate of Registration",
    "check": "missing-particulars",
    "kb": 3
  },
  {
    "file": "registration-certificate--other-organisation.pdf",
    "stem": "registration-certificate",
    "title": "Certificate of Registration",
    "check": "other-organisation",
    "kb": 3
  },
  {
    "file": "registration-certificate--unsigned.pdf",
    "stem": "registration-certificate",
    "title": "Certificate of Registration",
    "check": "unsigned",
    "kb": 3
  },
  {
    "file": "registration-certificate--valid.jpg",
    "stem": "registration-certificate",
    "title": "Certificate of Registration",
    "check": "valid",
    "kb": 53
  },
  {
    "file": "registration-certificate--valid.pdf",
    "stem": "registration-certificate",
    "title": "Certificate of Registration",
    "check": "valid",
    "kb": 3
  },
  {
    "file": "registration-certificate--validity-lapsed.pdf",
    "stem": "registration-certificate",
    "title": "Certificate of Registration",
    "check": "validity-lapsed",
    "kb": 3
  },
  {
    "file": "rent-agreement--address-mismatch.pdf",
    "stem": "rent-agreement",
    "title": "Leave and Licence Agreement",
    "check": "address-mismatch",
    "kb": 3
  },
  {
    "file": "rent-agreement--blank-template.pdf",
    "stem": "rent-agreement",
    "title": "Leave and Licence Agreement",
    "check": "blank-template",
    "kb": 3
  },
  {
    "file": "rent-agreement--illegible.pdf",
    "stem": "rent-agreement",
    "title": "Leave and Licence Agreement",
    "check": "illegible",
    "kb": 16
  },
  {
    "file": "rent-agreement--not-notarised.pdf",
    "stem": "rent-agreement",
    "title": "Leave and Licence Agreement",
    "check": "not-notarised",
    "kb": 3
  },
  {
    "file": "rent-agreement--other-organisation.pdf",
    "stem": "rent-agreement",
    "title": "Leave and Licence Agreement",
    "check": "other-organisation",
    "kb": 3
  },
  {
    "file": "rent-agreement--unsigned.pdf",
    "stem": "rent-agreement",
    "title": "Leave and Licence Agreement",
    "check": "unsigned",
    "kb": 3
  },
  {
    "file": "rent-agreement--valid.pdf",
    "stem": "rent-agreement",
    "title": "Leave and Licence Agreement",
    "check": "valid",
    "kb": 3
  },
  {
    "file": "rent-agreement--validity-lapsed.pdf",
    "stem": "rent-agreement",
    "title": "Leave and Licence Agreement",
    "check": "validity-lapsed",
    "kb": 3
  },
  {
    "file": "sample--file-locked.pdf",
    "stem": "sample",
    "title": "Password-protected PDF",
    "check": "file-locked",
    "kb": 4
  },
  {
    "file": "sample--file-type.docx",
    "stem": "sample",
    "title": "Word document",
    "check": "file-type",
    "kb": 1
  },
  {
    "file": "school-recognition-certificate--illegible.pdf",
    "stem": "school-recognition-certificate",
    "title": "Certificate of Recognition",
    "check": "illegible",
    "kb": 15
  },
  {
    "file": "school-recognition-certificate--missing-particulars.pdf",
    "stem": "school-recognition-certificate",
    "title": "Certificate of Recognition",
    "check": "missing-particulars",
    "kb": 3
  },
  {
    "file": "school-recognition-certificate--other-organisation.pdf",
    "stem": "school-recognition-certificate",
    "title": "Certificate of Recognition",
    "check": "other-organisation",
    "kb": 3
  },
  {
    "file": "school-recognition-certificate--unsigned.pdf",
    "stem": "school-recognition-certificate",
    "title": "Certificate of Recognition",
    "check": "unsigned",
    "kb": 3
  },
  {
    "file": "school-recognition-certificate--valid.pdf",
    "stem": "school-recognition-certificate",
    "title": "Certificate of Recognition",
    "check": "valid",
    "kb": 3
  },
  {
    "file": "school-recognition-certificate--validity-lapsed.pdf",
    "stem": "school-recognition-certificate",
    "title": "Certificate of Recognition",
    "check": "validity-lapsed",
    "kb": 3
  },
  {
    "file": "specimen--placeholder.pdf",
    "stem": "specimen",
    "title": "Specimen",
    "check": "placeholder",
    "kb": 2
  },
  {
    "file": "staff-list--blank-template.pdf",
    "stem": "staff-list",
    "title": "List of Employees",
    "check": "blank-template",
    "kb": 3
  },
  {
    "file": "staff-list--illegible.pdf",
    "stem": "staff-list",
    "title": "List of Employees",
    "check": "illegible",
    "kb": 16
  },
  {
    "file": "staff-list--incomplete-table.pdf",
    "stem": "staff-list",
    "title": "List of Employees",
    "check": "incomplete-table",
    "kb": 3
  },
  {
    "file": "staff-list--other-organisation.pdf",
    "stem": "staff-list",
    "title": "List of Employees",
    "check": "other-organisation",
    "kb": 4
  },
  {
    "file": "staff-list--unsigned.pdf",
    "stem": "staff-list",
    "title": "List of Employees",
    "check": "unsigned",
    "kb": 3
  },
  {
    "file": "staff-list--valid.pdf",
    "stem": "staff-list",
    "title": "List of Employees",
    "check": "valid",
    "kb": 4
  },
  {
    "file": "staff-monitoring-sheet--illegible.pdf",
    "stem": "staff-monitoring-sheet",
    "title": "Staff Monitoring Sheet",
    "check": "illegible",
    "kb": 15
  },
  {
    "file": "staff-monitoring-sheet--incomplete-table.pdf",
    "stem": "staff-monitoring-sheet",
    "title": "Staff Monitoring Sheet",
    "check": "incomplete-table",
    "kb": 3
  },
  {
    "file": "staff-monitoring-sheet--other-organisation.pdf",
    "stem": "staff-monitoring-sheet",
    "title": "Staff Monitoring Sheet",
    "check": "other-organisation",
    "kb": 3
  },
  {
    "file": "staff-monitoring-sheet--unsigned.pdf",
    "stem": "staff-monitoring-sheet",
    "title": "Staff Monitoring Sheet",
    "check": "unsigned",
    "kb": 3
  },
  {
    "file": "staff-monitoring-sheet--valid.pdf",
    "stem": "staff-monitoring-sheet",
    "title": "Staff Monitoring Sheet",
    "check": "valid",
    "kb": 3
  },
  {
    "file": "utilisation-certificate--illegible.pdf",
    "stem": "utilisation-certificate",
    "title": "Utilisation Certificate (GFR 12-A) 2025-26",
    "check": "illegible",
    "kb": 18
  },
  {
    "file": "utilisation-certificate--missing-particulars.pdf",
    "stem": "utilisation-certificate",
    "title": "Utilisation Certificate (GFR 12-A) 2025-26",
    "check": "missing-particulars",
    "kb": 4
  },
  {
    "file": "utilisation-certificate--other-organisation.pdf",
    "stem": "utilisation-certificate",
    "title": "Utilisation Certificate (GFR 12-A) 2025-26",
    "check": "other-organisation",
    "kb": 4
  },
  {
    "file": "utilisation-certificate--unsigned.pdf",
    "stem": "utilisation-certificate",
    "title": "Utilisation Certificate (GFR 12-A) 2025-26",
    "check": "unsigned",
    "kb": 3
  },
  {
    "file": "utilisation-certificate--valid.pdf",
    "stem": "utilisation-certificate",
    "title": "Utilisation Certificate (GFR 12-A) 2025-26",
    "check": "valid",
    "kb": 4
  },
  {
    "file": "utilisation-certificate--wrong-variant.pdf",
    "stem": "utilisation-certificate",
    "title": "Utilisation Certificate (GFR 12-A) 2025-26",
    "check": "wrong-variant",
    "kb": 4
  },
  {
    "file": "utilisation-certificate--wrong-year.pdf",
    "stem": "utilisation-certificate",
    "title": "Utilisation Certificate (GFR 12-A) 2025-26",
    "check": "wrong-year",
    "kb": 4
  }
];
