export interface SearchEntry {
  title: string;
  section: string;
  href: string;
  keywords: string;
  description: string;
  type: "foundation" | "component" | "pattern" | "resource" | "page";
  badge?: "Stable" | "Beta" | "Alpha" | "New";
  iconName: string;
}

export const SEARCH_DATA: SearchEntry[] = [
  // ── Getting Started ──
  {
    title: "What is SAMAVESH?",
    section: "Getting Started",
    href: "/design-system",
    keywords: "overview introduction welcome inclusion DoSJE ministry digital estate mission",
    description: "The shared visual and interaction language for the Ministry of Social Justice & Empowerment.",
    type: "page",
    iconName: "home",
  },
  {
    title: "For Designers",
    section: "Getting Started",
    href: "/design-system#for-designers",
    keywords: "designers figma library tokens type scale assets workflow spec",
    description: "Guidance, token models, and Figma library sync for UX and product designers.",
    type: "page",
    iconName: "palette",
  },
  {
    title: "For Developers",
    section: "Getting Started",
    href: "/design-system#for-developers",
    keywords: "developers react typescript tailwind packages npm install architecture",
    description: "Component architecture, strict typing, and token consumption for web engineers.",
    type: "page",
    iconName: "code",
  },

  // ── Foundations ──
  {
    title: "Color",
    section: "Foundations",
    href: "/design-system/foundations/color",
    keywords: "color colour palette primary brand saffron ashoka blue navy token swatch contrast dark mode AA AAA",
    description: "Semantic color tokens, brand themes, status ramps, and WCAG 2.2 AA contrast rules.",
    type: "foundation",
    badge: "Stable",
    iconName: "palette",
  },
  {
    title: "Typography",
    section: "Foundations",
    href: "/design-system/foundations/typography",
    keywords: "typography font noto sans devanagari hindi type specimen size weight headline body label display",
    description: "Bilingual type hierarchy using Noto Sans Latin and Devanagari across 14 scale steps.",
    type: "foundation",
    badge: "Stable",
    iconName: "text_fields",
  },
  {
    title: "Spacing",
    section: "Foundations",
    href: "/design-system/foundations/spacing",
    keywords: "spacing space gap margin padding scale 4px 8px 12px 16px 24px 32px 48px stack inline",
    description: "Spatial rhythm scale based on 4px increments for layouts, gutters, and component padding.",
    type: "foundation",
    badge: "Stable",
    iconName: "space_bar",
  },
  {
    title: "Shape & Corner Radius",
    section: "Foundations",
    href: "/design-system/foundations/shape",
    keywords: "shape radius corner border-radius pill full circle 2px 4px 6px 8px 12px 16px rounded",
    description: "Systematic border-radius tokens binding UI geometry to semantic surface roles.",
    type: "foundation",
    badge: "Stable",
    iconName: "rounded_corner",
  },
  {
    title: "Elevation & Shadows",
    section: "Foundations",
    href: "/design-system/foundations/elevation",
    keywords: "elevation shadow drop shadow layer depth surface z-index toast modal card float",
    description: "Surface depth hierarchy and ambient lighting model from flat base to floating sheets.",
    type: "foundation",
    badge: "Stable",
    iconName: "layers",
  },
  {
    title: "Layout Grid",
    section: "Foundations",
    href: "/design-system/foundations/layout-grid",
    keywords: "layout grid columns container breakpoints responsive 12-column mobile tablet desktop 1280px max-width",
    description: "Responsive 12-column grid and standard container boundaries across 4 breakpoint tiers.",
    type: "foundation",
    badge: "New",
    iconName: "grid_view",
  },
  {
    title: "Motion",
    section: "Foundations",
    href: "/design-system/foundations/motion",
    keywords: "motion animation transition duration easing cubic-bezier timing reduced-motion micro-interaction",
    description: "Predictable animation curves, timing tokens, and prefers-reduced-motion safety.",
    type: "foundation",
    badge: "Beta",
    iconName: "animation",
  },
  {
    title: "Density",
    section: "Foundations",
    href: "/design-system/foundations/density",
    keywords: "density compact comfortable dense data entry tables forms touch target 44px 48px height",
    description: "Comfortable and compact density modes adapting for touch vs data-heavy portal views.",
    type: "foundation",
    badge: "Stable",
    iconName: "density_medium",
  },
  {
    title: "Iconography",
    section: "Foundations",
    href: "/design-system/foundations/iconography",
    keywords: "iconography icon material symbols rounded svg emblems glyph size optical weight 300",
    description: "Material Symbols Rounded variable font guidelines with standard weight 300.",
    type: "foundation",
    badge: "Beta",
    iconName: "interests",
  },
  {
    title: "Accessibility",
    section: "Foundations",
    href: "/design-system/foundations/accessibility",
    keywords: "accessibility a11y wcag 2.2 gigw aria keyboard navigation contrast screen reader focus visible target size",
    description: "Government GIGW 3.0 & WCAG 2.2 AA non-negotiable compliance requirements.",
    type: "foundation",
    badge: "Stable",
    iconName: "accessibility_new",
  },

  // ── Actions ──
  {
    title: "Button",
    section: "Actions",
    href: "/design-system/components/actions/button",
    keywords: "button cta action primary secondary outlined text tonal inverse filled icon loading trigger submit",
    description: "Primary and secondary interactive action triggers with icon and loading state support.",
    type: "component",
    iconName: "smart_button",
  },

  // ── Forms & Inputs ──
  {
    title: "Aadhaar Input",
    section: "Forms & Inputs",
    href: "/design-system/components/forms/aadhaar-input",
    keywords: "aadhaar uidai identity 12 digit verhoeff checksum mask dpdp masked number verification",
    description: "Gov-compliant 12-digit Aadhaar input with Verhoeff validation and DPDP masking.",
    type: "component",
    iconName: "badge",
  },
  {
    title: "Captcha Field",
    section: "Forms & Inputs",
    href: "/design-system/components/forms/captcha-field",
    keywords: "captcha challenge security audio refresh bot protection verification code",
    description: "Accessible text/audio security captcha verification field with reload controls.",
    type: "component",
    iconName: "security",
  },
  {
    title: "Checkbox",
    section: "Forms & Inputs",
    href: "/design-system/components/forms/checkbox",
    keywords: "checkbox selection boolean multi-select indeterminate check tick",
    description: "Binary and multi-option selection control supporting indeterminate states.",
    type: "component",
    iconName: "check_box",
  },
  {
    title: "Chip",
    section: "Forms & Inputs",
    href: "/design-system/components/forms/chip",
    keywords: "chip tag filter removable badge selectable pill dismissible token",
    description: "Compact interactive element for filters, selections, and categorical tags.",
    type: "component",
    iconName: "label",
  },
  {
    title: "Declaration Checkbox",
    section: "Forms & Inputs",
    href: "/design-system/components/forms/declaration-checkbox",
    keywords: "declaration checkbox legal consent terms undertaking verification agree",
    description: "Formal statutory declaration checkbox for legal undertakings and scheme applications.",
    type: "component",
    iconName: "verified_user",
  },
  {
    title: "Form Card",
    section: "Forms & Inputs",
    href: "/design-system/components/forms/form-card",
    keywords: "form card container grouping panel fieldset boundary form section",
    description: "Surface card container to logically group related form sections and inputs.",
    type: "component",
    iconName: "contact_page",
  },
  {
    title: "Form Field",
    section: "Forms & Inputs",
    href: "/design-system/components/forms/form-field",
    keywords: "form field label hint error required validation control helper text message",
    description: "Accessible wrapper binding labels, helper text, and error states to any input.",
    type: "component",
    iconName: "dynamic_form",
  },
  {
    title: "Form Section",
    section: "Forms & Inputs",
    href: "/design-system/components/forms/form-section",
    keywords: "form section fieldset divider grouping title step wizard header",
    description: "Sectional header and container for dividing long multi-part portal forms.",
    type: "component",
    iconName: "folder_shared",
  },
  {
    title: "Geo Photo Input",
    section: "Forms & Inputs",
    href: "/design-system/components/forms/geo-photo-input",
    keywords: "geo photo input geolocation gps geotagged camera timestamp mobile inspection proof",
    description: "Camera capture component extracting GPS geotags and timestamps for field inspection.",
    type: "component",
    iconName: "add_a_photo",
  },
  {
    title: "Input (Text Field)",
    section: "Forms & Inputs",
    href: "/design-system/components/forms/input",
    keywords: "input text field textfield form control placeholder leading trailing icon error disabled",
    description: "Single-line text input atom with support for leading/trailing adornments and validation.",
    type: "component",
    iconName: "edit",
  },
  {
    title: "Label",
    section: "Forms & Inputs",
    href: "/design-system/components/forms/label",
    keywords: "label form label required optional asterisk caption typography",
    description: "Accessible form label atom with required/optional indicator badges.",
    type: "component",
    iconName: "text_format",
  },
  {
    title: "Media Gallery Input",
    section: "Forms & Inputs",
    href: "/design-system/components/forms/media-gallery-input",
    keywords: "media gallery input multi-upload image preview reorder delete photos evidence",
    description: "Multi-file image upload grid with thumbnail previews, reordering, and removal.",
    type: "component",
    iconName: "collections",
  },
  {
    title: "Media Upload",
    section: "Forms & Inputs",
    href: "/design-system/components/forms/media-upload",
    keywords: "media upload file upload drag and drop pdf document attachment browse",
    description: "Drag-and-drop file upload zone with file type validation and upload progress.",
    type: "component",
    iconName: "upload_file",
  },
  {
    title: "OTP Input",
    section: "Forms & Inputs",
    href: "/design-system/components/forms/otp-input",
    keywords: "otp one time password six box code sms autofill paste verification 2fa pin auth",
    description: "Segmented digit input for SMS and Aadhaar OTP verification with paste and auto-advance.",
    type: "component",
    iconName: "pin",
  },
  {
    title: "PAN Input",
    section: "Forms & Inputs",
    href: "/design-system/components/forms/pan-input",
    keywords: "pan card income tax identity permanent account number holder type regex alphanumeric",
    description: "Alphanumeric PAN input with automatic 5-char alphabetic / 4-digit formatting and regex checks.",
    type: "component",
    iconName: "credit_card",
  },
  {
    title: "Password Input",
    section: "Forms & Inputs",
    href: "/design-system/components/forms/password-input",
    keywords: "password input reveal hide toggle eye icon secret credentials login",
    description: "Secure password text input with accessible show/hide toggle.",
    type: "component",
    iconName: "lock",
  },
  {
    title: "Password Strength Meter",
    section: "Forms & Inputs",
    href: "/design-system/components/forms/password-strength-meter",
    keywords: "password strength meter score entropy requirements checklist bar indicator",
    description: "Real-time password security indicator validating character criteria and entropy score.",
    type: "component",
    iconName: "password",
  },
  {
    title: "Radio",
    section: "Forms & Inputs",
    href: "/design-system/components/forms/radio",
    keywords: "radio button option single select group radio-group choice",
    description: "Single-choice selection control for mutually exclusive option groups.",
    type: "component",
    iconName: "radio_button_checked",
  },
  {
    title: "Search Input",
    section: "Forms & Inputs",
    href: "/design-system/components/forms/search",
    keywords: "search input searchbox query clear magnifier lookup filter find",
    description: "Search text input field with leading magnifier and clear-button controls.",
    type: "component",
    iconName: "search",
  },
  {
    title: "Select (Dropdown)",
    section: "Forms & Inputs",
    href: "/design-system/components/forms/select",
    keywords: "select dropdown option picker menu listbox combo state district",
    description: "Native and custom select menus for single and multiple option selection.",
    type: "component",
    iconName: "arrow_drop_down_circle",
  },
  {
    title: "Textarea",
    section: "Forms & Inputs",
    href: "/design-system/components/forms/textarea",
    keywords: "textarea multi-line text input comment remarks description char count counter",
    description: "Multi-line text input with auto-resize and character count limitation.",
    type: "component",
    iconName: "subject",
  },
  {
    title: "Toggle Switch",
    section: "Forms & Inputs",
    href: "/design-system/components/forms/toggle",
    keywords: "toggle switch boolean enable disable on off setting state",
    description: "Interactive switch for toggling immediate boolean preferences and states.",
    type: "component",
    iconName: "toggle_on",
  },
  {
    title: "Wizard",
    section: "Forms & Inputs",
    href: "/design-system/components/forms/wizard",
    keywords: "wizard multi-step form stepper next previous steps progress scheme application",
    description: "Multi-step form wizard controller with validation gating and step preservation.",
    type: "component",
    iconName: "linear_scale",
  },

  // ── Navigation ──
  {
    title: "Account Menu",
    section: "Navigation",
    href: "/design-system/components/navigation/account-menu",
    keywords: "account menu user profile avatar logout settings portal session",
    description: "Authenticated portal account dropdown displaying user role and session actions.",
    type: "component",
    iconName: "account_circle",
  },
  {
    title: "App Switcher Panel",
    section: "Navigation",
    href: "/design-system/components/navigation/app-switcher-panel",
    keywords: "app switcher panel 9-dot grid portal apps ministries smile ajay nsfdc launcher",
    description: "Waffle-style 9-dot app launcher panel to traverse across MoSJE digital estate portals.",
    type: "component",
    iconName: "apps",
  },
  {
    title: "Brand Lockup",
    section: "Navigation",
    href: "/design-system/components/navigation/brand-lockup",
    keywords: "brand lockup national emblem logo ministry title identity DoSJE header",
    description: "Official Government of India national emblem and bilingual ministry brand lockup.",
    type: "component",
    iconName: "account_balance",
  },
  {
    title: "Footer",
    section: "Navigation",
    href: "/design-system/components/navigation/footer",
    keywords: "footer site links copyright disclaimer nic gigw emergency helpline",
    description: "Public website and portal footers with standard GIGW mandatory links.",
    type: "component",
    iconName: "dock",
  },
  {
    title: "Nav Sheet",
    section: "Navigation",
    href: "/design-system/components/navigation/nav-sheet",
    keywords: "nav sheet mobile navigation drawer overlay hamburger menu slideout",
    description: "Slide-out navigation drawer for mobile and tablet responsive layouts.",
    type: "component",
    iconName: "menu_open",
  },
  {
    title: "Sidebar",
    section: "Navigation",
    href: "/design-system/components/section-templates/sidebar",
    keywords: "sidebar portal navigation vertical menu collapsible active item nested",
    description: "Collapsible vertical navigation sidebar for admin dashboards and workflow portals.",
    type: "component",
    iconName: "view_sidebar",
  },
  {
    title: "Site Footer",
    section: "Navigation",
    href: "/design-system/components/navigation/site-footer",
    keywords: "site footer public website links sitemap terms privacy accessibility statement",
    description: "Unified public website footer with multi-tier link matrices and national portals bar.",
    type: "component",
    iconName: "pagefooter",
  },
  {
    title: "Site Header",
    section: "Navigation",
    href: "/design-system/components/section-templates/site-header",
    keywords: "site header masthead navigation topbar national emblem search searchbar",
    description: "Flagship public website masthead integrating accessibility bar, emblem, and main nav.",
    type: "component",
    iconName: "web",
  },
  {
    title: "Tabs",
    section: "Navigation",
    href: "/design-system/components/navigation/tabs",
    keywords: "tabs tablist tabpanel tabbed navigation roving tabindex wai-aria arrow keys",
    description: "WAI-ARIA accessible tabbed interface for switching between views on one page.",
    type: "component",
    iconName: "tab",
  },
  {
    title: "Tabs Overflow",
    section: "Navigation",
    href: "/design-system/components/navigation/tabs-overflow",
    keywords: "tabs overflow scrollable horizontal scroll fade gradient more dropdown",
    description: "Horizontally scrolling tab bar with edge fade masks and overflow menu support.",
    type: "component",
    iconName: "more_horiz",
  },
  {
    title: "Zone Switcher",
    section: "Navigation",
    href: "/design-system/components/navigation/zone-switcher",
    keywords: "zone switcher state district block level selector hierarchy jurisdiction",
    description: "Jurisdiction and administrative zone selector for state/district level portal operators.",
    type: "component",
    iconName: "swap_horiz",
  },

  // ── Feedback & Status ──
  {
    title: "Action Banner",
    section: "Feedback & Status",
    href: "/design-system/components/feedback/action-banner",
    keywords: "action banner announcement notice alert bar top persistent call to action",
    description: "Full-width announcement and urgent action banner for critical advisories.",
    type: "component",
    iconName: "campaign",
  },
  {
    title: "Alert",
    section: "Feedback & Status",
    href: "/design-system/components/feedback/alert",
    keywords: "alert notice callout warning error success info inline message",
    description: "Inline alert banner communicating info, success, warning, or danger system feedback.",
    type: "component",
    iconName: "info",
  },
  {
    title: "Badge",
    section: "Feedback & Status",
    href: "/design-system/components/feedback/badge",
    keywords: "badge status pill tag count indicator approved pending rejected",
    description: "Compact status and count indicator with semantic color mappings.",
    type: "component",
    iconName: "verified",
  },
  {
    title: "Chatbot (Assistive AI)",
    section: "Feedback & Status",
    href: "/design-system/components/feedback/chatbot",
    keywords: "chatbot assist ai virtual assistant samavesh saathi conversation dialog",
    description: "Floating and embedded AI assistant dialog for citizen scheme guidance.",
    type: "component",
    iconName: "chat",
  },
  {
    title: "Chatbot Mascot",
    section: "Feedback & Status",
    href: "/design-system/components/feedback/chatbot-mascot",
    keywords: "chatbot mascot saathi avatar brand mark animation floating launcher",
    description: "Official SAMAVESH Saathi mascot avatar and floating action button.",
    type: "component",
    iconName: "smart_toy",
  },
  {
    title: "Empty State",
    section: "Feedback & Status",
    href: "/design-system/components/feedback/empty-state",
    keywords: "empty state no data no results placeholder illustration zero state",
    description: "Placeholder container for empty lists, initial setup, or zero search results.",
    type: "component",
    iconName: "inbox",
  },
  {
    title: "Lightbox",
    section: "Feedback & Status",
    href: "/design-system/components/feedback/lightbox",
    keywords: "lightbox image zoom gallery preview modal full screen document inspection",
    description: "Full-screen media lightbox for inspecting uploaded document scans and photos.",
    type: "component",
    iconName: "photo_size_select_large",
  },
  {
    title: "Loader (Spinner)",
    section: "Feedback & Status",
    href: "/design-system/components/feedback/loader",
    keywords: "loader spinner progress loading indicator async waiting fetch",
    description: "Accessible circular loading spinner for pending asynchronous operations.",
    type: "component",
    iconName: "progress_activity",
  },
  {
    title: "Modal Dialog",
    section: "Feedback & Status",
    href: "/design-system/components/feedback/modal",
    keywords: "modal dialog popup overlay alertdialog confirmation backdrop trap focus",
    description: "Accessible modal dialog overlay with backdrop scrim and keyboard focus trapping.",
    type: "component",
    iconName: "open_in_new",
  },
  {
    title: "Side Sheet",
    section: "Feedback & Status",
    href: "/design-system/components/feedback/side-sheet",
    keywords: "side sheet drawer slideover panel details inspection secondary view",
    description: "Slide-over side drawer for inspecting application details without navigating away.",
    type: "component",
    iconName: "chrome_reader_mode",
  },
  {
    title: "Skeleton",
    section: "Feedback & Status",
    href: "/design-system/components/feedback/skeleton",
    keywords: "skeleton loading placeholder shimmer pulse wireframe content preview",
    description: "Content shimmer placeholder reflecting layout geometry while data loads.",
    type: "component",
    iconName: "rectangle",
  },
  {
    title: "SLA Progress Indicator",
    section: "Feedback & Status",
    href: "/design-system/components/feedback/sla-progress-indicator",
    keywords: "sla progress indicator service level agreement deadline breach overdue days timer guarantee",
    description: "Statutory SLA countdown and guarantee meter tracking citizen application timelines.",
    type: "component",
    iconName: "timer",
  },
  {
    title: "Stepper",
    section: "Feedback & Status",
    href: "/design-system/components/feedback/stepper",
    keywords: "stepper step indicator progress sequence workflow stages completed active",
    description: "Linear and branching workflow stage indicator showing completed and current steps.",
    type: "component",
    iconName: "timeline",
  },
  {
    title: "Toast",
    section: "Feedback & Status",
    href: "/design-system/components/feedback/toast",
    keywords: "toast snackbar notification toast notification auto dismiss transient alert live region",
    description: "Transient floating notification system announcing async success or status updates.",
    type: "component",
    iconName: "notifications",
  },
  {
    title: "Tooltip",
    section: "Feedback & Status",
    href: "/design-system/components/feedback/tooltip",
    keywords: "tooltip popover hover hint help icon info aria-describedby",
    description: "Accessible micro-popover providing contextual guidance on hover and keyboard focus.",
    type: "component",
    iconName: "help_outline",
  },

  // ── Data Display ──
  {
    title: "Accordion",
    section: "Data Display",
    href: "/design-system/components/data-display/accordion",
    keywords: "accordion collapsible expand collapse faq questions details summary",
    description: "Vertically stacked interactive panels for progressive disclosure of information.",
    type: "component",
    iconName: "expand_circle_down",
  },
  {
    title: "Approval Timeline",
    section: "Data Display",
    href: "/design-system/components/data-display/approval-timeline",
    keywords: "approval timeline audit trail history officer sanctions workflow signoff",
    description: "Hierarchical official sanction trail showing officer actions and timestamps.",
    type: "component",
    iconName: "approval",
  },
  {
    title: "Area Chart",
    section: "Data Display",
    href: "/design-system/components/data-display/area-chart",
    keywords: "area chart data viz visualization timeseries trends volume beneficiaries",
    description: "Time-series volume chart comparing cumulative metrics with gradient fills.",
    type: "component",
    iconName: "area_chart",
  },
  {
    title: "Avatar",
    section: "Data Display",
    href: "/design-system/components/data-display/avatar",
    keywords: "avatar profile photo user image initials fallback badge",
    description: "Circular and squircle user image representation with initials fallback.",
    type: "component",
    iconName: "face",
  },
  {
    title: "Axis",
    section: "Data Display",
    href: "/design-system/components/data-display/axis",
    keywords: "axis chart axis gridlines labels tick marks data viz scale",
    description: "Modular cartesian axis component for coordinate charts with tokenised typography.",
    type: "component",
    iconName: "ssid_chart",
  },
  {
    title: "Bar Chart",
    section: "Data Display",
    href: "/design-system/components/data-display/bar-chart",
    keywords: "bar chart column chart vertical horizontal comparison categories data viz",
    description: "Discrete categorical data comparison chart supporting vertical and horizontal bars.",
    type: "component",
    iconName: "bar_chart",
  },
  {
    title: "Card",
    section: "Data Display",
    href: "/design-system/components/data-display/card",
    keywords: "card container surface elevation clickable bordered interactive panel",
    description: "Versatile content container with header, body, footer, and media sections.",
    type: "component",
    iconName: "credit_card",
  },
  {
    title: "Chart Frame",
    section: "Data Display",
    href: "/design-system/components/data-display/chart-frame",
    keywords: "chart frame container data viz card export legend tooltip header",
    description: "Standard container shell enclosing charts with title, filters, and export controls.",
    type: "component",
    iconName: "aspect_ratio",
  },
  {
    title: "Combo Chart",
    section: "Data Display",
    href: "/design-system/components/data-display/combo-chart",
    keywords: "combo chart mixed chart bar line combined dual axis",
    description: "Dual-axis composite visualization pairing discrete bars with continuous trend lines.",
    type: "component",
    iconName: "waterfall_chart",
  },
  {
    title: "Data Table",
    section: "Data Display",
    href: "/design-system/components/data-display/data-table",
    keywords: "data table grid tabular sorting pagination filtering selection export excel csv",
    description: "High-density data grid featuring sorting, filtering, selection, and pagination.",
    type: "component",
    iconName: "table_chart",
  },
  {
    title: "Donut Chart",
    section: "Data Display",
    href: "/design-system/components/data-display/donut-chart",
    keywords: "donut chart pie ring percentage share breakdown distribution",
    description: "Ring proportion chart highlighting fractional distributions and total aggregates.",
    type: "component",
    iconName: "donut_large",
  },
  {
    title: "Funnel Chart",
    section: "Data Display",
    href: "/design-system/components/data-display/funnel-chart",
    keywords: "funnel chart conversion dropoff pipeline stages applications sanction disbursement",
    description: "Stage-by-stage conversion visualization for tracking scheme disbursement pipelines.",
    type: "component",
    iconName: "filter_alt",
  },
  {
    title: "Gauge",
    section: "Data Display",
    href: "/design-system/components/data-display/gauge",
    keywords: "gauge meter speedometer performance target threshold completion",
    description: "Radial dial meter showing progress against statutory targets and thresholds.",
    type: "component",
    iconName: "speed",
  },
  {
    title: "Heatmap",
    section: "Data Display",
    href: "/design-system/components/data-display/heatmap",
    keywords: "heatmap matrix intensity density activity calendar grid",
    description: "Two-dimensional color intensity matrix visualizing distribution density.",
    type: "component",
    iconName: "grid_on",
  },
  {
    title: "India Map",
    section: "Data Display",
    href: "/design-system/components/data-display/india-map",
    keywords: "india map states districts choropleth svg geography geographic data viz national",
    description: "Interactive SVG choropleth map of India with state and district level drills.",
    type: "component",
    iconName: "map",
  },
  {
    title: "Legend",
    section: "Data Display",
    href: "/design-system/components/data-display/legend",
    keywords: "legend chart key series color swatches labels indicator",
    description: "Accessible chart key matching categorical color tokens to series names.",
    type: "component",
    iconName: "list",
  },
  {
    title: "Line Chart",
    section: "Data Display",
    href: "/design-system/components/data-display/line-chart",
    keywords: "line chart trend timeseries continuous analytics performance",
    description: "Continuous line visualization for tracking metric trajectories over time.",
    type: "component",
    iconName: "show_chart",
  },
  {
    title: "Metric Card",
    section: "Data Display",
    href: "/design-system/components/data-display/metric-card",
    keywords: "metric card kpi stat number delta trend indicator comparison",
    description: "High-impact KPI summary card displaying big stats, delta trends, and badges.",
    type: "component",
    iconName: "analytics",
  },
  {
    title: "Pie Chart",
    section: "Data Display",
    href: "/design-system/components/data-display/pie-chart",
    keywords: "pie chart slices shares proportions distribution percentage",
    description: "Circular statistical graphic divided into proportional categorical slices.",
    type: "component",
    iconName: "pie_chart",
  },
  {
    title: "Profile Card",
    section: "Data Display",
    href: "/design-system/components/data-display/profile-card",
    keywords: "profile card user beneficiary details identity officer card",
    description: "Structured summary card showcasing citizen or official details, photo, and role.",
    type: "component",
    iconName: "badge",
  },
  {
    title: "Progress Bar",
    section: "Data Display",
    href: "/design-system/components/data-display/progress",
    keywords: "progress bar progress linear completion percentage indicator",
    description: "Linear progress bar showing operational percentage and threshold states.",
    type: "component",
    iconName: "sync",
  },
  {
    title: "Scatter Chart",
    section: "Data Display",
    href: "/design-system/components/data-display/scatter-chart",
    keywords: "scatter chart plot correlation distribution points outliers",
    description: "Cartesian scatter plot displaying relationships between dual continuous variables.",
    type: "component",
    iconName: "bubble_chart",
  },
  {
    title: "Sparkline",
    section: "Data Display",
    href: "/design-system/components/data-display/sparkline",
    keywords: "sparkline micro chart inline trend mini chart table chart",
    description: "Compact word-sized micro chart for embedding continuous trends inside table cells.",
    type: "component",
    iconName: "trending_up",
  },
  {
    title: "Vertical Timeline",
    section: "Data Display",
    href: "/design-system/components/data-display/vertical-timeline",
    keywords: "vertical timeline history events chronological milestones feed",
    description: "Chronological event stream detailing historical actions with status nodes.",
    type: "component",
    iconName: "history",
  },
  {
    title: "Visitor Counter",
    section: "Data Display",
    href: "/design-system/components/data-display/visitor-counter",
    keywords: "visitor counter hits traffic analytics odometre digital odometer live",
    description: "Standard government electronic visitor odometer with individual digit tumblers.",
    type: "component",
    iconName: "pin",
  },

  // ── Layout ──
  {
    title: "App Shell",
    section: "Layout",
    href: "/design-system/components/layout/app-shell",
    keywords: "app shell layout portal scaffold sidebar header content wrapper",
    description: "The holistic responsive shell framing portal navigation, headers, and views.",
    type: "component",
    iconName: "dashboard",
  },
  {
    title: "Band",
    section: "Layout",
    href: "/design-system/components/layout/band",
    keywords: "band strip section background full-width highlight banner",
    description: "Full-bleed horizontal section band for structuring public landing pages.",
    type: "component",
    iconName: "view_day",
  },
  {
    title: "Container",
    section: "Layout",
    href: "/design-system/components/layout/container",
    keywords: "container max-width center margin padding responsive bounds 1280px",
    description: "Centered structural boundary constraining page content to standard max widths.",
    type: "component",
    iconName: "crop_free",
  },
  {
    title: "Divider",
    section: "Layout",
    href: "/design-system/components/layout/divider",
    keywords: "divider separator line horizontal vertical border rule hr",
    description: "Subtle semantic rule separating adjacent content groups and list items.",
    type: "component",
    iconName: "remove",
  },
  {
    title: "Grid",
    section: "Layout",
    href: "/design-system/components/layout/grid",
    keywords: "grid css grid responsive columns rows gap auto-fit auto-fill",
    description: "Token-linked CSS Grid primitive simplifying multi-column responsive cards.",
    type: "component",
    iconName: "grid_view",
  },
  {
    title: "Page Header",
    section: "Layout",
    href: "/design-system/components/layout/page-header",
    keywords: "page header title breadcrumb actions subtitle hero",
    description: "Standardized page heading block incorporating breadcrumbs, title, and actions.",
    type: "component",
    iconName: "web_asset",
  },
  {
    title: "Section",
    section: "Layout",
    href: "/design-system/components/layout/section",
    keywords: "section semantic landmark html5 region spacing container",
    description: "Semantic landmark container applying vertical rhythm between page chapters.",
    type: "component",
    iconName: "view_agenda",
  },
  {
    title: "Site Layout",
    section: "Layout",
    href: "/design-system/components/layout/site-layout",
    keywords: "site layout public website framework header footer content",
    description: "Top-level layout framework governing the public DoSJE web estate.",
    type: "component",
    iconName: "view_quilt",
  },

  // ── Utilities ──
  {
    title: "Accessibility Bar",
    section: "Utilities",
    href: "/design-system/components/utilities/accessibility-bar",
    keywords: "accessibility bar top utility skip link font size a11y language switch india.gov.in GIGW UX4G",
    description: "Top government utility bar providing skip navigation, font scaling, and language toggles.",
    type: "component",
    iconName: "format_size",
  },
  {
    title: "Icon",
    section: "Utilities",
    href: "/design-system/components/utilities/icon",
    keywords: "icon material symbols rounded glyph svg size 24 weight 300 fill",
    description: "The official Material Symbols Rounded icon component with automated a11y hiding.",
    type: "component",
    iconName: "interests",
  },
  {
    title: "Live Region",
    section: "Utilities",
    href: "/design-system/components/utilities/live-region",
    keywords: "live region aria-live polite assertive screen reader announcements status",
    description: "Accessible ARIA live region manager for announcing dynamic DOM updates.",
    type: "component",
    iconName: "volume_up",
  },
  {
    title: "UX4G Accessibility Widget",
    section: "Utilities",
    href: "/design-system/components/utilities/ux4g-accessibility-widget",
    keywords: "ux4g accessibility widget floating button high contrast text spacing dyslexia reading guide",
    description: "Government accessibility toolbar with high contrast, reading guides, and font tweaks.",
    type: "component",
    iconName: "settings_accessibility",
  },

  // ── Auth & Dashboard ──
  {
    title: "Portal Login Shell",
    section: "Auth & Dashboard",
    href: "/design-system/components/auth/portal-login-shell",
    keywords: "portal login shell authentication sign in nic meri pehchaan sso credentials",
    description: "Standard multi-provider authentication shell supporting Meri Pehchaan and password sign-in.",
    type: "component",
    iconName: "vpn_key",
  },
  {
    title: "Portal Login Template",
    section: "Auth & Dashboard",
    href: "/design-system/components/auth/portal-login-template",
    keywords: "portal login template scheme login brand logo illustration security notice",
    description: "Full-page login template customizable per portal with official security notices.",
    type: "component",
    iconName: "login",
  },
  {
    title: "Chart Card",
    section: "Auth & Dashboard",
    href: "/design-system/components/dashboard/chart-card",
    keywords: "chart card dashboard card analytics header period selector download",
    description: "Dashboard surface container wrapping visualizations with time-range controls.",
    type: "component",
    iconName: "insert_chart",
  },
  {
    title: "Dashboard Grid",
    section: "Auth & Dashboard",
    href: "/design-system/components/dashboard/dashboard-grid",
    keywords: "dashboard grid layout kpi row charts tables responsive portal",
    description: "Pre-configured responsive dashboard layout arranging KPI rows and charts.",
    type: "component",
    iconName: "auto_awesome_mosaic",
  },
  {
    title: "Filter Bar",
    section: "Auth & Dashboard",
    href: "/design-system/components/dashboard/filter-bar",
    keywords: "filter bar search query date range state dropdown reset clear chips",
    description: "Integrated horizontal bar unifying search queries, date pickers, and filter pills.",
    type: "component",
    iconName: "tune",
  },
  {
    title: "KPI Row",
    section: "Auth & Dashboard",
    href: "/design-system/components/dashboard/kpi-row",
    keywords: "kpi row metric cards stats grid summary figures total beneficiaries",
    description: "Horizontal flex/grid container arranging metric cards in standard portal ratios.",
    type: "component",
    iconName: "view_column",
  },

  // ── Patterns ──
  {
    title: "Dashboard Scaffold",
    section: "Patterns",
    href: "/design-system/resources/patterns#dashboard",
    keywords: "dashboard scaffold pattern layout portal three row kpi charts table",
    description: "Canonical three-row scaffold for all 20+ MoSJE portal dashboards.",
    type: "pattern",
    badge: "New",
    iconName: "dashboard_customize",
  },
  {
    title: "Portal Login Pattern",
    section: "Patterns",
    href: "/design-system/resources/patterns#login",
    keywords: "portal login pattern authentication meri pehchaan sso 2fa credentials",
    description: "Unified citizen and officer sign-in flow pattern across all scheme portals.",
    type: "pattern",
    badge: "New",
    iconName: "passkey",
  },
  {
    title: "Form Wizard Pattern",
    section: "Patterns",
    href: "/design-system/resources/patterns#wizard",
    keywords: "form wizard pattern multi-step scheme application draft save submit",
    description: "End-to-end multi-step application wizard with autosave and validation.",
    type: "pattern",
    badge: "New",
    iconName: "checklist",
  },
  {
    title: "Data Tables Pattern",
    section: "Patterns",
    href: "/design-system/resources/patterns#data-table",
    keywords: "data tables pattern grid sorting filtering bulk actions export pagination",
    description: "Consistent tabular data exploration pattern for administrative registries.",
    type: "pattern",
    badge: "Alpha",
    iconName: "table_view",
  },
  {
    title: "Empty States Pattern",
    section: "Patterns",
    href: "/design-system/resources/patterns#empty-state",
    keywords: "empty states pattern placeholder zero state first run search empty",
    description: "Guidance on helpful, action-oriented empty states across views.",
    type: "pattern",
    badge: "Alpha",
    iconName: "upcoming",
  },

  // ── Resources ──
  {
    title: "Resources Overview",
    section: "Resources",
    href: "/design-system/resources",
    keywords: "resources overview guidelines tools assets packages tokens",
    description: "Central repository of design system guidelines, token specs, and tooling.",
    type: "resource",
    iconName: "menu_book",
  },
  {
    title: "AI Design Context",
    section: "Resources",
    href: "/design-system/resources/design-context",
    keywords: "ai design context llm prompt system architecture tokens rules instructions",
    description: "Machine-readable context and architectural rules for AI coding agents.",
    type: "resource",
    badge: "New",
    iconName: "smart_toy",
  },
  {
    title: "Design Tokens",
    section: "Resources",
    href: "/design-system/resources/tokens",
    keywords: "design tokens css variables style dictionary dtcg color space shape type",
    description: "Interactive browser for all 300+ design tokens exported from DTCG format.",
    type: "resource",
    badge: "New",
    iconName: "token",
  },
  {
    title: "Changelog",
    section: "Resources",
    href: "/design-system/resources/changelog",
    keywords: "changelog release notes version history updates breaking changes",
    description: "Comprehensive release history and evolution logs of the SAMAVESH design system.",
    type: "resource",
    iconName: "history",
  },
  {
    title: "Governance",
    section: "Resources",
    href: "/design-system/resources/governance",
    keywords: "governance component lifecycle stability alpha beta stable deprecated contribution rfc",
    description: "Component lifecycle management criteria from proposal to stable deprecation.",
    type: "resource",
    iconName: "gavel",
  },
  {
    title: "Contributing",
    section: "Resources",
    href: "/design-system/resources/contributing",
    keywords: "contributing pull request pr guidelines code standards review workflow git",
    description: "Step-by-step contribution guidelines for engineers and designers.",
    type: "resource",
    iconName: "volunteer_activism",
  },
  {
    title: "Roadmap",
    section: "Resources",
    href: "/design-system/resources/roadmap",
    keywords: "roadmap future releases upcoming milestones planned features next",
    description: "Strategic delivery milestones and upcoming components for the digital estate.",
    type: "resource",
    iconName: "map",
  },
];

