/**
 * Generated by scripts/build-docs-search-index.mjs.
 * DO NOT EDIT MANUALLY.
 * Run `node scripts/build-docs-search-index.mjs` to regenerate.
 */

export interface SearchEntry {
  title: string;
  section: string;
  href: string;
  keywords: string;
  description: string;
  type: "foundation" | "component" | "pattern" | "resource" | "page";
  badge?: "Stable" | "Beta" | "Alpha" | "New" | "Proposed" | "Deprecated";
  iconName: string;
}

export const SEARCH_DATA: SearchEntry[] = [
  {
    "title": "AadhaarInput",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/aadhaar-input",
    "keywords": "aadhaarinput forms & inputs playground 1. usage 2. code example 4. api reference 3. accessibility (a11y) value onValueChange invalid mask ...rest tokens wcag accessibility",
    "description": "An input specifically designed for collecting and securely masking Indian Aadhaar numbers.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Accessibility",
    "section": "Foundations",
    "href": "/design-system/foundations/accessibility",
    "keywords": "accessibility foundations wcag 2.1 aa + gigw the four pour principles the accessibility widget what it provides how to integrate behaviour &amp; theming checklist for designers checklist for developers baseline requirements how to test built-in by default src tokens wcag accessibility",
    "description": "The accessibility baseline for SAMAVESH — WCAG 2.1 AA + GIGW, the POUR principles, and practical checklists for designers and developers.",
    "type": "foundation",
    "badge": "Stable",
    "iconName": "accessibility"
  },
  {
    "title": "Accessibility Bar",
    "section": "Utilities",
    "href": "/design-system/components/utilities/accessibility-bar",
    "keywords": "accessibility bar utilities overview tone font size do &amp; don&apos;t interaction states layout (content width) usage token map api accessibility govLink skipTo showSkip skipLabel fontSize accessibility accessibilityHref onAccessibility language layout device maxWidth onFontScaleChange className tokens wcag accessibility",
    "description": "The government top utility bar (UX4G / GIGW) — Government of India link plus the accessibility controls (skip to content, font size, accessibility, language). The a11y surface itself, fully keyboard-operable and tokenised.",
    "type": "component",
    "badge": "Stable",
    "iconName": "build"
  },
  {
    "title": "Accordion",
    "section": "Data Display",
    "href": "/design-system/components/data-display/accordion",
    "keywords": "accordion data display overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "Collapsible disclosure containers for FAQs, scheme eligibility criteria, and nested application guidelines.",
    "type": "component",
    "badge": "Stable",
    "iconName": "bar_chart"
  },
  {
    "title": "Account Menu",
    "section": "Navigation",
    "href": "/design-system/components/navigation/account-menu",
    "keywords": "account menu navigation overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation Dr. R. Sharma tokens wcag accessibility",
    "description": "Dropdown profile menu displaying logged-in officer credentials, designation, portal switch links, and secure sign-out actions.",
    "type": "component",
    "badge": "Stable",
    "iconName": "navigation"
  },
  {
    "title": "Action Banner",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/action-banner",
    "keywords": "action banner feedback & status playground 1. usage 2. code example 4. api reference 3. accessibility (a11y) title description action className ...rest tokens wcag accessibility",
    "description": "A high-visibility call to action block used on public pages to direct users to key flows.",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "AI design context (design.md)",
    "section": "Resources",
    "href": "/design-system/resources/design-context",
    "keywords": "ai design context (design.md) resources   tokens wcag accessibility",
    "description": "The authoritative design contract an AI agent reads before building UI on SAMAVESH — token vocabulary, theming axes, component inventory, and the non-negotiable rules. Rendered from the source design.md.",
    "type": "resource",
    "iconName": "menu_book"
  },
  {
    "title": "Alert",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/alert",
    "keywords": "alert feedback & status playground 1. usage 2. anatomy 3. status variants 5. api reference 4. accessibility (a11y) status title children dismissible onDismiss action timestamp tokens wcag accessibility",
    "description": "Alerts display important, prominently placed messages that require the user",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "App Shell",
    "section": "Layout",
    "href": "/design-system/components/layout/app-shell",
    "keywords": "app shell layout overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "Foundational application skeleton for authenticated MoSJE portals, organizing the SiteHeader, ContentNav sidebar, main work area, and slim footer.",
    "type": "component",
    "badge": "Stable",
    "iconName": "view_quilt"
  },
  {
    "title": "App Switcher Panel",
    "section": "Navigation",
    "href": "/design-system/components/navigation/app-switcher-panel",
    "keywords": "app switcher panel navigation overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "Cross-portal directory modal allowing officers and beneficiaries to discover and jump across all 20 MoSJE portals seamlessly.",
    "type": "component",
    "badge": "Stable",
    "iconName": "navigation"
  },
  {
    "title": "Approval Timeline",
    "section": "Data Display",
    "href": "/design-system/components/data-display/approval-timeline",
    "keywords": "approval timeline data display overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "Vertical progression tracking component showing multi-tier administrative approval stages, timestamps, official notes, and officer designations.",
    "type": "component",
    "badge": "Beta",
    "iconName": "bar_chart"
  },
  {
    "title": "Area Chart",
    "section": "Data Display",
    "href": "/design-system/components/data-display/area-chart",
    "keywords": "area chart data display overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation Disbursed Disbursed tokens wcag accessibility",
    "description": "Time-series volumetric area visualization showing cumulative scheme funds, application trends, and demographic distributions.",
    "type": "component",
    "badge": "Beta",
    "iconName": "bar_chart"
  },
  {
    "title": "Avatar",
    "section": "Data Display",
    "href": "/design-system/components/data-display/avatar",
    "keywords": "avatar data display overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "Circular graphical representation of a citizen profile, department officer, or beneficiary with fallback initials.",
    "type": "component",
    "badge": "Stable",
    "iconName": "bar_chart"
  },
  {
    "title": "Axis",
    "section": "Data Display",
    "href": "/design-system/components/data-display/axis",
    "keywords": "axis data display overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance  tokens wcag accessibility",
    "description": "Mathematical and categorical axis primitive with Indian numbering formatting (Lakhs / Crores), grid ticks, and baseline alignment.",
    "type": "component",
    "badge": "Beta",
    "iconName": "bar_chart"
  },
  {
    "title": "Badge",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/badge",
    "keywords": "badge feedback & status overview playground status variants sizes do &amp; don&apos;t api accessibility status size children aria-label className ...rest tokens wcag accessibility",
    "description": "Badge is a small label indicating status, count, or category — a tonal pill in semantic colours (success, warning, danger, info) with two sizes.",
    "type": "component",
    "badge": "Stable",
    "iconName": "notifications"
  },
  {
    "title": "Band",
    "section": "Layout",
    "href": "/design-system/components/layout/band",
    "keywords": "band layout overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance  tokens wcag accessibility",
    "description": "Full-bleed horizontal background section container for organizing public website content into distinct visual layers.",
    "type": "component",
    "badge": "Stable",
    "iconName": "view_quilt"
  },
  {
    "title": "Bar Chart",
    "section": "Data Display",
    "href": "/design-system/components/data-display/bar-chart",
    "keywords": "bar chart data display overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "Vertical column and horizontal bar visualization for comparing categorical metrics across states, districts, and scheme categories.",
    "type": "component",
    "badge": "Beta",
    "iconName": "bar_chart"
  },
  {
    "title": "Brand Lockup",
    "section": "Navigation",
    "href": "/design-system/components/navigation/brand-lockup",
    "keywords": "brand lockup navigation overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "Official National Emblem and Ministry of Social Justice and Empowerment typography lockup compliant with State Emblem rules.",
    "type": "component",
    "badge": "Stable",
    "iconName": "navigation"
  },
  {
    "title": "Button",
    "section": "Actions",
    "href": "/design-system/components/actions/button",
    "keywords": "button actions anatomy variants responsive behavior &amp; keyboard code accessibility evidence purpose when to use / not states content &amp; voice related changelog variant appearance tone loading size iconLeft iconRight href disabled children ...rest tokens wcag accessibility",
    "description": "A Button triggers an action within the system — submitting a form, confirming a dialog, or running a command. The most-used interactive atom in the SAMAVESH design system.",
    "type": "component",
    "badge": "Stable",
    "iconName": "widgets"
  },
  {
    "title": "CaptchaField",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/captcha-field",
    "keywords": "captchafield forms & inputs playground 1. usage 2. code example 4. api reference 3. accessibility (a11y) challenge value onValueChange onRefresh error label placeholder tokens wcag accessibility",
    "description": "A legacy CAPTCHA challenge component for existing portals.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Card",
    "section": "Data Display",
    "href": "/design-system/components/data-display/card",
    "keywords": "card data display overview playground variants do &amp; don&apos;t api accessibility variant orientation className ...rest children className ...rest tokens wcag accessibility",
    "description": "Card is a surface for grouping related content — a styled container composed of header, body and footer sections, with outlined and elevated variants.",
    "type": "component",
    "badge": "Stable",
    "iconName": "bar_chart"
  },
  {
    "title": "Changelog",
    "section": "Resources",
    "href": "/design-system/resources/changelog",
    "keywords": "changelog resources   tokens wcag accessibility",
    "description": "Every release of the SAMAVESH design system — what was added, changed, and fixed in each version.",
    "type": "resource",
    "iconName": "menu_book"
  },
  {
    "title": "Chart Card",
    "section": "Auth & Dashboard",
    "href": "/design-system/components/dashboard/chart-card",
    "keywords": "chart card auth & dashboard overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "Structured container for data visualizations, metrics, and tabular summaries in analytical dashboards with built-in export actions and error states.",
    "type": "component",
    "badge": "Beta",
    "iconName": "bar_chart"
  },
  {
    "title": "Chart Frame",
    "section": "Data Display",
    "href": "/design-system/components/data-display/chart-frame",
    "keywords": "chart frame data display overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance  tokens wcag accessibility",
    "description": "Underlying SVG viewbox canvas that manages responsive margins, aspect ratios, titles, and legend placements.",
    "type": "component",
    "badge": "Beta",
    "iconName": "bar_chart"
  },
  {
    "title": "Chatbot",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/chatbot",
    "keywords": "chatbot feedback & status playground 1. usage 2. anatomy 3. states 4. placement and layering 5. motion 6. prototype 7. accessibility (a11y) 8. api reference open defaultOpen onOpenChange title subtitle greeting quickReplies onQuickReply messages typing composer composerPlaceholder onSubmit note endChatLabel tokens wcag accessibility",
    "description": "Samajik Sahayak, the estate",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "ChatbotMascot",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/chatbot-mascot",
    "keywords": "chatbotmascot feedback & status 1. why it is two nodes 2. sizes and the ring 3. the disc follows the brand 4. motion 5. api reference size ring spin tokens wcag accessibility",
    "description": "The Samajik Sahayak assistant mark: a navy disc carrying the mascot, and an optional seal ring bearing the bilingual wordmark.",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "Checkbox",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/checkbox",
    "keywords": "checkbox forms & inputs 1. usage 2. features & accessibility 3. code example  tokens wcag accessibility",
    "description": "Checkboxes allow users to select one or more items from a set, or to turn an option on or off.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Chip",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/chip",
    "keywords": "chip forms & inputs playground 1. usage 2. code example 4. api reference 3. accessibility (a11y) selected onSelectedChange leadingIcon onDismiss dismissLabel trailingDropdown disabled children tokens wcag accessibility",
    "description": "A compact, pill-shaped element used for filters, selections, and removable tags.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Color — Foundations",
    "section": "Foundations",
    "href": "/design-system/foundations/color",
    "keywords": "color — foundations foundations   tokens wcag accessibility",
    "description": "Colour is never the only carrier of meaning. Pair it with an icon, a label, a pattern or a position.",
    "type": "foundation",
    "badge": "Stable",
    "iconName": "palette"
  },
  {
    "title": "Combo Chart",
    "section": "Data Display",
    "href": "/design-system/components/data-display/combo-chart",
    "keywords": "combo chart data display overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation Target Actual Target Actual tokens wcag accessibility",
    "description": "Dual-axis composite visualization pairing bar columns (target amounts) with an overlaid line trend (actual realization percentage).",
    "type": "component",
    "badge": "Beta",
    "iconName": "bar_chart"
  },
  {
    "title": "Container",
    "section": "Layout",
    "href": "/design-system/components/layout/container",
    "keywords": "container layout overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance  tokens wcag accessibility",
    "description": "Max-width responsive bounding box (1280px standard) centering content with responsive horizontal gutters.",
    "type": "component",
    "badge": "Stable",
    "iconName": "view_quilt"
  },
  {
    "title": "Contributing",
    "section": "Resources",
    "href": "/design-system/resources/contributing",
    "keywords": "contributing resources propose a new component add or change a design token run the system locally pull-request checklist  tokens wcag accessibility",
    "description": "How to contribute to SAMAVESH — propose a new component, add or change a design token, run the system locally, and pass the pull-request checklist.",
    "type": "resource",
    "iconName": "menu_book"
  },
  {
    "title": "Dashboard Archetypes",
    "section": "Data Visualisation",
    "href": "/design-system/data-visualisation/archetypes",
    "keywords": "dashboard archetypes data visualisation   tokens wcag accessibility",
    "description": "Five named dashboard boards — scheme performance, geographic distribution, application pipeline, compliance status and beneficiary demographics — composed from the SAMAVESH visualisation layer.",
    "type": "pattern",
    "iconName": "bar_chart"
  },
  {
    "title": "Dashboard Grid",
    "section": "Auth & Dashboard",
    "href": "/design-system/components/dashboard/dashboard-grid",
    "keywords": "dashboard grid auth & dashboard overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "Responsive CSS grid container designed for high-density administrative dashboards and KPI monitoring screens.",
    "type": "component",
    "badge": "Beta",
    "iconName": "lock"
  },
  {
    "title": "Data Table",
    "section": "Data Display",
    "href": "/design-system/components/data-display/data-table",
    "keywords": "data table data display 1. usage 2. features & best practices 3. code example  tokens wcag accessibility",
    "description": "Data tables display sets of structured data, making it easy to scan, compare, and analyze information.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Data Visualisation",
    "section": "Data Visualisation",
    "href": "/design-system/data-visualisation",
    "keywords": "data visualisation data visualisation   tokens wcag accessibility",
    "description": "Every chart, metric, table and container in the SAMAVESH data-visualisation layer, rendered live against government data — the reference both designers and developers benchmark against.",
    "type": "page",
    "iconName": "bar_chart"
  },
  {
    "title": "DeclarationCheckbox",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/declaration-checkbox",
    "keywords": "declarationcheckbox forms & inputs playground 1. usage 2. code example 4. api reference 3. accessibility (a11y) checked onChange children title lead error tokens wcag accessibility",
    "description": "A statutory certification block that closes a government form.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Density",
    "section": "Foundations",
    "href": "/design-system/foundations/density",
    "keywords": "density foundations side by side when to use compact when not to use compact how to activate it tokens  tokens wcag accessibility",
    "description": "Comfortable and compact density modes — how SAMAVESH adapts control sizing for spacious public forms and data-dense portals.",
    "type": "foundation",
    "badge": "Stable",
    "iconName": "palette"
  },
  {
    "title": "Design tokens",
    "section": "Resources",
    "href": "/design-system/resources/tokens",
    "keywords": "design tokens resources   tokens wcag accessibility",
    "description": "Every SAMAVESH design token and its resolved value, rendered from the generated DTCG export — colors with live swatches, plus spacing, radius, type, shadow, and motion.",
    "type": "resource",
    "iconName": "menu_book"
  },
  {
    "title": "Divider",
    "section": "Layout",
    "href": "/design-system/components/layout/divider",
    "keywords": "divider layout why it exists orientation tone follows the surface, not the taste leave the length alone do &amp; don&apos;t token map migration status api accessibility orientation tone length decorative className tokens wcag accessibility",
    "description": "The estate",
    "type": "component",
    "iconName": "view_quilt"
  },
  {
    "title": "Donut Chart",
    "section": "Data Display",
    "href": "/design-system/components/data-display/donut-chart",
    "keywords": "donut chart data display overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "Circular proportional ring chart showing budget allocation percentages and scheme demographic shares with central summary slot.",
    "type": "component",
    "badge": "Beta",
    "iconName": "bar_chart"
  },
  {
    "title": "Elevation",
    "section": "Foundations",
    "href": "/design-system/foundations/elevation",
    "keywords": "elevation foundations the three levels when to use each tokens guidance  tokens wcag accessibility",
    "description": "Shadow tokens that give SAMAVESH surfaces a sense of depth — from pressed controls to floating modals.",
    "type": "foundation",
    "badge": "Stable",
    "iconName": "layers"
  },
  {
    "title": "Empty State",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/empty-state",
    "keywords": "empty state feedback & status playground 1. usage 2. code example 4. api reference 3. accessibility (a11y) title icon description action className ...rest tokens wcag accessibility",
    "description": "A centered placeholder for empty collections or zero-result views.",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "Error View",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/error-view",
    "keywords": "error view feedback & status playground 1. usage principles props accessibility &amp; standards kind badge title description searchUrl primaryAction secondaryAction wayfindingLinks errorDetails tokens wcag accessibility",
    "description": "A full-page resilient error state with Apple-inspired fluid motion, integrated search, recovery actions, and citizen wayfinding.",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "Filter Bar",
    "section": "Auth & Dashboard",
    "href": "/design-system/components/dashboard/filter-bar",
    "keywords": "filter bar auth & dashboard overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "Universal horizontal control bar for filtering data tables, maps, and chart queries by fiscal year, state, scheme, and status.",
    "type": "component",
    "badge": "Beta",
    "iconName": "lock"
  },
  {
    "title": "Footer",
    "section": "Navigation",
    "href": "/design-system/components/navigation/footer",
    "keywords": "footer navigation overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "Slim dark-navy application shell footer containing developer credits (NeGD / NIC), version numbers, and statutory policy links.",
    "type": "component",
    "badge": "Stable",
    "iconName": "navigation"
  },
  {
    "title": "FormCard",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/form-card",
    "keywords": "formcard forms & inputs playground 1. usage 2. code example 4. api reference 3. accessibility (a11y) title description required headingId actions children className tokens wcag accessibility",
    "description": "A titled surface card that accepts arbitrary children, ensuring consistent header styling across complex layouts.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "FormField",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/form-field",
    "keywords": "formfield forms & inputs playground 1. usage 2. code example 4. api reference 3. accessibility (a11y) label children hint error required id className tokens wcag accessibility",
    "description": "A structural molecule that wires a label, hint text, and error message to a form control.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "FormSection",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/form-section",
    "keywords": "formsection forms & inputs playground 1. usage 2. code example 4. api reference 3. accessibility (a11y) title description columns children className tokens wcag accessibility",
    "description": "A titled card wrapping a responsive field grid.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Funnel Chart",
    "section": "Data Display",
    "href": "/design-system/components/data-display/funnel-chart",
    "keywords": "funnel chart data display overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "Stage-by-stage pipeline visualization tracking citizen application drop-offs from initial registration to final bank DBT crediting.",
    "type": "component",
    "badge": "Beta",
    "iconName": "bar_chart"
  },
  {
    "title": "Gauge",
    "section": "Data Display",
    "href": "/design-system/components/data-display/gauge",
    "keywords": "gauge data display overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance  tokens wcag accessibility",
    "description": "Semi-circular radial dial indicating SLA completion rates, fund utilization thresholds, and performance targets.",
    "type": "component",
    "badge": "Beta",
    "iconName": "bar_chart"
  },
  {
    "title": "GeoPhotoInput",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/geo-photo-input",
    "keywords": "geophotoinput forms & inputs playground 1. usage 2. code example 4. api reference 3. accessibility (a11y) value onChange maxItems minItems maxSizeMb tokens wcag accessibility",
    "description": "An evidence-photo uploader that automatically extracts EXIF coordinates or requests device location.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Governance",
    "section": "Resources",
    "href": "/design-system/resources/governance",
    "keywords": "governance resources the component lifecycle proposing a new component (the rfc process) versioning policy (semver) deprecation window  tokens wcag accessibility",
    "description": "How SAMAVESH is governed — the component lifecycle, the RFC process for proposing components, our semantic versioning policy, and the deprecation window.",
    "type": "resource",
    "badge": "Proposed",
    "iconName": "menu_book"
  },
  {
    "title": "Grid",
    "section": "Layout",
    "href": "/design-system/components/layout/grid",
    "keywords": "grid layout overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance  tokens wcag accessibility",
    "description": "12-column responsive layout grid system with predefined responsive spans and gutters.",
    "type": "component",
    "badge": "Stable",
    "iconName": "view_quilt"
  },
  {
    "title": "Heatmap",
    "section": "Data Display",
    "href": "/design-system/components/data-display/heatmap",
    "keywords": "heatmap data display overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "Matrix grid visualization using color intensity to illustrate scheme activity and application volumes across calendar months and states.",
    "type": "component",
    "badge": "Beta",
    "iconName": "bar_chart"
  },
  {
    "title": "Icon",
    "section": "Utilities",
    "href": "/design-system/components/utilities/icon",
    "keywords": "icon utilities overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance  tokens wcag accessibility",
    "description": "Material Symbols Rounded icon component with strict 24px token grid alignment, optical sizing, and accessibility hiding defaults.",
    "type": "component",
    "badge": "Stable",
    "iconName": "build"
  },
  {
    "title": "Iconography",
    "section": "Foundations",
    "href": "/design-system/foundations/iconography",
    "keywords": "iconography foundations one component, any icon the {icon_catalogue.length} icons in the starter set seven sizes — dbim&rsquo;s four, plus what interface work needs weight 300 is the style named light almost nothing needs to be a vector an icon is never the only signal the figma property is the code prop  tokens wcag accessibility",
    "description": "The SAMAVESH icon system — one component holding any Material Symbols Rounded glyph, at weight 300, on a seven-step size scale.",
    "type": "foundation",
    "badge": "Stable",
    "iconName": "category"
  },
  {
    "title": "Identity Inputs — Aadhaar, OTP, PAN",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/identity-inputs",
    "keywords": "identity inputs — aadhaar, otp, pan forms & inputs aadhaar otp pan value onValueChange mask invalid value onValueChange label length onComplete invalid value onValueChange invalid tokens wcag accessibility",
    "description": "The three Indian identity controls every MoSJE service journey needs: a Verhoeff-checked, masked-by-default Aadhaar field, a six-box OTP input with paste and SMS autofill, and a PAN field that validates the holder-type character.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "India Map",
    "section": "Data Display",
    "href": "/design-system/components/data-display/india-map",
    "keywords": "india map data display overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "Choropleth SVG map of India illustrating state-wise and union territory scheme coverage, fund disbursals, and inspection counts.",
    "type": "component",
    "badge": "Beta",
    "iconName": "bar_chart"
  },
  {
    "title": "Input & FormField",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/input",
    "keywords": "input & formfield forms & inputs input props accessibility textarea props accessibility select props accessibility formfield error state props accessibility formsection props formcard props wizard props reviewsection &amp; reviewitem accessibility invalid type placeholder disabled ...native invalid rows placeholder disabled ...native options placeholder invalid disabled ...native tokens wcag accessibility",
    "description": "Text Input, Textarea, Select controls and the FormField molecule that wires labels, hints, and errors together accessibly.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Kpi Row",
    "section": "Auth & Dashboard",
    "href": "/design-system/components/dashboard/kpi-row",
    "keywords": "kpi row auth & dashboard overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "Horizontal metric summary row presenting key performance indicators, grant disbursals, and scheme beneficiary totals at a glance.",
    "type": "component",
    "badge": "Beta",
    "iconName": "lock"
  },
  {
    "title": "Label",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/label",
    "keywords": "label forms & inputs playground 1. usage 2. code example 4. api reference 3. accessibility (a11y) children htmlFor required hint ...rest tokens wcag accessibility",
    "description": "A standalone accessible label for form controls when you cannot use the FormField wrapper.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Layout Grid",
    "section": "Foundations",
    "href": "/design-system/foundations/layout-grid",
    "keywords": "layout grid foundations   tokens wcag accessibility",
    "description": "The SAMAVESH page container — a three-step cap with a margin ladder that steps with the cap, so content width only ever grows.",
    "type": "foundation",
    "badge": "Stable",
    "iconName": "grid_view"
  },
  {
    "title": "Legend",
    "section": "Data Display",
    "href": "/design-system/components/data-display/legend",
    "keywords": "legend data display overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance  tokens wcag accessibility",
    "description": "Categorical and sequential color legend explaining chart series, thresholds, and choropleth scale buckets.",
    "type": "component",
    "badge": "Beta",
    "iconName": "bar_chart"
  },
  {
    "title": "Lightbox",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/lightbox",
    "keywords": "lightbox feedback & status overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "Full-screen media overlay modal for inspecting scheme beneficiary certificates, event photo galleries, and geo-tagged inspection images.",
    "type": "component",
    "badge": "Beta",
    "iconName": "notifications"
  },
  {
    "title": "Line Chart",
    "section": "Data Display",
    "href": "/design-system/components/data-display/line-chart",
    "keywords": "line chart data display overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation Applications Applications tokens wcag accessibility",
    "description": "Continuous line graph with data point markers for analyzing monthly citizen applications, portal traffic, and fund burn rates.",
    "type": "component",
    "badge": "Beta",
    "iconName": "bar_chart"
  },
  {
    "title": "Live Region",
    "section": "Utilities",
    "href": "/design-system/components/utilities/live-region",
    "keywords": "live region utilities overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance  tokens wcag accessibility",
    "description": "Accessible ARIA live announcement utility for broadcasting dynamic search results, form status updates, and async timer alerts to screen readers.",
    "type": "component",
    "badge": "Stable",
    "iconName": "build"
  },
  {
    "title": "Loader",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/loader",
    "keywords": "loader feedback & status playground 1. usage 2. code example 4. api reference 3. accessibility (a11y) size variant label className ...rest tokens wcag accessibility",
    "description": "An accessible CSS spinner used to indicate that a process or data loading is currently underway.",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "MediaGalleryInput",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/media-gallery-input",
    "keywords": "mediagalleryinput forms & inputs playground 1. usage 2. code example 4. api reference 3. accessibility (a11y) value onChange maxItems maxSizeMb accept tokens wcag accessibility",
    "description": "A multi-file uploader supporting images and videos with inline previews.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "MediaUpload",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/media-upload",
    "keywords": "mediaupload forms & inputs playground 1. usage 2. code example 4. api reference 3. accessibility (a11y) value fileName onChange onClear accept maxSizeMb promptLabel hintLabel tokens wcag accessibility",
    "description": "An accessible file dropzone supporting image previews and client-side validation.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Metric Card",
    "section": "Data Display",
    "href": "/design-system/components/data-display/metric-card",
    "keywords": "metric card data display overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "Compact analytical card highlighting a single primary numerical statistic, trend delta indicator, and descriptive category label.",
    "type": "component",
    "badge": "Stable",
    "iconName": "bar_chart"
  },
  {
    "title": "Modal",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/modal",
    "keywords": "modal feedback & status 1. usage 2. sizes 3. anatomy 4. accessibility (a11y)  tokens wcag accessibility",
    "description": "Modals focus the user’s attention exclusively on one task or piece of information via a window that sits on top of the page content.",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "Motion",
    "section": "Foundations",
    "href": "/design-system/foundations/motion",
    "keywords": "motion foundations duration scale easing live demo reduced motion tokens guidance  tokens wcag accessibility",
    "description": "Duration and easing for SAMAVESH — purposeful, fast and respectful of reduced-motion preferences.",
    "type": "foundation",
    "badge": "Stable",
    "iconName": "animation"
  },
  {
    "title": "Nav Sheet",
    "section": "Navigation",
    "href": "/design-system/components/navigation/nav-sheet",
    "keywords": "nav sheet navigation overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "Full-height responsive off-canvas drawer housing primary navigation, language toggles, and user settings on mobile devices.",
    "type": "component",
    "badge": "Stable",
    "iconName": "navigation"
  },
  {
    "title": "Navbar (Header)",
    "section": "Navigation",
    "href": "/design-system/components/section-templates/site-header",
    "keywords": "navbar (header) navigation anatomy when to use — choosing a variant responsive props behavior &amp; keyboard code reuse across the estate accessibility variants portal variant the parts, on their own compact variant menus — dropdowns &amp; mega-menus content &amp; voice related changelog variant homeHref navExpanded navControlsId emblemSrc brandLines nav search actions onToggleNav brandDivider cobranding account / accountMenu sticky collapseOnScroll tokens wcag accessibility",
    "description": "The SAMAVESH Navbar (SiteHeader) — one component, two variants. Website: accessibility bar + brand row (search + Login) + nav row with mega-menus. Portal: collapse toggle + emblem divider + cobranding + account, with optional scroll-collapse.",
    "type": "component",
    "badge": "Beta",
    "iconName": "navigation"
  },
  {
    "title": "OtpInput",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/otp-input",
    "keywords": "otpinput forms & inputs playground 1. usage 2. code example 4. api reference 3. accessibility (a11y) value onChange length label onComplete invalid autoFocus tokens wcag accessibility",
    "description": "An accessible group of text inputs optimized for collecting One-Time Passwords (OTP).",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Page Header",
    "section": "Layout",
    "href": "/design-system/components/layout/page-header",
    "keywords": "page header layout overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance  tokens wcag accessibility",
    "description": "Standardized internal page masthead with title, metadata line, action buttons, and semantic heading level.",
    "type": "component",
    "badge": "Stable",
    "iconName": "view_quilt"
  },
  {
    "title": "Page Patterns",
    "section": "Patterns",
    "href": "/design-system/resources/patterns",
    "keywords": "page patterns patterns  Akash Kumar tokens wcag accessibility",
    "description": "Approved page-level scaffolds for MoSJE portals and websites — Dashboard, Portal Login, Form Wizard, Data Tables, and Empty States.",
    "type": "pattern",
    "badge": "Stable",
    "iconName": "dashboard_customize"
  },
  {
    "title": "PanInput",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/pan-input",
    "keywords": "paninput forms & inputs playground 1. usage 2. code example 4. api reference 3. accessibility (a11y) value onValueChange invalid ...rest tokens wcag accessibility",
    "description": "An input specifically designed for collecting Indian Permanent Account Numbers (PAN).",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Password Input",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/password-input",
    "keywords": "password input forms & inputs playground 1. usage 2. code example 4. api reference 3. accessibility (a11y) showLabel hideLabel hideToggle ...rest tokens wcag accessibility",
    "description": "A secure password field with an accessible reveal toggle.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "PasswordStrengthMeter",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/password-strength-meter",
    "keywords": "passwordstrengthmeter forms & inputs playground 1. usage 2. code example 4. api reference 3. accessibility (a11y) score caption id tokens wcag accessibility",
    "description": "An accessible password strength indicator designed for registration and password-reset flows.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Pie Chart",
    "section": "Data Display",
    "href": "/design-system/components/data-display/pie-chart",
    "keywords": "pie chart data display overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "Solid circular proportional chart representing parts of a whole across top-level statutory budget categories.",
    "type": "component",
    "badge": "Beta",
    "iconName": "bar_chart"
  },
  {
    "title": "Portal Login Shell",
    "section": "Auth & Dashboard",
    "href": "/design-system/components/auth/portal-login-shell",
    "keywords": "portal login shell auth & dashboard overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "The standardized authentication layout container shared across all 20 MoSJE portals. Enforces Gov.in branding, security disclaimers, dual-language toggle, and National Informatics Centre (NIC) authentication standards.",
    "type": "component",
    "badge": "Stable",
    "iconName": "lock"
  },
  {
    "title": "Portal Login Template",
    "section": "Auth & Dashboard",
    "href": "/design-system/components/auth/portal-login-template",
    "keywords": "portal login template auth & dashboard overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "A pre-configured template composing role-based login tabs (Citizen, Officer, State Admin), OTP verification, Captcha validation, and DigiLocker SSO integration.",
    "type": "component",
    "badge": "Stable",
    "iconName": "lock"
  },
  {
    "title": "Profile Card",
    "section": "Data Display",
    "href": "/design-system/components/data-display/profile-card",
    "keywords": "profile card data display overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance  tokens wcag accessibility",
    "description": "Government leadership and officer contact card featuring official portrait, designation, ministry division, and contact credentials.",
    "type": "component",
    "badge": "New",
    "iconName": "bar_chart"
  },
  {
    "title": "Progress",
    "section": "Data Display",
    "href": "/design-system/components/data-display/progress",
    "keywords": "progress data display overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance  tokens wcag accessibility",
    "description": "Linear progress bar indicating form wizard completion percentage, file upload progress, and statutory quota allocations.",
    "type": "component",
    "badge": "Stable",
    "iconName": "bar_chart"
  },
  {
    "title": "Radio",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/radio",
    "keywords": "radio forms & inputs 1. usage 2. features & accessibility 3. code example  tokens wcag accessibility",
    "description": "Radio buttons allow users to select exactly one mutually exclusive option from a list.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Resources",
    "section": "Resources",
    "href": "/design-system/resources",
    "keywords": "resources resources quick links building with an ai agent? get help  tokens wcag accessibility",
    "description": "Quick links to the SAMAVESH Figma library, Storybook, GitHub, changelog, governance, contributing guide, and roadmap — plus how to get help.",
    "type": "resource",
    "iconName": "menu_book"
  },
  {
    "title": "Roadmap",
    "section": "Resources",
    "href": "/design-system/resources/roadmap",
    "keywords": "roadmap resources   tokens wcag accessibility",
    "description": "Where SAMAVESH is heading — what is shipped now (v0.5), what is coming next (v0.6), and the longer-term plan toward v1.0.",
    "type": "resource",
    "iconName": "menu_book"
  },
  {
    "title": "Scatter Chart",
    "section": "Data Display",
    "href": "/design-system/components/data-display/scatter-chart",
    "keywords": "scatter chart data display overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation Districts Districts tokens wcag accessibility",
    "description": "Bivariate coordinate plot mapping district inspection frequency against grievance resolution velocity.",
    "type": "component",
    "badge": "Beta",
    "iconName": "bar_chart"
  },
  {
    "title": "Search",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/search",
    "keywords": "search forms & inputs playground 1. usage 2. sizes 3. code example 5. api reference 4. accessibility (a11y) value onChange size onClear onSubmit placeholder ...rest tokens wcag accessibility",
    "description": "An input field optimized for search queries, featuring a leading icon, optional clear button, and submit handler.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Section Title",
    "section": "Layout",
    "href": "/design-system/components/layout/section",
    "keywords": "section title layout overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance  tokens wcag accessibility",
    "description": "Section header block with section label eyebrow, heading, descriptive lede, and count badge.",
    "type": "component",
    "badge": "Stable",
    "iconName": "view_quilt"
  },
  {
    "title": "Select",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/select",
    "keywords": "select forms & inputs playground 1. usage 2. code example 4. api reference 3. accessibility (a11y) invalid options placeholder children ...rest tokens wcag accessibility",
    "description": "A native dropdown field that allows users to pick one option from a list.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Shape",
    "section": "Foundations",
    "href": "/design-system/foundations/shape",
    "keywords": "shape foundations how shape works the ladder choosing a rung prefer a role token pills and circles tokens do &amp; don&apos;t  tokens wcag accessibility",
    "description": "The SAMAVESH corner-radius ladder — twelve value-named rungs plus a fully-rounded sentinel, shared by every MoSJE site and portal.",
    "type": "foundation",
    "badge": "Stable",
    "iconName": "rounded_corner"
  },
  {
    "title": "Side Sheet",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/side-sheet",
    "keywords": "side sheet feedback & status overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "Slide-out right-rail panel for deep application inspection, multi-filter panels, and officer audit histories without losing page context.",
    "type": "component",
    "badge": "Stable",
    "iconName": "notifications"
  },
  {
    "title": "Sidebar Nav",
    "section": "Navigation",
    "href": "/design-system/components/section-templates/sidebar",
    "keywords": "sidebar nav navigation 1. import 2. usage 5. behaviour 6. portal usage 3. props 4. design tokens 7. accessibility groups pathname collapsed onCollapsedChange showCollapseControl footer className label items label href icon badge children label tokens wcag accessibility",
    "description": "The SAMAVESH SidebarNav — portal left-hand navigation. Supports two-level hierarchy with expandable groups, a curved connector visual, and expanded/collapsed modes.",
    "type": "component",
    "badge": "Beta",
    "iconName": "navigation"
  },
  {
    "title": "Site Footer",
    "section": "Navigation",
    "href": "/design-system/components/navigation/site-footer",
    "keywords": "site footer navigation overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "Comprehensive dual-band public website footer containing sitemap columns, social channels, grievance contacts, and statutory DBIM requirements.",
    "type": "component",
    "badge": "Stable",
    "iconName": "navigation"
  },
  {
    "title": "Site Layout",
    "section": "Layout",
    "href": "/design-system/components/layout/site-layout",
    "keywords": "site layout layout overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance  tokens wcag accessibility",
    "description": "Top-level layout shell for the unified public MoSJE website, hosting the 3-tier masthead, main body, and comprehensive statutory footer.",
    "type": "component",
    "badge": "Stable",
    "iconName": "view_quilt"
  },
  {
    "title": "Skeleton",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/skeleton",
    "keywords": "skeleton feedback & status overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance  tokens wcag accessibility",
    "description": "Animated placeholder shapes representing text, cards, and tables while asynchronous portal queries are loading.",
    "type": "component",
    "badge": "Stable",
    "iconName": "notifications"
  },
  {
    "title": "Sla Progress Indicator",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/sla-progress-indicator",
    "keywords": "sla progress indicator feedback & status overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance  tokens wcag accessibility",
    "description": "Statutory grievance and application SLA tracker showing consumed days versus statutory time limits with tone changes (On Track, Warning, Breached).",
    "type": "component",
    "badge": "Beta",
    "iconName": "notifications"
  },
  {
    "title": "SLA Progress Indicator",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/sla-progress",
    "keywords": "sla progress indicator feedback & status  label total elapsed unit variant paused completed thresholds status description action tokens wcag accessibility",
    "description": "Tracks time remaining against a Right to Service Act guarantee. Three variants, five states, always a concrete number — never a vague",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "Spacing",
    "section": "Foundations",
    "href": "/design-system/foundations/spacing",
    "keywords": "spacing foundations how spacing works the scale four families, one ladder tokens do &amp; don&apos;t inline stack padding section tokens wcag accessibility",
    "description": "The SAMAVESH spacing scale — an 8px base grid that keeps layout rhythm consistent across every MoSJE site and portal.",
    "type": "foundation",
    "badge": "Stable",
    "iconName": "palette"
  },
  {
    "title": "Sparkline",
    "section": "Data Display",
    "href": "/design-system/components/data-display/sparkline",
    "keywords": "sparkline data display overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance  tokens wcag accessibility",
    "description": "Miniature inline trend curve embedded within table rows and metric cards without axis chrome.",
    "type": "component",
    "badge": "Beta",
    "iconName": "bar_chart"
  },
  {
    "title": "Stepper",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/stepper",
    "keywords": "stepper feedback & status overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "Multi-step form wizard progression bar showing completed, current, and upcoming stages of complex citizen applications.",
    "type": "component",
    "badge": "Stable",
    "iconName": "notifications"
  },
  {
    "title": "Tabs",
    "section": "Navigation",
    "href": "/design-system/components/navigation/tabs",
    "keywords": "tabs navigation live demo 1. import 2. usage 3. indicator and track pair — only two of six combinations are correct 4. size 5. icons, badges and disabled tabs 10. guidelines 6. writing tab labels 7. props 8. tokens 9. accessibility Mouse / pen Keyboard Screen reader Touch tabs active onChange idBase ariaLabel indicator size track orientation divider overflow tokens wcag accessibility",
    "description": "The SAMAVESH Tabs / TabPanel — accessible tabbed navigation for non-linear sections, implementing the WAI-ARIA Tabs pattern with roving tabindex and Arrow/Home/End keyboard support.",
    "type": "component",
    "badge": "Beta",
    "iconName": "navigation"
  },
  {
    "title": "Tabs Overflow",
    "section": "Navigation",
    "href": "/design-system/components/navigation/tabs-overflow",
    "keywords": "tabs overflow navigation overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "Adaptive horizontal tab bar that automatically collapses trailing tabs into a \\",
    "type": "component",
    "badge": "Beta",
    "iconName": "navigation"
  },
  {
    "title": "Textarea",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/textarea",
    "keywords": "textarea forms & inputs playground 1. usage 2. code example 4. api reference 3. accessibility (a11y) invalid rows ...rest tokens wcag accessibility",
    "description": "A multi-line text input field used for long-form content.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Ticker",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/ticker",
    "keywords": "ticker feedback & status playground 1. usage 2. orientation — two shapes 3. behaviour by width 4. states 5. motion 6. divergences from the figma frame 7. code example 8. api reference 9. accessibility (a11y) items label icon action orientation height rows interval autoplay linkAs className ...rest tokens wcag accessibility",
    "description": "Recent announcements in two shapes: the full-bleed bar under the masthead, and the stacked panel that scrolls them.",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "Toast",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/toast",
    "keywords": "toast feedback & status playground 1. usage 2. code example 4. api reference 3. accessibility (a11y) message variant tokens wcag accessibility",
    "description": "Toasts are transient notifications used to provide brief, non-interruptive feedback about an operation.",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "Toggle",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/toggle",
    "keywords": "toggle forms & inputs playground 1. usage 2. sizes 3. code example 5. api reference 4. accessibility (a11y) checked onChange label size ...rest tokens wcag accessibility",
    "description": "An accessible switch component for toggling a setting on or off.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Tooltip",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/tooltip",
    "keywords": "tooltip feedback & status playground 1. usage 2. code example 4. api reference 3. accessibility (a11y) content children side sideOffset delay disabled duplicatesTriggerName tokens wcag accessibility",
    "description": "Tooltips display informative text when users hover over, focus on, or tap an element. They are small, contextual overlays.",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "Typography",
    "section": "Foundations",
    "href": "/design-system/foundations/typography",
    "keywords": "typography foundations why two typefaces line height for indic scripts do &amp; don&rsquo;t the rules, and where each one comes from the alias family that lied, and why it is gone non-negotiable, because these are government services where these numbers come from  tokens wcag accessibility",
    "description": "SAMAVESH typography — one 21-role scale rendered on two surfaces (Website, Portal), fluid across every viewport, and drawn for both English and हिन्दी.",
    "type": "foundation",
    "badge": "Stable",
    "iconName": "palette"
  },
  {
    "title": "UX4G Accessibility Widget",
    "section": "Utilities",
    "href": "/design-system/components/utilities/ux4g-accessibility-widget",
    "keywords": "ux4g accessibility widget utilities overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "The canonical Government of India (MeitY / UX4G) floating accessibility toolbar providing text resizing, high contrast, dyslexia fonts, and screen reader helpers.",
    "type": "component",
    "badge": "Stable",
    "iconName": "build"
  },
  {
    "title": "Vertical Timeline",
    "section": "Data Display",
    "href": "/design-system/components/data-display/vertical-timeline",
    "keywords": "vertical timeline data display overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance  tokens wcag accessibility",
    "description": "Historical event chronology component displaying ministry milestones, scheme release histories, and legal amendment timelines.",
    "type": "component",
    "badge": "New",
    "iconName": "bar_chart"
  },
  {
    "title": "Visitor Counter",
    "section": "Data Display",
    "href": "/design-system/components/data-display/visitor-counter",
    "keywords": "visitor counter data display overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance  tokens wcag accessibility",
    "description": "Statutory Government of India website footer element displaying total cumulative citizen visits in seven-segment digit style.",
    "type": "component",
    "badge": "Beta",
    "iconName": "bar_chart"
  },
  {
    "title": "What is SAMAVESH?",
    "section": "Getting Started",
    "href": "/design-system",
    "keywords": "what is samavesh? getting started  Button Card Badge Input / Textarea Select Form Field Accessibility Widget Color Mode tokens wcag accessibility",
    "description": "SAMAVESH (समावेश, inclusion) is the shared design language for the MoSJE digital estate — 13 websites and 20 portals serving 33+ organisations and schemes.",
    "type": "page",
    "iconName": "widgets"
  },
  {
    "title": "Wizard",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/wizard",
    "keywords": "wizard forms & inputs playground 1. usage 2. code example 4. api reference 3. accessibility (a11y) steps current onBack onNext onSubmit error errorRef children tokens wcag accessibility",
    "description": "A shared multi-step form shell with a Stepper, navigation controls, and accessibility wiring.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Zone Switcher",
    "section": "Navigation",
    "href": "/design-system/components/navigation/zone-switcher",
    "keywords": "zone switcher navigation overview & purpose usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance keyboard navigation  tokens wcag accessibility",
    "description": "Top utility control allowing users to switch between the Public Website, Officer Portal Zone, and Design System documentation.",
    "type": "component",
    "badge": "Stable",
    "iconName": "navigation"
  }
];
