/**
 * Generated by scripts/build-docs-search-index.mjs.
 * DO NOT EDIT MANUALLY.
 * Run `node scripts/build-docs-search-index.mjs` to regenerate.
 */

export interface SearchEntry {
  title: string;
  section: string;
  href: string;
  keywords: string;
  description: string;
  type: "foundation" | "component" | "pattern" | "resource" | "page";
  badge?: "Stable" | "Beta" | "Alpha" | "New" | "Proposed" | "Deprecated";
  iconName: string;
}

export const SEARCH_DATA: SearchEntry[] = [
  {
    "title": "Aadhaar Input — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/aadhaar-input",
    "keywords": "aadhaar input — design system forms & inputs masking and privacy example notes  tokens wcag accessibility",
    "description": "A twelve-digit Aadhaar field, grouped as you type, Verhoeff-checked, and masked to its last four digits by default.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Accessibility",
    "section": "Foundations",
    "href": "/design-system/foundations/accessibility",
    "keywords": "accessibility foundations wcag 2.1 aa + gigw the four pour principles the accessibility widget what it provides how to integrate behaviour &amp; theming checklist for designers checklist for developers baseline requirements how to test built-in by default src tokens wcag accessibility",
    "description": "The accessibility baseline for SAMAVESH — WCAG 2.1 AA + GIGW, the POUR principles, and practical checklists for designers and developers.",
    "type": "foundation",
    "badge": "Stable",
    "iconName": "accessibility"
  },
  {
    "title": "Accessibility Bar — Design System",
    "section": "Utilities",
    "href": "/design-system/components/utilities/accessibility-bar",
    "keywords": "accessibility bar — design system utilities tone is not a prop text size do and don&rsquo;t usage interaction states layout (content width) token map what happens on a phone  tokens wcag accessibility",
    "description": "The government top utility bar (UX4G / GIGW) — the Government of India link and the accessibility controls that open every page: skip to content, text size, accessibility, language.",
    "type": "component",
    "iconName": "build"
  },
  {
    "title": "Accordion — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/accordion",
    "keywords": "accordion — design system data display anatomy and state writing the headers example keyboard Accordion children Accordion className tokens wcag accessibility",
    "description": "Collapsible disclosure sections for frequently asked questions, eligibility criteria and application guidelines.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Account Menu — Design System",
    "section": "Navigation",
    "href": "/design-system/components/navigation/account-menu",
    "keywords": "account menu — design system navigation two modes, and the difference must be visible the one round thing in the masthead is the person writing the items headeraccount and accountmenuitem example keyboard HeaderAccount · name HeaderAccount · email HeaderAccount · role HeaderAccount · avatarSrc AccountMenuItem · label AccountMenuItem · onSelect AccountMenuItem · icon AccountMenuItem · danger Asha Ramesh Asha Ramesh tokens wcag accessibility",
    "description": "The signed-in account control in the portal masthead. Two modes: a static identity block, or a full APG menu button.",
    "type": "component",
    "iconName": "navigation"
  },
  {
    "title": "Account Prompt — Design System",
    "section": "Auth & Dashboard",
    "href": "/design-system/components/auth/account-prompt",
    "keywords": "account prompt — design system auth & dashboard   tokens wcag accessibility",
    "description": "The registration route at the foot of a sign-in form.",
    "type": "component",
    "iconName": "lock"
  },
  {
    "title": "Action Banner — Design System",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/action-banner",
    "keywords": "action banner — design system feedback & status two variants, one content model example fitting the page outline  tokens wcag accessibility",
    "description": "A call to action at the end of a section: a title, an optional sentence, and one control. Two variants share one content model.",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "AI design context (design.md)",
    "section": "Resources",
    "href": "/design-system/resources/design-context",
    "keywords": "ai design context (design.md) resources   tokens wcag accessibility",
    "description": "The authoritative design contract an AI agent reads before building UI on SAMAVESH — token vocabulary, theming axes, component inventory, and the non-negotiable rules. Rendered from the source design.md.",
    "type": "resource",
    "iconName": "menu_book"
  },
  {
    "title": "Alert — Design System",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/alert",
    "keywords": "alert — design system feedback & status the four statuses anatomy example how it is announced  tokens wcag accessibility",
    "description": "A standing message about the state of the page or the task: a status colour, an icon, a title and a sentence. It stays until the condition changes or the reader dismisses it.",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "App Shell — Design System",
    "section": "Layout",
    "href": "/design-system/components/layout/app-shell",
    "keywords": "app shell — design system layout anatomy never subtract a chrome height from the viewport the sidebar becomes a drawer, not a narrow column example landmarks and the skip link Asha Ramesh tokens wcag accessibility",
    "description": "The portal page skeleton: chrome, sidebar, content. Chrome rows are auto and the body row is 1fr, so nothing subtracts a chrome height from the viewport.",
    "type": "component",
    "iconName": "view_quilt"
  },
  {
    "title": "App Switcher Panel — Design System",
    "section": "Navigation",
    "href": "/design-system/components/navigation/app-switcher-panel",
    "keywords": "app switcher panel — design system navigation content, not chrome the registry is the source, and it has two layers grouping and order appentry example keyboard path group category desc org status newTab tokens wcag accessibility",
    "description": "The searchable content of the SAMAVESH app switcher: a current-app indicator, a search box, and the grouped list of estate destinations.",
    "type": "component",
    "iconName": "navigation"
  },
  {
    "title": "Approval Timeline — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/approval-timeline",
    "keywords": "approval timeline — design system data display show the whole chain, including what went back order and the pending step example what a screen reader gets ApprovalTimelineEvent.at ApprovalTimelineEvent.actorDisplayName ApprovalTimelineEvent.actorRoleLabel ApprovalTimelineEvent.action ApprovalTimelineEvent.remarks tokens wcag accessibility",
    "description": "The full history of a multi-tier approval chain: who acted, in what role, when, and what they said when returning something for correction.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Area Chart — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/area-chart",
    "keywords": "area chart — design system data display the states it draws overlap is the limit example what a screen reader gets Disbursed tokens wcag accessibility",
    "description": "A filled trend over an ordered axis, for cumulative readings such as funds disbursed to date or enrolment reached.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Auth Divider — Design System",
    "section": "Auth & Dashboard",
    "href": "/design-system/components/auth/auth-divider",
    "keywords": "auth divider — design system auth & dashboard   tokens wcag accessibility",
    "description": "A labelled rule separating two ways of signing in.",
    "type": "component",
    "iconName": "lock"
  },
  {
    "title": "Avatar — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/avatar",
    "keywords": "avatar — design system data display the fallback order four sizes, two shapes example the name is not automatic  tokens wcag accessibility",
    "description": "A person",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Axis — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/axis",
    "keywords": "axis — design system data display indian digit grouping is the default crowding, truncation and the unit example why the axis is hidden formatIndian(value) formatCompact(value) formatPercent(value, digits?) GridTick.pos GridTick.value Gridlines({ ticks, x0, x1, format, labelGutter }) XAxisLabels({ labels, x, y, rotate, maxChars }) tokens wcag accessibility",
    "description": "The gridlines, tick labels and number formatters every chart in the catalogue draws its scale with, including the Indian digit grouping.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Badge — Design System",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/badge",
    "keywords": "badge — design system feedback & status six roles, two sizes, two fills writing the label example naming a badge that has little text  tokens wcag accessibility",
    "description": "A small pill that annotates something with a status, a count or a category. It carries colour meaning and is never interactive.",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "Band — Design System",
    "section": "Layout",
    "href": "/design-system/components/layout/band",
    "keywords": "band — design system layout the composition is always band, container, content choosing a tone example naming the region  tokens wcag accessibility",
    "description": "A full-bleed horizontal section. The tone paints edge to edge while the Container inside holds the content column.",
    "type": "component",
    "iconName": "view_quilt"
  },
  {
    "title": "Bar Chart — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/bar-chart",
    "keywords": "bar chart — design system data display the states it draws orientation, grouping and stacking example what a screen reader gets Target Released tokens wcag accessibility",
    "description": "Vertical columns or horizontal bars comparing a figure across states, districts and scheme categories, in one series or several.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Bot Check — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/bot-check",
    "keywords": "bot check — design system forms & inputs why this is not a captcha what to reach for, in order the states, and the one that draws nothing the escape hatch is required, on purpose example notes  tokens wcag accessibility",
    "description": "The estate",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Brand Glyph — Design System",
    "section": "Utilities",
    "href": "/design-system/components/utilities/brand-glyph",
    "keywords": "brand glyph — design system utilities   tokens wcag accessibility",
    "description": "A third-party brand mark, optically normalised against its siblings.",
    "type": "component",
    "iconName": "build"
  },
  {
    "title": "Brand Lockup — Design System",
    "section": "Navigation",
    "href": "/design-system/components/navigation/brand-lockup",
    "keywords": "brand lockup — design system navigation the four rows compact and inverse the mark itself brandlines example one link, one name department ministry org tokens wcag accessibility",
    "description": "The National Emblem and the government text stack, as one home link. Always the National Emblem — never an invented mark.",
    "type": "component",
    "iconName": "navigation"
  },
  {
    "title": "Breadcrumb — Design System",
    "section": "Navigation",
    "href": "/design-system/components/navigation/breadcrumb",
    "keywords": "breadcrumb — design system navigation example items[].label items[].href tokens wcag accessibility",
    "description": "The trail showing where a page sits, with the current page as the last, non-interactive crumb.",
    "type": "component",
    "iconName": "navigation"
  },
  {
    "title": "Bullet Chart — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/bullet-chart",
    "keywords": "bullet chart — design system data display example why the bands are grey  tokens wcag accessibility",
    "description": "A measure against its target on one line: the value as a bar, the target as a tick across it.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Button",
    "section": "Actions",
    "href": "/design-system/components/actions/button",
    "keywords": "button actions purpose anatomy variants states sizes and touch content and voice two deprecated appearances, and one that is gone installation and import example tokens consumed in figma keyboard evidence  tokens wcag accessibility",
    "description": "A Button triggers an action within the system — submitting a form, confirming a dialog, or running a command. The most-used interactive atom in the SAMAVESH design system.",
    "type": "component",
    "iconName": "widgets"
  },
  {
    "title": "Button Group — Design System",
    "section": "Actions",
    "href": "/design-system/components/actions/button-group",
    "keywords": "button group — design system actions   tokens wcag accessibility",
    "description": "Related actions, kept together and kept apart.",
    "type": "component",
    "iconName": "widgets"
  },
  {
    "title": "Captcha Field — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/captcha-field",
    "keywords": "captcha field — design system forms & inputs read this before adding one example notes  tokens wcag accessibility",
    "description": "The legacy security-check field: a challenge, a refresh control and an answer. Retained for one existing portal, and an accessibility risk on any new one.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Card — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/card",
    "keywords": "card — design system data display composition variants and orientation one primary action example clickable cards wrap, they do not listen headings and focus CardHeader children CardBody children CardFooter children CardTitle children CardSubtitle children tokens wcag accessibility",
    "description": "A surface that groups related content — a header, a body and a footer — so a scheme summary, a metric or a news item reads as one block.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Card Skeleton — Design System",
    "section": "Auth & Dashboard",
    "href": "/design-system/components/dashboard/card-skeleton",
    "keywords": "card skeleton — design system auth & dashboard   tokens wcag accessibility",
    "description": "A shaped loading placeholder for a dashboard card.",
    "type": "component",
    "iconName": "lock"
  },
  {
    "title": "Card State — Design System",
    "section": "Auth & Dashboard",
    "href": "/design-system/components/dashboard/card-state",
    "keywords": "card state — design system auth & dashboard   tokens wcag accessibility",
    "description": "What a card shows when it has no figures to show.",
    "type": "component",
    "iconName": "lock"
  },
  {
    "title": "Changelog",
    "section": "Resources",
    "href": "/design-system/resources/changelog",
    "keywords": "changelog resources   tokens wcag accessibility",
    "description": "Every release of the SAMAVESH design system — what was added, changed, and fixed in each version.",
    "type": "resource",
    "iconName": "menu_book"
  },
  {
    "title": "Chart Card — Design System",
    "section": "Auth & Dashboard",
    "href": "/design-system/components/dashboard/chart-card",
    "keywords": "chart card — design system auth & dashboard six reasons a card has nothing to draw the skeleton promises the shape a card that cannot show its data must not talk about its data example what a screen reader hears  tokens wcag accessibility",
    "description": "The titled container a dashboard chart sits in. It owns the header, the grid span, the download control and every state the chart can be in — loading, empty, filtered to nothing, failed.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Chart Frame — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/chart-frame",
    "keywords": "chart frame — design system data display what it guarantees one place, not seventeen proportions, not a placeholder height example the table is the reading ChartState ChartStateFigure tokens wcag accessibility",
    "description": "The shell every chart renders through: the accessible SVG wrapper, the screen-reader data table, and the one place the five chart states are drawn.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Chatbot — Design System",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/chatbot",
    "keywords": "chatbot — design system feedback & status in the figma library anatomy states placement and layering motion prototype writing the script example a dialog, but deliberately not a modal one the log is a live region  tokens wcag accessibility",
    "description": "Samajik Sahayak, the estate",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "Chatbot Mascot — Design System",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/chatbot-mascot",
    "keywords": "chatbot mascot — design system feedback & status why it is two nodes two sizes, one with the ring the disc follows the brand motion example decorative unless you name it  tokens wcag accessibility",
    "description": "The Samajik Sahayak assistant mark: a brand-coloured disc carrying the mascot, and an optional white ring carrying the bilingual wordmark.",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "Checkbox — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/checkbox",
    "keywords": "checkbox — design system forms & inputs example keyboard  tokens wcag accessibility",
    "description": "A checkbox selects one or more items from a set, or turns a single option on or off. Supports the mixed state a “select all” control needs.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Chip — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/chip",
    "keywords": "chip — design system forms & inputs tone and size example keyboard  tokens wcag accessibility",
    "description": "A compact pill used as a filter toggle, a removable tag, a dropdown trigger or a static category, with an optional count.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Color — Foundations",
    "section": "Foundations",
    "href": "/design-system/foundations/color",
    "keywords": "color — foundations foundations   tokens wcag accessibility",
    "description": "Colour is never the only carrier of meaning. Pair it with an icon, a label, a pattern or a position.",
    "type": "foundation",
    "badge": "Stable",
    "iconName": "palette"
  },
  {
    "title": "Color Mode Provider — Design System",
    "section": "Utilities",
    "href": "/design-system/components/utilities/color-mode-provider",
    "keywords": "color mode provider — design system utilities   tokens wcag accessibility",
    "description": "Supplies the brand palette every component reads from.",
    "type": "component",
    "iconName": "build"
  },
  {
    "title": "Combo Chart — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/combo-chart",
    "keywords": "combo chart — design system data display the states it draws two axes, two names example what a screen reader gets Target Utilisation tokens wcag accessibility",
    "description": "Bars and a line on one canvas with two independent y axes, for a count and a rate that share a period but not a scale.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Combobox — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/combobox",
    "keywords": "combobox — design system forms & inputs example how it differs from filter select  tokens wcag accessibility",
    "description": "A text field that filters a long list as the reader types, then commits one of its options.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Consent Line — Design System",
    "section": "Auth & Dashboard",
    "href": "/design-system/components/auth/consent-line",
    "keywords": "consent line — design system auth & dashboard   tokens wcag accessibility",
    "description": "The standing consent sentence under every authentication form.",
    "type": "component",
    "iconName": "lock"
  },
  {
    "title": "Container — Design System",
    "section": "Layout",
    "href": "/design-system/components/layout/container",
    "keywords": "container — design system layout the cap is a ladder, not a number choosing a size example landmarks  tokens wcag accessibility",
    "description": "The centred content column. Applies the estate content cap and the responsive side margin together, because they are one rule.",
    "type": "component",
    "iconName": "view_quilt"
  },
  {
    "title": "Content Nav — Design System",
    "section": "Navigation",
    "href": "/design-system/components/navigation/content-nav",
    "keywords": "content nav — design system navigation why this is not sidebar nav  tokens wcag accessibility",
    "description": "The grouped section index beside a long content page.",
    "type": "component",
    "iconName": "navigation"
  },
  {
    "title": "Contributing",
    "section": "Resources",
    "href": "/design-system/resources/contributing",
    "keywords": "contributing resources propose a new component add or change a design token run the system locally pull-request checklist  tokens wcag accessibility",
    "description": "How to contribute to SAMAVESH — propose a new component, add or change a design token, run the system locally, and pass the pull-request checklist.",
    "type": "resource",
    "iconName": "menu_book"
  },
  {
    "title": "Dashboard Archetypes",
    "section": "Data Visualisation",
    "href": "/design-system/data-visualisation/archetypes",
    "keywords": "dashboard archetypes data visualisation   tokens wcag accessibility",
    "description": "Five named dashboard boards — scheme performance, geographic distribution, application pipeline, compliance status and beneficiary demographics — composed from the SAMAVESH visualisation layer.",
    "type": "pattern",
    "iconName": "bar_chart"
  },
  {
    "title": "Dashboard Grid — Design System",
    "section": "Auth & Dashboard",
    "href": "/design-system/components/dashboard/dashboard-grid",
    "keywords": "dashboard grid — design system auth & dashboard spans, and the one breakpoint close every row example  tokens wcag accessibility",
    "description": "The 12-column grid a portal dashboard is laid out on. Children declare their own width with a span prop; every child is full width below 768px.",
    "type": "component",
    "iconName": "lock"
  },
  {
    "title": "Data Table — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/data-table",
    "keywords": "data table — design system data display one table across the estate pagination, headers and alignment empty and filtered to nothing are different sentences example structure the pager the open gap DataTableColumn.key DataTableColumn.header DataTableColumn.render DataTableColumn.className DataTableColumn.exportValue DataTableColumn.noExport tokens wcag accessibility",
    "description": "Structured rows and columns with built-in pagination and a screen-reader caption, for scheme listings, applicant directories and transaction histories.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Data Visualisation",
    "section": "Data Visualisation",
    "href": "/design-system/data-visualisation",
    "keywords": "data visualisation data visualisation   tokens wcag accessibility",
    "description": "Every chart, metric, table and container in the SAMAVESH data-visualisation layer, rendered live against government data — the reference both designers and developers benchmark against.",
    "type": "page",
    "iconName": "bar_chart"
  },
  {
    "title": "Date Picker — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/date-picker",
    "keywords": "date picker — design system forms & inputs example  tokens wcag accessibility",
    "description": "A typed date field in dd/mm/yyyy, with a calendar as the second way in. The text input is the primary control.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Declaration Checkbox — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/declaration-checkbox",
    "keywords": "declaration checkbox — design system forms & inputs why it is not a checkbox example notes  tokens wcag accessibility",
    "description": "The statutory certification block that closes a government form: a bordered panel carrying the declaration text with a single required checkbox bound to it.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Demo Accounts Panel — Design System",
    "section": "Utilities",
    "href": "/design-system/components/utilities/demo-accounts-panel",
    "keywords": "demo accounts panel — design system utilities   tokens wcag accessibility",
    "description": "The shared credentials list used by the demo tooling.",
    "type": "component",
    "iconName": "build"
  },
  {
    "title": "Demo Dock — Design System",
    "section": "Utilities",
    "href": "/design-system/components/utilities/demo-dock",
    "keywords": "demo dock — design system utilities   tokens wcag accessibility",
    "description": "The floating demo console for the estate.",
    "type": "component",
    "iconName": "build"
  },
  {
    "title": "Demo Fab — Design System",
    "section": "Utilities",
    "href": "/design-system/components/utilities/demo-fab",
    "keywords": "demo fab — design system utilities   tokens wcag accessibility",
    "description": "The older, per-page demo credentials control.",
    "type": "component",
    "iconName": "build"
  },
  {
    "title": "Density",
    "section": "Foundations",
    "href": "/design-system/foundations/density",
    "keywords": "density foundations side by side when to use compact when not to use compact how to activate it tokens  tokens wcag accessibility",
    "description": "Comfortable and compact density modes — how SAMAVESH adapts control sizing for spacious public forms and data-dense portals.",
    "type": "foundation",
    "badge": "Stable",
    "iconName": "palette"
  },
  {
    "title": "Design tokens",
    "section": "Resources",
    "href": "/design-system/resources/tokens",
    "keywords": "design tokens resources   tokens wcag accessibility",
    "description": "Every SAMAVESH design token and its resolved value, rendered from the generated DTCG export — colors with live swatches, plus spacing, radius, type, shadow, and motion.",
    "type": "resource",
    "iconName": "menu_book"
  },
  {
    "title": "Divider — Design System",
    "section": "Layout",
    "href": "/design-system/components/layout/divider",
    "keywords": "divider — design system layout why it exists orientation tone follows the surface, not the taste leave the length alone do and don&apos;t example token map migration status decorative is the default, and that is a decision  tokens wcag accessibility",
    "description": "The estate",
    "type": "component",
    "iconName": "view_quilt"
  },
  {
    "title": "Document Library — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/document-library",
    "keywords": "document library — design system data display   tokens wcag accessibility",
    "description": "One shelf for everything a body publishes.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Donut Chart — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/donut-chart",
    "keywords": "donut chart — design system data display two modes, one component the states it draws the centre is the reading example what a screen reader gets  tokens wcag accessibility",
    "description": "A ring in two modes: segments that make up a whole, or a single figure against a target, with the total stated in the middle.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Elevation",
    "section": "Foundations",
    "href": "/design-system/foundations/elevation",
    "keywords": "elevation foundations the three levels when to use each tokens guidance  tokens wcag accessibility",
    "description": "Shadow tokens that give SAMAVESH surfaces a sense of depth — from pressed controls to floating modals.",
    "type": "foundation",
    "badge": "Stable",
    "iconName": "layers"
  },
  {
    "title": "Empty State — Design System",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/empty-state",
    "keywords": "empty state — design system feedback & status empty is not the same as filtered to nothing writing the copy example replacing a region, not announcing an event  tokens wcag accessibility",
    "description": "The answer a reader gets when a list, table or dashboard has nothing to show: what is absent, why, and what they can do next.",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "Error Summary — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/error-summary",
    "keywords": "error summary — design system forms & inputs example why each entry focuses the control  tokens wcag accessibility",
    "description": "The list at the top of a form that failed validation, naming every problem in field order and linking each one to its control.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Error View — Design System",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/error-view",
    "keywords": "error view — design system feedback & status three ways back, in order the four presets diagnostics are not for citizens example it owns the page&apos;s h1 the search and the controls  tokens wcag accessibility",
    "description": "The full-page state for 404, 500, 403 and maintenance: what happened, a way back, a search, and the destinations most citizens were looking for.",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "Fact Strip — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/fact-strip",
    "keywords": "fact strip — design system data display   tokens wcag accessibility",
    "description": "The row of standing facts under a page hero.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Filter Bar — Design System",
    "section": "Auth & Dashboard",
    "href": "/design-system/components/dashboard/filter-bar",
    "keywords": "filter bar — design system auth & dashboard active filters stay visible segmented control segmentedcontrol props example  tokens wcag accessibility",
    "description": "The row of controls that sits above a dashboard and decides what the cards below it show. Layout only — every control inside it keeps its own state.",
    "type": "component",
    "iconName": "lock"
  },
  {
    "title": "Filter Select — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/filter-select",
    "keywords": "filter select — design system forms & inputs example keyboard  tokens wcag accessibility",
    "description": "The compact dashboard filter, as a real listbox. Select remains the answer for a form field; this is for a filter row.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Flask Icon — Design System",
    "section": "Utilities",
    "href": "/design-system/components/utilities/flask-icon",
    "keywords": "flask icon — design system utilities   tokens wcag accessibility",
    "description": "The demo tooling",
    "type": "component",
    "iconName": "build"
  },
  {
    "title": "Footer — Design System",
    "section": "Navigation",
    "href": "/design-system/components/navigation/footer",
    "keywords": "footer — design system navigation what this footer is not keep the width in step with the header footerlink example the contentinfo landmark label href onClick tokens wcag accessibility",
    "description": "The slim navy app-shell footer: the NeGD and MeitY credit line, plus optional policy links.",
    "type": "component",
    "iconName": "navigation"
  },
  {
    "title": "Form Card — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/form-card",
    "keywords": "form card — design system forms & inputs why it exists example notes  tokens wcag accessibility",
    "description": "The sibling of Form Section: the same card chrome and section title, with an arbitrary body instead of a field grid.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Form Field — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/form-field",
    "keywords": "form field — design system forms & inputs the render prop, in plain english example notes  tokens wcag accessibility",
    "description": "The molecule that ties a control to its label, hint and error message, and wires every accessibility attribute through a render prop.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Form Section — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/form-section",
    "keywords": "form section — design system forms & inputs choosing the column count example notes  tokens wcag accessibility",
    "description": "A titled surface card wrapping a responsive one-, two- or three-column field grid. The shared form-layout primitive across the estate.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Funnel Chart — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/funnel-chart",
    "keywords": "funnel chart — design system data display the states it draws order is the argument example what a screen reader gets FunnelStage.label FunnelStage.value FunnelStage.color tokens wcag accessibility",
    "description": "The stages of one workflow in order, each bar sized by its share of the first, with the carry-through stated beside it.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Gauge — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/gauge",
    "keywords": "gauge — design system data display the states it draws the scale and the unit example what a screen reader gets  tokens wcag accessibility",
    "description": "One figure read against a scale, drawn as an arc with the value in the middle — a compliance rate, an occupancy against a sanctioned total.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Geo Photo Input — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/geo-photo-input",
    "keywords": "geo photo input — design system forms & inputs where the location comes from example notes  tokens wcag accessibility",
    "description": "An evidence-photograph control that reads coordinates from EXIF, falls back to the device",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Governance",
    "section": "Resources",
    "href": "/design-system/resources/governance",
    "keywords": "governance resources the component lifecycle proposing a new component (the rfc process) versioning policy (semver) deprecation window  tokens wcag accessibility",
    "description": "How SAMAVESH is governed — the component lifecycle, the RFC process for proposing components, our semantic versioning policy, and the deprecation window.",
    "type": "resource",
    "badge": "Proposed",
    "iconName": "menu_book"
  },
  {
    "title": "Grid — Design System",
    "section": "Layout",
    "href": "/design-system/components/layout/grid",
    "keywords": "grid — design system layout twelve tracks at every width gutters are the grid&apos;s, not the cell&apos;s griditem example reading order  tokens wcag accessibility",
    "description": "The twelve-column layout grid, as a component. Twelve tracks at every breakpoint; a child spans more of them on a small screen.",
    "type": "component",
    "iconName": "view_quilt"
  },
  {
    "title": "Grid Item — Design System",
    "section": "Layout",
    "href": "/design-system/components/layout/grid-item",
    "keywords": "grid item — design system layout   tokens wcag accessibility",
    "description": "One cell of a Grid.",
    "type": "component",
    "iconName": "view_quilt"
  },
  {
    "title": "Heatmap — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/heatmap",
    "keywords": "heatmap — design system data display the states it draws sequential or diverging, never rainbow always publish the key example what a screen reader gets  tokens wcag accessibility",
    "description": "A matrix of two categorical axes whose cells are shaded by value, for spotting where a figure concentrates across states and periods.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Icon — Design System",
    "section": "Utilities",
    "href": "/design-system/components/utilities/icon",
    "keywords": "icon — design system utilities one font, four axes load the font once example labelled or hidden — there is no third option  tokens wcag accessibility",
    "description": "A Material Symbols Rounded glyph — the estate",
    "type": "component",
    "iconName": "build"
  },
  {
    "title": "Icon Button — Design System",
    "section": "Actions",
    "href": "/design-system/components/actions/icon-button",
    "keywords": "icon button — design system actions   tokens wcag accessibility",
    "description": "A Button whose whole label is its icon.",
    "type": "component",
    "iconName": "widgets"
  },
  {
    "title": "Iconography",
    "section": "Foundations",
    "href": "/design-system/foundations/iconography",
    "keywords": "iconography foundations one component, any icon the {icon_catalogue.length} icons in the starter set seven sizes — dbim&rsquo;s four, plus what interface work needs weight 300 is the style named light almost nothing needs to be a vector an icon is never the only signal the figma property is the code prop  tokens wcag accessibility",
    "description": "The SAMAVESH icon system — one component holding any Material Symbols Rounded glyph, at weight 300, on a seven-step size scale.",
    "type": "foundation",
    "badge": "Stable",
    "iconName": "category"
  },
  {
    "title": "Identity Inputs — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/identity-inputs",
    "keywords": "identity inputs — design system forms & inputs the three controls examples ux4g parity AadhaarInput · value AadhaarInput · onValueChange AadhaarInput · mask AadhaarInput · invalid OtpInput · value OtpInput · onValueChange OtpInput · label OtpInput · length OtpInput · onComplete OtpInput · invalid PanInput · value PanInput · onValueChange PanInput · invalid tokens wcag accessibility",
    "description": "The three Indian identity controls every MoSJE service journey needs: a Verhoeff-checked, masked-by-default Aadhaar field, a six-box OTP input with paste and SMS autofill, and a PAN field that validates the holder-type character.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Illustration",
    "section": "Foundations",
    "href": "/design-system/foundations/illustration",
    "keywords": "illustration foundations three tiers, one geometry why no illustration here depicts a person four ink layers the set adding a scene Spot Scene Hero tokens wcag accessibility",
    "description": "The SAMAVESH drawn language — one geometry at three sizes, four tokenised ink layers, and the reason no illustration in this estate depicts a person.",
    "type": "foundation",
    "badge": "Stable",
    "iconName": "palette"
  },
  {
    "title": "India Bubble Map — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/india-bubble-map",
    "keywords": "india bubble map — design system data display   tokens wcag accessibility",
    "description": "One circle per state, area proportional to the value.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "India Map — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/india-map",
    "keywords": "india map — design system data display the states it draws boundaries and names example what a screen reader gets IndiaMapDatum.state IndiaMapDatum.value tokens wcag accessibility",
    "description": "A state-level choropleth of India, shading each state by its figure, with a legend and a screen-reader table of every value.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "India Point Map — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/india-point-map",
    "keywords": "india point map — design system data display   tokens wcag accessibility",
    "description": "Real coordinates on the national outline.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Input — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/input",
    "keywords": "input — design system forms & inputs adornments example notes  tokens wcag accessibility",
    "description": "A single-line text field built on the native input element and styled on the token contract. Pair it with FormField so the label, hint and error wiring come for free.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "KPI Row — Design System",
    "section": "Auth & Dashboard",
    "href": "/design-system/components/dashboard/kpi-row",
    "keywords": "kpi row — design system auth & dashboard composition example  tokens wcag accessibility",
    "description": "A responsive row of MetricCard tiles carrying the headline figures at the top of a dashboard — funds released, beneficiaries, applications pending.",
    "type": "component",
    "iconName": "lock"
  },
  {
    "title": "Label — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/label",
    "keywords": "label — design system forms & inputs prefer form field example notes  tokens wcag accessibility",
    "description": "A standalone label element for controls that are not wrapped in a Form Field, matching the Form Field label exactly.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Layout Grid",
    "section": "Foundations",
    "href": "/design-system/foundations/layout-grid",
    "keywords": "layout grid foundations   tokens wcag accessibility",
    "description": "The SAMAVESH page container — a three-step cap with a margin ladder that steps with the cap, so content width only ever grows.",
    "type": "foundation",
    "badge": "Stable",
    "iconName": "grid_view"
  },
  {
    "title": "Legend — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/legend",
    "keywords": "legend — design system data display passing ontoggle changes what it is three swatches example keyboard LegendItem.label LegendItem.color LegendItem.id LegendItem.value LegendItem.swatch LegendItem.colors LegendItem.scale LegendItem.on tokens wcag accessibility",
    "description": "The key beside a chart. Decorative by default; passing onToggle turns every entry into a switch for its own series.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Lightbox — Design System",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/lightbox",
    "keywords": "lightbox — design system feedback & status anatomy give every item a caption example keyboard focus and the dialog&apos;s name  tokens wcag accessibility",
    "description": "A full-screen viewer for a gallery of images and video: prev and next, an item counter, a caption bar and a thumbnail strip.",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "Line Chart — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/line-chart",
    "keywords": "line chart — design system data display the states it draws series, dots and the y axis example what a screen reader gets Applications tokens wcag accessibility",
    "description": "A continuous trend over an ordered axis — applications by month, releases by quarter — for one series or several.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Live Region — Design System",
    "section": "Utilities",
    "href": "/design-system/components/utilities/live-region",
    "keywords": "live region — design system utilities there is nothing to design example why the message is not state polite, almost always useLiveRegion().ref useLiveRegion().announce tokens wcag accessibility",
    "description": "A visually hidden ARIA live region for announcing a change that moves no focus — “Filter applied, 12 results”, “3 records exported”, “Saved”.",
    "type": "component",
    "iconName": "build"
  },
  {
    "title": "Loader — Design System",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/loader",
    "keywords": "loader — design system feedback & status choosing a size example the label is the whole announcement  tokens wcag accessibility",
    "description": "A spinner for a wait whose result has no known shape, announced to assistive technology through a live region and a visually hidden label.",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "Masked Contact Row — Design System",
    "section": "Auth & Dashboard",
    "href": "/design-system/components/auth/masked-contact-row",
    "keywords": "masked contact row — design system auth & dashboard   tokens wcag accessibility",
    "description": "Confirms where a one-time code was sent, and offers the way back to change it.",
    "type": "component",
    "iconName": "lock"
  },
  {
    "title": "Media Gallery Input — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/media-gallery-input",
    "keywords": "media gallery input — design system forms & inputs empty, filling, full example notes  tokens wcag accessibility",
    "description": "A multi-file dropzone for images and video, with a thumbnail grid, captured video poster frames, and client-side type, size and capacity checks.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Media Upload — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/media-upload",
    "keywords": "media upload — design system forms & inputs the two states example notes  tokens wcag accessibility",
    "description": "A single-file dropzone with a click target, drag and drop, an inline preview, and client-side type and size checks.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Metric Card — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/metric-card",
    "keywords": "metric card — design system data display a figure that has not arrived the change needs a baseline format the figure before you pass it example what a screen reader gets  tokens wcag accessibility",
    "description": "One headline figure with its label and, where there is one, the change against a stated baseline — with real states for a figure that has not arrived.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Modal — Design System",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/modal",
    "keywords": "modal — design system feedback & status anatomy sizes use it sparingly example keyboard focus trap, escape and focus restore background scroll  tokens wcag accessibility",
    "description": "The shared accessible dialog: a backdrop, a focus trap, Escape to close and focus returned to the control that opened it.",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "Motion",
    "section": "Foundations",
    "href": "/design-system/foundations/motion",
    "keywords": "motion foundations duration scale easing live demo reduced motion tokens guidance  tokens wcag accessibility",
    "description": "Duration and easing for SAMAVESH — purposeful, fast and respectful of reduced-motion preferences.",
    "type": "foundation",
    "badge": "Stable",
    "iconName": "animation"
  },
  {
    "title": "Nav Sheet — Design System",
    "section": "Navigation",
    "href": "/design-system/components/navigation/nav-sheet",
    "keywords": "nav sheet — design system navigation three states, not three variants it slides from the right one search field, not two navitem and headersearchconfig example modal behaviour NavItem · label NavItem · href NavItem · active NavItem · external NavItem · disabled NavItem · children NavItem · columns HeaderSearchConfig · placeholder HeaderSearchConfig · onSearch HeaderSearchConfig · onQueryChange HeaderSearchConfig · suggestions HeaderSearchConfig · onSuggestionSelect tokens wcag accessibility",
    "description": "The mobile navigation overlay: a 344px sheet with its own brand lockup, the masthead",
    "type": "component",
    "iconName": "navigation"
  },
  {
    "title": "Navbar (Header) — Design System",
    "section": "Navigation",
    "href": "/design-system/components/section-templates/site-header",
    "keywords": "navbar (header) — design system navigation anatomy choosing a variant the portal variant the compact variant dropdowns and mega-menus scroll condense when the navigation runs out of room responsive content and voice the shapes the props carry example the parts, on their own reading the pinned height keyboard the skip link has two halves one accessibility mechanism, everywhere BrandLines · department BrandLines · ministry BrandLines · org NavItem · label / href NavItem · active NavItem · external NavItem · disabled NavItem · children NavItem · columns HeaderSearchConfig · placeholder HeaderSearchConfig · onSearch HeaderSearchConfig · onQueryChange HeaderSearchConfig · suggestions HeaderSearchConfig · onSuggestionSelect HeaderAccount · name / email / role tokens wcag accessibility",
    "description": "The SAMAVESH Navbar — one component, three variants. Three tiers: accessibility bar, brand row, navigation row, with a scroll condense that keeps the emblem on the same left edge.",
    "type": "component",
    "iconName": "navigation"
  },
  {
    "title": "Org Logo — Design System",
    "section": "Brand",
    "href": "/design-system/components/brand/org-logo",
    "keywords": "org logo — design system brand every mark the estate ships why one component owns every path figma parity, and what is still missing example  tokens wcag accessibility",
    "description": "Organisation and scheme marks in the estate",
    "type": "component",
    "iconName": "widgets"
  },
  {
    "title": "OTP Input — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/otp-input",
    "keywords": "otp input — design system forms & inputs the parts that are usually wrong example keyboard  tokens wcag accessibility",
    "description": "Six separate boxes for a one-time password, with paste, SMS autofill, arrow-key movement and a numbered box for every digit.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Page Header — Design System",
    "section": "Layout",
    "href": "/design-system/components/layout/page-header",
    "keywords": "page header — design system layout it hugs, and that is the point what belongs in the actions slot example one h1 per page  tokens wcag accessibility",
    "description": "The row every portal page opens with: title, meta line, actions. It hugs its content and carries no fixed height.",
    "type": "component",
    "iconName": "view_quilt"
  },
  {
    "title": "Page Patterns",
    "section": "Patterns",
    "href": "/design-system/resources/patterns",
    "keywords": "page patterns patterns  Akash Kumar tokens wcag accessibility",
    "description": "Approved page-level scaffolds for MoSJE portals and websites — Dashboard, Portal Login, Form Wizard, Data Tables, and Empty States.",
    "type": "pattern",
    "badge": "Stable",
    "iconName": "dashboard_customize"
  },
  {
    "title": "Pagination — Design System",
    "section": "Navigation",
    "href": "/design-system/components/navigation/pagination",
    "keywords": "pagination — design system navigation prefer links  tokens wcag accessibility",
    "description": "Moving through a set of results a page at a time, as real links wherever the page number belongs in the URL.",
    "type": "component",
    "iconName": "navigation"
  },
  {
    "title": "PAN Input — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/pan-input",
    "keywords": "pan input — design system forms & inputs the fourth character example notes  tokens wcag accessibility",
    "description": "A ten-character Permanent Account Number field that uppercases as you type and validates the holder-type character.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Password Input — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/password-input",
    "keywords": "password input — design system forms & inputs the details that matter example keyboard  tokens wcag accessibility",
    "description": "A password field with a reveal toggle that is a real button, names the action rather than the state, and suppresses the browser",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Password Strength Meter — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/password-strength-meter",
    "keywords": "password strength meter — design system forms & inputs advisory, not a gate example notes  tokens wcag accessibility",
    "description": "Four segments and a word, shown under a password the reader is creating. Advisory, never a gate, and never beside a password being entered.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Pie Chart — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/pie-chart",
    "keywords": "pie chart — design system data display the states it draws what a pie cannot do example what a screen reader gets  tokens wcag accessibility",
    "description": "Shares of a single whole, drawn as slices with a legend beside them. For two to four parts that differ plainly in size.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Portal Card — Design System",
    "section": "Navigation",
    "href": "/design-system/components/navigation/portal-card",
    "keywords": "portal card — design system navigation interactive specimen implementation &amp; guidelines when to use it, and when not code example accessibility component props  tokens wcag accessibility",
    "description": "One portal in a grid of them — org mark, short code, full name, and a note when the portal is not built yet.",
    "type": "component",
    "badge": "New",
    "iconName": "navigation"
  },
  {
    "title": "Portal Login Shell — Design System",
    "section": "Auth & Dashboard",
    "href": "/design-system/components/auth/portal-login-shell",
    "keywords": "portal login shell — design system auth & dashboard what the shell owns, and what it does not the hero is decorative, and disappears example  tokens wcag accessibility",
    "description": "The full-page login layout every MoSJE portal signs in through — the utility bar, the Government of India masthead, the SAMAVESH hero, the tab strip and the footer. The form itself is the caller",
    "type": "component",
    "iconName": "lock"
  },
  {
    "title": "Portal Login Template — Design System",
    "section": "Auth & Dashboard",
    "href": "/design-system/components/auth/portal-login-template",
    "keywords": "portal login template — design system auth & dashboard three audiences, whatever they are called what the role decides, and what the portal decides three form modes, and one handoff how the mode selector presents itself example linking straight to a role tab portalloginconfig keyboard portalLoginUrl(path, roleId?) roleFromUrl(href) ROLE_PARAM portalId portalName portalTagline portalDescription changeHref roles defaultRoleId captcha brandAssets extraFields extraContent links tokens wcag accessibility",
    "description": "A whole portal login page built from one config object — the role tabs, the authentication mode selector, the credential form and the deep-linked URL.",
    "type": "component",
    "iconName": "lock"
  },
  {
    "title": "Profile Card — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/profile-card",
    "keywords": "profile card — design system data display the portrait is passed in what goes on it example the alt text is yours  tokens wcag accessibility",
    "description": "A portrait, a name and an official designation, for the leadership and officer listings on the website.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Progress — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/progress",
    "keywords": "progress — design system data display the states it draws, and why they split nought is not missing example what a screen reader gets  tokens wcag accessibility",
    "description": "A labelled horizontal bar for one figure against a maximum, at row height, with a real indeterminate state for a figure that has not arrived.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Radio — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/radio",
    "keywords": "radio — design system forms & inputs radio cards example keyboard  tokens wcag accessibility",
    "description": "A radio button for choosing exactly one option from a mutually exclusive set, in an inline variant and a full selectable card variant.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Resend Timer — Design System",
    "section": "Auth & Dashboard",
    "href": "/design-system/components/auth/resend-timer",
    "keywords": "resend timer — design system auth & dashboard the rule most often got wrong  tokens wcag accessibility",
    "description": "The resend affordance under a one-time-code field.",
    "type": "component",
    "iconName": "lock"
  },
  {
    "title": "Resources",
    "section": "Resources",
    "href": "/design-system/resources",
    "keywords": "resources resources quick links building with an ai agent? get help  tokens wcag accessibility",
    "description": "Quick links to the SAMAVESH Figma library, Storybook, GitHub, changelog, governance, contributing guide, and roadmap — plus how to get help.",
    "type": "resource",
    "iconName": "menu_book"
  },
  {
    "title": "Roadmap",
    "section": "Resources",
    "href": "/design-system/resources/roadmap",
    "keywords": "roadmap resources   tokens wcag accessibility",
    "description": "Where SAMAVESH is heading — what is shipped now (v0.5), what is coming next (v0.6), and the longer-term plan toward v1.0.",
    "type": "resource",
    "iconName": "menu_book"
  },
  {
    "title": "SAMAVESH Banner — Design System",
    "section": "Navigation",
    "href": "/design-system/components/navigation/samavesh-banner",
    "keywords": "samavesh banner — design system navigation interactive specimen implementation & guidelines overview & principles usage guidelines installation & import props reference code example wcag 2.2 aa & gigw 3.0 compliance band tones, and why the default fails contrast on purpose component props Senior Citizens Welfare Nasha Mukt Bharat Abhiyaan National Commission for Scheduled Castes National SC Finance & Development Corporation tokens wcag accessibility",
    "description": "Top identity banner and portal discovery drawer implementing Figma node 7116:33784 & 7298:29968.",
    "type": "component",
    "badge": "New",
    "iconName": "navigation"
  },
  {
    "title": "Scatter Chart — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/scatter-chart",
    "keywords": "scatter chart — design system data display the states it draws density, labels and axes example what a screen reader gets ScatterSeries.name ScatterSeries.points ScatterSeries.color ScatterPoint.x / .y ScatterPoint.label Districts tokens wcag accessibility",
    "description": "Plots one measured quantity against another, one mark per record, for distribution and correlation across districts or units.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Search — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/search",
    "keywords": "search — design system forms & inputs sizes and modes example keyboard  tokens wcag accessibility",
    "description": "A search field with a leading icon, an optional clear control, an optional submit handler and an optional autocomplete listbox, in three sizes.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Section Title — Design System",
    "section": "Layout",
    "href": "/design-system/components/layout/section",
    "keywords": "section title — design system layout use it rather than hand-rolling one writing the row example keeping the outline sequential  tokens wcag accessibility",
    "description": "The standard heading row for a content section: eyebrow, heading, optional count pill, description, and right-aligned actions.",
    "type": "component",
    "iconName": "view_quilt"
  },
  {
    "title": "Section Title — Design System",
    "section": "Layout",
    "href": "/design-system/components/layout/section-title",
    "keywords": "section title — design system layout use it instead of a hand-rolled heading  tokens wcag accessibility",
    "description": "The estate",
    "type": "component",
    "iconName": "view_quilt"
  },
  {
    "title": "Segmented Control — Design System",
    "section": "Auth & Dashboard",
    "href": "/design-system/components/dashboard/segmented-control",
    "keywords": "segmented control — design system auth & dashboard   tokens wcag accessibility",
    "description": "A single-select toggle for a dashboard period or view.",
    "type": "component",
    "iconName": "lock"
  },
  {
    "title": "Select — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/select",
    "keywords": "select — design system forms & inputs native by design example keyboard  tokens wcag accessibility",
    "description": "A native select element with a custom chevron, so the platform",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Shape",
    "section": "Foundations",
    "href": "/design-system/foundations/shape",
    "keywords": "shape foundations how shape works the ladder choosing a rung prefer a role token pills and circles tokens do &amp; don&apos;t  tokens wcag accessibility",
    "description": "The SAMAVESH corner-radius ladder — twelve value-named rungs plus a fully-rounded sentinel, shared by every MoSJE site and portal.",
    "type": "foundation",
    "badge": "Stable",
    "iconName": "rounded_corner"
  },
  {
    "title": "Side Sheet — Design System",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/side-sheet",
    "keywords": "side sheet — design system feedback & status side sheet or modal anatomy example keyboard focus trap and focus restore  tokens wcag accessibility",
    "description": "An edge-anchored panel for long forms and record inspection, keeping the list behind it visible while the task is carried out.",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "Sidebar Nav — Design System",
    "section": "Navigation",
    "href": "/design-system/components/navigation/sidebar-nav",
    "keywords": "sidebar nav — design system navigation   tokens wcag accessibility",
    "description": "The portal app-shell left navigation.",
    "type": "component",
    "iconName": "navigation"
  },
  {
    "title": "Sidebar Nav — Design System",
    "section": "Navigation",
    "href": "/design-system/components/section-templates/sidebar",
    "keywords": "sidebar nav — design system navigation active detection collapsed mode the connector portal usage sidebarnavgroup, sidebarnavitem and sidebarnavchild example tokens landmarks, and the toggle that points at them SidebarNavGroup · label SidebarNavGroup · items SidebarNavItem · label SidebarNavItem · href SidebarNavItem · icon SidebarNavItem · badge SidebarNavItem · children SidebarNavChild · label SidebarNavChild · href tokens wcag accessibility",
    "description": "The portal app-shell left navigation: a two-level hierarchy with expandable groups and a curved connector, in an expanded or icon-only collapsed mode.",
    "type": "component",
    "iconName": "navigation"
  },
  {
    "title": "Signing Into Bar — Design System",
    "section": "Auth & Dashboard",
    "href": "/design-system/components/auth/signing-into-bar",
    "keywords": "signing into bar — design system auth & dashboard   tokens wcag accessibility",
    "description": "Tells the citizen which portal they are about to sign into.",
    "type": "component",
    "iconName": "lock"
  },
  {
    "title": "Site Footer — Design System",
    "section": "Navigation",
    "href": "/design-system/components/navigation/site-footer",
    "keywords": "site footer — design system navigation three zones, in priority order the website variant writing the content the four content shapes example every navigation is named SiteFooterLink · label SiteFooterLink · href SiteFooterLink · external SiteFooterColumn · heading SiteFooterColumn · id SiteFooterColumn · links SiteFooterSocial · label SiteFooterSocial · href SiteFooterSocial · icon SiteFooterCredit · src / alt / href SiteFooterCredit · width / height SiteFooterCredit · prefix tokens wcag accessibility",
    "description": "The statutory footer for the SAMAVESH estate, in two variants. Structural, not content-bound: every label, href, logo and sentence arrives as a prop.",
    "type": "component",
    "iconName": "navigation"
  },
  {
    "title": "Site Layout — Design System",
    "section": "Layout",
    "href": "/design-system/components/layout/site-layout",
    "keywords": "site layout — design system layout every child is a band what goes where overlays belong to a rail example the skip link has two halves  tokens wcag accessibility",
    "description": "The website page skeleton: chrome, then a stack of Bands. The main region grows, so a short page still pins its footer to the bottom of the viewport.",
    "type": "component",
    "iconName": "view_quilt"
  },
  {
    "title": "Site Page Header — Design System",
    "section": "Layout",
    "href": "/design-system/components/layout/site-page-header",
    "keywords": "site page header — design system layout   tokens wcag accessibility",
    "description": "The banner every website page opens with.",
    "type": "component",
    "iconName": "view_quilt"
  },
  {
    "title": "Skeleton — Design System",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/skeleton",
    "keywords": "skeleton — design system feedback & status match the shape, not the content keep the shimmer quiet skeletontext props skeletonrow props example the skeleton is silent — the region is not  tokens wcag accessibility",
    "description": "A placeholder in the shape of the result, shown while a request is in flight so the layout does not jump when the data lands.",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "SLA Progress Indicator — Design System",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/sla-progress",
    "keywords": "sla progress indicator — design system feedback & status seven states, derived from one fraction a paused clock renders neutral, not escalating three variants, chosen by where they sit thresholds are fractions units ux4g parity example what a screen reader hears label the case, not the category  tokens wcag accessibility",
    "description": "Tracks time remaining against a Right to Service Act guarantee. Three variants, seven states, and always a concrete number — never a vague “Processing…”.",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "SLA Progress Indicator — Variants — Design System",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/sla-progress-indicator",
    "keywords": "sla progress indicator — variants — design system feedback & status picking a variant example the variants are equal to assistive technology  tokens wcag accessibility",
    "description": "The three shapes an SLA guarantee takes: a linear row, a circular dashboard tile, and a badge for a table cell.",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "Small Multiples — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/small-multiples",
    "keywords": "small multiples — design system data display example the shared scale is the whole point  tokens wcag accessibility",
    "description": "The same chart once per category, on one shared scale — the answer to a series count that colour cannot carry.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Spacing",
    "section": "Foundations",
    "href": "/design-system/foundations/spacing",
    "keywords": "spacing foundations how spacing works the scale four families, one ladder tokens do &amp; don&apos;t inline stack padding section tokens wcag accessibility",
    "description": "The SAMAVESH spacing scale — an 8px base grid that keeps layout rhythm consistent across every MoSJE site and portal.",
    "type": "foundation",
    "badge": "Stable",
    "iconName": "palette"
  },
  {
    "title": "Sparkline — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/sparkline",
    "keywords": "sparkline — design system data display the states it draws labelled or decorative — decide deliberately example what a screen reader gets  tokens wcag accessibility",
    "description": "A small, axis-free line showing the shape of a recent trend, sized to sit inside a table row, a card corner or a metric.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "SSO Button — Design System",
    "section": "Auth & Dashboard",
    "href": "/design-system/components/auth/sso-button",
    "keywords": "sso button — design system auth & dashboard   tokens wcag accessibility",
    "description": "The federated sign-in entry point — today, DigiLocker.",
    "type": "component",
    "iconName": "lock"
  },
  {
    "title": "Stepper — Design System",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/stepper",
    "keywords": "stepper — design system feedback & status three states, derived writing the labels example keyboard what a screen reader hears  tokens wcag accessibility",
    "description": "Horizontal progress through a multi-step form: which stages are complete, which one the applicant is on, and how many remain.",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "Tabs — Design System",
    "section": "Navigation",
    "href": "/design-system/components/navigation/tabs",
    "keywords": "tabs — design system navigation indicator and track — only two of six combinations are correct vertical lists size icons, badges and disabled tabs writing tab labels guidelines example tabpanel tabdef when a label is clipped anyway — one problem, four answers tokens keyboard traversal the aria-controls pairing automatic activation, and its cost idBase tabId children id label icon badge disabled tokens wcag accessibility",
    "description": "Accessible tabbed navigation for non-linear sections, implementing the WAI-ARIA Tabs pattern with a roving tabindex and Arrow, Home and End keyboard support.",
    "type": "component",
    "iconName": "navigation"
  },
  {
    "title": "Tabs Overflow — Design System",
    "section": "Navigation",
    "href": "/design-system/components/navigation/tabs-overflow",
    "keywords": "tabs overflow — design system navigation you ask for it; you do not place it it does not move tabs into the menu it lists every tab, not just the hidden ones the edge fade applies to an open list only example keyboard  tokens wcag accessibility",
    "description": "The Tabs / More trigger and its menu. Internal to Tabs: it appears only when a horizontal row cannot show every tab, and lists all of them.",
    "type": "component",
    "iconName": "navigation"
  },
  {
    "title": "Textarea — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/textarea",
    "keywords": "textarea — design system forms & inputs height example keyboard  tokens wcag accessibility",
    "description": "A native, vertically resizable multi-line text field for long-form answers such as grievance descriptions, remarks and addresses.",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Ticker — Design System",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/ticker",
    "keywords": "ticker — design system feedback & status two shapes, one data model behaviour by width states motion divergences from the figma frame example motion, pause and the live region put the name in the outline focus and tab order  tokens wcag accessibility",
    "description": "Recent announcements in two shapes: the full-bleed bar under the masthead, and the stacked panel that scrolls them.",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "Toast — Design System",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/toast",
    "keywords": "toast — design system feedback & status toast, alert or action banner writing the message example how a toast reaches a screen reader the timer, and what it constrains ToastProvider · children ToastProvider · durationMs useToast() → toast toast · message toast · variant tokens wcag accessibility",
    "description": "Transient confirmation of something the reader just did. It appears in a corner viewport, announces itself through a live region, and leaves on its own.",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "Toggle — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/toggle",
    "keywords": "toggle — design system forms & inputs sizes example keyboard  tokens wcag accessibility",
    "description": "A switch for a setting that takes effect immediately. A real checkbox input carrying role=\\",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Tooltip — Design System",
    "section": "Feedback & Status",
    "href": "/design-system/components/feedback/tooltip",
    "keywords": "tooltip — design system feedback & status placement a tooltip is never the only copy example wcag 1.4.13, part by part described, not named  tokens wcag accessibility",
    "description": "A hint bubble on hover and focus, meeting WCAG 1.4.13: dismissible with Escape, hoverable, and persistent until the reader leaves it.",
    "type": "component",
    "iconName": "notifications"
  },
  {
    "title": "Typography",
    "section": "Foundations",
    "href": "/design-system/foundations/typography",
    "keywords": "typography foundations why two typefaces line height for indic scripts do &amp; don&rsquo;t the rules, and where each one comes from the alias family that lied, and why it is gone non-negotiable, because these are government services where these numbers come from  tokens wcag accessibility",
    "description": "SAMAVESH typography — one 21-role scale rendered on two surfaces (Website, Portal), fluid across every viewport, and drawn for both English and हिन्दी.",
    "type": "foundation",
    "badge": "Stable",
    "iconName": "palette"
  },
  {
    "title": "UX4G Accessibility Widget — Design System",
    "section": "Utilities",
    "href": "/design-system/components/utilities/ux4g-accessibility-widget",
    "keywords": "ux4g accessibility widget — design system utilities what is ours and what is not mounted once, near the end of the root layout example two things the component does that the script cannot  tokens wcag accessibility",
    "description": "The official Government of India (MeitY / UX4G) accessibility widget — contrast, text sizing, spacing, link highlighting, dark mode, reading guides and disability profiles. The single accessibility mechanism for the estate.",
    "type": "component",
    "iconName": "build"
  },
  {
    "title": "Vertical Timeline — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/vertical-timeline",
    "keywords": "vertical timeline — design system data display choose an order and keep it keep the entries short example what a screen reader gets VerticalTimeline children VerticalTimeline className tokens wcag accessibility",
    "description": "A dated sequence of entries down a single rail, for a scheme",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "Visitor Counter — Design System",
    "section": "Data Display",
    "href": "/design-system/components/data-display/visitor-counter",
    "keywords": "visitor counter — design system data display mock data, by design why the first paint is blank example deliberately not a live region  tokens wcag accessibility",
    "description": "The “Total Visits” figure in the site footer, derived from a seeded baseline. Mock data by design, until a real analytics feed replaces it.",
    "type": "component",
    "iconName": "bar_chart"
  },
  {
    "title": "What is SAMAVESH?",
    "section": "Getting Started",
    "href": "/design-system",
    "keywords": "what is samavesh? getting started  Button Card Badge Input / Textarea Select Form Field Accessibility Widget Color Mode tokens wcag accessibility",
    "description": "SAMAVESH (समावेश, inclusion) is the shared design language for the MoSJE digital estate — 13 websites and 20 portals serving 33+ organisations and schemes.",
    "type": "page",
    "iconName": "widgets"
  },
  {
    "title": "Wizard — Design System",
    "section": "Forms & Inputs",
    "href": "/design-system/components/forms/wizard",
    "keywords": "wizard — design system forms & inputs the parent owns the state example notes  tokens wcag accessibility",
    "description": "The shared multi-step form shell: a stepper, the current step",
    "type": "component",
    "iconName": "edit_note"
  },
  {
    "title": "Zone Switcher — Design System",
    "section": "Navigation",
    "href": "/design-system/components/navigation/zone-switcher",
    "keywords": "zone switcher — design system navigation mounted once, by the hub the rail and the panel why the right wall demodocktab how the hub wires it two independent holds, and how to test them id label content tokens wcag accessibility",
    "description": "The estate",
    "type": "component",
    "iconName": "navigation"
  }
];
