import * as React from "react";
import type { Metadata } from "next";
import Link from "next/link";

import "./brand.css";
import { Callout, DoDont, FoundationDocPage } from "@/components/design-system/docs-kit/index";
import { MODES as COLOUR_MODES, RAMPS } from "../color/color-data";

export const metadata: Metadata = {
  title: "Brand & White-Labelling",
  description:
    "The brand pack contract — one file of identity primitives that re-skins SAMAVESH for another government body, what a swap changes and what it never touches, the two published brands and the code-only DBIM modes, and the contrast gate an inaccessible brand cannot pass.",
};

/*
 * DS Audit: FoundationDocPage ✅ · Callout ✅ · DoDont ✅
 * A NEW foundation. INFORMATION-ARCHITECTURE.md §"1. Foundations" planned "Brand &
 * White-Labelling (the brand pack contract) ← NEW, central" and no page was built.
 * Every figure below is quoted from a file in the repository, cited beside it. Nothing
 * here is estimated.
 */

/**
 * Every colour VALUE on this page is read from the colour foundation's generated data
 * (color-data.ts, itself read from dist/tokens.css), never typed. The four below are the
 * anchors the brand packs publish; the DBIM figure is the one sub-AA reading the preview found.
 */
const rung = (name: string, step: number) => RAMPS.find((r) => r.name === name)?.steps.find((s) => s.step === step);
const SAFFRON = rung("secondaryScale", 400)?.blue ?? "";
const GREEN = rung("accentScale", 600)?.blue ?? "";
const BLUE_KEY = rung("primaryScale", 500)?.blue ?? "";
const NAVY_KEY = rung("primaryScale", 600)?.navy ?? "";
const DBIM_GREEN_BRAND = COLOUR_MODES.find((m) => m.id === "dbim-green")?.roles.find((r) => r.token === "text/brand/primary/base");
const DBIM_GREEN_SHADE2 = DBIM_GREEN_BRAND?.value ?? "";
const DBIM_GREEN_ON_MUTED = DBIM_GREEN_BRAND?.ratio != null ? `${DBIM_GREEN_BRAND.ratio.toFixed(2)}:1` : "";

/**
 * The six token families a pack supplies, with the number of $value entries in each.
 * COUNTED from packages/tokens/brands/mosje/brand.json on 2026-09-04 by walking every
 * `$value` leaf: 1 + 3 + 1 + 22 + 33 + 22 = 82. brands/_starter/brand.json carries the
 * same 82 paths — the README's rule is "keep the token PATHS identical, change only
 * the values". Descriptions are the files' own `$description` text, shortened.
 */
const PACK = [
  {
    count: 33,
    path: "color.primaryRamp.{blue,navy,dbim}.50–950",
    use: "The only ramp that changes with data-brand. Generated by build/brand-ramps.mjs from anchors; steps are not hand-edited.",
    moves: true,
  },
  {
    count: 22,
    path: "color.secondaryRamp.{blue,navy}.50–950",
    use: `India Saffron ${SAFFRON} from the SAMAVESH logo. Brand-invariant: blue and navy hold identical values on purpose.`,
    moves: false,
  },
  {
    count: 22,
    path: "color.accentRamp.{blue,navy}.50–950",
    use: `India Green ${GREEN} from the SAMAVESH logo. Brand-invariant, and deliberately the same green the success status uses.`,
    moves: false,
  },
  {
    count: 3,
    path: "color.saffron.{50,500,700}",
    use: "Legacy three-step saffron alias (--ds-saffron*). Tracks secondaryRamp; color.secondaryScale.* is preferred.",
    moves: false,
  },
  {
    count: 1,
    path: "color.navy.700",
    use: "Legacy --ds-gov-navy alias for footers and dark surfaces.",
    moves: false,
  },
  {
    count: 1,
    path: "color.yellow.500",
    use: "The BETA-badge accent. Not a brand colour and not a status colour; its sole intended use is the badge on the brand lockup.",
    moves: false,
  },
] as const;

const PACK_TOTAL = PACK.reduce((n, f) => n + f.count, 0);

/**
 * The two published brands and the seven code-only modes, one per `[data-brand="…"]`
 * block in packages/design-system/tokens.css (nine blocks, counted 2026-09-04). The
 * exporter's Palette collection is the hardcoded pair ["Blue", "Navy"]
 * (packages/tokens/build/formats/figma-variables.mjs), so the seven below it are
 * unreachable from Figma by construction. Labels for the six groups are DBIM_GROUPS in
 * packages/tokens/build/brand-ramps.mjs; `dbim` is the standing instruction in CLAUDE.md.
 */
const MODES = [
  { id: "blue", label: "Blue", reach: "Figma · default", note: `Gov-blue ${BLUE_KEY} anchored at rung 500.` },
  { id: "navy", label: "Navy", reach: "Figma", note: `${NAVY_KEY} anchored at rung 600, the rung its lightness says.` },
  { id: "dbim", label: "DBIM Blue (transcription)", reach: "code-only", note: "DBIM's Blue primary palette, five numbered shades, verbatim." },
  { id: "dbim-blue", label: "DBIM · Blue", reach: "code-only", note: "Full conformance group." },
  { id: "dbim-burgundy", label: "DBIM · Burgundy", reach: "code-only", note: "Full conformance group." },
  { id: "dbim-purple", label: "DBIM · Purple", reach: "code-only", note: "Full conformance group." },
  { id: "dbim-green", label: "DBIM · Green", reach: "code-only", note: `Shade 2 ${DBIM_GREEN_SHADE2} measures 4.32:1 on white — reported, not corrected.` },
  { id: "dbim-chrome-yellow", label: "DBIM · Chrome Yellow", reach: "code-only", note: "Primary sits 10° from the warning status." },
  { id: "dbim-cinnamon-red", label: "DBIM · Cinnamon Red", reach: "code-only", note: "Primary sits dE 0.9 from the error status." },
] as const;

const PUBLISHED = MODES.filter((m) => m.reach.startsWith("Figma"));
const CODE_ONLY = MODES.filter((m) => m.reach === "code-only");
const DBIM_GROUPS = CODE_ONLY.filter((m) => m.id !== "dbim");

/**
 * The load-bearing pairings the brand gate asserts, transcribed from PAIRINGS in
 * packages/tokens/test/lib/contrast.mjs (nine entries, counted 2026-09-04). The gate
 * (test/brand-contrast.test.mjs) rebuilds dist/ with BRAND=<id>, resolves each custom
 * property through its alias chain, and fails the build below the minimum.
 */
const PAIRINGS = [
  { fg: "--sa-color-text-onPrimary", bg: "--sa-color-action-primary-default", min: "4.5:1", label: "button label on primary" },
  { fg: "--sa-color-text-onPrimary", bg: "--sa-color-action-primary-hover", min: "4.5:1", label: "button label on primary (hover)" },
  { fg: "--sa-color-text-default", bg: "--sa-bg-neutral-base", min: "4.5:1", label: "body text on surface" },
  { fg: "--sa-color-text-muted", bg: "--sa-bg-neutral-base", min: "4.5:1", label: "muted text on surface" },
  { fg: "--sa-color-action-primary-default", bg: "--sa-bg-neutral-base", min: "3.0:1", label: "primary as link / UI on surface" },
  { fg: "--sa-color-status-success", bg: "--sa-color-status-successTonal", min: "4.5:1", label: "success badge text on success tonal" },
  { fg: "--sa-color-status-warning", bg: "--sa-color-status-warningTonal", min: "4.5:1", label: "warning badge text on warning tonal" },
  { fg: "--sa-color-status-danger", bg: "--sa-color-status-dangerTonal", min: "4.5:1", label: "danger badge text on danger tonal" },
  { fg: "--sa-color-status-info", bg: "--sa-color-status-infoTonal", min: "4.5:1", label: "info badge text on info tonal" },
] as const;

export default function BrandPage(): React.JSX.Element {
  return (
    <FoundationDocPage
      name="Brand & White-Labelling"
      status="New"
      since="0.49.0"
      summary="A brand pack is the only thing a new government body supplies to run SAMAVESH under its own identity: one file of colour primitives whose paths never change and whose values do. Everything else — the semantic token contract, every component, pattern, page template and accessibility behaviour — is the universal core and is inherited unchanged. A pack that cannot meet WCAG AA on the load-bearing pairings does not build."
      figma={{ node: "brand" }}
      glance={[
        { value: PACK_TOTAL, label: "tokens in a pack", note: "six families, one brand.json" },
        { value: PUBLISHED.length, label: "brands published", note: "Blue and Navy — the Figma Palette modes" },
        { value: DBIM_GROUPS.length, label: "DBIM conformance modes", note: "code-only; never reach Figma" },
        { value: 2, label: "logo ramps invariant", note: "India Saffron and India Green" },
        { value: PAIRINGS.length, label: "contrast pairings gated", note: "asserted for mosje and _starter" },
        { value: 1, label: "sub-AA DBIM shade", note: "reported, not corrected" },
      ]}
      sections={[
        {
          id: "pack",
          keyword: "PACK",
          title: "A Brand Pack Is One File, and It Holds Only Identity Primitives",
          description:
            "brands/<brand-id>/brand.json supplies the brand-identity primitives and nothing else. The universal semantic tier references these paths, so a value swap re-skins the entire system with no other edit. A pack may not fork a component or change a semantic token's meaning.",
          content: (
            <>
              {/* Families in the order the file declares their ramps; the moving one leads. */}
              <ul className="br-pack" aria-label="Token families in a brand pack">
                {PACK.map((f) => (
                  <li key={f.path} className={`br-pack__row ${f.moves ? "br-pack__row--moves" : ""}`}>
                    <span className="br-pack__count">{f.count}</span>
                    <span className="br-pack__path">{f.path}</span>
                    <span className="br-pack__use">{f.use}</span>
                  </li>
                ))}
              </ul>
              <Callout type="info" title="What a pack does not hold">
                Emblem and logo SVGs, the favicon, portal and zone names, footer and contact details, locale defaults and any
                optional typeface are brand assets, not tokens. They live with the consuming app, or in a{" "}
                <code>brand.config.ts</code> beside <code>brand.json</code>, and Style Dictionary never builds them.
              </Callout>
            </>
          ),
        },
        {
          id: "swap",
          keyword: "SWAP",
          title: "On a Swap the Primary Ramp Moves and the Logo Colours Do Not",
          description:
            "Verified against the built stylesheet on 2026-08-12: between Blue and Navy, primaryScale differs in 11 of 11 rungs, neutralScale in 10 of 13, and every other ramp is byte-identical. The neutral re-lock is a guarantee that the grey follows the brand's hue, not a visible change — at 8-bit precision the two brands' greys differ by at most 1 per channel.",
          content: (
            <>
              <div className="br-swap">
                <div className="br-swap__col br-swap__col--moves">
                  <p className="br-swap__title">Moves with data-brand</p>
                  <ul className="br-swap__list">
                    <li>
                      <code>primaryScale</code> — every rung, from the pack&rsquo;s <code>primaryRamp</code>.
                    </li>
                    <li>
                      <code>neutralScale</code> — re-locked to the brand hue, within 1 per channel.
                    </li>
                  </ul>
                </div>
                <div className="br-swap__col">
                  <p className="br-swap__title">Stays invariant</p>
                  <ul className="br-swap__list">
                    <li>
                      <code>secondaryScale</code> — India Saffron, and <code>accentScale</code> — India Green: constants of the
                      SAMAVESH identity, not variants of it.
                    </li>
                    <li>The four status hues, and the chart structural tokens.</li>
                    <li>Shadows — Blue and Navy composite to dE 0.00, identical.</li>
                    <li>Spacing, radius, motion and the type-role scales.</li>
                    <li>The whole semantic contract, every component, pattern and page template.</li>
                  </ul>
                </div>
              </div>
              <Callout type="warning" title="Why the logo ramps are pinned">
                Navy used to swap the secondary ramp to green, which landed it 1.00:1 from the success colour — a status and a
                brand accent that could not be told apart. That is audit finding C-02, fixed on 2026-08-11 and held by{" "}
                <code>test/hue-separation.test.mjs</code>.
              </Callout>
            </>
          ),
        },
        {
          id: "brands",
          keyword: "BRANDS",
          title: "Two Brands Reach Figma; Seven Code-Only Modes Never Do",
          description:
            "Each tile repaints through its own data-brand island, so every colour shown is the mode's real token. Blue and Navy are the SAMAVESH library's Palette modes. The seven beneath them exist so DBIM's published palette can be evaluated in the running estate, and the exporter cannot see them.",
          content: (
            <>
              <div className="br-modes" aria-label="Every data-brand mode in the estate">
                {MODES.map((m) => (
                  <div key={m.id} data-brand={m.id} className={`br-mode ${m.reach === "code-only" ? "br-mode--code-only" : ""}`}>
                    <div className="br-mode__head">
                      <span className="br-mode__id">{m.id}</span>
                      <span className="br-mode__reach">{m.reach}</span>
                    </div>
                    <div className="br-mode__primary" aria-hidden="true">
                      Aa
                    </div>
                    <div className="br-mode__status" aria-hidden="true">
                      <span className="is-success" />
                      <span className="is-warning" />
                      <span className="is-danger" />
                      <span className="is-info" />
                    </div>
                    <p className="br-mode__ink">
                      <strong>{m.label}.</strong> {m.note}
                    </p>
                  </div>
                ))}
              </div>
              <Callout type="info" title="Why a DBIM mode never reaches the library">
                <code>figma-variables.mjs</code> declares the Palette collection&rsquo;s modes as the hardcoded pair{" "}
                <code>[&quot;Blue&quot;, &quot;Navy&quot;]</code> and reads only <code>colorModes.navy</code>, so a DBIM brand is
                unreachable from the exporter by construction rather than by discipline. The standing instruction is the same: the
                Palette collection stays <code>[Blue, Navy]</code>, and no Dbim mode is added without being explicitly asked.
              </Callout>
              <p>
                A <code>dbim-*</code> group is full conformance, not a repainted primary. Selecting one also moves the four status
                colours to DBIM&rsquo;s own — Liberty Green, Mustard Yellow, Coral Red and DBIM Blue — replaces the brand-tinted greys
                with DBIM&rsquo;s pure ones, and sets body text to Deep Earthy Brown, which is not a neutral step at all. The six groups are synthesised at build time by{" "}
                <code>build/dbim-brand-modes.mjs</code> from one rule rather than written as roughly nine hundred JSON entries, and they
                are selectable in the demo dock&rsquo;s Colour tab under their own heading, tagged demo only.
              </p>
              <p>
                Where <code>dbim</code> is active, two DBIM usage rules apply: text uses shade 1 or 2 (DBIM §4.4); icons and the
                footer use the key colour, shade 1 (§3.7, §5.6).
              </p>
            </>
          ),
        },
        {
          id: "gate",
          keyword: "GATE",
          title: "An Inaccessible Brand Cannot Build",
          description:
            "There is no compliance by construction. test/brand-contrast.test.mjs rebuilds dist/ with the pack under test, resolves each pairing through its alias chain, and fails the build when any ratio falls below the minimum. It runs for the mosje pack and again for the _starter template, so the gate is proven against a re-skin and not only against the default.",
          content: (
            <>
              <div className="fdp__scroll">
                <table className="fdp__standards br-gate">
                  <thead>
                    <tr>
                      <th scope="col">Pairing</th>
                      <th scope="col">Foreground</th>
                      <th scope="col">Background</th>
                      <th scope="col">Minimum</th>
                    </tr>
                  </thead>
                  <tbody>
                    {PAIRINGS.map((p) => (
                      <tr key={p.label}>
                        <td>{p.label}</td>
                        <td>
                          <code>{p.fg}</code>
                        </td>
                        <td>
                          <code>{p.bg}</code>
                        </td>
                        <td>{p.min}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <p>
                Hover is not exempt: WCAG 1.4.3 applies to text in every state, and a primary button whose label washes out on
                hover fails for exactly the readers it matters most for. The four status-on-tonal rows are the badge and pill
                pairings every portal&rsquo;s status indicators use; all four shipped below AA until August 2026, because the ramp
                step for the foreground had been chosen for the solid fill, not for the tonal pairing.
              </p>
              <Callout type="warning" title="What the DBIM preview found, and why it was left as found">
                DBIM&rsquo;s own palette does not always meet DBIM&rsquo;s own rule 4, that colour usage must ensure accessibility.{" "}
                <code>dbim-green</code>&rsquo;s shade 2 <code>{DBIM_GREEN_SHADE2}</code> measures 4.32:1 on white and {DBIM_GREEN_ON_MUTED} on
                the muted ground, below AA. On Cinnamon Red the primary is dE 0.9 from the error status; on Chrome Yellow it is 10° from the
                warning status. All three are recorded with their measurements in <code>test/hue-separation.test.mjs</code> and
                <code>docs/design-system/colour-system.md</code> rather than corrected: a conformance palette that has been quietly fixed demonstrates
                nothing.
              </Callout>
            </>
          ),
        },
        {
          id: "steps",
          keyword: "STEPS",
          title: "A New Body Supplies One File and Touches No Core Code",
          description:
            "The procedure from packages/tokens/brands/README.md. The _starter template is a deliberately different emerald-and-amber palette so a re-skin is visually obvious.",
          content: (
            <>
              <ol>
                <li>
                  <code>cp -r brands/_starter brands/&lt;your-body&gt;</code>
                </li>
                <li>
                  Replace the values in <code>brand.json</code> with the body&rsquo;s identity, keeping every path. Drop the emblem,
                  logo, favicon and names into the consuming app.
                </li>
                <li>
                  <code>BRAND=&lt;your-body&gt; npm run build -w @mosje/tokens</code> — the build emits that brand&rsquo;s{" "}
                  <code>--sa-*</code> primitives into every output: CSS, the design-system <code>tokens.css</code>, Tailwind v3 and v4,
                  TypeScript and Figma.
                </li>
                <li>
                  <code>npm test -w @mosje/tokens</code> — the contrast gate must pass.
                </li>
                <li>Compose the screens from the design-system components and page templates. No core code is touched.</li>
              </ol>
              <DoDont
                cards={[
                  {
                    type: "do",
                    preview: <code>primaryRamp.{"{blue,navy,dbim}"}</code>,
                    label:
                      "Supply all three primary keys. Since 2026-08-11 the semantic layer references color.primaryRamp.dbim.*, so a pack without it fails the build; copy the navy values if the body has no third key colour.",
                  },
                  {
                    type: "do",
                    preview: <code>build/ramp.mjs</code>,
                    label: "Generate ramps with the build's own tool so the ramp-quality gate passes, and keep primaryRamp.*.500 dark enough that white on it stays at or above 4.5:1.",
                  },
                  {
                    type: "dont",
                    preview: <code>color.action.primary.default = &quot;#…&quot;</code>,
                    label: "A pack changes values under the six paths, never a semantic token's meaning and never a component. The core is inherited, not edited.",
                  },
                ]}
              />
            </>
          ),
        },
      ]}
      tokens={[]}
      tokensIntro={
        <>
          The {PACK_TOTAL} primitives a pack supplies are Tier 1 — <code>color.primaryRamp.*</code>,{" "}
          <code>color.secondaryRamp.*</code>, <code>color.accentRamp.*</code>, <code>color.saffron.*</code>,{" "}
          <code>color.navy.700</code> and <code>color.yellow.500</code> — and are never bound directly. A component bound to a
          primitive cannot be re-skinned by a pack, and the tier-discipline gate fails app code that reaches for a{" "}
          <code>--sa-ref-*</code> value. Bind the Tier-2 roles the brand feeds — <code>--sa-color-action-primary-*</code>,{" "}
          <code>--sa-color-primaryScale-*</code>, <code>--sa-color-secondaryScale-*</code>,{" "}
          <code>--sa-color-accentScale-*</code> — which are documented, with every value, on the{" "}
          <Link href="/design-system/foundations/color">Colour page</Link>. No table is printed here because no Tier-2 token belongs
          to this foundation alone.
        </>
      }
      a11y={[
        {
          criterion: "1.4.3 Contrast (Minimum)",
          level: "AA",
          description: "Text on the brand's primary, on the surface, and status text on its tonal chip, at 4.5:1 in every brand.",
          status: "verified",
          evidence:
            "packages/tokens/test/brand-contrast.test.mjs asserts nine pairings for the mosje pack and again for _starter on every `npm test -w @mosje/tokens`; the colour-system audit of 2026-09-04 §10 measured blue, navy and the six dbim-* previews.",
        },
        {
          criterion: "1.4.11 Non-text Contrast",
          level: "AA",
          description: "The primary as a link or control on the surface at 3:1; control borders on the muted ground at 3:1.",
          status: "partial",
          evidence:
            "The primary-on-surface pairing is gated at 3.0:1 per brand. The control border (4.07–4.45 on the muted ground, audit §10) was measured, not gated — a pack cannot move the neutral border, but nothing asserts it.",
        },
        {
          criterion: "1.4.1 Use of Color",
          level: "A",
          description: "Colour is never the sole carrier of a status, whichever brand is active.",
          status: "partial",
          evidence:
            "The colour-system audit §2.3 records the icon-plus-word rule on every status component. It is a component property, reviewed per component, and no brand-level test asserts it.",
        },
        {
          criterion: "DBIM 3.0 §4 — colour usage must ensure accessibility",
          level: "GIGW",
          description: "DBIM's own conformance palettes are held to the same AA floor as the estate's brands.",
          status: "partial",
          evidence:
            "All six dbim-* modes are resolved and measured in the colour-system audit §10; the one sub-AA shade (green group shade 2, 4.32:1) is reported in test/hue-separation.test.mjs and deliberately not corrected.",
        },
      ]}
      standards={[
        {
          clause: "DBIM 3.0 §4 — primary groups (five numbered shades)",
          says: "Six published primary groups; shade 1 is the key colour, text uses shade 1 or 2.",
          does: "Each group is transcribed verbatim into a code-only dbim-* mode, its five shades pinned to rungs 800 · 600 · 400 · 200 · 100 in every group, the remaining rungs interpolated. The estate's 4–16 L* ladder-shape rule is exempted for these six.",
          why: "A search over every assignment of five shades to eleven rungs found no configuration that held both DBIM's hexes and the ladder shape for five of the six groups. Fitting each group separately would put shade 2 on a different rung per group and DBIM's rules would stop being expressible as a token reference. The accessibility gates still bind.",
        },
        {
          clause: "DBIM 3.0 §4 rule 4 — colour usage must ensure accessibility",
          says: "The published palette is to be used accessibly.",
          does: `Green group shade 2 ${DBIM_GREEN_SHADE2} measures 4.32:1 on white and ${DBIM_GREEN_ON_MUTED} on the muted ground, below AA, and is left at DBIM's value; the measurement is recorded rather than the colour adjusted.`,
          why: "The dbim-* modes exist to evaluate DBIM's palette as published. A conformance preview that has been quietly corrected demonstrates nothing; the shipping brands, Blue and Navy, pass the gate.",
        },
        {
          clause: "UX4G 3.0 — default primary (violet)",
          says: "Ships a violet primary and a Theme Craft mechanism for replacing it.",
          does: `The MoSJE default is gov-blue ${BLUE_KEY}; UX4G's colour is not adopted.`,
          why: "DBIM requires a primary group built from the ministry's key colour, and DBIM and SAMAVESH set the brand. UX4G's structural conventions are adopted; its brand and aesthetic preferences are not.",
        },
      ]}
      related={[
        { label: "Colour", href: "/design-system/foundations/color", reason: "the Tier-2 roles a pack feeds, with every value per brand" },
        { label: "Iconography", href: "/design-system/foundations/iconography", reason: "Material Symbols and the bespoke marks; the organisation crests moved to the Brand page in Figma on 2026-08-31" },
        { label: "Accessibility", href: "/design-system/foundations/accessibility", reason: "the floor the contrast gate enforces" },
      ]}
    />
  );
}
