/*
 * THE REFERENCE TABLES OF THE ABOUT US PAGE — the Department's own figures.
 *
 * Transcribed MECHANICALLY from https://www.dosje.gov.in/about-us/ on 21 Sep 2026
 * (parsed from the page's HTML, spans kept as published), never retyped. Values are
 * verbatim, including the source's own spellings ("Andman & Nicobar Islands",
 * "Uttaranchal", "Orissa") and its dates of reference (2001, 2004-05, 2008, 2011,
 * 2018). Two edits only: the titles are set in Title Case, and the Former
 * Secretaries' names, published in capitals, are set in title case (TYP-07).
 * The transgender table's first header row repeated its own title and is dropped.
 */
export interface Cell { t: string; r?: number; c?: number }
export interface RefTable {
  id: string;
  title: string;
  /** The h3 the table sits under in "Sector-Wise Detailed Information"; null = elsewhere. */
  group: string | null;
  head: Cell[][];
  body: Cell[][];
}

export const ABOUT_TABLES: RefTable[] = [
  {
    id: "bureau-allocation",
    title: "Bureau Head-Wise Allocation of Work",
    group: null,
    head: [
      [{t: "Name of the Officer"}, {t: "Work Allocated"}]
    ],
    body: [
      [{t: "Ms. Mona K. Khandhar, AS", r: 7}, {t: "Centrally Sponsored Scheme for implementation of the Protection of Civil Rights (PCR) Act, 1955 and the Scheduled Castes and the Scheduled Tribes (Prevention of Atrocities) Act, 1989."}],
      [{t: "PM-Anusuchit Jati Abhyuday Yojana (PM-AJAY)"}],
      [{t: "Beggary component of SMILE(Support for Marginalized Individuals for Livelihood & Enterprise (SMILE)"}],
      [{t: "Rehabilitation for Transgender Persons component of SMILE(Support for Marginalized Individuals for Livelihood & Enterprise (SMILE)"}],
      [{t: "Transgender Persons (Protection of Rights) Act, 2019."}],
      [{t: "LGBTQIA+ and Welfare of Transgender Persons."}],
      [{t: "IT Division"}],
      [{t: "Ms. Debolina Thakur AS & FA", r: 4}, {t: "Budget & IFD"}],
      [{t: "Release of funds as per budgetary support, audit paras, PAC, EFC, and SFC of the department in conjunction with the concerned Joint Secretary and Standing Committee work related to Demands for Grants."}],
      [{t: "To be consulted in formulation of schemes, annual plans, vision document, PPP, EAP, NITI Aayog issues, enabling policy & regulatory framework to attract private sector funds."}],
      [{t: "Gender Budgeting"}],
      [{t: "Ms. Monali P. Dhakate, JS", r: 5}, {t: "Coordination, IGoM"}],
      [{t: "Pradhan Mantri Dakshataaur Kushalata Sampann Hitgrahi Yojna (PM-DAKSH)"}],
      [{t: "Media"}],
      [{t: "Matters relating to Development and Welfare Board for Nomadic and Semi Nomadic Communities (DWBDNCs)"}],
      [{t: "The matters related to SEED (assigned to CEO, DWBDNCs) will be routed through him."}],
      [{t: "Shri Sajeesh Kumar N, JS", r: 5}, {t: "Atal Vayo AbhyudayYojana (AVYAY)"}],
      [{t: "The Maintenance and welfare of Parents and Senior Citizens Act, 2007 (56 of 2007)"}],
      [{t: "All other matters relating to Senior Citizens"}],
      [{t: "Establishment, Cash Section"}],
      [{t: "General Administration"}],
      [{t: "Shri Shailendra Kumar, JS", r: 5}, {t: "Official Language, Corporate Cell, Narmada and all R&R matters"}],
      [{t: "SCD-VI Section ( Matters related to NCSC, NCBC, NCSK& JBCI at Department level)"}],
      [{t: "Revision of lists for SCs (RL Cell)"}],
      [{t: "Facilitation/ RTI Cell, CR-RR Section"}],
      [{t: "Parliament, Legal Cell, Vigilance, Gati Shakti"}],
      [{t: "Shri Parveen Kumar Thind, JS", r: 12}, {t: "PM-Young Achievers Scholarship Award Scheme for Vibrant India (PM-YASASVI)"}],
      [{t: "Scholarships for Higher Education for Young Achievers Scheme (SHREYAS-OBC)"}],
      [{t: "Matters relating to the National Backward Classes Finance and Development Corporation (NBCFDC)"}],
      [{t: "Matters relating to Commission to examine sub-categorization of OBCs (CESOB)"}],
      [{t: "All matters relating to OBCs /EWS"}],
      [{t: "Samras Cell"}],
      [{t: "Matters related to the National Scheduled Castes Finance and Development Corporation (NSFDC)"}],
      [{t: "Scholarships for Higher Education for Young Achievers Scheme (SHREYAS- SCs)"}],
      [{t: "Pre & Post Matric Scholarship Schemes for SCs"}],
      [{t: "Direct Benefit Transfer (DBT)"}],
      [{t: "Scheme of Residential Education for Students in High Schools in Targeted Area(SRESHTA-SCs)"}],
      [{t: "Matters related to Dr. Ambedkar Foundation (DAF)/DAIC-DANM/BJRNF"}],
      [{t: "Shri Sandeep Rewaji Rathod, JS", r: 11}, {t: "Matter relating to Prohibition, Rehabilitation of victims of alcoholism and substance abuse, and their families."}],
      [{t: "National Action Plan for Drug Demand Reduction (NAPDDR)"}],
      [{t: "Nasha Mukt Bharat Abhiyaan (NMBA)"}],
      [{t: "Prohibition of Employment as Manual Scavengers and their Rehabilitation Act 2013(MS Act 2013)"}],
      [{t: "All matters relating to the Self Employment Scheme for Rehabilitation of Manual Scavengers (SRMS)"}],
      [{t: "National Action Plan for Mechanised Sanitation Ecosystem (NAMSTE)"}],
      [{t: "The National Safai Karamchari Finance and Development Corporation (NSKFDC)"}],
      [{t: "International Conventions and Agreements on matters dealt within the Department and G-20 matters"}],
      [{t: "Project Monitoring Units (PMUs)"}],
      [{t: "Capacity Building"}],
      [{t: "Matters related to National Institute of Social Defence (NISD) at Department level"}],
      [{t: "Ms. Pratima Gupta, DDG", r: 18}, {t: "Matters related to Pragati Portal"}],
      [{t: "Evaluation Studies of Scheme of the Department"}],
      [{t: "Monitoring matters and issues related to NITI Aayog"}],
      [{t: "Handbook/All Statistics related matters"}],
      [{t: "Preparation of Annual Report"}],
      [{t: "Sectoral Group of Secretaries (SGoS)/ Vision Document"}],
      [{t: "Public Grievances (CPGRAM), PM-CARES"}],
      [{t: "Overall Coordination of E-Samiksha"}],
      [{t: "Social Audit of Schemes"}],
      [{t: "I- MESA- Awareness generation, research, evaluation and training"}],
      [{t: "All other matters related to Statistics Division"}],
      [{t: "Development Action Plan for SCs (DAPSC) and related matters/ schemes"}],
      [{t: "Output-Outcome Monitoring Framework"}],
      [{t: "Economic Inclusion Division (Venture Capital Funds, Credit Enhancement Guarantee Scheme, VISVAS scheme for SC’s and OBC’s, PM-SURAJ, Loan schemes of NSFDC and NBCFDC etc.)"}],
      [{t: "Economic Survey"}],
      [{t: "Examination and preparation of comments on Draft Cabinet Note/ CCEA/EFC/SFC/PIB/DIB Notes of other Ministries"}],
      [{t: "Policy/regulatory framework to attract private sector funds/PPP"}],
      [{t: "Matters related to SDG-30"}]
    ],
  },
  {
    id: "sc-castes-notified",
    title: "State-Wise Number of Castes Notified as Scheduled Castes (as on 23.09.2008)",
    group: "Scheduled Castes",
    head: [
      [{t: "Sr. No."}, {t: "State/Union Territory"}, {t: "Number of Castes"}]
    ],
    body: [
      [{t: "1"}, {t: "Andhra Pradesh"}, {t: "60"}],
      [{t: "2"}, {t: "Arunachal Pradesh"}, {t: "0"}],
      [{t: "3"}, {t: "Assam"}, {t: "16"}],
      [{t: "4"}, {t: "Bihar"}, {t: "23"}],
      [{t: "5"}, {t: "Chhattisgarh"}, {t: "44"}],
      [{t: "6"}, {t: "Goa"}, {t: "05"}],
      [{t: "7"}, {t: "Gujarat"}, {t: "36"}],
      [{t: "8"}, {t: "Haryana"}, {t: "37"}],
      [{t: "9"}, {t: "Himachal Pradesh"}, {t: "57"}],
      [{t: "10"}, {t: "Jammu and Kashmir"}, {t: "13"}],
      [{t: "11"}, {t: "Jharkhand"}, {t: "22"}],
      [{t: "12"}, {t: "Karnataka"}, {t: "101"}],
      [{t: "13"}, {t: "Kerala"}, {t: "55"}],
      [{t: "14"}, {t: "Madhya Pradesh"}, {t: "48"}],
      [{t: "15"}, {t: "Maharashtra"}, {t: "59"}],
      [{t: "16"}, {t: "Manipur"}, {t: "07"}],
      [{t: "17"}, {t: "Meghalaya"}, {t: "16"}],
      [{t: "18"}, {t: "Mizoram"}, {t: "16"}],
      [{t: "19"}, {t: "Nagaland"}, {t: "0"}],
      [{t: "20"}, {t: "Orissa"}, {t: "93"}],
      [{t: "21"}, {t: "Punjab"}, {t: "39"}],
      [{t: "22"}, {t: "Rajasthan"}, {t: "59"}],
      [{t: "23"}, {t: "Sikkim"}, {t: "04"}],
      [{t: "24"}, {t: "Tamil Nadu"}, {t: "76"}],
      [{t: "25"}, {t: "Tripura"}, {t: "34"}],
      [{t: "26"}, {t: "Uttar Pradesh"}, {t: "66"}],
      [{t: "27"}, {t: "Uttaranchal"}, {t: "65"}],
      [{t: "28"}, {t: "West Bengal"}, {t: "60"}],
      [{t: "29"}, {t: "Andman & Nicobar Islands"}, {t: "0"}],
      [{t: "30"}, {t: "Chandigarh"}, {t: "36"}],
      [{t: "31"}, {t: "Dadra & Nagar Haveli"}, {t: "04"}],
      [{t: "32"}, {t: "Daman & Diu"}, {t: "05"}],
      [{t: "33"}, {t: "NCT of Delhi"}, {t: "36"}],
      [{t: "34"}, {t: "Lakshdweep"}, {t: "0"}],
      [{t: "35"}, {t: "Pondicherry"}, {t: "16"}],
      [{t: ""}, {t: "Total"}, {t: "1208"}]
    ],
  },
  {
    id: "sc-blocks-40",
    title: "State-Wise, District-Wise List of Blocks with >40% SC Population",
    group: "Scheduled Castes",
    head: [
      [{t: "S. No."}, {t: "State"}, {t: "District"}, {t: "Block"}, {t: "%age of SC Population"}]
    ],
    body: [
      [{t: "1", r: 2}, {t: "Andhra Pradesh", r: 2}, {t: "1. Adilabad"}, {t: "1. Kotapalle"}, {t: "41"}],
      [{t: "2. Guntur"}, {t: "2. Amruthalur"}, {t: "42"}],
      [{t: "2"}, {t: "Haryana"}, {t: "3. Yamunanagar"}, {t: "3. Mustafabad"}, {t: "40"}],
      [{t: "3", r: 4}, {t: "Himachal Pradesh", r: 4}, {t: "4. Kullu"}, {t: "4. Nermand"}, {t: "45"}],
      [{t: "5. Sirmaur", r: 2}, {t: "5. Rajgarh"}, {t: "45"}],
      [{t: "6. Sangrah"}, {t: "41"}],
      [{t: "6. Solan"}, {t: "7. Solan"}, {t: "41"}],
      [{t: "4"}, {t: "Jammu & Kashmir"}, {t: "7. Jammu"}, {t: "8. Bishnah"}, {t: "47"}],
      [{t: "5", r: 2}, {t: "Jharkhand", r: 2}, {t: "8. Chatra", r: 2}, {t: "9. Kunda"}, {t: "63"}],
      [{t: "10. Lawalaung"}, {t: "56"}],
      [{t: "6"}, {t: "Kerala"}, {t: "9. Kollam"}, {t: "11. Parakode (Minor)"}, {t: "57"}],
      [{t: "7", r: 28}, {t: "Punjab", r: 28}, {t: "10. Amritsar", r: 2}, {t: "12. Jandiala Guru"}, {t: "43"}],
      [{t: "13. Verka"}, {t: "41"}],
      [{t: "11. Faridkot"}, {t: "14. Faridkot"}, {t: "40"}],
      [{t: "12. Gurdaspur", r: 2}, {t: "15. Narot Jaimal Singh"}, {t: "48"}],
      [{t: "16. Bamial"}, {t: "45"}],
      [{t: "13. Hoshiarpur", r: 4}, {t: "17. Hoshiarpur-I"}, {t: "48"}],
      [{t: "18. Hoshiarpur-II"}, {t: "48"}],
      [{t: "19. Mahilpur"}, {t: "44"}],
      [{t: "20. Bhunga"}, {t: "41"}],
      [{t: "14. Jalandhar", r: 9}, {t: "21. Jalandhar East"}, {t: "55"}],
      [{t: "22. Phillaur (P)"}, {t: "50"}],
      [{t: "23. Jalandhar West"}, {t: "48"}],
      [{t: "24. Noor Mehal"}, {t: "48"}],
      [{t: "25. Adampur"}, {t: "47"}],
      [{t: "26. Rurka Kalan"}, {t: "46"}],
      [{t: "27. Bhogpur"}, {t: "46"}],
      [{t: "28. Nakodar"}, {t: "43"}],
      [{t: "29. Shahkot"}, {t: "40"}],
      [{t: "15. Kapurthala"}, {t: "30. Phagwara"}, {t: "49"}],
      [{t: "16. Ludhiana", r: 2}, {t: "31. Khanna"}, {t: "43"}],
      [{t: "32. Ludhiana-II"}, {t: "41"}],
      [{t: "17. Muktsar", r: 3}, {t: "33. Muktsar"}, {t: "44"}],
      [{t: "34. Lambi"}, {t: "43"}],
      [{t: "35. Malout"}, {t: "41"}],
      [{t: "18. Nawanshahr", r: 3}, {t: "36. Banga"}, {t: "51"}],
      [{t: "37. Nawanshahr"}, {t: "45"}],
      [{t: "38. Aur"}, {t: "44"}],
      [{t: "19. Patiala"}, {t: "39. Amloh (P)"}, {t: "51"}]
    ],
  },
  {
    id: "sc-blocks-40-50",
    title: "State-Wise, District-Wise List of Blocks with >40% but Less than 50% SC Population",
    group: "Scheduled Castes",
    head: [
      [{t: "State"}, {t: "District"}, {t: "Blocks"}, {t: "% SC Population"}]
    ],
    body: [
      [{t: "Andhra Pradesh", r: 2}, {t: "Adilabad"}, {t: "1. Kotapalle"}, {t: "41.18"}],
      [{t: "Guntur"}, {t: "2. Amruthalur"}, {t: "42.22"}],
      [{t: "Haryana"}, {t: "Yamunanagar"}, {t: "3. Mustafabad"}, {t: "40.42"}],
      [{t: "Himachal Pradesh", r: 4}, {t: "Kullu"}, {t: "4. Nermand"}, {t: "44.85"}],
      [{t: "Sirmaur", r: 2}, {t: "5. Rajgarh"}, {t: "44.88"}],
      [{t: "6. Sangrah"}, {t: "40.60"}],
      [{t: "Solan"}, {t: "7. Solan"}, {t: "41.19"}],
      [{t: "Jammu & Kashmir"}, {t: "Jammu"}, {t: "8. Bishnah"}, {t: "46.79"}],
      [{t: "Punjab", r: 24}, {t: "Amritsar", r: 2}, {t: "9. Jandiala Guru"}, {t: "43.11"}],
      [{t: "10. Verka"}, {t: "41.19"}],
      [{t: "Faridkot"}, {t: "11. Faridkot"}, {t: "40.15"}],
      [{t: "Gurdaspur", r: 2}, {t: "12. Bamial"}, {t: "44.73"}],
      [{t: "13. Narot Jaimal Singh"}, {t: "48.20"}],
      [{t: "Hoshiarpur", r: 4}, {t: "14. Bhunga"}, {t: "40.67"}],
      [{t: "15. Hoshiarpur-I"}, {t: "48.37"}],
      [{t: "16. Hoshiarpur-II"}, {t: "47.75"}],
      [{t: "17. Mahilpur"}, {t: "43.81"}],
      [{t: "Jalandhar", r: 7}, {t: "18. Adampur"}, {t: "47.30"}],
      [{t: "19. Bhogpur"}, {t: "45.86"}],
      [{t: "20. Jalandhar West"}, {t: "47.63"}],
      [{t: "21. Nakodar"}, {t: "43.42"}],
      [{t: "22. Noor Mehal"}, {t: "47.50"}],
      [{t: "23. Rurka Kalan"}, {t: "45.92"}],
      [{t: "24. Shahkot"}, {t: "40.41"}],
      [{t: "Kapurthala"}, {t: "25. Phagwara"}, {t: "49.15"}],
      [{t: "Ludhiana", r: 2}, {t: "26. Khanna"}, {t: "42.58"}],
      [{t: "27. Ludhiana-II"}, {t: "40.73"}],
      [{t: "Muktsar", r: 3}, {t: "28. Lambi"}, {t: "43.04"}],
      [{t: "29. Malout"}, {t: "41.00"}],
      [{t: "30. Muktsar"}, {t: "44.32"}],
      [{t: "Nawanshahr", r: 2}, {t: "31. Aur"}, {t: "44.42"}],
      [{t: "32. Nawanshahr"}, {t: "45.48"}],
      [{t: "Rajasthan", r: 3}, {t: "Ganganagar", r: 3}, {t: "33. Anupgarh"}, {t: "42.41"}],
      [{t: "34. Karanpur"}, {t: "46.86"}],
      [{t: "35. Raisinghnagar"}, {t: "43.64"}],
      [{t: "Tamil Nadu", r: 14}, {t: "Cuddalore", r: 4}, {t: "36. Keerapalayam"}, {t: "40.06"}],
      [{t: "37. Komaratchi"}, {t: "40.96"}],
      [{t: "38. Mangalur"}, {t: "41.20"}],
      [{t: "39. Nallur"}, {t: "43.74"}],
      [{t: "Kancheepuram", r: 2}, {t: "40. Lathur"}, {t: "42.96"}],
      [{t: "41. Maduranthakam"}, {t: "48.90"}],
      [{t: "Ramanathapuram"}, {t: "42. Bogalur"}, {t: "41.32"}],
      [{t: "The Nilgiris"}, {t: "43. Coonoor"}, {t: "41.39"}],
      [{t: "Thiruvarur", r: 5}, {t: "44. Koradacheri"}, {t: "41.81"}],
      [{t: "45. Kottur"}, {t: "44.38"}],
      [{t: "46. Thiruthuraipoondi"}, {t: "49.30"}],
      [{t: "47. Thiruvarur"}, {t: "41.83"}],
      [{t: "48. Valangaiman"}, {t: "43.45"}],
      [{t: "Thoothukkudi"}, {t: "49. Ottapidaram"}, {t: "40.81"}],
      [{t: "Uttar Pradesh", r: 26}, {t: "Chandauli"}, {t: "50. Naugarh"}, {t: "44.95"}],
      [{t: "Faizabad"}, {t: "51. Dariyabad"}, {t: "46.79"}],
      [{t: "Hardoi", r: 7}, {t: "52. Ahrori"}, {t: "49.42"}],
      [{t: "53. Behadar"}, {t: "48.50"}],
      [{t: "54. Hariyawan"}, {t: "40.92"}],
      [{t: "55. Kachhauna"}, {t: "47.79"}],
      [{t: "56. Kothwan"}, {t: "48.73"}],
      [{t: "57. Sursa"}, {t: "47.44"}],
      [{t: "58. Tadiyawan"}, {t: "45.18"}],
      [{t: "Kaushambi", r: 2}, {t: "59. Chail"}, {t: "41.18"}],
      [{t: "60. Kaushambi"}, {t: "42.32"}],
      [{t: "Lucknow", r: 4}, {t: "61. Gosaiganj"}, {t: "44.76"}],
      [{t: "62. Kakori"}, {t: "40.07"}],
      [{t: "63. Mal"}, {t: "45.98"}],
      [{t: "64. Mohanlalganj"}, {t: "45.49"}],
      [{t: "Mirzapur", r: 2}, {t: "65. Hallia"}, {t: "43.86"}],
      [{t: "66. Lalganj"}, {t: "40.45"}],
      [{t: "Rae Bareli"}, {t: "67. Bachhrawan"}, {t: "43.02"}],
      [{t: "Sitapur", r: 4}, {t: "68. Gondlamau"}, {t: "42.52"}],
      [{t: "69. Kasmanda"}, {t: "40.48"}],
      [{t: "70. Machhrehta"}, {t: "44.45"}],
      [{t: "71. Misrikh"}, {t: "46.54"}],
      [{t: "Sonbhadra", r: 2}, {t: "72. Ghorawal"}, {t: "44.20"}],
      [{t: "73. Myorpur"}, {t: "41.54"}],
      [{t: "Unnao", r: 2}, {t: "74. Auras"}, {t: "45.34"}],
      [{t: "75. Hasanganj"}, {t: "42.55"}],
      [{t: "West Bengal", r: 27}, {t: "Bankura", r: 3}, {t: "76. Indus"}, {t: "41.77"}],
      [{t: "77. Patrasayer"}, {t: "44.70"}],
      [{t: "78. Sonamukhi"}, {t: "41.96"}],
      [{t: "Dakshin Dinajpur*"}, {t: "79. Kushmundi"}, {t: "44.41"}],
      [{t: "Jalpaiguri", r: 4}, {t: "80. Alipurduar - I"}, {t: "46.88"}],
      [{t: "81. Alipurduar - II"}, {t: "40.53"}],
      [{t: "82. Dhupguri"}, {t: "41.83"}],
      [{t: "83. Rajganj"}, {t: "48.54"}],
      [{t: "Koch Bihar", r: 5}, {t: "84. Cooch Behar - I"}, {t: "40.53"}],
      [{t: "85. Cooch Behar - II"}, {t: "45.93"}],
      [{t: "86. Dinhata - I"}, {t: "43.97"}],
      [{t: "87. Dinhata - II"}, {t: "44.99"}],
      [{t: "88. Tufanganj - I"}, {t: "45.73"}],
      [{t: "Maldah", r: 2}, {t: "89. Bamangola"}, {t: "49.87"}],
      [{t: "90. Habibpur"}, {t: "46.29"}],
      [{t: "Nadia", r: 4}, {t: "91. Chakdah"}, {t: "44.34"}],
      [{t: "92. Hanskhali"}, {t: "49.21"}],
      [{t: "93. Krishnaganj"}, {t: "44.71"}],
      [{t: "94. Ranaghat - II"}, {t: "45.62"}],
      [{t: "North Twenty Four Parganas", r: 3}, {t: "95. Bongaon"}, {t: "47.06"}],
      [{t: "96. Gaighata"}, {t: "48.00"}],
      [{t: "97. Sandeskhali - II"}, {t: "44.65"}],
      [{t: "South Twenty Four Parganas", r: 5}, {t: "98. Baruipur"}, {t: "42.78"}],
      [{t: "99. Bishnupur - I"}, {t: "47.89"}],
      [{t: "100. Jaynagar - I"}, {t: "40.96"}],
      [{t: "101. Kultali"}, {t: "47.26"}],
      [{t: "102. Mandirbazar"}, {t: "43.41"}]
    ],
  },
  {
    id: "sc-blocks-50",
    title: "List of Blocks with >50% SC Population",
    group: "Scheduled Castes",
    head: [
      [{t: "State"}, {t: "District"}, {t: "Blocks"}, {t: "% SC Population"}]
    ],
    body: [
      [{t: "Jharkhand", r: 2}, {t: "Chatra", r: 2}, {t: "1. Kunda"}, {t: "63.02"}],
      [{t: "2. Lawalaung"}, {t: "55.97"}],
      [{t: "Kerala"}, {t: "Kollam"}, {t: "3. Parakode (Minor)"}, {t: "56.94"}],
      [{t: "Punjab", r: 4}, {t: "Jalandhar", r: 2}, {t: "4. Jalandhar East"}, {t: "54.71"}],
      [{t: "5. Phillaur (P)"}, {t: "50.02"}],
      [{t: "Nawanshahr"}, {t: "6. Banga"}, {t: "50.72"}],
      [{t: "Patiala"}, {t: "7. Amloh (P)"}, {t: "51.30"}],
      [{t: "Tamil Nadu", r: 2}, {t: "Kancheepuram"}, {t: "8. Chithamur"}, {t: "50.62"}],
      [{t: "Nagapattinam"}, {t: "9. Kilvelur"}, {t: "52.33"}],
      [{t: "Uttar Pradesh", r: 7}, {t: "Chandauli"}, {t: "10. Forest Villages"}, {t: "56.58"}],
      [{t: "Mirzapur"}, {t: "11. Marihan"}, {t: "55.34"}],
      [{t: "Sonbhadra", r: 5}, {t: "12. Babhani"}, {t: "62.67"}],
      [{t: "13. Chopan"}, {t: "56.13"}],
      [{t: "14. Duddhi"}, {t: "54.80"}],
      [{t: "15. Forest Villages"}, {t: "79.21"}],
      [{t: "16. Nagwa"}, {t: "52.80"}],
      [{t: "West Bengal", r: 17}, {t: "Darjiling"}, {t: "17. Kharibari"}, {t: "50.85"}],
      [{t: "Jalpaiguri", r: 2}, {t: "18. Jalpaiguri"}, {t: "60.65"}],
      [{t: "19. Maynaguri"}, {t: "70.83"}],
      [{t: "Koch Bihar", r: 7}, {t: "20. Haldibari"}, {t: "61.86"}],
      [{t: "21. Mathabhanga - I"}, {t: "68.54"}],
      [{t: "22. Mathabhanga - II"}, {t: "65.39"}],
      [{t: "23. Mekliganj"}, {t: "71.43"}],
      [{t: "24. Sitai"}, {t: "67.33"}],
      [{t: "25. Sitalkuchi"}, {t: "54.85"}],
      [{t: "26. Tufanganj - II"}, {t: "50.63"}],
      [{t: "Medinipur"}, {t: "27. Khejuri - II"}, {t: "56.76"}],
      [{t: "North Twenty Four Parganas", r: 2}, {t: "28. Bagda"}, {t: "54.35"}],
      [{t: "29. Hingalganj"}, {t: "64.95"}],
      [{t: "South Twenty Four Parganas", r: 3}, {t: "30. Canning - I"}, {t: "50.66"}],
      [{t: "31. Gosaba"}, {t: "64.28"}],
      [{t: "32. Sonarpur"}, {t: "57.96"}],
      [{t: "Uttar Dinajpur"}, {t: "33. Kaliaganj"}, {t: "60.48"}]
    ],
  },
  {
    id: "sc-districts-40",
    title: "Districts Having More than 40% SC Population in India",
    group: "Scheduled Castes",
    head: [
      [{t: "State", r: 2}, {t: "District", r: 2}, {t: "Population (in Lakhs)", c: 2}, {t: "%SC Population", r: 2}],
      [{t: "Total"}, {t: "SC"}]
    ],
    body: [
      [{t: "West Bengal"}, {t: "Koch Bihar"}, {t: "24.8"}, {t: "12.4"}, {t: "50.1"}],
      [{t: "Uttar Pradesh"}, {t: "Sonbhadra"}, {t: "14.6"}, {t: "6.1"}, {t: "41.9"}],
      [{t: "Punjab"}, {t: "Nawanshahr"}, {t: "5.9"}, {t: "2.4"}, {t: "40.5"}]
    ],
  },
  {
    id: "sc-literacy-2001",
    title: "State/UT-Wise SCs & PD Literacy Rate, 2001",
    group: "Scheduled Castes",
    head: [
      [{t: "State/UT", r: 2}, {t: "Literacy Rate 2001", c: 3}],
      [{t: "Total"}, {t: "SC"}, {t: "PD"}]
    ],
    body: [
      [{t: "1. Uttar Pradesh"}, {t: "56.3"}, {t: "46.3"}, {t: "44.5"}],
      [{t: "2. Maharashtra"}, {t: "76.9"}, {t: "71.9"}, {t: "57.6"}],
      [{t: "3. Bihar"}, {t: "47.0"}, {t: "28.5"}, {t: "37.2"}],
      [{t: "4. West Bengal"}, {t: "68.6"}, {t: "59.0"}, {t: "52.7"}],
      [{t: "5. Andhra Pradesh"}, {t: "60.5"}, {t: "53.5"}, {t: "44.2"}],
      [{t: "6. Tamil Nadu"}, {t: "73.5"}, {t: "63.2"}, {t: "58.6"}],
      [{t: "7. Madhya Pradesh"}, {t: "63.7"}, {t: "58.6"}, {t: "49.7"}],
      [{t: "8. Rajasthan"}, {t: "60.1"}, {t: "52.2"}, {t: "45.3"}],
      [{t: "9. Karnataka"}, {t: "66.6"}, {t: "52.9"}, {t: "50.3"}],
      [{t: "10. Gujarat"}, {t: "69.1"}, {t: "70.5"}, {t: "54.0"}],
      [{t: "11. Orissa"}, {t: "63.1"}, {t: "55.5"}, {t: "48.8"}],
      [{t: "12. Kerala"}, {t: "90.9"}, {t: "82.7"}, {t: "67.0"}],
      [{t: "13. Jharkhand"}, {t: "53.6"}, {t: "37.6"}, {t: "41.5"}],
      [{t: "14. Assam"}, {t: "63.3"}, {t: "66.8"}, {t: "45.5"}],
      [{t: "15. Punjab"}, {t: "69.7"}, {t: "56.2"}, {t: "49.5"}],
      [{t: "16. Haryana"}, {t: "57.9"}, {t: "55.4"}, {t: "48.8"}],
      [{t: "17. Chhattisgarh"}, {t: "64.7"}, {t: "64.0"}, {t: "47.9"}],
      [{t: "18. Delhi"}, {t: "81.7"}, {t: "70.8"}, {t: "65.5"}],
      [{t: "19. J&K"}, {t: "55.5"}, {t: "59.0"}, {t: "39.9"}],
      [{t: "20. Uttarakhand"}, {t: "71.6"}, {t: "63.4"}, {t: "51.8"}],
      [{t: "21. Himachal Pradesh"}, {t: "76.5"}, {t: "70.3"}, {t: "51.9"}],
      [{t: "22. Tripura"}, {t: "73.2"}, {t: "74.7"}, {t: "52.5"}],
      [{t: "23. Manipur"}, {t: "70.5"}, {t: "72.3"}, {t: "42.9"}],
      [{t: "24. Meghalaya"}, {t: "62.5"}, {t: "56.3"}, {t: "37.9"}],
      [{t: "25. Nagaland"}, {t: "66.6"}, {t: "NA"}, {t: "30.8"}],
      [{t: "26. Goa"}, {t: "82.0"}, {t: "71.9"}, {t: "50"}],
      [{t: "27. Aru .Pradesh"}, {t: "54.3"}, {t: "67.6"}, {t: "39.4"}],
      [{t: "28. Puducherry"}, {t: "81.2"}, {t: "69.1"}, {t: "57.7"}],
      [{t: "29. Mizoram"}, {t: "88.8"}, {t: "89.2"}, {t: "56.3"}],
      [{t: "30. Chandigarh"}, {t: "81.9"}, {t: "67.7"}, {t: "62.5"}],
      [{t: "31. Sikkim"}, {t: "68.8"}, {t: "63.0"}, {t: "40.0"}],
      [{t: "32. A & N Islands"}, {t: "81.3"}, {t: "NA"}, {t: "57.1"}],
      [{t: "33. D & Nagar Haveli"}, {t: "57.6"}, {t: "78.2"}, {t: "25.0"}],
      [{t: "34. Daman & Diu"}, {t: "78.2"}, {t: "85.1"}, {t: "33.3"}],
      [{t: "35. Lakshadweep"}, {t: "86.7"}, {t: "NA"}, {t: "45.0"}],
      [{t: "Total"}, {t: "64.8"}, {t: "54.7"}, {t: "49.3"}]
    ],
  },
  {
    id: "sc-ger",
    title: "Gross Enrolment Ratio (GER) among Total Population and SC Population",
    group: "Scheduled Castes",
    head: [
      [{t: "Age Group", r: 2}, {t: "Total", c: 3}, {t: "SC", c: 3}],
      [{t: "Boys"}, {t: "Girls"}, {t: "Total"}, {t: "Boys"}, {t: "Girls"}, {t: "Total"}]
    ],
    body: [
      [{t: "6-11 (Classes I-V)"}, {t: "112.6"}, {t: "105.8"}, {t: "109.4"}, {t: "126.1"}, {t: "110.0"}, {t: "118.4"}],
      [{t: "11-14 (Classes VI-VII)"}, {t: "75.4"}, {t: "66.5"}, {t: "71.1"}, {t: "81.0"}, {t: "64.9"}, {t: "73.4"}],
      [{t: "6-14 (Classes I-VIII)"}, {t: "98.5"}, {t: "91.0"}, {t: "94.9"}, {t: "109.3"}, {t: "93.6"}, {t: "101.8"}],
      [{t: "14-16 (Classes IX-X)"}, {t: "57.7"}, {t: "46.2"}, {t: "52.2"}, {t: "54.8"}, {t: "40.3"}, {t: "48.1"}],
      [{t: "16-18 (Classes XI-XII)"}, {t: "31.5"}, {t: "25.1"}, {t: "28.5"}, {t: "27.9"}, {t: "20.7"}, {t: "24.6"}],
      [{t: "14-16 (Classes IX-XII)"}, {t: "44.7"}, {t: "35.8"}, {t: "40.4"}, {t: "41.7"}, {t: "30.8"}, {t: "36.6"}],
      [{t: "6-18 (Classes I-XII)"}, {t: "80.6"}, {t: "73.1"}, {t: "77.0"}, {t: "87.8"}, {t: "74.5"}, {t: "81.5"}],
      [{t: "18-24 (Higher Edn.)"}, {t: "13.6"}, {t: "9.3"}, {t: "11.6"}, {t: "10.1"}, {t: "6.4"}, {t: "8.3"}]
    ],
  },
  {
    id: "sc-dropout",
    title: "Sex-Wise Drop-out Rates among Total Population and SC Population",
    group: "Scheduled Castes",
    head: [
      [{t: "Classes", r: 2}, {t: "Total", c: 3}, {t: "SC", c: 3}],
      [{t: "Boys"}, {t: "Girls"}, {t: "Total"}, {t: "Boys"}, {t: "Girls"}, {t: "Total"}]
    ],
    body: [
      [{t: "I-V"}, {t: "28.5"}, {t: "21.5"}, {t: "25.4"}, {t: "33.6"}, {t: "34.0"}, {t: "33.7"}],
      [{t: "I-VIII"}, {t: "48.4"}, {t: "45.9"}, {t: "48.7"}, {t: "53.7"}, {t: "57.2"}, {t: "55.2"}],
      [{t: "I-X"}, {t: "60.0"}, {t: "63.5"}, {t: "61.5"}, {t: "68.1"}, {t: "73.7"}, {t: "70.5"}]
    ],
  },
  {
    id: "bpl-2004-05",
    title: "State-Wise Percentage of Population Below Poverty Line by Social Groups, 2004-05",
    group: "Social Groups",
    head: [
      [{t: "No. States", r: 2}, {t: "Rural", c: 4}, {t: "Urban", c: 4}, {t: "Rural & Urban"}],
      [{t: "SC"}, {t: "OBC"}, {t: "Others"}, {t: "All"}, {t: "SC"}, {t: "OBC"}, {t: "Others"}, {t: "All"}, {t: "Combined"}]
    ],
    body: [
      [{t: "1. Andhra Pradesh"}, {t: "15.4"}, {t: "9.5"}, {t: "4.1"}, {t: "11.2"}, {t: "39.9"}, {t: "28.9"}, {t: "20.6"}, {t: "28.0"}, {t: "15.8"}],
      [{t: "2. Assam"}, {t: "27.7"}, {t: "18.8"}, {t: "25.4"}, {t: "22.3"}, {t: "8.6"}, {t: "8.6"}, {t: "4.2"}, {t: "3.3"}, {t: "19.7"}],
      [{t: "3. Bihar"}, {t: "64.0"}, {t: "37.8"}, {t: "26.6"}, {t: "42.1"}, {t: "67.2"}, {t: "41.4"}, {t: "18.3"}, {t: "34.6"}, {t: "41.4"}],
      [{t: "4. Chhattisgarh"}, {t: "32.7"}, {t: "33.9"}, {t: "29.2"}, {t: "40.8"}, {t: "52.0"}, {t: "52.7"}, {t: "21.4"}, {t: "41.2"}, {t: "40.9"}],
      [{t: "5. Delhi"}, {t: "0.0"}, {t: "0.0"}, {t: "10.6"}, {t: "6.9"}, {t: "35.8"}, {t: "18.3"}, {t: "6.4"}, {t: "15.2"}, {t: "14.7"}],
      [{t: "6. Gujarat"}, {t: "21.8"}, {t: "19.1"}, {t: "4.8"}, {t: "19.1"}, {t: "16.0"}, {t: "22.9"}, {t: "7.0"}, {t: "13.0"}, {t: "16.8"}],
      [{t: "7. Haryana"}, {t: "26.8"}, {t: "13.9"}, {t: "4.2"}, {t: "13.6"}, {t: "33.4"}, {t: "22.5"}, {t: "5.9"}, {t: "15.1"}, {t: "14.0"}],
      [{t: "8. Himachal Pradesh"}, {t: "19.6"}, {t: "9.1"}, {t: "6.4"}, {t: "10.7"}, {t: "5.6"}, {t: "10.1"}, {t: "2.0"}, {t: "3.4"}, {t: "10.0"}],
      [{t: "9. Jammu & Kasmir"}, {t: "5.2"}, {t: "10.0"}, {t: "3.3"}, {t: "4.6"}, {t: "13.7"}, {t: "4.8"}, {t: "7.8"}, {t: "7.9"}, {t: "5.4"}],
      [{t: "10. Jharkhand"}, {t: "57.9"}, {t: "40.2"}, {t: "37.1"}, {t: "46.3"}, {t: "47.2"}, {t: "19.1"}, {t: "9.2"}, {t: "20.2"}, {t: "40.3"}],
      [{t: "11. Karnataka"}, {t: "31.8"}, {t: "20.9"}, {t: "13.6"}, {t: "20.8"}, {t: "50.6"}, {t: "39.1"}, {t: "20.3"}, {t: "32.6"}, {t: "25.0"}],
      [{t: "12. Kerala"}, {t: "21.6"}, {t: "13.7"}, {t: "6.6"}, {t: "13.2"}, {t: "32.5"}, {t: "24.3"}, {t: "7.8"}, {t: "20.2"}, {t: "15.0"}],
      [{t: "13. Madhya Pradesh"}, {t: "42.8"}, {t: "29.6"}, {t: "13.4"}, {t: "36.9"}, {t: "67.3"}, {t: "55.5"}, {t: "20.8"}, {t: "42.1"}, {t: "38.3"}],
      [{t: "14. Maharashtra"}, {t: "44.8"}, {t: "23.9"}, {t: "18.9"}, {t: "29.6"}, {t: "43.2"}, {t: "35.6"}, {t: "26.8"}, {t: "32.2"}, {t: "30.7"}],
      [{t: "15. Orissa"}, {t: "50.2"}, {t: "36.9"}, {t: "23.4"}, {t: "46.8"}, {t: "72.6"}, {t: "50.2"}, {t: "28.9"}, {t: "44.3"}, {t: "46.4"}],
      [{t: "16. Punjab"}, {t: "14.6"}, {t: "10.6"}, {t: "2.2"}, {t: "9.1"}, {t: "16.1"}, {t: "8.4"}, {t: "2.9"}, {t: "7.1"}, {t: "8.4"}],
      [{t: "17. Rajasthan"}, {t: "28.7"}, {t: "13.1"}, {t: "8.2"}, {t: "18.7"}, {t: "52.1"}, {t: "35.6"}, {t: "20.7"}, {t: "32.9"}, {t: "22.1"}],
      [{t: "18. Tamil Nadu"}, {t: "31.2"}, {t: "19.8"}, {t: "19.1"}, {t: "22.8"}, {t: "40.2"}, {t: "20.9"}, {t: "6.5"}, {t: "22.2"}, {t: "22.5"}],
      [{t: "19. Uttar Pradesh"}, {t: "44.8"}, {t: "32.9"}, {t: "19.7"}, {t: "33.4"}, {t: "44.9"}, {t: "36.6"}, {t: "19.2"}, {t: "30.6"}, {t: "32.8"}],
      [{t: "20. Uttarakhand"}, {t: "54.2"}, {t: "44.8"}, {t: "33.5"}, {t: "40.8"}, {t: "65.7"}, {t: "46.5"}, {t: "25.5"}, {t: "36.5"}, {t: "39.6"}],
      [{t: "21. West Bengal"}, {t: "29.5"}, {t: "18.3"}, {t: "27.5"}, {t: "28.6"}, {t: "28.5"}, {t: "10.4"}, {t: "13.0"}, {t: "14.8"}, {t: "24.7"}],
      [{t: "*All India"}, {t: "36.8"}, {t: "26.7"}, {t: "16.1"}, {t: "28.3"}, {t: "39.9"}, {t: "31.4"}, {t: "16.0"}, {t: "25.7"}, {t: "27.5"}]
    ],
  },
  {
    id: "senior-citizens-2001",
    title: "State-Wise Senior Citizens (60+) Population, 2001",
    group: "Senior Citizens",
    head: [
      [{t: "Population", r: 2}, {t: "State/UT", r: 2}, {t: "Population,2001 (in Crore)", c: 3}],
      [{t: "Total"}, {t: "Sr. Ctz"}, {t: "%"}]
    ],
    body: [
      [{t: "I. > 5 Crore", r: 10}, {t: "1. Uttar Pradesh"}, {t: "16.6"}, {t: "1.2"}, {t: "7.0"}],
      [{t: "2. Maharashtra"}, {t: "9.6"}, {t: "0.9"}, {t: "8.9"}],
      [{t: "3. Bihar"}, {t: "8.2"}, {t: "0.6"}, {t: "6.7"}],
      [{t: "4. West Bengal"}, {t: "8.0"}, {t: "0.6"}, {t: "7.1"}],
      [{t: "5. Andhra Pradesh"}, {t: "7.5"}, {t: "0.6"}, {t: "7.7"}],
      [{t: "6. Tamil Nadu"}, {t: "6.2"}, {t: "0.6"}, {t: "8.9"}],
      [{t: "7. Madhya Pradesh"}, {t: "6.0"}, {t: "0.4"}, {t: "7.2"}],
      [{t: "8. Rajasthan"}, {t: "5.6"}, {t: "0.4"}, {t: "6.8"}],
      [{t: "9. Karnataka"}, {t: "5.2"}, {t: "0.4"}, {t: "7.9"}],
      [{t: "10. Gujarat"}, {t: "5.0"}, {t: "0.4"}, {t: "7.0"}],
      [{t: "II. 2-5 Crore", r: 7}, {t: "11. Orissa"}, {t: "3.6"}, {t: "0.3"}, {t: "8.3"}],
      [{t: "12. Kerala"}, {t: "3.1"}, {t: "0.3"}, {t: "10.6"}],
      [{t: "13. Jharkhand"}, {t: "2.6"}, {t: "0.2"}, {t: "6.2"}],
      [{t: "14. Assam"}, {t: "2.6"}, {t: "0.2"}, {t: "6.2"}],
      [{t: "15. Punjab"}, {t: "2.4"}, {t: "0.2"}, {t: "9.2"}],
      [{t: "16. Haryana"}, {t: "2.1"}, {t: "0.2"}, {t: "7.6"}],
      [{t: "17. Chhattisgarh"}, {t: "2.0"}, {t: "0.2"}, {t: "7.5"}],
      [{t: "III. 0.5-2 Crore", r: 4}, {t: "18. Delhi"}, {t: "1.3"}, {t: "0.07"}, {t: "5.4"}],
      [{t: "19. Jammu & Kashmir"}, {t: "1.0"}, {t: "0.07"}, {t: "7.0"}],
      [{t: "20. Uttarakhand"}, {t: "0.8"}, {t: "0.07"}, {t: "8.8"}],
      [{t: "21. Himachal Pradesh"}, {t: "0.6"}, {t: "0.06"}, {t: "10.0"}],
      [{t: "IV. 0.1-0.5 Crore", r: 7}, {t: "22. Tripura"}, {t: "0.3"}, {t: "0.02"}, {t: "6.7"}],
      [{t: "23. Manipur"}, {t: "0.2"}, {t: "0.02"}, {t: "10.0"}],
      [{t: "24. Meghalaya"}, {t: "0.2"}, {t: "0.01"}, {t: "5.0"}],
      [{t: "25. Nagaland"}, {t: "0.2"}, {t: "0.01"}, {t: "5.0"}],
      [{t: "26. Goa"}, {t: "0.1"}, {t: "0.01"}, {t: "10.0"}],
      [{t: "27. Arunachal Pradesh"}, {t: "0.1"}, {t: "0.005"}, {t: "5.0"}],
      [{t: "28. Puducherry"}, {t: "0.1"}, {t: "0.008"}, {t: "8.0"}],
      [{t: "V. < 0.1 Crore", r: 8}, {t: "29. Mizoram"}, {t: "0.09"}, {t: "0.005"}, {t: "5.6"}],
      [{t: "30. Chandigarh"}, {t: "0.09"}, {t: "0.004"}, {t: "4.4"}],
      [{t: "31. Sikkim"}, {t: "0.05"}, {t: "0.002"}, {t: "4.0"}],
      [{t: "32. A&N Islands"}, {t: "0.04"}, {t: "0.001"}, {t: "2.5"}],
      [{t: "33. D& Nagar Haveli"}, {t: "0.02"}, {t: "0.001"}, {t: "4.0"}],
      [{t: "34. Daman & Diu"}, {t: "0.02"}, {t: "0.001"}, {t: "5.1"}],
      [{t: "35. Lakshadweep"}, {t: "0.006"}, {t: "*"}, {t: "6.1"}],
      [{t: "Total"}, {t: "102.7"}, {t: "7.7"}, {t: "7.5"}]
    ],
  },
  {
    id: "obc-central-list-2018",
    title: "State/UT-Wise Number of Entries in the Central List of OBCs as on March, 2018",
    group: "Other Backward Classes",
    head: [
      [{t: "Sl.No"}, {t: "State/UT"}, {t: "No. of Entries as in the Central List of OBCs 12.04.2018"}]
    ],
    body: [
      [{t: "1"}, {t: "Andhra Pradesh"}, {t: "104"}],
      [{t: "2"}, {t: "Arunachal Pradesh*"}, {t: "0"}],
      [{t: "3"}, {t: "Assam"}, {t: "28"}],
      [{t: "4"}, {t: "Bihar"}, {t: "132"}],
      [{t: "5"}, {t: "Chhatisgarh"}, {t: "67"}],
      [{t: "6"}, {t: "Goa"}, {t: "17"}],
      [{t: "7"}, {t: "Gujarat"}, {t: "105"}],
      [{t: "8"}, {t: "Haryana"}, {t: "73"}],
      [{t: "9"}, {t: "Himachal Pradesh"}, {t: "52"}],
      [{t: "10"}, {t: "J & K"}, {t: "23"}],
      [{t: "11"}, {t: "Jharkhand"}, {t: "134"}],
      [{t: "12"}, {t: "Karnataka**"}, {t: "199"}],
      [{t: "13"}, {t: "Kerala"}, {t: "83"}],
      [{t: "14"}, {t: "Madhya Pradesh"}, {t: "68"}],
      [{t: "15"}, {t: "Maharashtra"}, {t: "256"}],
      [{t: "16"}, {t: "Manipur"}, {t: "4"}],
      [{t: "17"}, {t: "Mizoram*"}, {t: "0"}],
      [{t: "18"}, {t: "Meghalaya*"}, {t: "0"}],
      [{t: "19"}, {t: "Nagaland*"}, {t: "0"}],
      [{t: "20"}, {t: "Orissa"}, {t: "197"}],
      [{t: "21"}, {t: "Punjab"}, {t: "65"}],
      [{t: "22"}, {t: "Rajasthan"}, {t: "69"}],
      [{t: "23"}, {t: "Sikkim"}, {t: "8"}],
      [{t: "24"}, {t: "Tamil Nadu"}, {t: "182"}],
      [{t: "25"}, {t: "Telangana"}, {t: "86"}],
      [{t: "26"}, {t: "Tripura"}, {t: "42"}],
      [{t: "27"}, {t: "Uttar Pradesh"}, {t: "76"}],
      [{t: "28"}, {t: "Uttrakhand"}, {t: "78"}],
      [{t: "29"}, {t: "West Bengal"}, {t: "98"}],
      [{t: "30"}, {t: "A & N Islands"}, {t: "5"}],
      [{t: "31"}, {t: "Chandigarh"}, {t: "60"}],
      [{t: "32"}, {t: "Daman & Diu"}, {t: "44"}],
      [{t: "33"}, {t: "Dadra & Nagar Haveli"}, {t: "10"}],
      [{t: "34"}, {t: "Delhi"}, {t: "56"}],
      [{t: "35"}, {t: "Lakshadweep*"}, {t: "0"}],
      [{t: "36"}, {t: "Pudducherry"}, {t: "58"}],
      [{t: ""}, {t: "Grand Total"}, {t: "2479"}]
    ],
  },
  {
    id: "transgender-2011",
    title: "State/UT-Wise Population of Others (TG) as per Census 2011",
    group: "Transgender Persons",
    head: [
      [{t: "#"}, {t: "State/UT"}, {t: "Transgender Population"}]
    ],
    body: [
      [{t: "-"}, {t: "India"}, {t: "4,87,803"}],
      [{t: "1"}, {t: "Uttar Pradesh"}, {t: "1,37,465"}],
      [{t: "2"}, {t: "Andhra Pradesh"}, {t: "43,769"}],
      [{t: "3"}, {t: "Maharashtra"}, {t: "40,891"}],
      [{t: "4"}, {t: "Bihar"}, {t: "40,827"}],
      [{t: "5"}, {t: "West Bengal"}, {t: "30,349"}],
      [{t: "6"}, {t: "Madhya Pradesh"}, {t: "29,597"}],
      [{t: "7"}, {t: "Tamil Nadu"}, {t: "22,364"}],
      [{t: "8"}, {t: "Orissa"}, {t: "20,332"}],
      [{t: "9"}, {t: "Karnataka"}, {t: "20,266"}],
      [{t: "10"}, {t: "Rajasthan"}, {t: "16,517"}],
      [{t: "11"}, {t: "Jharkhand"}, {t: "13,463"}],
      [{t: "12"}, {t: "Gujarat"}, {t: "11,544"}],
      [{t: "13"}, {t: "Assam"}, {t: "11,374"}],
      [{t: "14"}, {t: "Punjab"}, {t: "10,243"}],
      [{t: "15"}, {t: "Haryana"}, {t: "8,422"}],
      [{t: "16"}, {t: "Chhattisgarh"}, {t: "6,591"}],
      [{t: "17"}, {t: "Uttarakhand"}, {t: "4,555"}],
      [{t: "18"}, {t: "Delhi"}, {t: "4,213"}],
      [{t: "19"}, {t: "Jammu and Kashmir"}, {t: "4,137"}],
      [{t: "20"}, {t: "Kerala"}, {t: "3,902"}],
      [{t: "21"}, {t: "Himachal Pradesh"}, {t: "2,051"}],
      [{t: "22"}, {t: "Manipur"}, {t: "1,343"}],
      [{t: "23"}, {t: "Tripura"}, {t: "833"}],
      [{t: "24"}, {t: "Meghalaya"}, {t: "627"}],
      [{t: "25"}, {t: "Arunachal Pradesh"}, {t: "495"}],
      [{t: "26"}, {t: "Goa"}, {t: "398"}],
      [{t: "27"}, {t: "Nagaland"}, {t: "398"}],
      [{t: "28"}, {t: "Puducherry"}, {t: "252"}],
      [{t: "29"}, {t: "Mizoram"}, {t: "166"}],
      [{t: "30"}, {t: "Chandigarh"}, {t: "142"}],
      [{t: "31"}, {t: "Sikkim"}, {t: "126"}],
      [{t: "32"}, {t: "Daman and Diu"}, {t: "59"}],
      [{t: "33"}, {t: "Andaman and Nicobar"}, {t: "47"}],
      [{t: "34"}, {t: "Dadra and Nagar Have"}, {t: "43"}],
      [{t: "35"}, {t: "Lakshadweep"}, {t: "2"}]
    ],
  },
  {
    id: "former-secretaries",
    title: "Former Secretaries",
    group: null,
    head: [
      [{t: "Sr"}, {t: "Name"}, {t: "From"}, {t: "To"}]
    ],
    body: [
      [{t: "1"}, {t: "Shri J. A. Kalyankrishnan"}, {t: "25.09.1985"}, {t: "30.11.1985"}],
      [{t: "2"}, {t: "Shri S. S. Varma"}, {t: "02.12.1985"}, {t: "31.12.1989"}],
      [{t: "3"}, {t: "Shri J. M. Qureshi"}, {t: "01.01.1990"}, {t: "22.01.1990"}],
      [{t: "4"}, {t: "Shri P. S. Krishnan"}, {t: "03.01.1990"}, {t: "31.12.1990"}],
      [{t: "5"}, {t: "Shri J. M. Qureshi"}, {t: "01.01.1991"}, {t: "31.03.1991"}],
      [{t: "6"}, {t: "Smt. Usha Vohra"}, {t: "01.04.1991"}, {t: "24.05.1992"}],
      [{t: "7"}, {t: "Shri K. S. R. Murthy"}, {t: "25.05.1992"}, {t: "31.05.1993"}],
      [{t: "8"}, {t: "Shri A. Mohandas Moses"}, {t: "01.06.1993"}, {t: "27.01.1994"}],
      [{t: "9"}, {t: "Shri Mata Prasad"}, {t: "28.01.1994"}, {t: "24.06.1995"}],
      [{t: "10"}, {t: "Shri K. B. Saxena"}, {t: "22.08.1995"}, {t: "28.09.1996"}],
      [{t: "11"}, {t: "Shri K. K. Baksi"}, {t: "28.09.1996"}, {t: "04.02.1998"}],
      [{t: "12"}, {t: "Shri D. K. Manavalan"}, {t: "04.02.1998"}, {t: "05.05.1999"}],
      [{t: "13"}, {t: "Smt. Asha Das"}, {t: "05.05.1999"}, {t: "31.10.2001"}],
      [{t: "14"}, {t: "Shri C. Gopal Reddy"}, {t: "05.11.2001"}, {t: "30.09.2003"}],
      [{t: "15"}, {t: "Shri B. S. Baswan"}, {t: "01.07.2003"}, {t: "30.06.2004"}],
      [{t: "16"}, {t: "Smt. Sarita Prasad"}, {t: "30.06.2004"}, {t: "31.08.2006"}],
      [{t: "17"}, {t: "Dr Veena Chhotray"}, {t: "31.08.2006"}, {t: "31.03.2008"}],
      [{t: "18"}, {t: "Shri K. M. Acharya"}, {t: "01.04.2008"}, {t: "30.06.2012"}],
      [{t: "19"}, {t: "Shri Anil Goswami"}, {t: "02.07.2012"}, {t: "27.04.2013"}],
      [{t: "20"}, {t: "Shri Sudhir Bhargava"}, {t: "09.05.2013"}, {t: "31.01.2015"}],
      [{t: "21"}, {t: "Ms Anita Agnihotri"}, {t: "02.02.2015"}, {t: "31.10.2016"}],
      [{t: "22"}, {t: "Smt. G. Latha Krishna Rao"}, {t: "31.10.2016"}, {t: "30.04.2018"}],
      [{t: "23"}, {t: "Smt. Nilam Sawhney"}, {t: "21.05.2018"}, {t: "13.11.2019"}],
      [{t: "24"}, {t: "Shri R. Subrahmanyam"}, {t: "13.12.2019"}, {t: "31.08.2022"}],
      [{t: "25"}, {t: "Shri Anjali Bhawra"}, {t: "01.09.2022"}, {t: "21.04.2023"}],
      [{t: "26"}, {t: "Shri Saurabh Garg"}, {t: "21.04.2023"}, {t: "11.06.2024"}],
      [{t: "27"}, {t: "Shri Amit Yadav"}, {t: "11.06.2024"}, {t: "30.11.2025"}]
    ],
  },
];
