/**
 * GENERATED by scripts/build-legacy-scheme-map.mjs — do not edit by hand; edit
 * the script's ALIASES or REVIEWED tables and re-run it.
 *
 * Old-site scheme listings (content/website/schemes.json) that are the same
 * scheme as a record in the scheme master, found by normalised name match and
 * then hand-reviewed against docs/audit/website-schemes-placement-2026-09-09.csv.
 * A mapped listing permanently redirects to the master page and is not indexed
 * by search on its own. 38 of 140 listings are mapped.
 */
export const LEGACY_TO_MASTER: Readonly<Record<string, string>> = {
  "10663": "pre-matric-sc",
  "central-sector-scheme-of-national-overseas-scholarship": "nos",
  "central-sector-scholarship-of-top-class-education-for-sc-students": "top-class-sc",
  "centrally-sponsored-scheme-for-implementation-of-the-protection-of-civil-rights-act-1955-and-the-scheduled-castes-and-the-scheduled-tribes-prevention-of-atrocities-act-1989": "pcr-poa",
  "changes-in-the-centrally-sponsored-scheme-of-pre-matric-scholarship-to-children-of-those-engaged-in-unclean-occupations": "pre-matric-sc",
  "construction-of-hostels-for-obc-boys-and-girls": "yasasvi-hostel",
  "dr-ambedkar-centre-of-excellence-free-coaching-scheme-2": "free-coaching",
  "dr-ambedkar-medical-aid-scheme": "daf-medical-aid",
  "dr-ambedkar-national-merit-award-for-meritorious-students-of-secondary-examination-belonging-to-scheduled-castes-and-scheduled-tribes-2": "daf-merit-award",
  "dr-ambedkar-national-merit-award-scheme-for-meritorious-students-of-senior-secondary-school-examination-belonging-to-scheduled-caste-2": "daf-merit-award",
  "dr-ambedkar-scheme-of-interest-subsidy-on-educational-loan-for-overseas-studies-for-obcs-ebcs": "interest-subsidy-overseas",
  "elderline": "avyay-elderline",
  "free-coaching-for-scs-obcs-and-beneficiaries-of-pm-cares-children-scheme": "free-coaching",
  "geriatric-caregivers-training": "avyay-caregivers",
  "guidelines-of-national-action-for-mechanized-sanitation-ecosystem-namaste-scheme-2": "namaste",
  "integrated-programme-for-senior-citizens-ipsrc": "avyay-ipsrc",
  "national-action-for-mechanised-sanitation-ecosystem-namaste": "namaste",
  "national-action-plan-for-drug-demand-reduction": "napddr",
  "national-fellowship-for-obc-students-nf-obc": "nfobc",
  "national-fellowship-for-scheduled-caste-students": "nfsc",
  "national-overseas-scholarship-nos-for-sc-etc-candidates": "nos",
  "pm-special-training-of-geriatric-care-givers": "avyay-caregivers",
  "post-matric-scholarship-for-sc-students": "pms-sc",
  "pradhan-mantri-anusuchit-jaati-abhyuday-yojna-pm-ajay": "pm-ajay",
  "pre-matric-scholarships-scheme-for-scheduled-castes-others": "pre-matric-sc",
  "rashtriya-vayoshri-yojana-rvy": "avyay-rvy",
  "revised-guidelines-of-national-action-for-mechanized-sanitation-ecosystem-namaste-scheme": "namaste",
  "revised-scheme-guidelines-for-inclusion-of-waste-pickers-component-under-namaste": "namaste",
  "scheme-for-residential-education-for-students-in-high-schools-in-targeted-areas-shreshta": "shreshta",
  "schemes-implemented-by-national-safai-karamcharis-finance-development-corporation": "nskfdc-loans",
  "scholarship-for-pm-cares-children": "pm-cares-scholarship",
  "seed-free-coaching": "seed",
  "seed-health-insurance": "seed",
  "seed-housing": "seed",
  "seed-livelihood": "seed",
  "self-employment-scheme-for-rehabilitation-of-manual-scavengers-srms-applicable-from-november-2013": "namaste",
  "self-employment-scheme-for-rehabilitation-of-manual-scavengers-srms-applicable-from-november-2013-3": "namaste",
  "top-class-education-in-colllege-for-obc-ebc-and-dnt-students": "yasasvi-college"
};

/**
 * Listings the placement audit identifies as State Government schemes. They are
 * not schemes of the Department, so search does not index them. 46 listings.
 */
export const STATE_SCHEME_SLUGS: ReadonlySet<string> = new Set([
  "ashram-shalas",
  "assistance-to-students-of-dnts-studying-in-self-financed-institutes",
  "award-of-stipend-to-vjnt-and-sbc-students-studying-in-iti",
  "basti-development-scheme",
  "civil-service-incentive-scheme",
  "cm-housing-rent-scheme",
  "commencement-managment-of-ashram-schools",
  "district-level-prizes-for-public-examination-10th-and-12th",
  "dnt-employment-scheme",
  "excellent-award-scheme-for-social-workers",
  "financial-assistance-to-the-students-who-studied-10th-standard-in-government-schools-and-pursuing-hsc-in-the-best-private-schools",
  "free-education-for-3-year-polytechnic-courses",
  "free-education-in-professional-courses",
  "free-education-in-undergraduate-colleges",
  "gadia-lohar-scheme",
  "girls-literacy-promotion-scheme-class-11th",
  "housing-plan",
  "housing-scheme-for-scheduled-castes-and-dnts",
  "infrastructure-for-nomadic-semi-nomadic-tribes-concrete-roads-and-drainage",
  "itis-improvement-of-education-arts",
  "legal-aid-to-the-scheduled-castes-and-vimukta-jatis",
  "maintenance-allowance-to-backward-class-students-under-training-in-sainik-schools",
  "meritorious-scholarships-to-vjnt-and-sbc-students-studying-in-secondary-schools",
  "mukhyamantri-vimukt-ghumantu-and-ardhghumantu-swarozgar-yojana-cm-self-employment-scheme",
  "pandit-din-dayal-upadhyay-awas-yojana-housing-scheme",
  "payment-of-maintenance-allowance-to-vjnt-and-sbc-students-studying-in-professional-courses-and-living-in-hostel-attached-to-professional-colleges",
  "post-matric-scholarship",
  "post-ssc-scholarship-for-boys",
  "post-ssc-scholarship-to-girls",
  "pre-ssc-scholarship",
  "primary-education",
  "purchase-of-land-to-provide-accomodation-for-the-homeless",
  "rajarshi-chhatrapati-shahu-maharaj-merit-scholarship",
  "savitribai-phule-scholarship-for-vjnt-and-sbc-girl-students",
  "scholarship-for-technical-and-professional-courses",
  "scholarships-for-post-matric-students",
  "special-incentives-for-pre-matric-students",
  "state-scholarship-class-6th-to-10th",
  "talent-pool-scheme-for-dnts",
  "training-of-motor-driving-to-vjnt-sbc-obcs",
  "tuition-fees-and-examination-fees-for-vjnt-sbc-students-studying-in-high-schools",
  "tution-fee-reimbusrment-scheme-of-sainik-school-public-schools",
  "uniform-assistance-scheme",
  "vimukt-jaati-basti-development-scheme",
  "vimukt-jati-hostel-scheme",
  "vocational-training-for-vjnt-and-sbc-candidates-studying-in-government-industrial-training-institute"
]);
