/* GENERATED by @mosje/tokens — do not edit. Edit packages/tokens/src/*.json + the
   tailwind/v3 format. Pairs with @mosje/design-system/tokens.css (defines --sa-*). */
module.exports = {
  "theme": {
    "extend": {
      "colors": {
        "navy": "var(--sa-color-brand-navy)",
        "primary": "var(--sa-color-action-primary-default)",
        "primary-dark": "var(--sa-color-action-primary-hover)",
        "primary-tonal": "var(--sa-color-action-primary-tonal)",
        "success": "var(--sa-color-status-success)",
        "success-tonal": "var(--sa-color-status-successTonal)",
        "danger": "var(--sa-color-status-danger)",
        "warning": "var(--sa-color-status-warning)",
        "saffron": "var(--sa-color-brand-saffron)",
        "saffron-light": "var(--sa-color-secondaryScale-200)",
        "saffron-dark": "var(--sa-color-brand-saffronDark)",
        "yellow": "var(--sa-color-brand-yellow)",
        "ink": "var(--sa-color-text-default)",
        "ink-muted": "var(--sa-color-text-muted)",
        "surface": "var(--sa-bg-neutral-base)",
        "surface-muted": "var(--sa-bg-neutral-subtler)",
        "border-ds": "var(--sa-border-neutral-subtle)",
        "border-strong": "var(--sa-border-neutral-base)"
      },
      "borderRadius": {
        "none": "var(--sa-shape-0)",
        "xxs": "var(--sa-shape-2)",
        "xs": "var(--sa-shape-4)",
        "sm": "var(--sa-shape-6)",
        "md": "var(--sa-shape-8)",
        "lg": "var(--sa-shape-12)",
        "xl": "var(--sa-shape-16)",
        "2xl": "var(--sa-shape-20)",
        "3xl": "var(--sa-shape-24)",
        "4xl": "var(--sa-shape-32)",
        "5xl": "var(--sa-shape-40)",
        "full": "var(--sa-shape-full)"
      },
      "fontFamily": {
        "sans": [
          "Noto Sans",
          "ui-sans-serif",
          "system-ui",
          "sans-serif"
        ]
      },
      "boxShadow": {
        "ds-xs": "var(--sa-elevation-card)",
        "ds-lg": "var(--sa-elevation-modal)",
        "ds-xl": "var(--sa-elevation-toast)"
      }
    }
  }
};
