// Indian States & UTs — exact option list used across the SCW portal dropdowns
// (Event create, Volunteer filters, registration forms, etc.).
export const INDIAN_STATES = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttarakhand",
  "Uttar Pradesh",
  "West Bengal",
] as const;

// Bhashini language switcher options (अ/A button) — 22 scheduled languages + English.
export const BHASHINI_LANGUAGES: { label: string; native: string }[] = [
  { label: "English", native: "English" },
  { label: "Assamese", native: "অসমীয়া" },
  { label: "Bengali", native: "বাংলা" },
  { label: "Bodo", native: "बड़ो" },
  { label: "Dogri", native: "डोगरी" },
  { label: "Goan Konkani", native: "गोवा कोंकणी" },
  { label: "Gujarati", native: "ગુજરાતી" },
  { label: "Hindi", native: "हिन्दी" },
  { label: "Kannada", native: "ಕನ್ನಡ" },
  { label: "Kashmiri", native: "कश्मीरी" },
  { label: "Maithili", native: "मैथिली" },
  { label: "Malayalam", native: "മലയാളം" },
  { label: "Manipuri", native: "মণিপুরী" },
  { label: "Marathi", native: "मराठी" },
  { label: "Nepali", native: "नेपाली" },
  { label: "Odia", native: "ଓଡ଼ିଆ" },
  { label: "Punjabi", native: "ਪੰਜਾਬੀ" },
  { label: "Sanskrit", native: "संस्कृत" },
  { label: "Santali", native: "संताली" },
  { label: "Sindhi", native: "سنڌي" },
  { label: "Tamil", native: "தமிழ்" },
  { label: "Telugu", native: "తెలుగు" },
  { label: "Urdu", native: "اردو" },
];
