#!/usr/bin/env node
/**
 * Generates the service-discovery prototype data and the research document from the
 * scheme master, so the prototypes, the Figma frames and the deck all read ONE list.
 *
 *   node tools/service-discovery/build-data.mjs
 *
 * Reads   docs/research/dosje-scheme-master-2026-09.json
 * Writes  apps/hub/public/prototypes/service-discovery/data.js
 *         docs/research/dosje-scheme-master-2026-09.md
 *
 * The JSON is the only file to edit. A record with no source, an unknown persona or
 * offering id, or an unknown apply route fails the build — an invented scheme cannot
 * reach a screen.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const masterPath = resolve(root, "docs/research/dosje-scheme-master-2026-09.json");
const dataPath = resolve(root, "apps/hub/public/prototypes/service-discovery/data.js");
const docPath = resolve(root, "docs/research/dosje-scheme-master-2026-09.md");

const m = JSON.parse(readFileSync(masterPath, "utf8"));

/* ── validate ───────────────────────────────────────────────────────────── */
const personaIds = new Set(m.personas.map((p) => p.id));
const offeringIds = new Set(m.offerings.map((o) => o.id));
const routeIds = new Set(Object.keys(m.routes));
const errors = [];
const seen = new Set();
for (const s of m.schemes) {
  if (seen.has(s.id)) errors.push(`${s.id}: duplicate id`);
  seen.add(s.id);
  if (!s.sources?.length) errors.push(`${s.id}: no source`);
  for (const w of s.who) if (!personaIds.has(w)) errors.push(`${s.id}: unknown persona "${w}"`);
  for (const o of s.offers) if (!offeringIds.has(o)) errors.push(`${s.id}: unknown offering "${o}"`);
  for (const a of s.apply) if (!routeIds.has(a)) errors.push(`${s.id}: unknown route "${a}"`);
  for (const k of ["name", "provides", "named"]) if (!s[k]) errors.push(`${s.id}: missing ${k}`);
  if (/\b\d{2,3}\s+schemes?\b/i.test(s.provides)) errors.push(`${s.id}: a scheme count in "provides"`);
}
for (const p of m.personas) {
  if (!m.schemes.some((s) => s.who.includes(p.id))) errors.push(`persona "${p.id}" has no scheme`);
}
for (const o of m.offerings) {
  if (!m.schemes.some((s) => s.offers.includes(o.id))) errors.push(`offering "${o.id}" has no scheme`);
}
if (errors.length) {
  console.error("scheme master is not valid:\n  " + errors.join("\n  "));
  process.exit(1);
}

/* ── data.js ────────────────────────────────────────────────────────────── */
const js = (v) => JSON.stringify(v, null, 2);
const dataJs = `/* GENERATED by tools/service-discovery/build-data.mjs from
   docs/research/dosje-scheme-master-2026-09.json — do not edit here.

   Every scheme, persona and offering below is taken from the Department's own
   Annual Report 2025-26, its Demand for Grants 2026-27 and the PIB Year-End
   Review 2025. The beta site's Schemes list is NOT a source. Nothing here is a
   count, and nothing here states that anyone is eligible: \`who\` records whom a
   scheme names as its target group; the sanctioning authority decides. */

const PERSONAS = ${js(m.personas.map(({ id, label, sub, portal }) => ({ id, label, short: label, sub, ...(portal ? { portal: { route: portal.route, blurb: portal.blurb } } : {}) })))};

const OFFERINGS = ${js(m.offerings.map(({ id, label, short, sub }) => ({ id, label, short: short || label, sub })))};

const ROUTES = ${js(Object.fromEntries(Object.entries(m.routes).map(([k, r]) => [k, { label: r.label, href: r.href }])))};

const SCHEMES = ${js(
  m.schemes.map((s) => ({
    id: s.id,
    name: s.name,
    umbrella: s.umbrella,
    type: s.type,
    who: s.who,
    offers: s.offers,
    provides: s.provides,
    named: s.named,
    apply: s.apply,
    ...(s.offersFor ? { offersFor: s.offersFor } : {}),
  })),
)};

/* Kept for the old prototypes' variable names while they are migrated. */
const GROUPS = PERSONAS;
const GROUP_LABEL = Object.fromEntries(PERSONAS.map((g) => [g.id, g.label]));
const OFFER_LABEL = Object.fromEntries(OFFERINGS.map((o) => [o.id, o.label]));

/* Group artwork. The live persona panel draws each group as an illustrated
   figure and those files exist for the groups it already shows; a persona
   added by this master, or one whose artwork was withdrawn, is drawn as a
   plain token-coloured mark, never a stand-in figure. The label beside it
   carries the group. */
const HAS_ART = new Set(${js(m.personas.filter((p) => p.art !== false && existsSync(resolve(root, "apps/hub/public/prototypes/service-discovery/personas", p.id + ".png"))).map((p) => p.id))});
/* Material Symbols Rounded, the estate's icon set, for the groups with no
   figure: what the scheme gives, not what a person is assumed to look like. */
const MARK_ICON = { drug:'health_and_safety', begging:'night_shelter', atrocity:'balance' };
function markHTML(id) {
  if (HAS_ART.has(id)) return \`<img src="personas/\${id}.png" alt="">\`;
  if (MARK_ICON[id]) return \`<span class="mark-icon" role="presentation"><span class="mi">\${MARK_ICON[id]}</span></span>\`;
  return \`<span class="mark-none" role="presentation"></span>\`;
}

/** Does this record provide \`offer\` to \`who\`? A grant to the NGO that runs an
    old-age home is not an offering to the senior citizen who lives in it. */
function pairOk(s, who, offer) {
  if (who && !s.who.includes(who)) return false;
  if (offer && !s.offers.includes(offer)) return false;
  if (who && offer && s.offersFor && s.offersFor[offer] && !s.offersFor[offer].includes(who)) return false;
  if (who && !offer && s.offersFor) {
    // the persona must be served by at least one offering of the record
    return s.offers.some((o) => !s.offersFor[o] || s.offersFor[o].includes(who));
  }
  return true;
}

/** One expression, used by every surface, so a key and a list never disagree. */
function matchSchemes({ who, offer }) {
  return SCHEMES.filter((s) => pairOk(s, who, offer));
}

/** The offerings a persona can actually be shown, in master order. */
function offersFor(who) {
  return OFFERINGS.filter((o) => SCHEMES.some((s) => pairOk(s, who, o.id)));
}

function routeLabel(id) { return ROUTES[id] ? ROUTES[id].label : id; }
/* "Apply on" a portal, "Call" a helpline, "Apply through" an office or agency. */
function applyLabel(id) {
  const r = ROUTES[id]; if (!r) return 'Apply';
  if (r.href && r.href.startsWith('tel:')) return 'Call ' + r.label;
  return (/portal/i.test(r.label) ? 'Apply on ' : 'Apply through ') + r.label;
}
`;
writeFileSync(dataPath, dataJs);

/* ── typed module for the assistant route ──────────────────────────────── */
const tsPath = resolve(root, "apps/hub/src/lib/explorations/service-discovery-master.ts");
const ts = `/* GENERATED by tools/service-discovery/build-data.mjs from
   docs/research/dosje-scheme-master-2026-09.json — do not edit here. */

export interface SdPersona { id: string; label: string; short: string; sub: string; portal?: { route: string; blurb: string } }
export interface SdOffering { id: string; label: string; short: string; sub: string }
export interface SdScheme {
  id: string; name: string; umbrella: string | null; type: string;
  who: string[]; offers: string[]; provides: string; named: string; apply: string[];
  offersFor?: Record<string, string[]>;
  /** The scheme's page on the Department's legacy site, where one was cited. */
  page?: string;
}

export const SD_PERSONAS: SdPersona[] = ${js(m.personas.map(({ id, label, sub, portal }) => ({ id, label, short: label, sub, ...(portal ? { portal: { route: portal.route, blurb: portal.blurb } } : {}) })))};
export const SD_OFFERINGS: SdOffering[] = ${js(m.offerings.map(({ id, label, short, sub }) => ({ id, label, short: short || label, sub })))};
export const SD_ROUTES: Record<string, { label: string; href: string | null }> = ${js(Object.fromEntries(Object.entries(m.routes).map(([k, r]) => [k, { label: r.label, href: r.href }])))};
export const SD_SCHEMES: SdScheme[] = ${js(
  m.schemes.map((s) => {
    const sj = s.sources.map((x) => /^SJ (\d+)$/.exec(x)).find(Boolean);
    return {
      id: s.id, name: s.name, umbrella: s.umbrella, type: s.type, who: s.who, offers: s.offers,
      provides: s.provides, named: s.named, apply: s.apply, ...(s.offersFor ? { offersFor: s.offersFor } : {}),
      ...(sj ? { page: "https://socialjustice.gov.in/schemes/" + sj[1] } : {}),
    };
  }),
)};

/** Does this record provide \`offer\` to \`who\`? Same rule as the prototypes' data.js. */
export function sdPairOk(s: SdScheme, who?: string, offer?: string): boolean {
  if (who && !s.who.includes(who)) return false;
  if (offer && !s.offers.includes(offer)) return false;
  if (who && offer && s.offersFor?.[offer] && !s.offersFor[offer].includes(who)) return false;
  if (who && !offer && s.offersFor) return s.offers.some((o) => !s.offersFor?.[o] || s.offersFor[o].includes(who));
  return true;
}
export function sdMatch(who?: string, offer?: string): SdScheme[] {
  return SD_SCHEMES.filter((s) => sdPairOk(s, who, offer));
}
export function sdOffersFor(who: string): SdOffering[] {
  return SD_OFFERINGS.filter((o) => SD_SCHEMES.some((s) => sdPairOk(s, who, o.id)));
}
/** "Apply on" a portal, "Call" a helpline, "Apply through" an office or agency. */
export function sdApplyLabel(routeId: string | undefined): string {
  const r = routeId ? SD_ROUTES[routeId] : undefined;
  if (!r) return "Apply";
  if (r.href?.startsWith("tel:")) return \`Call \${r.label}\`;
  return (/portal/i.test(r.label) ? "Apply on " : "Apply through ") + r.label;
}
`;
writeFileSync(tsPath, ts);

/* ── research document ─────────────────────────────────────────────────── */
const P = Object.fromEntries(m.personas.map((p) => [p.id, p]));
const O = Object.fromEntries(m.offerings.map((o) => [o.id, o]));
const pairOk = (s, who, offer) =>
  s.who.includes(who) && s.offers.includes(offer) && !(s.offersFor?.[offer] && !s.offersFor[offer].includes(who));
const matrix = m.personas
  .map((p) => {
    const cells = m.offerings.map((o) => {
      const n = m.schemes.filter((s) => pairOk(s, p.id, o.id)).length;
      return n ? String(n) : "·";
    });
    return `| ${p.label} | ${cells.join(" | ")} |`;
  })
  .join("\n");

const schemeRows = m.schemes
  .map(
    (s) =>
      `| ${s.name}${s.umbrella ? `<br><small>${s.umbrella}</small>` : ""} | ${s.type} | ${s.who
        .map((w) => P[w].short || P[w].label)
        .join(", ")} | ${s.offers.map((o) => O[o].short || O[o].label).join(", ")} | ${s.provides} | ${s.named} | ${s.apply
        .map((a) => m.routes[a].label)
        .join("; ")} | ${s.sources.join(", ")}${s.note ? `<br>**Note.** ${s.note}` : ""} |`,
  )
  .join("\n");

const doc = `# The Department's schemes, mapped to the people it serves and to what it provides

> **Generated** from \`dosje-scheme-master-2026-09.json\` by \`tools/service-discovery/build-data.mjs\`
> on ${m.generated}. Edit the JSON, not this file.

## 1. Why this exists

The service-discovery options reviewed on 8 September 2026 carried a figure of 134
schemes, taken from the beta site's own Schemes list. The review found that list untrustworthy:
it counts guideline documents, status tables, State schemes and a list of offences as
schemes of the Department. This master starts again from the Department's own published
record and nothing else.

## 2. Sources

| Key | Document |
|---|---|
| **AR** | Department of Social Justice and Empowerment, *Annual Report 2025-26*, Chapter 3 "Schemes & Organizations" and §1.2 "Mandate and Mission" — socialjustice.gov.in/writereaddata/UploadFile/71441776233188.pdf |
| **SBE** | *Notes on Demands for Grants 2026-27*, Demand No. 93, Department of Social Justice and Empowerment — indiabudget.gov.in/doc/eb/sbe93.pdf |
| **PIB** | *Year-End Review 2025: Overview of Schemes and Key Achievements of the Department of Social Justice and Empowerment*, PIB release 2209488, 29 December 2025 |
| **SJ** | socialjustice.gov.in/schemes/\\<n\\> — the Department's legacy site, scheme pages |
| **DOSJE** | dosje.gov.in organisation pages — used only to confirm portal names |

**What was not used.** \`apps/hub/src/content/website/schemes.json\`, the scrape of the beta site's
Schemes list, and the beta site's pagination count.

## 3. The people the Department serves — the left-hand side

The Department's mandate (AR §1.2) names twelve groups: ${m.mandate.groups.join("; ")}.

The finder presents them as ${m.personas.length} personas. Three are not in the mandate's list and
each says why it is here:

| Persona | On the screen | Why it is a persona |
|---|---|---|
${m.personas.map((p) => `| **${p.label}** | ${p.sub} | ${p.mandate} |`).join("\n")}

**Persons with disabilities** are not in the mandate and no DoSJE surface names them. Their
schemes are the Department of Empowerment of Persons with Disabilities', a separate Department
of the same Ministry since 2012 (see §7).

**Left off.** *Economically Weaker Sections* are named in the mandate but no scheme in
Chapter 3 or the Demand for Grants serves EWS as such, so there is nothing to show. *Women
and girls* are a reservation inside schemes — 30% of Top Class slots, 50% of the overseas
interest subsidy, the NSKFDC women's loan schemes — not a target group of any scheme, so the
finder does not ask about gender.

## 4. What the Department provides — the right-hand side

| Offering | What it covers |
|---|---|
${m.offerings.map((o) => `| **${o.label}** | ${o.sub} |`).join("\n")}

## 5. The mapping — persona × offering, counted in records

| | ${m.offerings.map((o) => o.short || o.label).join(" | ")} |
|---|${m.offerings.map(() => "---:").join("|")}|
${matrix}

A cell is the number of records below that name the persona AND provide the offering. A dot
means none. **No cell in this table is shown on any screen** — the counts exist so the design
team can see the empty cells, and the screens show the schemes themselves.

## 6. The schemes — ${m.schemes.length} records

| Scheme | Type | Names | Provides | What it provides | Whom it names | Where to apply | Sources |
|---|---|---|---|---|---|---|---|
${schemeRows}

## 7. What the beta site lists that this master does not

| Listed on the beta site | Why it is not here |
|---|---|
${m.excluded.map((e) => `| ${e.title} | ${e.why} |`).join("\n")}

## 8. Where the sources disagree

| Field | One source says | Another says | What the surfaces do |
|---|---|---|---|
${m.conflicts.map((c) => `| ${c.field} | ${c.a} | ${c.b} | ${c.decision} |`).join("\n")}

## 9. Open questions for the Department

- Whether the Department wants **Students** as a persona in its own right, or folded back into
  each community. The 8 September review asked for it on the persona screen.
- Whether **Victims of Atrocities** and **Persons Engaged in Begging** are to be named on a
  public home page, and in which words. Both are in the Department's own mandate.
- Confirmation from NSFDC of its **income ceiling** (see §8).
- Whether **PM-DAKSH** should be shown at all after its merger into PM-KVY from 2026-27.
- The application route for **Post-Matric and Pre-Matric SC** scholarships in each State — the
  legacy site says the State selects, and some States use their own portals rather than NSP.
`;
writeFileSync(docPath, doc);


/* ── the data-sources report: what was taken from where ─────────────────── */
const srcPath = resolve(root, "docs/research/service-discovery-data-sources.md");
const DOCS = {
  AR: "Department of Social Justice and Empowerment, Annual Report 2025-26 — socialjustice.gov.in/writereaddata/UploadFile/71441776233188.pdf (Chapter 3 for the schemes, §1.2 for the mandate)",
  SBE: "Notes on Demands for Grants 2026-27, Demand No. 93, Department of Social Justice and Empowerment — indiabudget.gov.in/doc/eb/sbe93.pdf",
  PIB: "Press Information Bureau, Year-End Review 2025 of the Department, release 2209488 (29 December 2025), and the individual releases cited by number",
  SJ: "socialjustice.gov.in/schemes/<n> — the Department's legacy site, one page per scheme",
  DOSJE: "dosje.gov.in — the Department's organisation pages, used only for portal and helpline names",
};
const tag = (x) => (x.match(/^(AR|SBE|PIB|SJ|DOSJE)/) || ["?"])[0];
const srcDoc = `# Service Discovery — where every piece of data came from

Generated ${m.generated || "from the scheme master"} by \`tools/service-discovery/build-data.mjs\` from
\`docs/research/dosje-scheme-master-2026-09.json\`. This is the reference for anyone who later asks
"where did that come from?". Nothing on any screen, slide or Figma frame comes from anywhere else.
The beta website's own Schemes list was **not** used: the 8 September 2026 review found it counts
guideline pages, status tables and State schemes as Department schemes.

## 1. The documents

| Code | Document |
|---|---|
${Object.entries(DOCS).map(([k, v]) => `| **${k}** | ${v} |`).join("\n")}

Every row below cites at least one of these. A figure (an amount, an age, an income ceiling)
appears on a screen only when a source states it; where two sources disagree the figure is left
off and the disagreement is in §7.

## 2. The groups a citizen chooses from

| On the screen | Taken from |
|---|---|
${m.personas.map((p) => `| ${p.label} | ${p.mandate}${/§|AR /.test(p.mandate) ? "" : " (AR §1.2)"} |`).join("\n")}

The mandate itself, AR §1.2, names: ${m.mandate.groups.join("; ")}.

## 3. The kinds of support

| On the screen | What it covers | Source |
|---|---|---|
${m.offerings.map((o) => `| ${o.label} | ${o.sub} | ${o.source || "AR Chapter 3 — the sections of the schemes tagged with it (see §5)"} |`).join("\n")}

## 4. Portals, helplines and places to apply

A link is shown on a screen only where the site answered when checked on ${m.linkChecks.checked}
(${m.linkChecks.method}). The rest are named in words.

| Route | Shown as | Link | Source |
|---|---|---|---|
${Object.entries(m.routes).map(([k, r]) => `| \`${k}\` | ${r.label} | ${r.href ? r.href : (r.hrefUnconfirmed ? `named only — ${m.linkChecks.didNotAnswer[k] || "not confirmed"}` : "named only")} | ${r.source || ""} |`).join("\n")}

The persona band on the One Tap option shows one of these per group:

| Group | Band | Source |
|---|---|---|
${m.personas.filter((p) => p.portal).map((p) => `| ${p.label} | ${m.routes[p.portal.route].label} — ${p.portal.blurb} | ${p.portal.source} |`).join("\n")}

## 5. The schemes — every field, and its source

| Scheme | Type | Who it names | What it gives | Where to apply | Sources |
|---|---|---|---|---|---|
${m.schemes.map((s) => `| **${s.name}**${s.umbrella ? `<br><small>${s.umbrella}</small>` : ""} | ${s.type} | ${s.named} | ${s.provides} | ${s.apply.map((a) => m.routes[a] ? m.routes[a].label : a).join("; ")} | ${s.sources.join("; ")} |`).join("\n")}

Codes: ${Object.keys(DOCS).join(", ")} as in §1. "AR §3.n" is a section of Chapter 3 of the Annual
Report; "SBE n.nn" is a line item in the Demand for Grants; "SJ n" is the legacy site's scheme page
number; "PIB n" is a release number.

## 6. What the beta site lists that is not here, and why

| Listed there | Why it is not here |
|---|---|
${m.excluded.map((e) => `| ${e.title} | ${e.why} |`).join("\n")}

## 7. Where the sources disagree

${m.conflicts.map((c) => `- **${c.field}** — one source says ${c.a}; another says ${c.b}. ${c.decision}`).join("\n")}

## 8. What has not been verified

- The links listed as "named only" in §4: ${Object.entries(m.linkChecks.didNotAnswer).map(([k, v]) => `\`${k}\` (${v})`).join("; ")}.
- The State-level application route for the SC scholarships: the legacy site says the State
  selects, and some States use their own portals rather than the National Scholarship Portal.
- Every row is to be confirmed by the division that owns the scheme before anything is built.

## 9. Cross-check against myScheme

myScheme (myscheme.gov.in, run by NeGD under MeitY) lists ${m.crossChecks.myscheme.entries.length} schemes under "Ministry of Social
Justice and Empowerment" (captured ${m.crossChecks.myscheme.captured}). ${m.crossChecks.myscheme.note}

| myScheme entry | How it relates to this master |
|---|---|
${m.crossChecks.myscheme.entries.map((e) => `| ${e.name} | ${e.reading} |`).join("\n")}
`;
writeFileSync(srcPath, srcDoc);

console.log(`wrote ${dataPath}\nwrote ${docPath}\nwrote ${srcPath}\n${m.schemes.length} schemes · ${m.personas.length} personas · ${m.offerings.length} offerings`);
