// Treatment-Centre SYNTHETIC seed data. Every record here is invented for the
// demo — there is NO real patient PII. Scale mirrors the live demo centres.

import type {
  Patient,
  Beneficiary,
  PeerEducator,
  FollowUp,
  Readmission,
  AwarenessProgramme,
  StaffMember,
  CentreActivity,
  SaptahEvent,
} from "./types";

// =============================================================================
// IRCA — 18 synthetic patients
// =============================================================================

export const SEED_PATIENTS: Patient[] = [
  {
    id: "p1",
    registrationNumber: "DM2627013638",
    registrationProgress: "Completed",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Arjun Mehta",
    gender: "Male",
    age: 33,
    dateOfAdmission: "2026-05-12",
    currentAddress: "12 Demo Marg, Sector 4",
    permanentAddress: "12 Demo Marg, Sector 4",
    state: "DELHI",
    district: "New Delhi",
    placeOfResidence: "Urban",
    maritalStatus: "Never Married",
    livingArrangements: "Nuclear Family",
    education: "Professional Degree",
    occupation: "Legislators/Senior Officials/Managers",
    employment: "Employed",
    income: "45001-60,000",
    category: "Unreserved",
    contactNumber: "9000000001",
    governmentId: "Aadhaar Card",
    drugUse: [
      { drug: "Alcohol", ageOfFirstUse: "18", reason: "Peer Pressure", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "60" },
      { drug: "Opioids", ageOfFirstUse: "22", reason: "Curiosity", usedLast3Months: "Yes", dailyUse: "No", durationMonths: "30" },
    ],
    provisionalDiagnosis: "6C40 — Disorders due to use of alcohol",
    clinicalDetails: {
      "IV drug use (ever)": "Yes",
      "IV drug use (last 3 months)": "No",
      "Shared needles (ever)": "No",
      "Sexual practices": "Single partner",
      "HCV test history": "Yes",
      "HCV result": "Negative",
      "HBV test history": "Yes",
      "HBV result": "Negative",
      "ASSIST score (alcohol)": "27+ (High risk)",
      "ASSIST score (other drugs)": "4-26 (Moderate risk)",
      "Previous treatment": "Yes",
      "Treatment taken from": "State Govt De-addiction Facility",
      "Source of referral": "Family",
      "Ever hospitalised": "No",
      "Avg. daily expenditure (₹)": "500",
      "Source of money": "Legal earning, Borrowing from friends",
      "Ever apprehended": "Yes",
      "Apprehended — for selling (ever)": "Yes",
      "Apprehended — for selling (last month)": "No",
      "Apprehended — for possession (ever)": "Yes",
      "Apprehended — for possession (last month)": "No",
      "Apprehended — unruly behaviour (ever)": "No",
      "Apprehended — unruly behaviour (last month)": "No",
      "Apprehended — other crime (ever)": "No",
      "Apprehended — other crime (last month)": "No",
      "Family history of substance use": "Yes",
      "Days since last use": "3",
      "Motivation at admission": "Contemplation",
    },
    withdrawalSymptoms: ["Tremors", "Insomnia", "Nausea"],
    psychiatricSymptoms: ["Depression"],
    chronicProblems: ["Liver Disorders"],
    otherMedicalProblems: ["Jaundice"],
    headInjury: "No",
    previousDrugTreatment: "Yes",
    prevTreatmentYear: "2024",
    prevTreatmentDuration: "21",
    prevTreatmentCenter: "State Govt De-addiction Facility, New Delhi",
    treatmentReceivedTypes: ["Pharmacological", "Psychosocial"],
    relapseReason: "Peer pressure / social situations",
    dosageLog: [
      {
        date: "2026-05-13",
        complaints: "Anxiety, insomnia, craving",
        medication: "Tab Buprenorphine 2mg, Tab Clonidine 0.1mg",
        changeReason: "Induction phase",
        remarks: "Tolerating medication well, vitals stable",
      },
      {
        date: "2026-05-20",
        complaints: "Mild craving, improved sleep",
        medication: "Tab Buprenorphine 4mg",
        changeReason: "Dose stabilisation after induction",
        remarks: "Good response, no withdrawal noted",
      },
    ],
    individualCounselling: [
      { sessionNo: "1", date: "2026-05-14", issues: "Motivation enhancement, relapse prevention planning" },
      { sessionNo: "2", date: "2026-05-21", issues: "Cognitive reframing, trigger identification" },
    ],
    groupCounselling: [
      { sessionNo: "1", date: "2026-05-15", issues: "Peer sharing, coping skills" },
      { sessionNo: "2", date: "2026-05-22", issues: "Building a sober support network" },
    ],
    familyCounselling: [
      { sessionNo: "1", date: "2026-05-16", issues: "Family psychoeducation, support system" },
    ],
    referralServices: ["ICTC", "Narcotics Anonymous"],
    referralRemark: "Referred for HIV testing and peer support group",
    homeVisits: [
      { date: "2026-05-25", purpose: "Assess home environment and family support", outcome: "Supportive family, advised continued follow-up" },
      { date: "2026-06-08", purpose: "Review abstinence and medication adherence", outcome: "Abstinent, adhering to schedule" },
    ],
    finalDiagnosis: "6C40 — Disorders due to use of alcohol",
    medicalComorbidity: "Hypertension",
    psychiatricComorbidity: "Mild depression",
    neurologicalCondition: "None",
    dischargeMotivation: "Action",
    dischargeMedication: "Tab Buprenorphine 2mg once daily and Tab Naltrexone 50mg",
    dischargeRemark: "Patient stable and advised to continue follow-up and counselling",
    dischargeDate: "2026-06-12",
    followUpDate: "2026-06-26",
  },
  {
    id: "p2",
    registrationNumber: "DM2627013630",
    registrationProgress: "In Progress",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Vikram Sample",
    gender: "Male",
    age: 33,
    dateOfAdmission: "2026-05-18",
    currentAddress: "5 Test Lane",
    permanentAddress: "5 Test Lane",
    state: "DELHI",
    district: "South Delhi",
    placeOfResidence: "Urban",
    maritalStatus: "Never Married",
    livingArrangements: "Alone",
    education: "Graduate",
    occupation: "Craft and related trade workers",
    employment: "Self-Employed",
    income: "20,001-35,000",
    category: "OBC",
    contactNumber: "9000000002",
    governmentId: "Voter ID",
    drugUse: [
      { drug: "Cannabis", ageOfFirstUse: "16", reason: "Curiosity", usedLast3Months: "Yes", dailyUse: "No", durationMonths: "36" },
    ],
    provisionalDiagnosis: "6C41 — Disorders due to use of cannabis",
  },
  {
    id: "p3",
    registrationNumber: "DM2627001290",
    registrationProgress: "In Progress",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Priya Demo",
    gender: "Female",
    age: 30,
    dateOfAdmission: "2026-04-29",
    currentAddress: "21 Placeholder Road",
    permanentAddress: "21 Placeholder Road",
    state: "MAHARASHTRA",
    district: "Pune",
    placeOfResidence: "Urban",
    maritalStatus: "Married",
    livingArrangements: "Joint Family",
    education: "Graduate",
    occupation: "Professionals",
    employment: "Employed",
    income: "35,001-45,000",
    category: "Unreserved",
    contactNumber: "9000000003",
    governmentId: "Aadhaar Card",
    drugUse: [
      { drug: "Sedatives, hypnotics and anxiolytics", ageOfFirstUse: "24", reason: "Anxiety and Depression", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "18" },
    ],
    provisionalDiagnosis: "6C44 — Disorders due to use of sedatives, hypnotics or anxiolytics",
  },
  {
    id: "p4",
    registrationNumber: "DM2627000549",
    registrationProgress: "Pending",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Sunita Example",
    gender: "Female",
    age: 30,
    dateOfAdmission: "2026-06-02",
    currentAddress: "9 Mock Street",
    permanentAddress: "9 Mock Street",
    state: "PUNJAB",
    district: "Amritsar",
    placeOfResidence: "Rural",
    maritalStatus: "Married",
    livingArrangements: "Nuclear Family",
    education: "Intermediate/Diploma",
    occupation: "Professionals",
    employment: "House person",
    income: "7501-20,000",
    category: "SC",
    contactNumber: "9000000004",
    governmentId: "Aadhaar Card",
    drugUse: [
      { drug: "Opioids", ageOfFirstUse: "22", reason: "Family Problem", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "48" },
    ],
    provisionalDiagnosis: "6C43 — Disorders due to use of opioids",
  },
  {
    id: "p5",
    registrationNumber: "DM2627000364",
    registrationProgress: "Pending",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Rohit Trial",
    gender: "Male",
    age: 30,
    dateOfAdmission: "2026-06-05",
    currentAddress: "44 Specimen Avenue",
    permanentAddress: "44 Specimen Avenue",
    state: "UTTAR PRADESH",
    district: "Lucknow",
    placeOfResidence: "Urban",
    maritalStatus: "Never Married",
    livingArrangements: "With Friend/Hostel",
    education: "Intermediate/Diploma",
    occupation: "Professionals",
    employment: "Currently Unemployed",
    income: "<7500",
    category: "OBC",
    contactNumber: "9000000005",
    governmentId: "PAN Card",
    drugUse: [
      { drug: "Nicotine", ageOfFirstUse: "15", reason: "Peer Pressure", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "72" },
    ],
    provisionalDiagnosis: "6C4A — Disorders due to use of nicotine",
  },
  {
    id: "p6",
    registrationNumber: "DM2627000362",
    registrationProgress: "Completed",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Anil Placeholder",
    gender: "Male",
    age: 25,
    dateOfAdmission: "2026-03-21",
    currentAddress: "7 Dummy Colony",
    permanentAddress: "7 Dummy Colony",
    state: "DELHI",
    district: "West Delhi",
    placeOfResidence: "Urban",
    maritalStatus: "Married",
    livingArrangements: "Joint Family",
    education: "Professional Degree",
    occupation: "Professionals",
    employment: "Employed",
    income: ">60,000",
    category: "Unreserved",
    contactNumber: "9000000006",
    governmentId: "Driving Licence",
    drugUse: [
      { drug: "Cocaine", ageOfFirstUse: "20", reason: "Curiosity", usedLast3Months: "No", dailyUse: "No", durationMonths: "12" },
    ],
    provisionalDiagnosis: "6C45 — Disorders due to use of cocaine",
  },
  {
    id: "p7",
    registrationNumber: "DM2627000298",
    registrationProgress: "Completed",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Kamal Singh",
    gender: "Male",
    age: 26,
    dateOfAdmission: "2026-04-10",
    currentAddress: "3 Central Demo Lane, Paharganj",
    permanentAddress: "3 Central Demo Lane, Paharganj",
    state: "DELHI",
    district: "Central Delhi",
    placeOfResidence: "Urban",
    maritalStatus: "Never Married",
    livingArrangements: "With Friend/Hostel",
    education: "High School",
    occupation: "Elementary occupations",
    employment: "Currently Unemployed",
    income: "<7500",
    category: "SC",
    contactNumber: "9000000007",
    governmentId: "Aadhaar Card",
    drugUse: [
      { drug: "Opioids", ageOfFirstUse: "19", reason: "Peer Pressure", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "84" },
      { drug: "Alcohol", ageOfFirstUse: "17", reason: "Curiosity", usedLast3Months: "Yes", dailyUse: "No", durationMonths: "96" },
    ],
    provisionalDiagnosis: "6C43 — Disorders due to use of opioids",
  },
  {
    id: "p8",
    registrationNumber: "DM2627000277",
    registrationProgress: "In Progress",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Rekha Devi Test",
    gender: "Female",
    age: 42,
    dateOfAdmission: "2026-05-03",
    currentAddress: "Plot 15, Synthetic Nagar",
    permanentAddress: "Plot 15, Synthetic Nagar",
    state: "PUNJAB",
    district: "Ludhiana",
    placeOfResidence: "Urban",
    maritalStatus: "Married",
    livingArrangements: "Joint Family",
    education: "Middle School",
    occupation: "House person",
    employment: "House person",
    income: "7501-20,000",
    category: "OBC",
    contactNumber: "9000000008",
    governmentId: "Aadhaar Card",
    drugUse: [
      { drug: "Alcohol", ageOfFirstUse: "30", reason: "Family Problem", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "120" },
    ],
    provisionalDiagnosis: "6C40 — Disorders due to use of alcohol",
  },
  {
    id: "p9",
    registrationNumber: "DM2627000255",
    registrationProgress: "Pending",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Suresh Dummy",
    gender: "Male",
    age: 19,
    dateOfAdmission: "2026-06-08",
    currentAddress: "Dummy Mohalla, Near Test Chowk",
    permanentAddress: "Dummy Mohalla, Near Test Chowk",
    state: "UTTAR PRADESH",
    district: "Varanasi",
    placeOfResidence: "Rural",
    maritalStatus: "Never Married",
    livingArrangements: "Nuclear Family",
    education: "High School",
    occupation: "Elementary occupations",
    employment: "Never Employed",
    income: "<7500",
    category: "ST",
    contactNumber: "9000000009",
    governmentId: "Aadhaar Card",
    drugUse: [
      { drug: "Cannabis", ageOfFirstUse: "15", reason: "Peer Pressure", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "24" },
    ],
    provisionalDiagnosis: "6C41 — Disorders due to use of cannabis",
  },
  {
    id: "p10",
    registrationNumber: "DM2627000231",
    registrationProgress: "Completed",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Anita Fake",
    gender: "Female",
    age: 38,
    dateOfAdmission: "2026-03-15",
    currentAddress: "404 Null Road, Andheri",
    permanentAddress: "404 Null Road, Andheri",
    state: "MAHARASHTRA",
    district: "Mumbai",
    placeOfResidence: "Urban",
    maritalStatus: "Divorced",
    livingArrangements: "Alone",
    education: "Graduate",
    occupation: "Clerks",
    employment: "Employed",
    income: "20,001-35,000",
    category: "Unreserved",
    contactNumber: "9000000010",
    governmentId: "PAN Card",
    drugUse: [
      { drug: "Sedatives, hypnotics and anxiolytics", ageOfFirstUse: "28", reason: "Anxiety and Depression", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "60" },
      { drug: "Alcohol", ageOfFirstUse: "25", reason: "Loneliness", usedLast3Months: "Yes", dailyUse: "No", durationMonths: "72" },
    ],
    provisionalDiagnosis: "6C44 — Disorders due to use of sedatives, hypnotics or anxiolytics",
  },
  {
    id: "p11",
    registrationNumber: "DM2627000199",
    registrationProgress: "Completed",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Ramu Testcase",
    gender: "Male",
    age: 45,
    dateOfAdmission: "2026-02-28",
    currentAddress: "X-99 Sample Road, Karol Bagh",
    permanentAddress: "X-99 Sample Road, Karol Bagh",
    state: "DELHI",
    district: "Central Delhi",
    placeOfResidence: "Urban",
    maritalStatus: "Separated",
    livingArrangements: "Alone",
    education: "Middle School",
    occupation: "Craft and related trade workers",
    employment: "Self-Employed",
    income: "20,001-35,000",
    category: "OBC",
    contactNumber: "9000000011",
    governmentId: "Ration Card",
    drugUse: [
      { drug: "Opioids", ageOfFirstUse: "28", reason: "Occupation-Related", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "96" },
      { drug: "Alcohol", ageOfFirstUse: "20", reason: "Individual Problem", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "144" },
    ],
    provisionalDiagnosis: "6C43 — Disorders due to use of opioids",
  },
  {
    id: "p12",
    registrationNumber: "DM2627000184",
    registrationProgress: "In Progress",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Geeta Sample",
    gender: "Female",
    age: 31,
    dateOfAdmission: "2026-05-25",
    currentAddress: "17 Void Street, Agra Cantonment",
    permanentAddress: "Village Dummy, Agra Rural",
    state: "UTTAR PRADESH",
    district: "Agra",
    placeOfResidence: "Rural",
    maritalStatus: "Married",
    livingArrangements: "Joint Family",
    education: "Primary School",
    occupation: "Skilled (agricultural and forestry)",
    employment: "Self-Employed",
    income: "<7500",
    category: "SC",
    contactNumber: "9000000012",
    governmentId: "Aadhaar Card",
    drugUse: [
      { drug: "Cannabis", ageOfFirstUse: "20", reason: "Individual Problem", usedLast3Months: "Yes", dailyUse: "No", durationMonths: "48" },
      { drug: "Nicotine", ageOfFirstUse: "18", reason: "Peer Pressure", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "60" },
    ],
    provisionalDiagnosis: "6C41 — Disorders due to use of cannabis",
  },
  {
    id: "p13",
    registrationNumber: "DM2627000162",
    registrationProgress: "Pending",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Harish Demo",
    gender: "Male",
    age: 22,
    dateOfAdmission: "2026-06-12",
    currentAddress: "51 Fake Nagar, Civil Lines",
    permanentAddress: "51 Fake Nagar, Civil Lines",
    state: "PUNJAB",
    district: "Jalandhar",
    placeOfResidence: "Urban",
    maritalStatus: "Never Married",
    livingArrangements: "Nuclear Family",
    education: "Intermediate/Diploma",
    occupation: "Technical and Associate Professionals",
    employment: "Employed",
    income: "20,001-35,000",
    category: "Unreserved",
    contactNumber: "9000000013",
    governmentId: "Voter ID",
    drugUse: [
      { drug: "Stimulants (amphetamines/methamphetamines/methcathinone)", ageOfFirstUse: "19", reason: "Peer Pressure", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "18" },
    ],
    provisionalDiagnosis: "6C46 — Disorders due to use of stimulants, including amphetamines, methamphetamine or methcathinone",
  },
  {
    id: "p14",
    registrationNumber: "DM2627000148",
    registrationProgress: "Completed",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Lakshmi Trial",
    gender: "Female",
    age: 55,
    dateOfAdmission: "2026-01-14",
    currentAddress: "8 Null Block, Nagpur East",
    permanentAddress: "8 Null Block, Nagpur East",
    state: "MAHARASHTRA",
    district: "Nagpur",
    placeOfResidence: "Urban",
    maritalStatus: "Widow/Widower",
    livingArrangements: "Alone",
    education: "Graduate",
    occupation: "Professionals",
    employment: "Employed",
    income: "35,001-45,000",
    category: "Unreserved",
    contactNumber: "9000000014",
    governmentId: "Aadhaar Card",
    drugUse: [
      { drug: "Alcohol", ageOfFirstUse: "40", reason: "Loneliness", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "84" },
    ],
    provisionalDiagnosis: "6C40 — Disorders due to use of alcohol",
  },
  {
    id: "p15",
    registrationNumber: "DM2627000135",
    registrationProgress: "In Progress",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Mukesh Placeholder",
    gender: "Male",
    age: 37,
    dateOfAdmission: "2026-04-17",
    currentAddress: "Zero Colony, Meerut",
    permanentAddress: "Zero Colony, Meerut",
    state: "UTTAR PRADESH",
    district: "Meerut",
    placeOfResidence: "Urban",
    maritalStatus: "Married",
    livingArrangements: "Nuclear Family",
    education: "High School",
    occupation: "Plant and machine operators",
    employment: "Employed",
    income: "20,001-35,000",
    category: "OBC",
    contactNumber: "9000000015",
    governmentId: "Driving Licence",
    drugUse: [
      { drug: "Volatile Inhalants", ageOfFirstUse: "14", reason: "Peer Pressure", usedLast3Months: "No", dailyUse: "No", durationMonths: "180" },
      { drug: "Cannabis", ageOfFirstUse: "16", reason: "Curiosity", usedLast3Months: "Yes", dailyUse: "No", durationMonths: "120" },
    ],
    provisionalDiagnosis: "6C41 — Disorders due to use of cannabis",
  },
  {
    id: "p16",
    registrationNumber: "DM2627000120",
    registrationProgress: "Completed",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Savitri Example",
    gender: "Female",
    age: 35,
    dateOfAdmission: "2026-03-05",
    currentAddress: "Sample Lane 3, Varanasi Ghats Area",
    permanentAddress: "Sample Lane 3, Varanasi Ghats Area",
    state: "UTTAR PRADESH",
    district: "Varanasi",
    placeOfResidence: "Urban",
    maritalStatus: "Married",
    livingArrangements: "Joint Family",
    education: "Graduate",
    occupation: "Skilled (shop and sales)",
    employment: "Self-Employed",
    income: "20,001-35,000",
    category: "OBC",
    contactNumber: "9000000016",
    governmentId: "Aadhaar Card",
    drugUse: [
      { drug: "Alcohol", ageOfFirstUse: "25", reason: "Family Problem", usedLast3Months: "Yes", dailyUse: "No", durationMonths: "60" },
    ],
    provisionalDiagnosis: "6C40 — Disorders due to use of alcohol",
  },
  {
    id: "p17",
    registrationNumber: "DM2627000107",
    registrationProgress: "Pending",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Gurpreet Trial",
    gender: "Male",
    age: 52,
    dateOfAdmission: "2026-06-15",
    currentAddress: "Fake Colony, Patiala Road",
    permanentAddress: "Fake Colony, Patiala Road",
    state: "PUNJAB",
    district: "Patiala",
    placeOfResidence: "Rural",
    maritalStatus: "Married",
    livingArrangements: "Joint Family",
    education: "Illiterate",
    occupation: "Skilled (agricultural and forestry)",
    employment: "Self-Employed",
    income: "7501-20,000",
    category: "ST",
    contactNumber: "9000000017",
    governmentId: "Aadhaar Card",
    drugUse: [
      { drug: "Opioids", ageOfFirstUse: "25", reason: "Occupation-Related", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "162" },
      { drug: "Nicotine", ageOfFirstUse: "18", reason: "Peer Pressure", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "204" },
    ],
    provisionalDiagnosis: "6C43 — Disorders due to use of opioids",
  },
  {
    id: "p18",
    registrationNumber: "DM2627000094",
    registrationProgress: "In Progress",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Manjula Dummy",
    gender: "Transgender",
    age: 24,
    dateOfAdmission: "2026-06-01",
    currentAddress: "Test Street, New Delhi Area",
    permanentAddress: "Test Street, New Delhi Area",
    state: "DELHI",
    district: "East Delhi",
    placeOfResidence: "Urban",
    maritalStatus: "Never Married",
    livingArrangements: "Alone",
    education: "High School",
    occupation: "Elementary occupations",
    employment: "Currently Unemployed",
    income: "<7500",
    category: "Unreserved",
    contactNumber: "9000000018",
    governmentId: "Voter ID",
    drugUse: [
      { drug: "Cannabis", ageOfFirstUse: "17", reason: "Individual Problem", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "42" },
      { drug: "MDMA/MDA", ageOfFirstUse: "20", reason: "Curiosity", usedLast3Months: "Yes", dailyUse: "No", durationMonths: "18" },
    ],
    provisionalDiagnosis: "6C41 — Disorders due to use of cannabis",
  },
];

// =============================================================================
// ODIC — 16 synthetic beneficiaries (10 Drop-in Centre + 6 Outreach)
// =============================================================================

export const SEED_BENEFICIARIES: Beneficiary[] = [
  {
    id: "b1",
    registrationNumber: "OD2627000101",
    registrationProgress: "Completed",
    name: "Manoj Sample",
    gender: "Male",
    age: 28,
    dateOfRegistration: "2026-05-10",
    referredBy: "Awareness Programme",
    state: "DELHI",
    district: "Central Delhi",
    placeOfResidence: "Urban",
    contactNumber: "9000000101",
    category: "OBC",
    kind: "Drop-in Centre",
  },
  {
    id: "b2",
    registrationNumber: "OD2627000102",
    registrationProgress: "In Progress",
    name: "Deepak Demo",
    gender: "Male",
    age: 35,
    dateOfRegistration: "2026-05-22",
    referredBy: "Self",
    state: "DELHI",
    district: "East Delhi",
    placeOfResidence: "Urban",
    contactNumber: "9000000102",
    category: "Unreserved",
    kind: "Outreach",
  },
  {
    id: "b3",
    registrationNumber: "OD2627000103",
    registrationProgress: "Completed",
    name: "Ramesh Trial",
    gender: "Male",
    age: 23,
    dateOfRegistration: "2026-04-18",
    referredBy: "Hospital/Health Centre",
    state: "UTTAR PRADESH",
    district: "Kanpur",
    placeOfResidence: "Urban",
    contactNumber: "9000000103",
    category: "SC",
    kind: "Drop-in Centre",
  },
  {
    id: "b4",
    registrationNumber: "OD2627000104",
    registrationProgress: "Pending",
    name: "Seema Placeholder",
    gender: "Female",
    age: 32,
    dateOfRegistration: "2026-06-01",
    referredBy: "Family",
    state: "DELHI",
    district: "South Delhi",
    placeOfResidence: "Urban",
    contactNumber: "9000000104",
    category: "Unreserved",
    kind: "Drop-in Centre",
  },
  {
    id: "b5",
    registrationNumber: "OD2627000105",
    registrationProgress: "In Progress",
    name: "Prakash Dummy",
    gender: "Male",
    age: 40,
    dateOfRegistration: "2026-05-14",
    referredBy: "Recovered User",
    state: "MAHARASHTRA",
    district: "Mumbai",
    placeOfResidence: "Urban",
    contactNumber: "9000000105",
    category: "OBC",
    kind: "Outreach",
  },
  {
    id: "b6",
    registrationNumber: "OD2627000106",
    registrationProgress: "Completed",
    name: "Pooja Example",
    gender: "Female",
    age: 27,
    dateOfRegistration: "2026-04-05",
    referredBy: "Friends",
    state: "PUNJAB",
    district: "Amritsar",
    placeOfResidence: "Urban",
    contactNumber: "9000000106",
    category: "SC",
    kind: "Drop-in Centre",
  },
  {
    id: "b7",
    registrationNumber: "OD2627000107",
    registrationProgress: "Completed",
    name: "Naresh Fake",
    gender: "Male",
    age: 45,
    dateOfRegistration: "2026-03-20",
    referredBy: "National Helpline",
    state: "UTTAR PRADESH",
    district: "Lucknow",
    placeOfResidence: "Urban",
    contactNumber: "9000000107",
    category: "OBC",
    kind: "Drop-in Centre",
  },
  {
    id: "b8",
    registrationNumber: "OD2627000108",
    registrationProgress: "In Progress",
    name: "Kamla Sample",
    gender: "Female",
    age: 38,
    dateOfRegistration: "2026-05-30",
    referredBy: "Private Practitioner",
    state: "DELHI",
    district: "West Delhi",
    placeOfResidence: "Urban",
    contactNumber: "9000000108",
    category: "Unreserved",
    kind: "Outreach",
  },
  {
    id: "b9",
    registrationNumber: "OD2627000109",
    registrationProgress: "Pending",
    name: "Sanjay Test",
    gender: "Male",
    age: 31,
    dateOfRegistration: "2026-06-10",
    referredBy: "Referral",
    state: "PUNJAB",
    district: "Ludhiana",
    placeOfResidence: "Urban",
    contactNumber: "9000000109",
    category: "ST",
    kind: "Drop-in Centre",
  },
  {
    id: "b10",
    registrationNumber: "OD2627000110",
    registrationProgress: "Completed",
    name: "Radha Dummy",
    gender: "Female",
    age: 29,
    dateOfRegistration: "2026-03-08",
    referredBy: "Awareness Programme",
    state: "MAHARASHTRA",
    district: "Nashik",
    placeOfResidence: "Rural",
    contactNumber: "9000000110",
    category: "SC",
    kind: "Outreach",
  },
  {
    id: "b11",
    registrationNumber: "OD2627000111",
    registrationProgress: "In Progress",
    name: "Ashok Demo",
    gender: "Male",
    age: 50,
    dateOfRegistration: "2026-04-25",
    referredBy: "Self",
    state: "UTTAR PRADESH",
    district: "Agra",
    placeOfResidence: "Rural",
    contactNumber: "9000000111",
    category: "OBC",
    kind: "Drop-in Centre",
  },
  {
    id: "b12",
    registrationNumber: "OD2627000112",
    registrationProgress: "Completed",
    name: "Champa Placeholder",
    gender: "Female",
    age: 22,
    dateOfRegistration: "2026-02-14",
    referredBy: "Family",
    state: "DELHI",
    district: "New Delhi",
    placeOfResidence: "Urban",
    contactNumber: "9000000112",
    category: "Unreserved",
    kind: "Drop-in Centre",
  },
  {
    id: "b13",
    registrationNumber: "OD2627000113",
    registrationProgress: "Pending",
    name: "Bhola Trial",
    gender: "Male",
    age: 19,
    dateOfRegistration: "2026-06-14",
    referredBy: "Friends",
    state: "PUNJAB",
    district: "Jalandhar",
    placeOfResidence: "Urban",
    contactNumber: "9000000113",
    category: "SC",
    kind: "Outreach",
  },
  {
    id: "b14",
    registrationNumber: "OD2627000114",
    registrationProgress: "In Progress",
    name: "Vimla Testcase",
    gender: "Female",
    age: 44,
    dateOfRegistration: "2026-05-07",
    referredBy: "Hospital/Health Centre",
    state: "MAHARASHTRA",
    district: "Pune",
    placeOfResidence: "Urban",
    contactNumber: "9000000114",
    category: "OBC",
    kind: "Drop-in Centre",
  },
  {
    id: "b15",
    registrationNumber: "OD2627000115",
    registrationProgress: "Completed",
    name: "Dinesh Sample",
    gender: "Male",
    age: 36,
    dateOfRegistration: "2026-04-11",
    referredBy: "Recovered User",
    state: "UTTAR PRADESH",
    district: "Varanasi",
    placeOfResidence: "Rural",
    contactNumber: "9000000115",
    category: "ST",
    kind: "Drop-in Centre",
  },
  {
    id: "b16",
    registrationNumber: "OD2627000116",
    registrationProgress: "In Progress",
    name: "Saroj Demo",
    gender: "Female",
    age: 33,
    dateOfRegistration: "2026-05-19",
    referredBy: "National Helpline",
    state: "PUNJAB",
    district: "Patiala",
    placeOfResidence: "Rural",
    contactNumber: "9000000116",
    category: "Unreserved",
    kind: "Outreach",
  },
];

// =============================================================================
// CPLI — 10 synthetic peer educators
// =============================================================================

export const SEED_PEER_EDUCATORS: PeerEducator[] = [
  { id: "pe1", name: "Vipul Demo", numberOfVolunteers: 14, address: "Karol Bagh, Delhi" },
  { id: "pe2", name: "Ankit Sample", numberOfVolunteers: 12, address: "Sector 18, Noida" },
  { id: "pe3", name: "Ritu Placeholder", numberOfVolunteers: 9, address: "Vasant Kunj, Delhi" },
  { id: "pe4", name: "Harpal Trial", numberOfVolunteers: 18, address: "Model Town, Ludhiana" },
  { id: "pe5", name: "Meena Dummy", numberOfVolunteers: 7, address: "Laxmi Nagar, Delhi" },
  { id: "pe6", name: "Joginder Fake", numberOfVolunteers: 22, address: "Civil Lines, Jalandhar" },
  { id: "pe7", name: "Sundar Example", numberOfVolunteers: 11, address: "Gomti Nagar, Lucknow" },
  { id: "pe8", name: "Parvati Test", numberOfVolunteers: 8, address: "Shivaji Nagar, Pune" },
  { id: "pe9", name: "Rakesh Testcase", numberOfVolunteers: 15, address: "Rohini, Delhi" },
  { id: "pe10", name: "Kamini Sample", numberOfVolunteers: 6, address: "Salt Lake, Kolkata" },
];

// =============================================================================
// Follow-Ups — 15 synthetic records (IRCA + ODIC patients)
// =============================================================================

export const SEED_FOLLOW_UPS: FollowUp[] = [
  { id: "f1",  registrationNumber: "DM2627000362", name: "Anil Placeholder",    followUpDate: "2026-06-01", followUpNumber: 1, status: "Completed" },
  { id: "f2",  registrationNumber: "DM2627013638", name: "Arjun Mehta",         followUpDate: "2026-06-05", followUpNumber: 1, status: "Completed" },
  { id: "f3",  registrationNumber: "DM2627001290", name: "Priya Demo",           followUpDate: "2026-06-08", followUpNumber: 1, status: "Completed" },
  { id: "f4",  registrationNumber: "DM2627000362", name: "Anil Placeholder",    followUpDate: "2026-06-15", followUpNumber: 2, status: "Completed" },
  { id: "f5",  registrationNumber: "DM2627013638", name: "Arjun Mehta",         followUpDate: "2026-06-19", followUpNumber: 2, status: "Pending" },
  { id: "f6",  registrationNumber: "DM2627000298", name: "Kamal Singh",          followUpDate: "2026-06-10", followUpNumber: 1, status: "Completed" },
  { id: "f7",  registrationNumber: "DM2627000277", name: "Rekha Devi Test",     followUpDate: "2026-06-12", followUpNumber: 1, status: "Completed" },
  { id: "f8",  registrationNumber: "DM2627000231", name: "Anita Fake",           followUpDate: "2026-06-06", followUpNumber: 1, status: "Completed" },
  { id: "f9",  registrationNumber: "DM2627000199", name: "Ramu Testcase",        followUpDate: "2026-06-14", followUpNumber: 1, status: "Missed" },
  { id: "f10", registrationNumber: "DM2627000148", name: "Lakshmi Trial",        followUpDate: "2026-06-03", followUpNumber: 1, status: "Completed" },
  { id: "f11", registrationNumber: "DM2627000120", name: "Savitri Example",      followUpDate: "2026-06-07", followUpNumber: 1, status: "Completed" },
  { id: "f12", registrationNumber: "OD2627000101", name: "Manoj Sample",         followUpDate: "2026-06-13", followUpNumber: 1, status: "Completed" },
  { id: "f13", registrationNumber: "OD2627000103", name: "Ramesh Trial",         followUpDate: "2026-06-17", followUpNumber: 1, status: "Pending" },
  { id: "f14", registrationNumber: "OD2627000106", name: "Pooja Example",        followUpDate: "2026-06-09", followUpNumber: 1, status: "Completed" },
  { id: "f15", registrationNumber: "OD2627000107", name: "Naresh Fake",          followUpDate: "2026-06-18", followUpNumber: 1, status: "Completed" },
];

// =============================================================================
// Readmissions — 8 synthetic records (IRCA patients only)
// =============================================================================

export const SEED_READMISSIONS: Readmission[] = [
  { id: "r1", registrationNumber: "DM2627013630", name: "Vikram Sample",    readmissionDate: "2026-06-10", reason: "Relapse" },
  { id: "r2", registrationNumber: "DM2627000549", name: "Sunita Example",   readmissionDate: "2026-06-11", reason: "Incomplete previous treatment" },
  { id: "r3", registrationNumber: "DM2627000298", name: "Kamal Singh",       readmissionDate: "2026-06-03", reason: "Relapse" },
  { id: "r4", registrationNumber: "DM2627000277", name: "Rekha Devi Test",  readmissionDate: "2026-05-28", reason: "Medical complications" },
  { id: "r5", registrationNumber: "DM2627000255", name: "Suresh Dummy",      readmissionDate: "2026-06-15", reason: "Voluntary re-admission" },
  { id: "r6", registrationNumber: "DM2627000199", name: "Ramu Testcase",     readmissionDate: "2026-05-20", reason: "Relapse" },
  { id: "r7", registrationNumber: "DM2627000135", name: "Mukesh Placeholder", readmissionDate: "2026-06-05", reason: "Family pressure" },
  { id: "r8", registrationNumber: "DM2627000107", name: "Gurpreet Trial",    readmissionDate: "2026-06-18", reason: "Incomplete previous treatment" },
];

// =============================================================================
// Awareness Programmes — 10 records (IRCA + ODIC shared)
// =============================================================================

export const SEED_AWARENESS: AwarenessProgramme[] = [
  { id: "a1",  hotspot: "Sector 4 Community Hall area",      awarenessDate: "2026-05-15", venueName: "Sector 4 Community Hall",          peopleAttended: 45  },
  { id: "a2",  hotspot: "Govt. School campus vicinity",       awarenessDate: "2026-05-28", venueName: "Govt. Sr. Sec. School",            peopleAttended: 120 },
  { id: "a3",  hotspot: "Main Market, Laxmi Nagar",          awarenessDate: "2026-04-22", venueName: "Main Market, Laxmi Nagar",         peopleAttended: 200 },
  { id: "a4",  hotspot: "Block D, Jahangirpuri",             awarenessDate: "2026-05-01", venueName: "Block D, Jahangirpuri",            peopleAttended: 180 },
  { id: "a5",  hotspot: "Demo Degree College campus",        awarenessDate: "2026-05-06", venueName: "Demo Degree College, Rohini",      peopleAttended: 95  },
  { id: "a6",  hotspot: "Anganwadi No. 14, Shahdara",        awarenessDate: "2026-05-18", venueName: "Anganwadi No. 14, Shahdara",       peopleAttended: 55  },
  { id: "a7",  hotspot: "Gram Panchayat area, Varanasi",     awarenessDate: "2026-06-02", venueName: "Gram Panchayat Hall, Varanasi",    peopleAttended: 80  },
  { id: "a8",  hotspot: "Lucknow Railway Station area",      awarenessDate: "2026-06-07", venueName: "Lucknow Railway Station",          peopleAttended: 300 },
  { id: "a9",  hotspot: "Local Police Station, Amritsar",    awarenessDate: "2026-06-11", venueName: "Local Police Station, Amritsar",   peopleAttended: 40  },
  { id: "a10", hotspot: "Transport Nagar, Delhi",            awarenessDate: "2026-06-16", venueName: "Transport Nagar, Delhi",           peopleAttended: 70  },
];

// =============================================================================
// Staff — 5 members, one per designation (shared across all roles)
// =============================================================================

export const SEED_STAFF: StaffMember[] = [
  { id: "s1", designation: "PROJECT COORDINATOR CUM VOCATIONAL COUNSELLOR", name: "Dinesh Testcase",    mobile: "9000000201", education: "M.A. Sociology" },
  { id: "s2", designation: "DOCTOR",                                         name: "Dr. Ramesh Demo",    mobile: "9000000202", education: "MBBS, DPM" },
  { id: "s3", designation: "COUNSELLOR / SOCIAL WORKER / PSYCHOLOGIST",      name: "Kavita Trial",       mobile: "9000000203", education: "MSW, M.A. Psychology" },
  { id: "s4", designation: "NURSE",                                           name: "Sunita Dummy",       mobile: "9000000204", education: "B.Sc. Nursing" },
  { id: "s5", designation: "PROFESSIONAL PERSON EDUCATOR",                   name: "Mohan Placeholder",  mobile: "9000000205", education: "B.A. Social Work" },
];

// =============================================================================
// Centre Activities — 10 records
// =============================================================================

export const SEED_ACTIVITIES: CentreActivity[] = [
  { id: "ac1",  activity: "De-addiction camp",                      category: "Health Related Activities/Camps",                                                  date: "2026-05-20", location: "Block A",                   beneficiaries: 60 },
  { id: "ac2",  activity: "Family counselling drive",               category: "Formation of support groups and initiating counselling networks",                  date: "2026-06-03", location: "Centre premises",           beneficiaries: 28 },
  { id: "ac3",  activity: "Yoga & wellness session",                category: "Yoga and Meditation Activities",                                                   date: "2026-05-05", location: "Open ground, Centre",       beneficiaries: 35 },
  { id: "ac4",  activity: "Vocational skill training — candles",    category: "Training and awareness generation activities with children, adolescents, youth and Nasha Mukti Mitr", date: "2026-04-28", location: "Vocational Training Room",  beneficiaries: 22 },
  { id: "ac5",  activity: "Group therapy session",                  category: "Formation of support groups and initiating counselling networks",                  date: "2026-05-12", location: "Counselling Hall",          beneficiaries: 18 },
  { id: "ac6",  activity: "Peer support group meeting",             category: "Formation of Clubs (for substance use prevention) in educational institutions and communities", date: "2026-05-26", location: "Community Room",            beneficiaries: 15 },
  { id: "ac7",  activity: "Recreational outing — nature walk",      category: "Sports and physical activities",                                                   date: "2026-06-08", location: "City Park, Sector 7",       beneficiaries: 30 },
  { id: "ac8",  activity: "Legal aid awareness session",            category: "Seminars, Webinars or Workshops for awareness generation",                         date: "2026-06-13", location: "Multi-purpose Hall",        beneficiaries: 25 },
  { id: "ac9",  activity: "Nutrition & health checkup camp",        category: "Health Related Activities/Camps",                                                  date: "2026-06-17", location: "Medical Room",              beneficiaries: 40 },
  { id: "ac10", activity: "Art therapy workshop",                   category: "Wall Paintings/Graffiti and art competitions",                                     date: "2026-06-19", location: "Activity Room",             beneficiaries: 20 },
];

// =============================================================================
// Nasha Mukt Bharat Saptah 2026 / Activity Events — 10 records
// =============================================================================

export const SEED_SAPTAH_EVENTS: SaptahEvent[] = [
  { id: "se1",  event: "Nasha Mukt Bharat Saptah 2026", activity: "Flash mobs, drives and Rallies",                                                        date: "2026-06-26", coordinatingDept: "District Social Welfare Dept",    totalParticipants: 350, maleParticipants: 210, femaleParticipants: 140, numEducationalInstitutions: 3,  isCompleted: "Completed" },
  { id: "se2",  event: "Nasha Mukt Bharat Saptah 2026", activity: "NMBA pledge (including e-pledge) in educational institutions, hotspots and public places", date: "2026-06-27", coordinatingDept: "Town Municipality",                totalParticipants: 210, maleParticipants: 120, femaleParticipants: 90,  numEducationalInstitutions: 2,  isCompleted: "Completed" },
  { id: "se3",  event: "Nasha Mukt Bharat Saptah 2026", activity: "Seminars, Webinars or Workshops for awareness generation",                                date: "2026-06-26", coordinatingDept: "Education Dept",                   totalParticipants: 180, maleParticipants: 90,  femaleParticipants: 90,  numEducationalInstitutions: 4,  isCompleted: "Completed" },
  { id: "se4",  event: "Nasha Mukt Bharat Saptah 2026", activity: "Nukkad Natak, Skits and Play",                                                             date: "2026-06-28", coordinatingDept: "Youth Affairs Department",         totalParticipants: 250, maleParticipants: 150, femaleParticipants: 100, numEducationalInstitutions: 0,  isCompleted: "Completed" },
  { id: "se5",  event: "Nasha Mukt Bharat Saptah 2026", activity: "Flash mobs, drives and Rallies",                                                            date: "2026-06-29", coordinatingDept: "District Administration",          totalParticipants: 400, maleParticipants: 220, femaleParticipants: 180, numEducationalInstitutions: 5,  isCompleted: "Completed" },
  { id: "se6",  event: "Nasha Mukt Bharat Saptah 2026", activity: "Focus Group Discussions with various stakeholders in high risk areas (online and offline)", date: "2026-06-27", coordinatingDept: "Higher Education Dept",           totalParticipants: 320, maleParticipants: 200, femaleParticipants: 120, numEducationalInstitutions: 6,  isCompleted: "Completed" },
  { id: "se7",  event: "Nasha Mukt Bharat Saptah 2026", activity: "Networking with the self-help groups/local leaders/ nongovernmental organizations to reach out to high-risk groups in the neighborhood", date: "2026-06-30", coordinatingDept: "Panchayati Raj Dept", totalParticipants: 150, maleParticipants: 100, femaleParticipants: 50,  numEducationalInstitutions: 1,  isCompleted: "Completed" },
  { id: "se8",  event: "Nasha Mukt Bharat Saptah 2026", activity: "Sports and physical activities",                                                             date: "2026-07-01", coordinatingDept: "Sports Authority",                 totalParticipants: 200, maleParticipants: 130, femaleParticipants: 70,  numEducationalInstitutions: 2,  isCompleted: "Completed" },
  { id: "se9",  event: "Nasha Mukt Bharat Saptah 2026", activity: "Formation of support groups and initiating counselling networks to address the issues related to substance use", date: "2026-07-01", coordinatingDept: "Religious Affairs", totalParticipants: 90, maleParticipants: 60, femaleParticipants: 30, numEducationalInstitutions: 0, isCompleted: "Completed" },
  { id: "se10", event: "Nasha Mukt Bharat Saptah 2026", activity: "Involvement and convergence with various government departments",                            date: "2026-07-02", coordinatingDept: "District Collectorate",           totalParticipants: 500, maleParticipants: 280, femaleParticipants: 220, numEducationalInstitutions: 8,  isCompleted: "Completed" },
];
