// Treatment-Centre SYNTHETIC seed data. Every record here is invented for the
// demo — there is NO real patient PII. Scale mirrors the live demo centres.

import type {
  Patient,
  Beneficiary,
  PeerEducator,
  FollowUp,
  Readmission,
  AwarenessProgramme,
  StaffMember,
  CentreActivity,
  SaptahEvent,
} from "./types";

// =============================================================================
// IRCA — 18 synthetic patients
// =============================================================================

export const SEED_PATIENTS: Patient[] = [
  {
    id: "p1",
    registrationNumber: "DM2627013638",
    registrationProgress: "Completed",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Arjun Mehta",
    gender: "Male",
    age: 33,
    dateOfAdmission: "2026-05-12",
    currentAddress: "12 Demo Marg, Sector 4",
    permanentAddress: "12 Demo Marg, Sector 4",
    state: "DELHI",
    district: "New Delhi",
    placeOfResidence: "Urban",
    maritalStatus: "Never Married",
    livingArrangements: "Nuclear Family",
    education: "Professional Degree",
    occupation: "Legislators/Senior Officials/Managers",
    employment: "Employed",
    income: "45001-60,000",
    category: "Unreserved",
    contactNumber: "9000000001",
    governmentId: "Aadhaar Card",
    drugUse: [
      { drug: "Alcohol", ageOfFirstUse: "18", reason: "Peer Pressure", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "60" },
    ],
    provisionalDiagnosis: "6C40 — Disorders due to use of alcohol",
  },
  {
    id: "p2",
    registrationNumber: "DM2627013630",
    registrationProgress: "In Progress",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Vikram Sample",
    gender: "Male",
    age: 33,
    dateOfAdmission: "2026-05-18",
    currentAddress: "5 Test Lane",
    permanentAddress: "5 Test Lane",
    state: "DELHI",
    district: "South Delhi",
    placeOfResidence: "Urban",
    maritalStatus: "Never Married",
    livingArrangements: "Alone",
    education: "Graduate",
    occupation: "Craft and related trade workers",
    employment: "Self-Employed",
    income: "20,001-35,000",
    category: "OBC",
    contactNumber: "9000000002",
    governmentId: "Voter ID",
    drugUse: [
      { drug: "Cannabis", ageOfFirstUse: "16", reason: "Curiosity", usedLast3Months: "Yes", dailyUse: "No", durationMonths: "36" },
    ],
    provisionalDiagnosis: "6C41 — Disorders due to use of cannabis",
  },
  {
    id: "p3",
    registrationNumber: "DM2627001290",
    registrationProgress: "In Progress",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Priya Demo",
    gender: "Female",
    age: 30,
    dateOfAdmission: "2026-04-29",
    currentAddress: "21 Placeholder Road",
    permanentAddress: "21 Placeholder Road",
    state: "MAHARASHTRA",
    district: "Pune",
    placeOfResidence: "Urban",
    maritalStatus: "Married",
    livingArrangements: "Joint Family",
    education: "Graduate",
    occupation: "Professionals",
    employment: "Employed",
    income: "35,001-45,000",
    category: "Unreserved",
    contactNumber: "9000000003",
    governmentId: "Aadhaar Card",
    drugUse: [
      { drug: "Sedatives, hypnotics and anxiolytics", ageOfFirstUse: "24", reason: "Anxiety and Depression", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "18" },
    ],
    provisionalDiagnosis: "6C44 — Disorders due to use of sedatives, hypnotics or anxiolytics",
  },
  {
    id: "p4",
    registrationNumber: "DM2627000549",
    registrationProgress: "Pending",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Sunita Example",
    gender: "Female",
    age: 30,
    dateOfAdmission: "2026-06-02",
    currentAddress: "9 Mock Street",
    permanentAddress: "9 Mock Street",
    state: "PUNJAB",
    district: "Amritsar",
    placeOfResidence: "Rural",
    maritalStatus: "Married",
    livingArrangements: "Nuclear Family",
    education: "Intermediate/Diploma",
    occupation: "Professionals",
    employment: "House person",
    income: "7501-20,000",
    category: "SC",
    contactNumber: "9000000004",
    governmentId: "Aadhaar Card",
    drugUse: [
      { drug: "Opioids", ageOfFirstUse: "22", reason: "Family Problem", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "48" },
    ],
    provisionalDiagnosis: "6C43 — Disorders due to use of opioids",
  },
  {
    id: "p5",
    registrationNumber: "DM2627000364",
    registrationProgress: "Pending",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Rohit Trial",
    gender: "Male",
    age: 30,
    dateOfAdmission: "2026-06-05",
    currentAddress: "44 Specimen Avenue",
    permanentAddress: "44 Specimen Avenue",
    state: "UTTAR PRADESH",
    district: "Lucknow",
    placeOfResidence: "Urban",
    maritalStatus: "Never Married",
    livingArrangements: "With Friend/Hostel",
    education: "Intermediate/Diploma",
    occupation: "Professionals",
    employment: "Currently Unemployed",
    income: "<7500",
    category: "OBC",
    contactNumber: "9000000005",
    governmentId: "PAN Card",
    drugUse: [
      { drug: "Nicotine", ageOfFirstUse: "15", reason: "Peer Pressure", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "72" },
    ],
    provisionalDiagnosis: "6C4A — Disorders due to use of nicotine",
  },
  {
    id: "p6",
    registrationNumber: "DM2627000362",
    registrationProgress: "Completed",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Anil Placeholder",
    gender: "Male",
    age: 25,
    dateOfAdmission: "2026-03-21",
    currentAddress: "7 Dummy Colony",
    permanentAddress: "7 Dummy Colony",
    state: "DELHI",
    district: "West Delhi",
    placeOfResidence: "Urban",
    maritalStatus: "Married",
    livingArrangements: "Joint Family",
    education: "Professional Degree",
    occupation: "Professionals",
    employment: "Employed",
    income: ">60,000",
    category: "Unreserved",
    contactNumber: "9000000006",
    governmentId: "Driving Licence",
    drugUse: [
      { drug: "Cocaine", ageOfFirstUse: "20", reason: "Curiosity", usedLast3Months: "No", dailyUse: "No", durationMonths: "12" },
    ],
    provisionalDiagnosis: "6C45 — Disorders due to use of cocaine",
  },
  {
    id: "p7",
    registrationNumber: "DM2627000298",
    registrationProgress: "Completed",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Kamal Singh",
    gender: "Male",
    age: 26,
    dateOfAdmission: "2026-04-10",
    currentAddress: "3 Central Demo Lane, Paharganj",
    permanentAddress: "3 Central Demo Lane, Paharganj",
    state: "DELHI",
    district: "Central Delhi",
    placeOfResidence: "Urban",
    maritalStatus: "Never Married",
    livingArrangements: "With Friend/Hostel",
    education: "High School",
    occupation: "Elementary occupations",
    employment: "Currently Unemployed",
    income: "<7500",
    category: "SC",
    contactNumber: "9000000007",
    governmentId: "Aadhaar Card",
    drugUse: [
      { drug: "Opioids", ageOfFirstUse: "19", reason: "Peer Pressure", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "84" },
      { drug: "Alcohol", ageOfFirstUse: "17", reason: "Curiosity", usedLast3Months: "Yes", dailyUse: "No", durationMonths: "96" },
    ],
    provisionalDiagnosis: "6C43 — Disorders due to use of opioids",
  },
  {
    id: "p8",
    registrationNumber: "DM2627000277",
    registrationProgress: "In Progress",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Rekha Devi Test",
    gender: "Female",
    age: 42,
    dateOfAdmission: "2026-05-03",
    currentAddress: "Plot 15, Synthetic Nagar",
    permanentAddress: "Plot 15, Synthetic Nagar",
    state: "PUNJAB",
    district: "Ludhiana",
    placeOfResidence: "Urban",
    maritalStatus: "Married",
    livingArrangements: "Joint Family",
    education: "Middle School",
    occupation: "House person",
    employment: "House person",
    income: "7501-20,000",
    category: "OBC",
    contactNumber: "9000000008",
    governmentId: "Aadhaar Card",
    drugUse: [
      { drug: "Alcohol", ageOfFirstUse: "30", reason: "Family Problem", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "120" },
    ],
    provisionalDiagnosis: "6C40 — Disorders due to use of alcohol",
  },
  {
    id: "p9",
    registrationNumber: "DM2627000255",
    registrationProgress: "Pending",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Suresh Dummy",
    gender: "Male",
    age: 19,
    dateOfAdmission: "2026-06-08",
    currentAddress: "Dummy Mohalla, Near Test Chowk",
    permanentAddress: "Dummy Mohalla, Near Test Chowk",
    state: "UTTAR PRADESH",
    district: "Varanasi",
    placeOfResidence: "Rural",
    maritalStatus: "Never Married",
    livingArrangements: "Nuclear Family",
    education: "High School",
    occupation: "Elementary occupations",
    employment: "Never Employed",
    income: "<7500",
    category: "ST",
    contactNumber: "9000000009",
    governmentId: "Aadhaar Card",
    drugUse: [
      { drug: "Cannabis", ageOfFirstUse: "15", reason: "Peer Pressure", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "24" },
    ],
    provisionalDiagnosis: "6C41 — Disorders due to use of cannabis",
  },
  {
    id: "p10",
    registrationNumber: "DM2627000231",
    registrationProgress: "Completed",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Anita Fake",
    gender: "Female",
    age: 38,
    dateOfAdmission: "2026-03-15",
    currentAddress: "404 Null Road, Andheri",
    permanentAddress: "404 Null Road, Andheri",
    state: "MAHARASHTRA",
    district: "Mumbai",
    placeOfResidence: "Urban",
    maritalStatus: "Divorced",
    livingArrangements: "Alone",
    education: "Graduate",
    occupation: "Clerks",
    employment: "Employed",
    income: "20,001-35,000",
    category: "Unreserved",
    contactNumber: "9000000010",
    governmentId: "PAN Card",
    drugUse: [
      { drug: "Sedatives, hypnotics and anxiolytics", ageOfFirstUse: "28", reason: "Anxiety and Depression", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "60" },
      { drug: "Alcohol", ageOfFirstUse: "25", reason: "Loneliness", usedLast3Months: "Yes", dailyUse: "No", durationMonths: "72" },
    ],
    provisionalDiagnosis: "6C44 — Disorders due to use of sedatives, hypnotics or anxiolytics",
  },
  {
    id: "p11",
    registrationNumber: "DM2627000199",
    registrationProgress: "Completed",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Ramu Testcase",
    gender: "Male",
    age: 45,
    dateOfAdmission: "2026-02-28",
    currentAddress: "X-99 Sample Road, Karol Bagh",
    permanentAddress: "X-99 Sample Road, Karol Bagh",
    state: "DELHI",
    district: "Central Delhi",
    placeOfResidence: "Urban",
    maritalStatus: "Separated",
    livingArrangements: "Alone",
    education: "Middle School",
    occupation: "Craft and related trade workers",
    employment: "Self-Employed",
    income: "20,001-35,000",
    category: "OBC",
    contactNumber: "9000000011",
    governmentId: "Ration Card",
    drugUse: [
      { drug: "Opioids", ageOfFirstUse: "28", reason: "Occupation-Related", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "96" },
      { drug: "Alcohol", ageOfFirstUse: "20", reason: "Individual Problem", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "144" },
    ],
    provisionalDiagnosis: "6C43 — Disorders due to use of opioids",
  },
  {
    id: "p12",
    registrationNumber: "DM2627000184",
    registrationProgress: "In Progress",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Geeta Sample",
    gender: "Female",
    age: 31,
    dateOfAdmission: "2026-05-25",
    currentAddress: "17 Void Street, Agra Cantonment",
    permanentAddress: "Village Dummy, Agra Rural",
    state: "UTTAR PRADESH",
    district: "Agra",
    placeOfResidence: "Rural",
    maritalStatus: "Married",
    livingArrangements: "Joint Family",
    education: "Primary School",
    occupation: "Skilled (agricultural and forestry)",
    employment: "Self-Employed",
    income: "<7500",
    category: "SC",
    contactNumber: "9000000012",
    governmentId: "Aadhaar Card",
    drugUse: [
      { drug: "Cannabis", ageOfFirstUse: "20", reason: "Individual Problem", usedLast3Months: "Yes", dailyUse: "No", durationMonths: "48" },
      { drug: "Nicotine", ageOfFirstUse: "18", reason: "Peer Pressure", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "60" },
    ],
    provisionalDiagnosis: "6C41 — Disorders due to use of cannabis",
  },
  {
    id: "p13",
    registrationNumber: "DM2627000162",
    registrationProgress: "Pending",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Harish Demo",
    gender: "Male",
    age: 22,
    dateOfAdmission: "2026-06-12",
    currentAddress: "51 Fake Nagar, Civil Lines",
    permanentAddress: "51 Fake Nagar, Civil Lines",
    state: "PUNJAB",
    district: "Jalandhar",
    placeOfResidence: "Urban",
    maritalStatus: "Never Married",
    livingArrangements: "Nuclear Family",
    education: "Intermediate/Diploma",
    occupation: "Technical and Associate Professionals",
    employment: "Employed",
    income: "20,001-35,000",
    category: "Unreserved",
    contactNumber: "9000000013",
    governmentId: "Voter ID",
    drugUse: [
      { drug: "Stimulants (amphetamines/methamphetamines/methcathinone)", ageOfFirstUse: "19", reason: "Peer Pressure", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "18" },
    ],
    provisionalDiagnosis: "6C46 — Disorders due to use of stimulants, including amphetamines, methamphetamine or methcathinone",
  },
  {
    id: "p14",
    registrationNumber: "DM2627000148",
    registrationProgress: "Completed",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Lakshmi Trial",
    gender: "Female",
    age: 55,
    dateOfAdmission: "2026-01-14",
    currentAddress: "8 Null Block, Nagpur East",
    permanentAddress: "8 Null Block, Nagpur East",
    state: "MAHARASHTRA",
    district: "Nagpur",
    placeOfResidence: "Urban",
    maritalStatus: "Widow/Widower",
    livingArrangements: "Alone",
    education: "Graduate",
    occupation: "Professionals",
    employment: "Employed",
    income: "35,001-45,000",
    category: "Unreserved",
    contactNumber: "9000000014",
    governmentId: "Aadhaar Card",
    drugUse: [
      { drug: "Alcohol", ageOfFirstUse: "40", reason: "Loneliness", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "84" },
    ],
    provisionalDiagnosis: "6C40 — Disorders due to use of alcohol",
  },
  {
    id: "p15",
    registrationNumber: "DM2627000135",
    registrationProgress: "In Progress",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Mukesh Placeholder",
    gender: "Male",
    age: 37,
    dateOfAdmission: "2026-04-17",
    currentAddress: "Zero Colony, Meerut",
    permanentAddress: "Zero Colony, Meerut",
    state: "UTTAR PRADESH",
    district: "Meerut",
    placeOfResidence: "Urban",
    maritalStatus: "Married",
    livingArrangements: "Nuclear Family",
    education: "High School",
    occupation: "Plant and machine operators",
    employment: "Employed",
    income: "20,001-35,000",
    category: "OBC",
    contactNumber: "9000000015",
    governmentId: "Driving Licence",
    drugUse: [
      { drug: "Volatile Inhalants", ageOfFirstUse: "14", reason: "Peer Pressure", usedLast3Months: "No", dailyUse: "No", durationMonths: "180" },
      { drug: "Cannabis", ageOfFirstUse: "16", reason: "Curiosity", usedLast3Months: "Yes", dailyUse: "No", durationMonths: "120" },
    ],
    provisionalDiagnosis: "6C41 — Disorders due to use of cannabis",
  },
  {
    id: "p16",
    registrationNumber: "DM2627000120",
    registrationProgress: "Completed",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Savitri Example",
    gender: "Female",
    age: 35,
    dateOfAdmission: "2026-03-05",
    currentAddress: "Sample Lane 3, Varanasi Ghats Area",
    permanentAddress: "Sample Lane 3, Varanasi Ghats Area",
    state: "UTTAR PRADESH",
    district: "Varanasi",
    placeOfResidence: "Urban",
    maritalStatus: "Married",
    livingArrangements: "Joint Family",
    education: "Graduate",
    occupation: "Skilled (shop and sales)",
    employment: "Self-Employed",
    income: "20,001-35,000",
    category: "OBC",
    contactNumber: "9000000016",
    governmentId: "Aadhaar Card",
    drugUse: [
      { drug: "Alcohol", ageOfFirstUse: "25", reason: "Family Problem", usedLast3Months: "Yes", dailyUse: "No", durationMonths: "60" },
    ],
    provisionalDiagnosis: "6C40 — Disorders due to use of alcohol",
  },
  {
    id: "p17",
    registrationNumber: "DM2627000107",
    registrationProgress: "Pending",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Gurpreet Trial",
    gender: "Male",
    age: 52,
    dateOfAdmission: "2026-06-15",
    currentAddress: "Fake Colony, Patiala Road",
    permanentAddress: "Fake Colony, Patiala Road",
    state: "PUNJAB",
    district: "Patiala",
    placeOfResidence: "Rural",
    maritalStatus: "Married",
    livingArrangements: "Joint Family",
    education: "Illiterate",
    occupation: "Skilled (agricultural and forestry)",
    employment: "Self-Employed",
    income: "7501-20,000",
    category: "ST",
    contactNumber: "9000000017",
    governmentId: "Aadhaar Card",
    drugUse: [
      { drug: "Opioids", ageOfFirstUse: "25", reason: "Occupation-Related", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "162" },
      { drug: "Nicotine", ageOfFirstUse: "18", reason: "Peer Pressure", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "204" },
    ],
    provisionalDiagnosis: "6C43 — Disorders due to use of opioids",
  },
  {
    id: "p18",
    registrationNumber: "DM2627000094",
    registrationProgress: "In Progress",
    treatmentCenter: "IRCA De-Addiction Centre (Demo)",
    name: "Manjula Dummy",
    gender: "Transgender",
    age: 24,
    dateOfAdmission: "2026-06-01",
    currentAddress: "Test Street, New Delhi Area",
    permanentAddress: "Test Street, New Delhi Area",
    state: "DELHI",
    district: "East Delhi",
    placeOfResidence: "Urban",
    maritalStatus: "Never Married",
    livingArrangements: "Alone",
    education: "High School",
    occupation: "Elementary occupations",
    employment: "Currently Unemployed",
    income: "<7500",
    category: "Unreserved",
    contactNumber: "9000000018",
    governmentId: "Voter ID",
    drugUse: [
      { drug: "Cannabis", ageOfFirstUse: "17", reason: "Individual Problem", usedLast3Months: "Yes", dailyUse: "Yes", durationMonths: "42" },
      { drug: "MDMA/MDA", ageOfFirstUse: "20", reason: "Curiosity", usedLast3Months: "Yes", dailyUse: "No", durationMonths: "18" },
    ],
    provisionalDiagnosis: "6C41 — Disorders due to use of cannabis",
  },
];

// =============================================================================
// ODIC — 16 synthetic beneficiaries (10 Drop-in Centre + 6 Outreach)
// =============================================================================

export const SEED_BENEFICIARIES: Beneficiary[] = [
  {
    id: "b1",
    registrationNumber: "OD2627000101",
    registrationProgress: "Completed",
    name: "Manoj Sample",
    gender: "Male",
    age: 28,
    dateOfRegistration: "2026-05-10",
    referredBy: "Awareness Programme",
    state: "DELHI",
    district: "Central Delhi",
    placeOfResidence: "Urban",
    contactNumber: "9000000101",
    category: "OBC",
    kind: "Drop-in Centre",
  },
  {
    id: "b2",
    registrationNumber: "OD2627000102",
    registrationProgress: "In Progress",
    name: "Deepak Demo",
    gender: "Male",
    age: 35,
    dateOfRegistration: "2026-05-22",
    referredBy: "Self",
    state: "DELHI",
    district: "East Delhi",
    placeOfResidence: "Urban",
    contactNumber: "9000000102",
    category: "Unreserved",
    kind: "Outreach",
  },
  {
    id: "b3",
    registrationNumber: "OD2627000103",
    registrationProgress: "Completed",
    name: "Ramesh Trial",
    gender: "Male",
    age: 23,
    dateOfRegistration: "2026-04-18",
    referredBy: "Hospital/Health Centre",
    state: "UTTAR PRADESH",
    district: "Kanpur",
    placeOfResidence: "Urban",
    contactNumber: "9000000103",
    category: "SC",
    kind: "Drop-in Centre",
  },
  {
    id: "b4",
    registrationNumber: "OD2627000104",
    registrationProgress: "Pending",
    name: "Seema Placeholder",
    gender: "Female",
    age: 32,
    dateOfRegistration: "2026-06-01",
    referredBy: "Family",
    state: "DELHI",
    district: "South Delhi",
    placeOfResidence: "Urban",
    contactNumber: "9000000104",
    category: "Unreserved",
    kind: "Drop-in Centre",
  },
  {
    id: "b5",
    registrationNumber: "OD2627000105",
    registrationProgress: "In Progress",
    name: "Prakash Dummy",
    gender: "Male",
    age: 40,
    dateOfRegistration: "2026-05-14",
    referredBy: "Recovered User",
    state: "MAHARASHTRA",
    district: "Mumbai",
    placeOfResidence: "Urban",
    contactNumber: "9000000105",
    category: "OBC",
    kind: "Outreach",
  },
  {
    id: "b6",
    registrationNumber: "OD2627000106",
    registrationProgress: "Completed",
    name: "Pooja Example",
    gender: "Female",
    age: 27,
    dateOfRegistration: "2026-04-05",
    referredBy: "Friends",
    state: "PUNJAB",
    district: "Amritsar",
    placeOfResidence: "Urban",
    contactNumber: "9000000106",
    category: "SC",
    kind: "Drop-in Centre",
  },
  {
    id: "b7",
    registrationNumber: "OD2627000107",
    registrationProgress: "Completed",
    name: "Naresh Fake",
    gender: "Male",
    age: 45,
    dateOfRegistration: "2026-03-20",
    referredBy: "National Helpline",
    state: "UTTAR PRADESH",
    district: "Lucknow",
    placeOfResidence: "Urban",
    contactNumber: "9000000107",
    category: "OBC",
    kind: "Drop-in Centre",
  },
  {
    id: "b8",
    registrationNumber: "OD2627000108",
    registrationProgress: "In Progress",
    name: "Kamla Sample",
    gender: "Female",
    age: 38,
    dateOfRegistration: "2026-05-30",
    referredBy: "Private Practitioner",
    state: "DELHI",
    district: "West Delhi",
    placeOfResidence: "Urban",
    contactNumber: "9000000108",
    category: "Unreserved",
    kind: "Outreach",
  },
  {
    id: "b9",
    registrationNumber: "OD2627000109",
    registrationProgress: "Pending",
    name: "Sanjay Test",
    gender: "Male",
    age: 31,
    dateOfRegistration: "2026-06-10",
    referredBy: "Referral",
    state: "PUNJAB",
    district: "Ludhiana",
    placeOfResidence: "Urban",
    contactNumber: "9000000109",
    category: "ST",
    kind: "Drop-in Centre",
  },
  {
    id: "b10",
    registrationNumber: "OD2627000110",
    registrationProgress: "Completed",
    name: "Radha Dummy",
    gender: "Female",
    age: 29,
    dateOfRegistration: "2026-03-08",
    referredBy: "Awareness Programme",
    state: "MAHARASHTRA",
    district: "Nashik",
    placeOfResidence: "Rural",
    contactNumber: "9000000110",
    category: "SC",
    kind: "Outreach",
  },
  {
    id: "b11",
    registrationNumber: "OD2627000111",
    registrationProgress: "In Progress",
    name: "Ashok Demo",
    gender: "Male",
    age: 50,
    dateOfRegistration: "2026-04-25",
    referredBy: "Self",
    state: "UTTAR PRADESH",
    district: "Agra",
    placeOfResidence: "Rural",
    contactNumber: "9000000111",
    category: "OBC",
    kind: "Drop-in Centre",
  },
  {
    id: "b12",
    registrationNumber: "OD2627000112",
    registrationProgress: "Completed",
    name: "Champa Placeholder",
    gender: "Female",
    age: 22,
    dateOfRegistration: "2026-02-14",
    referredBy: "Family",
    state: "DELHI",
    district: "New Delhi",
    placeOfResidence: "Urban",
    contactNumber: "9000000112",
    category: "Unreserved",
    kind: "Drop-in Centre",
  },
  {
    id: "b13",
    registrationNumber: "OD2627000113",
    registrationProgress: "Pending",
    name: "Bhola Trial",
    gender: "Male",
    age: 19,
    dateOfRegistration: "2026-06-14",
    referredBy: "Friends",
    state: "PUNJAB",
    district: "Jalandhar",
    placeOfResidence: "Urban",
    contactNumber: "9000000113",
    category: "SC",
    kind: "Outreach",
  },
  {
    id: "b14",
    registrationNumber: "OD2627000114",
    registrationProgress: "In Progress",
    name: "Vimla Testcase",
    gender: "Female",
    age: 44,
    dateOfRegistration: "2026-05-07",
    referredBy: "Hospital/Health Centre",
    state: "MAHARASHTRA",
    district: "Pune",
    placeOfResidence: "Urban",
    contactNumber: "9000000114",
    category: "OBC",
    kind: "Drop-in Centre",
  },
  {
    id: "b15",
    registrationNumber: "OD2627000115",
    registrationProgress: "Completed",
    name: "Dinesh Sample",
    gender: "Male",
    age: 36,
    dateOfRegistration: "2026-04-11",
    referredBy: "Recovered User",
    state: "UTTAR PRADESH",
    district: "Varanasi",
    placeOfResidence: "Rural",
    contactNumber: "9000000115",
    category: "ST",
    kind: "Drop-in Centre",
  },
  {
    id: "b16",
    registrationNumber: "OD2627000116",
    registrationProgress: "In Progress",
    name: "Saroj Demo",
    gender: "Female",
    age: 33,
    dateOfRegistration: "2026-05-19",
    referredBy: "National Helpline",
    state: "PUNJAB",
    district: "Patiala",
    placeOfResidence: "Rural",
    contactNumber: "9000000116",
    category: "Unreserved",
    kind: "Outreach",
  },
];

// =============================================================================
// CPLI — 10 synthetic peer educators
// =============================================================================

export const SEED_PEER_EDUCATORS: PeerEducator[] = [
  { id: "pe1", name: "Vipul Demo", numberOfVolunteers: 14, address: "Karol Bagh, Delhi" },
  { id: "pe2", name: "Ankit Sample", numberOfVolunteers: 12, address: "Sector 18, Noida" },
  { id: "pe3", name: "Ritu Placeholder", numberOfVolunteers: 9, address: "Vasant Kunj, Delhi" },
  { id: "pe4", name: "Harpal Trial", numberOfVolunteers: 18, address: "Model Town, Ludhiana" },
  { id: "pe5", name: "Meena Dummy", numberOfVolunteers: 7, address: "Laxmi Nagar, Delhi" },
  { id: "pe6", name: "Joginder Fake", numberOfVolunteers: 22, address: "Civil Lines, Jalandhar" },
  { id: "pe7", name: "Sundar Example", numberOfVolunteers: 11, address: "Gomti Nagar, Lucknow" },
  { id: "pe8", name: "Parvati Test", numberOfVolunteers: 8, address: "Shivaji Nagar, Pune" },
  { id: "pe9", name: "Rakesh Testcase", numberOfVolunteers: 15, address: "Rohini, Delhi" },
  { id: "pe10", name: "Kamini Sample", numberOfVolunteers: 6, address: "Salt Lake, Kolkata" },
];

// =============================================================================
// Follow-Ups — 15 synthetic records (IRCA + ODIC patients)
// =============================================================================

export const SEED_FOLLOW_UPS: FollowUp[] = [
  { id: "f1",  registrationNumber: "DM2627000362", name: "Anil Placeholder",    followUpDate: "2026-06-01", followUpNumber: 1, status: "Completed" },
  { id: "f2",  registrationNumber: "DM2627013638", name: "Arjun Mehta",         followUpDate: "2026-06-05", followUpNumber: 1, status: "Completed" },
  { id: "f3",  registrationNumber: "DM2627001290", name: "Priya Demo",           followUpDate: "2026-06-08", followUpNumber: 1, status: "Completed" },
  { id: "f4",  registrationNumber: "DM2627000362", name: "Anil Placeholder",    followUpDate: "2026-06-15", followUpNumber: 2, status: "Completed" },
  { id: "f5",  registrationNumber: "DM2627013638", name: "Arjun Mehta",         followUpDate: "2026-06-19", followUpNumber: 2, status: "Pending" },
  { id: "f6",  registrationNumber: "DM2627000298", name: "Kamal Singh",          followUpDate: "2026-06-10", followUpNumber: 1, status: "Completed" },
  { id: "f7",  registrationNumber: "DM2627000277", name: "Rekha Devi Test",     followUpDate: "2026-06-12", followUpNumber: 1, status: "Completed" },
  { id: "f8",  registrationNumber: "DM2627000231", name: "Anita Fake",           followUpDate: "2026-06-06", followUpNumber: 1, status: "Completed" },
  { id: "f9",  registrationNumber: "DM2627000199", name: "Ramu Testcase",        followUpDate: "2026-06-14", followUpNumber: 1, status: "Missed" },
  { id: "f10", registrationNumber: "DM2627000148", name: "Lakshmi Trial",        followUpDate: "2026-06-03", followUpNumber: 1, status: "Completed" },
  { id: "f11", registrationNumber: "DM2627000120", name: "Savitri Example",      followUpDate: "2026-06-07", followUpNumber: 1, status: "Completed" },
  { id: "f12", registrationNumber: "OD2627000101", name: "Manoj Sample",         followUpDate: "2026-06-13", followUpNumber: 1, status: "Completed" },
  { id: "f13", registrationNumber: "OD2627000103", name: "Ramesh Trial",         followUpDate: "2026-06-17", followUpNumber: 1, status: "Pending" },
  { id: "f14", registrationNumber: "OD2627000106", name: "Pooja Example",        followUpDate: "2026-06-09", followUpNumber: 1, status: "Completed" },
  { id: "f15", registrationNumber: "OD2627000107", name: "Naresh Fake",          followUpDate: "2026-06-18", followUpNumber: 1, status: "Completed" },
];

// =============================================================================
// Readmissions — 8 synthetic records (IRCA patients only)
// =============================================================================

export const SEED_READMISSIONS: Readmission[] = [
  { id: "r1", registrationNumber: "DM2627013630", name: "Vikram Sample",    readmissionDate: "2026-06-10", reason: "Relapse" },
  { id: "r2", registrationNumber: "DM2627000549", name: "Sunita Example",   readmissionDate: "2026-06-11", reason: "Incomplete previous treatment" },
  { id: "r3", registrationNumber: "DM2627000298", name: "Kamal Singh",       readmissionDate: "2026-06-03", reason: "Relapse" },
  { id: "r4", registrationNumber: "DM2627000277", name: "Rekha Devi Test",  readmissionDate: "2026-05-28", reason: "Medical complications" },
  { id: "r5", registrationNumber: "DM2627000255", name: "Suresh Dummy",      readmissionDate: "2026-06-15", reason: "Voluntary re-admission" },
  { id: "r6", registrationNumber: "DM2627000199", name: "Ramu Testcase",     readmissionDate: "2026-05-20", reason: "Relapse" },
  { id: "r7", registrationNumber: "DM2627000135", name: "Mukesh Placeholder", readmissionDate: "2026-06-05", reason: "Family pressure" },
  { id: "r8", registrationNumber: "DM2627000107", name: "Gurpreet Trial",    readmissionDate: "2026-06-18", reason: "Incomplete previous treatment" },
];

// =============================================================================
// Awareness Programmes — 10 records (IRCA + ODIC shared)
// =============================================================================

export const SEED_AWARENESS: AwarenessProgramme[] = [
  { id: "a1",  activity: "Community awareness session",               date: "2026-05-15", location: "Sector 4 Community Hall",          participants: 45  },
  { id: "a2",  activity: "School outreach lecture",                   date: "2026-05-28", location: "Govt. Sr. Sec. School",            participants: 120 },
  { id: "a3",  activity: "Street play on drug awareness",             date: "2026-04-22", location: "Main Market, Laxmi Nagar",         participants: 200 },
  { id: "a4",  activity: "Nukkad Natak — anti-addiction drama",       date: "2026-05-01", location: "Block D, Jahangirpuri",            participants: 180 },
  { id: "a5",  activity: "Workshop for college students",             date: "2026-05-06", location: "Demo Degree College, Rohini",      participants: 95  },
  { id: "a6",  activity: "Awareness camp at Anganwadi centre",        date: "2026-05-18", location: "Anganwadi No. 14, Shahdara",       participants: 55  },
  { id: "a7",  activity: "Village awareness meeting",                 date: "2026-06-02", location: "Gram Panchayat Hall, Varanasi",    participants: 80  },
  { id: "a8",  activity: "Awareness drive at railway station",        date: "2026-06-07", location: "Lucknow Railway Station",          participants: 300 },
  { id: "a9",  activity: "Police station awareness programme",        date: "2026-06-11", location: "Local Police Station, Amritsar",   participants: 40  },
  { id: "a10", activity: "Auto-rickshaw & taxi driver awareness",     date: "2026-06-16", location: "Transport Nagar, Delhi",           participants: 70  },
];

// =============================================================================
// Staff — 10 members (shared across all roles)
// =============================================================================

export const SEED_STAFF: StaffMember[] = [
  { id: "s1",  name: "Dr. Neha Demo",           designation: "Project Director",             qualification: "MD (Psychiatry)",          contactNumber: "9000000201" },
  { id: "s2",  name: "Sanjay Sample",            designation: "Counsellor",                   qualification: "M.A. (Psychology)",        contactNumber: "9000000202" },
  { id: "s3",  name: "Kavita Trial",             designation: "Social Worker",                qualification: "MSW",                      contactNumber: "9000000203" },
  { id: "s4",  name: "Dr. Ramesh Placeholder",  designation: "Medical Officer",              qualification: "MBBS, DPM",               contactNumber: "9000000204" },
  { id: "s5",  name: "Sunita Dummy",             designation: "Staff Nurse",                  qualification: "B.Sc. Nursing",            contactNumber: "9000000205" },
  { id: "s6",  name: "Mohan Fake",               designation: "Outreach Worker",              qualification: "B.A. (Social Work)",       contactNumber: "9000000206" },
  { id: "s7",  name: "Lata Example",             designation: "Data Entry Operator",          qualification: "B.Com, DCA",              contactNumber: "9000000207" },
  { id: "s8",  name: "Dinesh Testcase",          designation: "Programme Coordinator",        qualification: "M.A. (Sociology)",         contactNumber: "9000000208" },
  { id: "s9",  name: "Anjali Sample",            designation: "Lab Technician",               qualification: "D.M.L.T.",                contactNumber: "9000000209" },
  { id: "s10", name: "Pramod Demo",              designation: "Peon / Support Staff",         qualification: "12th Pass",                contactNumber: "9000000210" },
];

// =============================================================================
// Centre Activities — 10 records
// =============================================================================

export const SEED_ACTIVITIES: CentreActivity[] = [
  { id: "ac1",  activity: "De-addiction camp",                      date: "2026-05-20", location: "Block A",                   beneficiaries: 60 },
  { id: "ac2",  activity: "Family counselling drive",               date: "2026-06-03", location: "Centre premises",           beneficiaries: 28 },
  { id: "ac3",  activity: "Yoga & wellness session",                date: "2026-05-05", location: "Open ground, Centre",       beneficiaries: 35 },
  { id: "ac4",  activity: "Vocational skill training — candles",    date: "2026-04-28", location: "Vocational Training Room",  beneficiaries: 22 },
  { id: "ac5",  activity: "Group therapy session",                  date: "2026-05-12", location: "Counselling Hall",          beneficiaries: 18 },
  { id: "ac6",  activity: "Peer support group meeting",             date: "2026-05-26", location: "Community Room",            beneficiaries: 15 },
  { id: "ac7",  activity: "Recreational outing — nature walk",      date: "2026-06-08", location: "City Park, Sector 7",       beneficiaries: 30 },
  { id: "ac8",  activity: "Legal aid awareness session",            date: "2026-06-13", location: "Multi-purpose Hall",        beneficiaries: 25 },
  { id: "ac9",  activity: "Nutrition & health checkup camp",        date: "2026-06-17", location: "Medical Room",              beneficiaries: 40 },
  { id: "ac10", activity: "Art therapy workshop",                   date: "2026-06-19", location: "Activity Room",             beneficiaries: 20 },
];

// =============================================================================
// Nasha Mukt Bharat Saptah 2026 Events — 10 records
// =============================================================================

export const SEED_SAPTAH_EVENTS: SaptahEvent[] = [
  { id: "se1",  eventName: "Nasha Mukt Bharat Saptah — Awareness Rally",           date: "2026-06-26", location: "District HQ",                  participants: 350 },
  { id: "se2",  eventName: "Nasha Mukt Bharat Saptah — Pledge Drive",              date: "2026-06-27", location: "Town Hall",                     participants: 210 },
  { id: "se3",  eventName: "Nasha Mukt Bharat Saptah — School Visit",              date: "2026-06-26", location: "Govt. School, Sector 8",        participants: 180 },
  { id: "se4",  eventName: "Nasha Mukt Bharat Saptah — Street Play",               date: "2026-06-28", location: "Main Market Square",            participants: 250 },
  { id: "se5",  eventName: "Nasha Mukt Bharat Saptah — Candle March",              date: "2026-06-29", location: "Gandhi Chowk",                  participants: 400 },
  { id: "se6",  eventName: "Nasha Mukt Bharat Saptah — College Seminar",           date: "2026-06-27", location: "Demo Degree College Auditorium", participants: 320 },
  { id: "se7",  eventName: "Nasha Mukt Bharat Saptah — Village Campaign",          date: "2026-06-30", location: "Gram Panchayat, Model Village",  participants: 150 },
  { id: "se8",  eventName: "Nasha Mukt Bharat Saptah — Sports Meet",               date: "2026-07-01", location: "Sports Complex",                participants: 200 },
  { id: "se9",  eventName: "Nasha Mukt Bharat Saptah — Religious Leaders Meet",    date: "2026-07-01", location: "Community Centre",              participants: 90  },
  { id: "se10", eventName: "Nasha Mukt Bharat Saptah — Closing Ceremony",          date: "2026-07-02", location: "District Assembly Hall",        participants: 500 },
];
